### ISSUE TITLE
[Bug] 星穹铁道的抽卡记录，角色活动跃迁无法更新

### ISSUE THREAD

**Issue by Xiao-Ma-cookiemx** [Scighost/Starward#1002]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

![image](https://github.com/user-attachments/assets/5b6a0533-464a-4bbe-b43b-515045a9fe35)

### Reproduction Steps

在跃迁记录点选更新记录

### Starward Version

0.12.2-preview.1

### Windows Version

19045.4651

### Log

```shell
NA
```

**Comment by SSB-ARFCN** [comment]
清除URL快取 再試一次

**Comment by icercat** [comment]
![image](https://github.com/user-attachments/assets/bda7fa1b-a62a-409f-a2c1-8a2894ccb52a)
我有幾乎一樣的問題

估計是他的錯誤Log

[22:34:55.624] [EROR] Starward.Pages.GachaLogPage
Update gacha log
System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.data.list[1].rank_type | LineNumber: 0 | BytePositionInLine: 444.
 ---> System.FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.
   at System.Text.Json.ThrowHelper.ThrowFormatException(NumericType)
   at System.Text.Json.Serialization.Converters.Int32Converter.ReadNumberWithCustomHandling(Utf8JsonReader&, JsonNumberHandling, JsonSerializerOptions)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object, ReadStack& , Utf8JsonReader&)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack& , T& )
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack& , T& , Boolean& )
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack& , TCollection& )
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack& , T& , Boolean& )
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object, ReadStack& , Utf8JsonReader&)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack& , T& )
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack& , T& , Boolean& )
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object, ReadStack& , Utf8JsonReader&)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack& , T& )
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack& , T& , Boolean& )
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader&, JsonSerializerOptions, ReadStack&)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& , Utf8JsonReader& , Exception)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader&, JsonSerializerOptions, ReadStack&)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState&, JsonReaderState&, ReadStack&)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream, CancellationToken)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObjectAsync(Stream, CancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.<FromJsonAsyncCore>g__Core|12_0[TValue,TJsonOptions](HttpClient, Task`1, Boolean, CancellationTokenSource, Func`4, TJsonOptions, CancellationToken)
   at Starward.Core.Gacha.GachaLogClient.GetGachaLogByQueryAsync[T](String gachaUrlPrefix, GachaLogQuery param, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\Gacha\GachaLogClient.cs:line 281
   at Starward.Core.Gacha.GachaLogClient.GetGachaLogByTypeAsync[T](String prefix, GachaType gachaType, Int64 endId, IProgress`1 progress, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\Gacha\GachaLogClient.cs:line 306
   at Starward.Core.Gacha.GachaLogClient.GetGachaLogAsync[T](String gachaUrl, Int64 endId, String lang, IProgress`1 progress, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\Gacha\GachaLogClient.cs:line 259
   at Starward.Core.Gacha.StarRail.StarRailGachaClient.GetGachaLogAsync(String gachaUrl, Int64 endId, String lang, IProgress`1 progress, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\Gacha\StarRail\StarRailGachaClient.cs:line 71
   at Starward.Services.Gacha.GachaLogService.GetGachaLogAsync(String url, Boolean all, String lang, IProgress`1 progress, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GachaLogService.cs:line 147
   at Starward.Pages.GachaLogPage.UpdateGachaLogInternalAsync(String url, Boolean all) in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 398
   at Starward.Pages.GachaLogPage.UpdateGachaLogAsync(String param) in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 359

**Comment by link-fgfgui** [comment]
![image](https://github.com/user-attachments/assets/967b0e20-65d3-4697-a87d-f3cf0f24c042)
抽了云璃就这样了

**Comment by link-fgfgui** [comment]
还是说是8月1号的锅?

**Comment by letr007** [comment]
同样为抽了云璃后出现此问题

**Comment by Scighost** [comment]
![image](https://github.com/user-attachments/assets/dad5fdab-1812-4f0d-9c6f-3ea33cb3e6f6)

可能是api返回的数据有些超出预期，在游戏中打开抽卡记录后，请点击这个清除 URL 缓存文件，然后上传 `data_2` 文件。

**Comment by Xiao-Ma-cookiemx** [comment]
文件直接上传，格式不支持，我压缩了`data_2`
[data_2.zip](https://github.com/user-attachments/files/16449892/data_2.zip)

**Comment by Scighost** [comment]
已修复，请等待下个版本发布

**Comment by Xiao-Ma-cookiemx** [comment]
> 已修复，请等待下个版本发布

感谢
