### ISSUE TITLE
[Bug] 星铁2.4预下载

### ISSUE THREAD

**Issue by YeiJ** [Scighost/Starward#1006]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

在2.4开服前预下载校验并解压了约15GB的包体，可是2.4开服后用Starward启动虽然没有下载流程但是再次校验并解压了15.05GB的包体，这是正常现象吗？

### Reproduction Steps

见描述

### Starward Version

0.12.1

### Windows Version

22631.3880

### Log

```shell
[17:09:37.489] [INFO] 
Welcome to Starward v0.12.1
System: Microsoft Windows NT 10.0.22631.0
Command Line: D:\MeowGame\Starward\app-0.12.1\Starward.dll

[17:09:37.527] [INFO] Starward.Services.DatabaseService
Database path is 'D:\MeowGame\Starward'

[17:09:37.576] [INFO] Starward.Services.DatabaseService
Database version is 9, target version is 9.

[17:09:37.646] [INFO] Starward.Pages.MainPage
Last game region is hkrpg_cn

[17:09:37.658] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hkrpg_cn

[17:09:38.499] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "D:\MeowGame\Honkai_StarRail"

[17:09:38.521] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.3.0".

[17:09:39.414] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[17:09:40.090] [INFO] Starward.Services.UpdateService
Current version: "0.12.1", latest version: "0.12.2-preview.1", ignore version: null

[17:09:42.179] [WARN] Starward.Pages.UpdatePage
Get release
System.ArgumentException: 参数错误。

The value cannot be infinite or Not a Number (NaN).
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32)
   at Microsoft.UI.Xaml.Controls.Primitives.RangeBase.set_Value(Double)
   at Starward.Pages.UpdatePage.UpdateProgressValue() in D:\a\Starward\Starward\src\Starward\Pages\UpdatePage.xaml.cs:line 402
   at Starward.Pages.UpdatePage.UpdateProgressState() in D:\a\Starward\Starward\src\Starward\Pages\UpdatePage.xaml.cs:line 342
   at Starward.Pages.UpdatePage.GetReleaseAsync() in D:\a\Starward\Starward\src\Starward\Pages\UpdatePage.xaml.cs:line 117

[17:09:42.221] [EROR] Starward.Pages.UpdatePage
Update progress
System.ArgumentException: 参数错误。

The value cannot be infinite or Not a Number (NaN).
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32)
   at Microsoft.UI.Xaml.Controls.Primitives.RangeBase.set_Value(Double)
   at Starward.Pages.UpdatePage.UpdateProgressValue() in D:\a\Starward\Starward\src\Starward\Pages\UpdatePage.xaml.cs:line 402
   at Starward.Pages.UpdatePage.UpdateProgressState() in D:\a\Starward\Starward\src\Starward\Pages\UpdatePage.xaml.cs:line 342
   at Starward.Pages.UpdatePage._timer_Tick(DispatcherQueueTimer sender, Object args) in D:\a\Starward\Starward\src\Starward\Pages\UpdatePage.xaml.cs:line 413

#######
省略两千行相同的错误
#######


[17:10:10.300] [EROR] Starward.Pages.UpdatePage
Update progress
System.ArgumentException: 参数错误。

The value cannot be infinite or Not a Number (NaN).
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32)
   at ABI.Microsoft.UI.Xaml.Controls.Primitives.IRangeBaseMethods.set_Value(IObjectReference, Double)
   at Starward.Pages.UpdatePage.UpdateProgressValue() in D:\a\Starward\Starward\src\Starward\Pages\UpdatePage.xaml.cs:line 402
   at Starward.Pages.UpdatePage.UpdateProgressState() in D:\a\Starward\Starward\src\Starward\Pages\UpdatePage.xaml.cs:line 342
   at Starward.Pages.UpdatePage._timer_Tick(DispatcherQueueTimer sender, Object args) in D:\a\Starward\Starward\src\Starward\Pages\UpdatePage.xaml.cs:line 413
```

**Comment by CreeperAWA** [comment]
同样出现此问题，以前是没有的，感觉不正常但似乎又合理（再校验一遍防止出错也没啥 ~~电脑性能差当我没说~~）

**Comment by fuuunyfun** [comment]
现在预下载好像没有解压缩这一步了 开服才解压 这个是预下载的日志
```
[14:35:07.638] [INFO] 
Welcome to Starward v0.12.1
System: Microsoft Windows NT 10.0.22621.0
Command Line: E:\Starward\app-0.12.1\Starward.dll download --biz hkrpg_cn --loc "E:\Starward\Game\Star Rail Game" --lang 1

[14:35:08.851] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
Initialize install game service
biz: hkrpg_cn
path: "E:\Starward\Game\Star Rail Game"
lang: Chinese
repair: False
reinstall: False

[14:35:08.914] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
Start install game, skipVerify: False

[14:35:10.581] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
Prepare for download.

[14:35:19.301] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
Request head: "https://autopatchcn.bhsr.com/client/diff/hkrpg_cn/audio_zh-cn_2.3.0_2.4.0_hdiff_wsTSCLyBgGJgIebu.zip"

[14:35:19.301] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
Request head: "https://autopatchcn.bhsr.com/client/diff/hkrpg_cn/game_2.3.0_2.4.0_hdiff_FNHhATYIXnJyCVxE.zip"

[14:35:20.951] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
Start download files.

[14:35:20.951] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
2 files need to download.

[14:35:20.952] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
Download: FileName "audio_zh-cn_2.3.0_2.4.0_hdiff_wsTSCLyBgGJgIebu.zip", Url "https://autopatchcn.bhsr.com/client/diff/hkrpg_cn/audio_zh-cn_2.3.0_2.4.0_hdiff_wsTSCLyBgGJgIebu.zip"

[14:35:20.952] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
Download: FileName "game_2.3.0_2.4.0_hdiff_FNHhATYIXnJyCVxE.zip", Url "https://autopatchcn.bhsr.com/client/diff/hkrpg_cn/game_2.3.0_2.4.0_hdiff_FNHhATYIXnJyCVxE.zip"

[14:35:32.565] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
Download Successfully: FileName "audio_zh-cn_2.3.0_2.4.0_hdiff_wsTSCLyBgGJgIebu.zip"

[14:42:51.072] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
Download Successfully: FileName "game_2.3.0_2.4.0_hdiff_FNHhATYIXnJyCVxE.zip"

[14:42:51.075] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
Verify downloaded files.

[14:43:40.366] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
Clear deprecated files.

[14:43:40.766] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
Install game finished.
```
校验完就直接结束了(我电脑有点差 总不能说50秒完成校验加解压吧
下面是开服安装的日志
```
[08:28:10.947] [INFO] 
Welcome to Starward v0.12.2-preview.1
System: Microsoft Windows NT 10.0.22621.0
Command Line: E:\Starward\app-0.12.2-preview.1\Starward.dll
###省略部分
[08:31:34.968] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[08:31:34.968] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hkrpg_cn

[08:31:35.045] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "E:\Starward\Game\Star Rail Game"

[08:31:35.083] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.3.0".
###不知道怎么回事少了两分钟的日志 其他日志也找不到 可能和新测试的安装器有关
[08:33:43.353] [INFO] Starward.Services.Download.InstallGameService
Write config.ini (game_version="2.4.0")

[08:33:43.356] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "E:\Starward\Game\Star Rail Game"

[08:33:43.363] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.4.0".
```
两分钟差不多可以对上解压时间

**Comment by CreeperAWA** [comment]
现在预下载似乎是版本更新后 开始游戏 会变为 更新游戏 然后再解压，解压完成后再次变为 开始游戏

**Comment by YeiJ** [comment]
> 现在预下载似乎是版本更新后 开始游戏 会变为 更新游戏 然后再解压，解压完成后再次变为 开始游戏

可是我预下载下载完之后是解压过一次的

**Comment by Scighost** [comment]
0.12.1 之后我重写了下载功能，之前的代码已经记不太清了，后续的版本应该不存在这个问题。
