### ISSUE TITLE
[Bug] 原神的祈愿记录无法显示

### ISSUE THREAD

**Issue by bsgz** [Scighost/Starward#1009]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

![Snipaste_2024-08-02_09-46-52](https://github.com/user-attachments/assets/bdfefb0c-9979-44ce-9565-e566d6957509)
![Snipaste_2024-08-02_09-46-42](https://github.com/user-attachments/assets/7fdb3d85-b885-4022-8f24-e96c3dc740d3)

### Reproduction Steps

打开祈愿记录

### Starward Version

0.12.2-preview.1

### Windows Version

22631.3737

### Log

```shell
[09:43:30.385] [INFO] 
Welcome to Starward v0.12.2-preview.1
System: Microsoft Windows NT 10.0.22631.0
Command Line: K:\Starward\app-0.12.2-preview.1\Starward.dll

[09:43:30.451] [INFO] Starward.Services.DatabaseService
Database path is 'K:\Starward'

[09:43:30.486] [INFO] Starward.Services.DatabaseService
Database version is 9, target version is 9.

[09:43:30.592] [INFO] Starward.Pages.MainPage
Last game region is hk4e_cn

[09:43:30.610] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[09:43:31.481] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "E:\Genshin Impact Game"

[09:43:31.492] [INFO] Starward.Pages.GameLauncherPage
Game is running ("YuanShen", 21520)

[09:43:31.506] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "4.8.0".

[09:43:32.407] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[09:43:33.071] [INFO] Starward.Services.UpdateService
Current version: "0.12.2-preview.1", latest version: "0.12.2-preview.1", ignore version: null

[09:43:36.205] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_cn

[09:43:36.301] [EROR] Starward.Pages.GachaLogPage
UpdateGachaTypeStats
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32, sqlite3)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1156
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1184
   at System.Collections.Generic.List`1..ctor(IEnumerable`1)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 815
   at Starward.Services.Gacha.GenshinGachaService.GetGachaLogItemEx(Int64 uid) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GenshinGachaService.cs:line 53
   at Starward.Services.Gacha.GachaLogService.GetGachaTypeStats(Int64 uid) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GachaLogService.cs:line 171
   at Starward.Pages.GachaLogPage.UpdateGachaTypeStats(Nullable`1 uid) in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 249

[09:43:36.835] [EROR] Starward.Pages.GachaLogPage
Update wiki data hk4e_cn
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32, sqlite3)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 638
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 527
   at Starward.Services.Gacha.GenshinGachaService.UpdateGachaInfoAsync(GameBiz gameBiz, String lang, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GenshinGachaService.cs:line 165
   at Starward.Pages.GachaLogPage.UpdateWikiDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 285

[09:43:53.930] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_cn

[09:43:53.987] [EROR] Starward.Pages.GachaLogPage
UpdateGachaTypeStats
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32, sqlite3)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1156
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1184
   at System.Collections.Generic.List`1..ctor(IEnumerable`1)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 815
   at Starward.Services.Gacha.GenshinGachaService.GetGachaLogItemEx(Int64 uid) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GenshinGachaService.cs:line 53
   at Starward.Services.Gacha.GachaLogService.GetGachaTypeStats(Int64 uid) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GachaLogService.cs:line 171
   at Starward.Pages.GachaLogPage.UpdateGachaTypeStats(Nullable`1 uid) in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 249

[09:43:54.237] [EROR] Starward.Pages.GachaLogPage
Update wiki data hk4e_cn
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32, sqlite3)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 638
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 527
   at Starward.Services.Gacha.GenshinGachaService.UpdateGachaInfoAsync(GameBiz gameBiz, String lang, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GenshinGachaService.cs:line 165
   at Starward.Pages.GachaLogPage.UpdateWikiDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 285

[09:43:56.193] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[09:43:56.193] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hkrpg_cn

[09:43:59.264] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[09:43:59.264] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_cn

[09:43:59.361] [EROR] Starward.Pages.GachaLogPage
UpdateGachaTypeStats
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32, sqlite3)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1156
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1184
   at System.Collections.Generic.List`1..ctor(IEnumerable`1)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 815
   at Starward.Services.Gacha.GenshinGachaService.GetGachaLogItemEx(Int64 uid) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GenshinGachaService.cs:line 53
   at Starward.Services.Gacha.GachaLogService.GetGachaTypeStats(Int64 uid) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GachaLogService.cs:line 171
   at Starward.Pages.GachaLogPage.UpdateGachaTypeStats(Nullable`1 uid) in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 249

[09:43:59.614] [EROR] Starward.Pages.GachaLogPage
Update wiki data hk4e_cn
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32, sqlite3)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 638
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 527
   at Starward.Services.Gacha.GenshinGachaService.UpdateGachaInfoAsync(GameBiz gameBiz, String lang, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GenshinGachaService.cs:line 165
   at Starward.Pages.GachaLogPage.UpdateWikiDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 285

[09:44:02.040] [INFO] Starward.Pages.MainPage
Change game region to nap_cn

[09:44:02.041] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param nap_cn

[09:44:08.058] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[09:44:08.058] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hkrpg_cn

[09:44:09.872] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[09:44:09.873] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_cn

[09:44:09.969] [EROR] Starward.Pages.GachaLogPage
UpdateGachaTypeStats
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32, sqlite3)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1156
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1184
   at System.Collections.Generic.List`1..ctor(IEnumerable`1)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 815
   at Starward.Services.Gacha.GenshinGachaService.GetGachaLogItemEx(Int64 uid) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GenshinGachaService.cs:line 53
   at Starward.Services.Gacha.GachaLogService.GetGachaTypeStats(Int64 uid) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GachaLogService.cs:line 171
   at Starward.Pages.GachaLogPage.UpdateGachaTypeStats(Nullable`1 uid) in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 249

[09:44:10.183] [EROR] Starward.Pages.GachaLogPage
Update wiki data hk4e_cn
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32, sqlite3)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 638
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 527
   at Starward.Services.Gacha.GenshinGachaService.UpdateGachaInfoAsync(GameBiz gameBiz, String lang, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GenshinGachaService.cs:line 165
   at Starward.Pages.GachaLogPage.UpdateWikiDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 285

[09:45:02.751] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[09:45:02.751] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hkrpg_cn

[09:45:04.199] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[09:45:04.199] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_cn

[09:45:04.289] [EROR] Starward.Pages.GachaLogPage
UpdateGachaTypeStats
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32, sqlite3)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1156
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1184
   at System.Collections.Generic.List`1..ctor(IEnumerable`1)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 815
   at Starward.Services.Gacha.GenshinGachaService.GetGachaLogItemEx(Int64 uid) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GenshinGachaService.cs:line 53
   at Starward.Services.Gacha.GachaLogService.GetGachaTypeStats(Int64 uid) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GachaLogService.cs:line 171
   at Starward.Pages.GachaLogPage.UpdateGachaTypeStats(Nullable`1 uid) in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 249

[09:45:04.503] [EROR] Starward.Pages.GachaLogPage
Update wiki data hk4e_cn
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32, sqlite3)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 638
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 527
   at Starward.Services.Gacha.GenshinGachaService.UpdateGachaInfoAsync(GameBiz gameBiz, String lang, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GenshinGachaService.cs:line 165
   at Starward.Pages.GachaLogPage.UpdateWikiDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 285

[09:45:37.225] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[09:45:37.226] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hkrpg_cn

[09:45:39.017] [INFO] Starward.Pages.MainPage
Change game region to nap_cn

[09:45:39.018] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param nap_cn

[09:45:40.401] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[09:45:40.401] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_cn

[09:45:40.494] [EROR] Starward.Pages.GachaLogPage
UpdateGachaTypeStats
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32, sqlite3)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1156
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1184
   at System.Collections.Generic.List`1..ctor(IEnumerable`1)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 815
   at Starward.Services.Gacha.GenshinGachaService.GetGachaLogItemEx(Int64 uid) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GenshinGachaService.cs:line 53
   at Starward.Services.Gacha.GachaLogService.GetGachaTypeStats(Int64 uid) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GachaLogService.cs:line 171
   at Starward.Pages.GachaLogPage.UpdateGachaTypeStats(Nullable`1 uid) in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 249

[09:45:40.730] [EROR] Starward.Pages.GachaLogPage
Update wiki data hk4e_cn
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32, sqlite3)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 638
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 527
   at Starward.Services.Gacha.GenshinGachaService.UpdateGachaInfoAsync(GameBiz gameBiz, String lang, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GenshinGachaService.cs:line 165
   at Starward.Pages.GachaLogPage.UpdateWikiDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 285

[09:46:45.778] [INFO] Starward.Services.Gacha.GenshinGachaService
Last gacha log id of uid 235265849 is 1720706760000703549

[09:46:47.363] [EROR] Starward.Pages.GachaLogPage
UpdateGachaTypeStats
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32, sqlite3)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1156
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1184
   at System.Collections.Generic.List`1..ctor(IEnumerable`1)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 815
   at Starward.Services.Gacha.GenshinGachaService.GetGachaLogItemEx(Int64 uid) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GenshinGachaService.cs:line 53
   at Starward.Services.Gacha.GachaLogService.GetGachaTypeStats(Int64 uid) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GachaLogService.cs:line 171
   at Starward.Pages.GachaLogPage.UpdateGachaTypeStats(Nullable`1 uid) in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 249

[09:47:33.319] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[09:47:33.320] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hkrpg_cn

[09:47:34.802] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[09:47:34.803] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_cn

[09:47:34.903] [EROR] Starward.Pages.GachaLogPage
UpdateGachaTypeStats
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32, sqlite3)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1156
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1184
   at System.Collections.Generic.List`1..ctor(IEnumerable`1)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 815
   at Starward.Services.Gacha.GenshinGachaService.GetGachaLogItemEx(Int64 uid) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GenshinGachaService.cs:line 53
   at Starward.Services.Gacha.GachaLogService.GetGachaTypeStats(Int64 uid) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GachaLogService.cs:line 171
   at Starward.Pages.GachaLogPage.UpdateGachaTypeStats(Nullable`1 uid) in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 249

[09:47:35.395] [EROR] Starward.Pages.GachaLogPage
Update wiki data hk4e_cn
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32, sqlite3)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 638
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 527
   at Starward.Services.Gacha.GenshinGachaService.UpdateGachaInfoAsync(GameBiz gameBiz, String lang, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GenshinGachaService.cs:line 165
   at Starward.Pages.GachaLogPage.UpdateWikiDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 285
```

**Comment by Scighost** [comment]
`database disk image is malformed`

可能因为断电或蓝屏，你的数据库文件 `StarwardDatabasedb` 损坏了，需要使用工具修复或备份文件覆盖。
