### ISSUE TITLE
点击开始游戏后无法启动

### ISSUE THREAD

**Issue by czybenren** [Scighost/Starward#1018]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

        点击开始游戏后无法启动，我确保我关联了游戏路径，游戏也没有问题，使用管理员模式也没有解决，查看日志之后，发现错误为"没有应用程序与此操作的指定文件有关联。"上网搜寻后无果，望解决

### Starward Version

0.12.2-preview.1

### Windows Version

22631.3880

### Log

```shell
[08:47:24.312] [EROR] Starward.Pages.GameLauncherPage
Start game
System.ComponentModel.Win32Exception (1155): An error occurred trying to start process 'D:\Program Files\miHoYo Launcher\games\Star Rail Game\StarRail.exe' with working directory 'D:\Program Files\miHoYo Launcher\games\Star Rail Game'. 没有应用程序与此操作的指定文件有关联。
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo)
   at Starward.Services.Launcher.GameLauncherService.StartGame(GameBiz biz, Boolean ignoreRunningGame, String installPath) in D:\a\Starward\Starward\src\Starward\Services\Launcher\GameLauncherService.cs:line 383
   at Starward.Pages.GameLauncherPage.StartGameAsync() in D:\a\Starward\Starward\src\Starward\Pages\GameLauncherPage.xaml.cs:line 439
```

**Comment by Scighost** [comment]
可能是文件损坏，请尝试修复游戏。
