### ISSUE TITLE
[Bug] 使用starward进行版本更新后启动时提示缺少unityplayer.dll

### ISSUE THREAD

**Issue by miapupu** [Scighost/Starward#1025]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

如题，不论是铁道的2.4更新三蹦子7.7的更新都出现了这种问题，并且使用starward的修复功能无法正常修复，需要使用官方启动器才能正常修复

### Reproduction Steps

使用官启进行预下载后使用starward进行更新（铁道）/使用starward不预载在更新当天直接更新（崩坏三）均出现了该问题

### Expected Behavior

正常情况下不应当缺失文件，或应该能通过修复直接解决

### Screenshots

![JN0@QP A49EB(QEGJ~MG}2R](https://github.com/user-attachments/assets/4a3b5669-27b5-4e1f-a81f-51eaab8d010b)

### Starward Version

0.12.0

### Windows Version

19045.4651

### Log

```shell
Command Line: F:\Starward\app-0.12.0\Starward.dll

[11:16:45.248] [INFO] Starward.Services.DatabaseService
Database path is 'F:\Starward'

[11:16:45.615] [INFO] Starward.Services.DatabaseService
Database version is 9, target version is 9.

[11:16:54.541] [INFO] Starward.Pages.MainPage
Last game region is nap_cn

[11:16:55.377] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param nap_cn

[11:17:07.369] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "H:\Program Files\miHoYo Launcher\games\ZenlessZoneZero Game"

[11:17:08.066] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[11:17:08.137] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.0.0".

[11:17:11.231] [EROR] Starward.Services.HoYoPlayService
Download image: ""
System.InvalidOperationException: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage)
   at System.Net.Http.HttpClient.GetByteArrayAsync(Uri , CancellationToken)
   at Starward.Services.HoYoPlayService.<>c__DisplayClass14_0.<<PrepareImagesAsync>b__0>d.MoveNext() in D:\a\Starward\Starward\src\Starward\Services\HoYoPlayService.cs:line 201

[11:17:45.787] [INFO] Starward.Pages.MainPage
Change game region to bh3_cn

[11:17:45.788] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param bh3_cn

[11:17:46.024] [INFO] Starward.Pages.GameLauncherPage
Game install path of bh3_cn: "E:\Honkai Impact 3\Games"

[11:17:46.407] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of bh3_cn is "7.6.0".

[11:17:47.508] [WARN] Starward.Pages.MainPage
Check update: "The SSL connection could not be established, see inner exception."

[11:26:52.627] [EROR] Starward.Services.HoYoPlayService
Download image: ""
System.InvalidOperationException: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage)
   at System.Net.Http.HttpClient.GetByteArrayAsync(Uri , CancellationToken)
   at Starward.Services.HoYoPlayService.<>c__DisplayClass14_0.<<PrepareImagesAsync>b__0>d.MoveNext() in D:\a\Starward\Starward\src\Starward\Services\HoYoPlayService.cs:line 201

[11:33:55.204] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[11:33:55.205] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[11:33:55.685] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "E:\Genshin Impact\Genshin Impact Game"

[11:33:55.848] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "4.8.0".

[11:33:56.450] [INFO] Starward.Pages.MainPage
Change game region to bh3_cn

[11:33:56.451] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param bh3_cn

[11:33:56.592] [INFO] Starward.Pages.GameLauncherPage
Game install path of bh3_cn: "E:\Honkai Impact 3\Games"

[11:33:56.644] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of bh3_cn is "7.6.0".

[11:33:59.742] [INFO] Starward.Pages.MainPage
Change game region to bh3_cn

[11:33:59.742] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param bh3_cn

[11:33:59.850] [INFO] Starward.Pages.MainPage
Change game region to bh3_cn

[11:33:59.850] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param bh3_cn

[11:33:59.868] [INFO] Starward.Pages.GameLauncherPage
Game install path of bh3_cn: "E:\Honkai Impact 3\Games"

[11:33:59.876] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of bh3_cn is "7.6.0".

[11:34:00.000] [INFO] Starward.Pages.GameLauncherPage
Game install path of bh3_cn: "E:\Honkai Impact 3\Games"

[11:34:00.024] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of bh3_cn is "7.6.0".

[11:36:49.531] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[11:36:49.532] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[11:36:49.614] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "E:\Genshin Impact\Genshin Impact Game"

[11:36:49.645] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "4.8.0".

[11:36:50.326] [INFO] Starward.Pages.MainPage
Change game region to bh3_cn

[11:36:50.327] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param bh3_cn

[11:36:50.437] [INFO] Starward.Pages.GameLauncherPage
Game install path of bh3_cn: "E:\Honkai Impact 3\Games"

[11:36:50.465] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of bh3_cn is "7.7.0".

[11:36:51.481] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (bh3_cn)
path: "E:\Honkai Impact 3\Games\BH3.exe"
arg: null

[11:36:52.554] [INFO] Starward.Pages.GameLauncherPage
Game started ("BH3", 4000)

[11:36:52.840] [EROR] Starward.Services.HoYoPlayService
Download image: ""
System.InvalidOperationException: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage)
   at System.Net.Http.HttpClient.GetByteArrayAsync(Uri , CancellationToken)
   at Starward.Services.HoYoPlayService.<>c__DisplayClass14_0.<<PrepareImagesAsync>b__0>d.MoveNext() in D:\a\Starward\Starward\src\Starward\Services\HoYoPlayService.cs:line 201

[11:36:54.564] [INFO] Starward.Services.PlayTimeService
Game process (bh3_cn, 4000) has no window

[11:36:56.164] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[11:36:56.165] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hkrpg_cn

[11:36:56.263] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[11:36:56.263] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hkrpg_cn

[11:36:56.274] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "H:\Star Rail\Game"

[11:36:56.282] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.4.0".

[11:36:56.351] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "H:\Star Rail\Game"

[11:36:56.358] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.4.0".

[11:36:56.587] [INFO] Starward.Services.PlayTimeService
Game process (bh3_cn, 4000) has no window

[11:36:57.975] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hkrpg_cn)
path: "H:\Star Rail\Game\StarRail.exe"
arg: ""

[11:36:58.575] [INFO] Starward.Pages.GameLauncherPage
Game started ("StarRail", 8884)

[11:36:58.600] [INFO] Starward.Services.PlayTimeService
Start to log playtime (bh3_cn, 4000)

[11:37:00.584] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hkrpg_cn, 8884)

[11:37:02.634] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[11:37:27.866] [INFO] Starward.Pages.MainPage
Change game region to bh3_cn

[11:37:27.866] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param bh3_cn

[11:37:27.947] [INFO] Starward.Pages.MainPage
Change game region to bh3_cn

[11:37:27.947] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param bh3_cn

[11:37:27.995] [INFO] Starward.Pages.GameLauncherPage
Game install path of bh3_cn: "E:\Honkai Impact 3\Games"

[11:37:28.018] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of bh3_cn is "7.7.0".

[11:37:28.018] [INFO] Starward.Pages.GameLauncherPage
Game install path of bh3_cn: "E:\Honkai Impact 3\Games"

[11:37:28.025] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of bh3_cn is "7.7.0".

[11:37:30.930] [INFO] Starward.Pages.MainPage
Navigate to "GameSettingPage" with param bh3_cn

[11:37:32.700] [INFO] Starward.Pages.MainPage
Navigate to "ScreenshotPage" with param bh3_cn

[11:37:33.103] [INFO] Starward.Pages.ScreenshotPage
Screenshot folder is "E:\Honkai Impact 3\Games\ScreenShot"

[11:37:35.302] [INFO] Starward.Pages.MainPage
Change game region to bh3_cn

[11:37:35.302] [INFO] Starward.Pages.MainPage
Navigate to "ScreenshotPage" with param bh3_cn

[11:37:35.342] [INFO] Starward.Pages.ScreenshotPage
Screenshot folder is "E:\Honkai Impact 3\Games\ScreenShot"

[11:37:35.393] [INFO] Starward.Pages.MainPage
Change game region to bh3_cn

[11:37:35.394] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param bh3_cn

[11:37:35.520] [INFO] Starward.Pages.GameLauncherPage
Game install path of bh3_cn: "E:\Honkai Impact 3\Games"

[11:37:35.542] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of bh3_cn is "7.7.0".

[11:37:57.939] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (bh3_cn)
path: "E:\Honkai Impact 3\Games\BH3.exe"
arg: null

[11:37:58.571] [INFO] Starward.Pages.GameLauncherPage
Game started ("BH3", 12148)

[11:38:00.581] [INFO] Starward.Services.PlayTimeService
Game process (bh3_cn, 12148) has no window

[11:38:02.588] [INFO] Starward.Services.PlayTimeService
Game process (bh3_cn, 12148) has no window

[11:38:11.617] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[11:38:49.951] [INFO] Starward.Pages.MainPage
Change game region to bh3_cn

[11:38:49.951] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param bh3_cn

[11:38:50.078] [INFO] Starward.Pages.MainPage
Change game region to bh3_cn

[11:38:50.078] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param bh3_cn

[11:38:50.126] [INFO] Starward.Pages.GameLauncherPage
Game install path of bh3_cn: "E:\Honkai Impact 3\Games"

[11:38:50.149] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of bh3_cn is "7.7.0".

[11:38:50.150] [INFO] Starward.Pages.GameLauncherPage
Game install path of bh3_cn: "E:\Honkai Impact 3\Games"

[11:38:50.156] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of bh3_cn is "7.7.0".

[11:39:20.663] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (bh3_cn)
path: "E:\Honkai Impact 3\Games\BH3.exe"
arg: null

[11:39:21.266] [INFO] Starward.Pages.GameLauncherPage
Game started ("BH3", 11112)

[11:39:23.275] [INFO] Starward.Services.PlayTimeService
Game process (bh3_cn, 11112) has no window

[11:39:25.282] [INFO] Starward.Services.PlayTimeService
Start to log playtime (bh3_cn, 11112)

[11:39:27.288] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[11:39:49.961] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (bh3_cn)
path: "E:\Honkai Impact 3\Games\BH3.exe"
arg: null

[11:39:50.556] [INFO] Starward.Pages.GameLauncherPage
Game started ("BH3", 10724)

[11:39:52.559] [INFO] Starward.Services.PlayTimeService
Game process (bh3_cn, 10724) has no window

[11:39:54.570] [INFO] Starward.Services.PlayTimeService
Game process (bh3_cn, 10724) has no window

[11:39:56.576] [INFO] Starward.Services.PlayTimeService
Game process (bh3_cn, 10724) has no window

[11:39:58.581] [INFO] Starward.Services.PlayTimeService
Start to log playtime (bh3_cn, 10724)

[11:43:34.006] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[11:43:34.007] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hkrpg_cn

[11:43:34.154] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[11:43:34.154] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hkrpg_cn

[11:43:34.224] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "H:\Star Rail\Game"

[11:43:34.232] [INFO] Starward.Pages.GameLauncherPage
Game is running ("StarRail", 8884)

[11:43:34.253] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "H:\Star Rail\Game"

[11:43:34.258] [INFO] Starward.Pages.GameLauncherPage
Game is running ("StarRail", 8884)

[11:43:34.279] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.4.0".

[11:43:34.280] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.4.0".

[11:43:35.954] [INFO] Starward.Pages.MainPage
Change game region to bh3_cn

[11:43:35.955] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param bh3_cn

[11:43:36.113] [INFO] Starward.Pages.MainPage
Change game region to bh3_cn

[11:43:36.113] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param bh3_cn

[11:43:36.157] [INFO] Starward.Pages.GameLauncherPage
Game install path of bh3_cn: "E:\Honkai Impact 3\Games"

[11:43:36.161] [INFO] Starward.Pages.GameLauncherPage
Game is running ("BH3", 10724)

[11:43:36.163] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of bh3_cn is "7.7.0".

[11:43:36.215] [INFO] Starward.Pages.GameLauncherPage
Game install path of bh3_cn: "E:\Honkai Impact 3\Games"

[11:43:36.223] [INFO] Starward.Pages.GameLauncherPage
Game is running ("BH3", 10724)

[11:43:36.245] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of bh3_cn is "7.7.0".
```

**Comment by Scighost** [comment]
更新到最新的预览版

**Comment by Eric-Joker** [comment]
就算最新正式版也应该修了
