### ISSUE TITLE
[Bug] 502 & Url read failure

### ISSUE THREAD

**Issue by GhostVPN1** [Scighost/Starward#1027]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

Hey! In Genshin I get 502 and after paste the URL new i get Warn that the parsing can't be done.

Reinstall, clear all data and caches, don't help

### Reproduction Steps

Just Refresh

### Starward Version

0.12.1

### Windows Version

Newet

### Log

```shell
[13:13:22.507] [INFO] 
Welcome to Starward v0.12.1
System: Microsoft Windows NT 10.0.22631.0
Command Line: E:\Starward_Portable_0.10.4_x64\Starward_Portable_0.11.6_x64\Starward\app-0.12.1\Starward.dll

[13:13:22.737] [INFO] Starward.Services.DatabaseService
Database path is 'E:\Starward_Portable_0.10.4_x64\Starward_Portable_0.11.6_x64\Starward'

[13:13:22.999] [INFO] Starward.Services.DatabaseService
Database version is 9, target version is 9.

[13:13:23.121] [INFO] Starward.Pages.MainPage
Last game region is hk4e_global

[13:13:23.151] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_global

[13:13:23.765] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_global: "E:\Genshin Impact game"

[13:13:23.784] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_global is "4.8.0".

[13:13:24.725] [INFO] Starward.Services.UpdateService
Start to check update (Preview: False, Arch: X64)

[13:13:25.262] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_global

[13:13:25.310] [INFO] Starward.Services.UpdateService
Current version: "0.12.1", latest version: "0.12.1", ignore version: null

[13:13:28.045] [WARN] Starward.Pages.GachaLogPage
Request mihoyo api error: "Something went wrong...please retry later (-502)"

[13:15:01.798] [INFO] Starward.Pages.Setting.AppearanceSettingPage
Language change to "de-DE"

[13:15:03.960] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_global

[13:15:06.627] [WARN] Starward.Pages.GachaLogPage
Request mihoyo api error: "Something went wrong...please retry later (-502)"

[13:15:33.737] [WARN] Starward.Pages.GachaLogPage
Request mihoyo api error: "Something went wrong...please retry later (-502)"

[13:17:37.710] [WARN] Starward.Pages.GachaLogPage
Request mihoyo api error: "Something went wrong...please retry later (-502)"

[14:11:06.942] [WARN] Starward.Pages.GachaLogPage
Request mihoyo api error: "Something went wrong...please retry later (-502)"

[14:11:23.697] [WARN] Starward.Pages.GachaLogPage
Request mihoyo api error: "Something went wrong...please retry later (-502)"

[14:11:24.548] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_global

[14:11:25.033] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_global

[14:11:25.086] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_global: "E:\Genshin Impact game"

[14:11:25.092] [INFO] Starward.Pages.GameLauncherPage
Game is running ("GenshinImpact", 9492)

[14:11:25.112] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_global is "4.8.0".

[14:11:41.929] [EROR] Starward.Pages.Setting.FileSettingPage
Delete folder '"C:\Users\wawie\AppData\Local\Starward\log"'
System.IO.IOException: The process cannot access the file 'Starward_240810_131322.log' because it is being used by another process.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String, WIN32_FIND_DATA&, Boolean)
   at System.IO.FileSystem.RemoveDirectory(String, Boolean)
   at Starward.Pages.Setting.FileSettingPage.<>c__DisplayClass20_0.<DeleteFolderAsync>b__0() in D:\a\Starward\Starward\src\Starward\Pages\Setting\FileSettingPage.xaml.cs:line 368

[14:11:48.259] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_global

[14:11:50.369] [WARN] Starward.Pages.GachaLogPage
Request mihoyo api error: "Something went wrong...please retry later (-502)"

[14:12:45.250] [EROR] Starward.Pages.GachaLogPage
Input url
System.ArgumentException: Kann die Wunschlisten-Eintrag URL nicht analysieren.
   at Starward.Core.Gacha.Genshin.GenshinGachaClient.GetGachaUrlPrefix(String gachaUrl, String lang) in D:\a\Starward\Starward\src\Starward.Core\Gacha\Genshin\GenshinGachaClient.cs:line 61
   at Starward.Core.Gacha.GachaLogClient.GetUidByGachaUrlAsync(String gachaUrl) in D:\a\Starward\Starward\src\Starward.Core\Gacha\GachaLogClient.cs:line 91
   at Starward.Services.Gacha.GachaLogService.GetUidFromGachaLogUrl(String url) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GachaLogService.cs:line 103
   at Starward.Pages.GachaLogPage.UpdateGachaLogInternalAsync(String url, Boolean all) in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 375
   at Starward.Pages.GachaLogPage.InputUrlAsync() in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 475

[14:17:28.129] [INFO] Starward.Pages.Setting.AppearanceSettingPage
Language change to "en-US"

[14:17:51.879] [EROR] Starward.Pages.Setting.FileSettingPage
Delete folder '"C:\Users\wawie\AppData\Local\Starward\log"'
System.IO.IOException: The process cannot access the file 'Starward_240810_131322.log' because it is being used by another process.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String, WIN32_FIND_DATA&, Boolean)
   at System.IO.FileSystem.RemoveDirectory(String, Boolean)
   at Starward.Pages.Setting.FileSettingPage.<>c__DisplayClass20_0.<DeleteFolderAsync>b__0() in D:\a\Starward\Starward\src\Starward\Pages\Setting\FileSettingPage.xaml.cs:line 368

[14:17:54.239] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_global

[14:17:56.871] [WARN] Starward.Pages.GachaLogPage
Request mihoyo api error: "Something went wrong...please retry later (-502)"

[14:18:01.118] [WARN] Starward.Pages.GachaLogPage
Request mihoyo api error: "Something went wrong...please retry later (-502)"

[14:18:08.364] [WARN] Starward.Pages.GachaLogPage
Request mihoyo api error: "Something went wrong...please retry later (-502)"

[14:18:33.065] [EROR] Starward.Pages.GachaLogPage
Input url
System.ArgumentException: Cannot parse the wish record URL.
   at Starward.Core.Gacha.Genshin.GenshinGachaClient.GetGachaUrlPrefix(String gachaUrl, String lang) in D:\a\Starward\Starward\src\Starward.Core\Gacha\Genshin\GenshinGachaClient.cs:line 61
   at Starward.Core.Gacha.GachaLogClient.GetUidByGachaUrlAsync(String gachaUrl) in D:\a\Starward\Starward\src\Starward.Core\Gacha\GachaLogClient.cs:line 91
   at Starward.Services.Gacha.GachaLogService.GetUidFromGachaLogUrl(String url) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GachaLogService.cs:line 103
   at Starward.Pages.GachaLogPage.UpdateGachaLogInternalAsync(String url, Boolean all) in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 375
   at Starward.Pages.GachaLogPage.InputUrlAsync() in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 475

[14:18:49.796] [EROR] Starward.Pages.GachaLogPage
Input url
System.ArgumentException: Cannot parse the wish record URL.
   at Starward.Core.Gacha.Genshin.GenshinGachaClient.GetGachaUrlPrefix(String gachaUrl, String lang) in D:\a\Starward\Starward\src\Starward.Core\Gacha\Genshin\GenshinGachaClient.cs:line 61
   at Starward.Core.Gacha.GachaLogClient.GetUidByGachaUrlAsync(String gachaUrl) in D:\a\Starward\Starward\src\Starward.Core\Gacha\GachaLogClient.cs:line 91
   at Starward.Services.Gacha.GachaLogService.GetUidFromGachaLogUrl(String url) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GachaLogService.cs:line 103
   at Starward.Pages.GachaLogPage.UpdateGachaLogInternalAsync(String url, Boolean all) in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 375
   at Starward.Pages.GachaLogPage.InputUrlAsync() in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 475
```

**Comment by Eric-Joker** [comment]
try preview vision
