### ISSUE TITLE
[Question] 开拓月历无法正常加载

### ISSUE THREAD

**Issue by CreeperAWA** [Scighost/Starward#1040]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

我的开拓月历无法正常加载，显示如下
![image](https://github.com/user-attachments/assets/3ddc985b-bb3b-4fe0-8645-67264ecea575)
重新登录账号后可用加载，但是再刷新也不行了，更新设备指纹也试过，都不行
但是战绩、末日幻影都是可用加载的，其他的没打，看不出来

### Starward Version

0.12.2-preview.2

### Windows Version

版本	Windows 11 专业工作站版 版本号	23H2 安装日期	‎2024-‎07-‎29 操作系统版本	22635.4010 体验	Windows Feature Experience Pack 1000.22700.1035.0

### Log

```shell
[11:54:58.683] [EROR] Starward.Pages.HoyolabToolbox.TrailblazeCalendarPage
Get realtime trailblaze calendar data ("hkrpg_cn", 138477977).
Starward.Core.miHoYoApiException: 请先登录 (-100)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 170
   at Starward.Core.GameRecord.HyperionClient.GetTrailblazeCalendarSummaryAsync(GameRecordRole role, String month, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 455
   at Starward.Services.GameRecordService.GetTrailblazeCalendarSummaryAsync(GameRecordRole role, String month) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 668
   at Starward.Pages.HoyolabToolbox.TrailblazeCalendarPage.GetCurrentSummaryAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\TrailblazeCalendarPage.xaml.cs:line 123
```

**Comment by CreeperAWA** [comment]
我今日更新了最新的预览版`0.12.2 Preview 3`，该问题仍出现

**Comment by CreeperAWA** [comment]
问题已解决
