### ISSUE TITLE
[Bug] 因战绩更新，导致启动器无法正常使用部分功能

### ISSUE THREAD

**Issue by CreeperAWA** [Scighost/Starward#1042]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

米哈游更新了战绩功能，导致启动器的战绩功能无法正常使用，不知是不是UA的问题

我在我手机比较新的版本的米游社抓到的UA是`okhttp/4.9.3`
~~不一定能用，技术不到家，猜测~~

### Reproduction Steps

打开启动器的米游社工具箱，点击战绩，在我的角色一栏点击“全部角色”

### Expected Behavior

正常使用全部功能，如下图
![F928D6E15848B4022CC48970E4A85C14](https://github.com/user-attachments/assets/e0b467dd-d5c7-495e-9e2b-e272e1881c70)
点击角色可以进入
![134FAEE7E356DC92E9856A603A18A18B](https://github.com/user-attachments/assets/fddd099a-5214-48b8-9a0a-92bb94389e12)

### Screenshots

![image](https://github.com/user-attachments/assets/2d3db0ca-02fd-46ad-aa1d-9bed794412bd)

### Starward Version

0.12.2-preview.2

### Windows Version

22635.4076

### Log

```shell
[14:36:38.737] [INFO] 
Welcome to Starward v0.12.2-preview.2
System: Microsoft Windows NT 10.0.22635.0
Command Line: D:\information\Starward\app-0.12.2-preview.2\Starward.dll

[14:36:38.798] [INFO] Starward.Services.DatabaseService
Database path is 'D:\information\Starward'

[14:36:38.857] [INFO] Starward.Services.DatabaseService
Database version is 9, target version is 9.

[14:36:38.941] [INFO] Starward.Pages.MainPage
Last game region is hkrpg_cn

[14:36:38.951] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hkrpg_cn

[14:36:39.700] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "D:\information\MiHoYoGAME\Honkai Star Rail"

[14:36:39.720] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.4.0".

[14:36:40.650] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[14:36:41.638] [INFO] Starward.Services.UpdateService
Current version: "0.12.2-preview.2", latest version: "0.12.2-preview.2", ignore version: null

[14:36:42.144] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hkrpg_cn

[14:36:42.155] [INFO] Starward.Services.GameRecordService
Change region to China.

[14:36:43.224] [EROR] Starward.Services.HoYoPlayService
PrepareDataForServerAsync
System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.Net.Http.HttpIOException: The response ended prematurely while waiting for the next frame from the server. (ResponseEnded)
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception )
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders()
   at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task, MemoryStream)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage, HttpCompletionOption, CancellationTokenSource, Boolean, CancellationTokenSource, CancellationToken)
   at Starward.Core.HoYoPlay.HoYoPlayClient.CommonGetAsync[T](String url, String node, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\HoYoPlay\HoYoPlayClient.cs:line 45
   at Starward.Core.HoYoPlay.HoYoPlayClient.GetGamePackageAsync(String launcherId, String language, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\HoYoPlay\HoYoPlayClient.cs:line 159
   at Starward.Services.HoYoPlayService.PrepareDataForServerAsync(String launcherId, String language) in D:\a\Starward\Starward\src\Starward\Services\HoYoPlayService.cs:line 113

[14:36:43.236] [EROR] Starward.Services.HoYoPlayService
PrepareDataForBilibiliServerAsync
System.Net.Http.HttpRequestException: The response ended prematurely while waiting for the next frame from the server. (ResponseEnded)
 ---> System.Net.Http.HttpIOException: The response ended prematurely while waiting for the next frame from the server. (ResponseEnded)
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception )
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders()
   at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage, Boolean, Boolean, CancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage, HttpCompletionOption, CancellationTokenSource, Boolean, CancellationTokenSource, CancellationToken)
   at Starward.Core.HoYoPlay.HoYoPlayClient.CommonGetAsync[T](String url, String node, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\HoYoPlay\HoYoPlayClient.cs:line 45
   at Starward.Core.HoYoPlay.HoYoPlayClient.GetGameBackgroundAsync(String launcherId, String language, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\HoYoPlay\HoYoPlayClient.cs:line 109
   at Starward.Services.HoYoPlayService.PrepareDataForBilibiliServerAsync(String language) in D:\a\Starward\Starward\src\Starward\Services\HoYoPlayService.cs:line 144
```

**Comment by Scighost** [comment]
这个页面就是会这样，我也不知道怎么办，但不影响使用

**Comment by CreeperAWA** [comment]
换下UA看看？
