### ISSUE TITLE
[Bug] 星穹鐵道國際服帳號紀錄無法拉取

### ISSUE THREAD

**Issue by acheron240401** [Scighost/Starward#1079]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

Starward 內初次導入帳號紀錄，依照 APP 指示操作會出現錯誤訊息。

```
miHoYoApiException - Input URL
Something went wrong … please retry later (-502)
```

此問題與 #1011 相關，該問題的遊戲服為 hkrpg_cn，在 [0.12.2 Preview 3](https://github.com/Scighost/Starward/releases/tag/0.12.2-preview.3) 被修復，此問題的遊戲服為 hkrpg_global

### Reproduction Steps

1. 在遊戲內使用問題回報，導向到瀏覽器的問題回報首頁
2. 複製完整 URL，貼到 Starward 裡
3. 重現 Bug

### Screenshots

輸入 URL 後出現錯誤警示
![螢幕擷取畫面 2024-09-05 172126](https://github.com/user-attachments/assets/6a4fac12-1cd6-40c1-98c2-c597a931aa87)

在瀏覽器進入自助查詢頁面，功能正常
![螢幕擷取畫面 2024-09-05 172320](https://github.com/user-attachments/assets/07510ddd-186e-4e9d-a329-731bbad1b87b)

### Starward Version

0.13.1

### Windows Version

22631.4037

### Log

```shell
[17:19:37.358] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_global

[17:19:37.358] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hkrpg_global

[17:19:37.411] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_global: "X:\Program Files\Star Rail\Games"

[17:19:37.440] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_global is "2.4.0".

[17:21:10.819] [INFO] Starward.Pages.MainPage
Navigate to "SelfQueryPage" with param hkrpg_global

[17:21:16.530] [EROR] Starward.Pages.SelfQueryPage
Input url
Starward.Core.miHoYoApiException: Something went wrong...please retry later (-502)
   at Starward.Core.SelfQuery.SelfQueryClient.CommonGetAsync[T](String url, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\SelfQuery\SelfQueryClient.cs:line 41
   at Starward.Core.SelfQuery.SelfQueryClient.GetStarRailUserInfoAsync(CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\SelfQuery\SelfQueryClient.cs:line 209
   at Starward.Core.SelfQuery.SelfQueryClient.InitializeAsync(String url, GameBiz gameBiz, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\SelfQuery\SelfQueryClient.cs:line 104
   at Starward.Services.SelfQueryService.InitializeAsync(String url, GameBiz gameBiz) in D:\a\Starward\Starward\src\Starward\Services\SelfQueryService.cs:line 40
   at Starward.Pages.SelfQueryPage.InputURLAsync() in D:\a\Starward\Starward\src\Starward\Pages\SelfQueryPage.xaml.cs:line 340
```

**Comment by Scighost** [comment]
#1077
