### ISSUE TITLE
[Bug] 无法更新崩坏3

### ISSUE THREAD

**Issue by herta0426** [Scighost/Starward#1098]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

之前预下载了
然后现在是这个 不知道怎么解决

### Reproduction Steps

点击更新显示这个

### Expected Behavior

更新完成

### Screenshots

![image](https://github.com/user-attachments/assets/600d9022-a2a0-441e-a664-5817e6883d13)

### Starward Version

0.13.2

### Windows Version

22635.4145

### Log

```shell
[17:23:03.570] [INFO] 
Welcome to Starward v0.13.2
System: Microsoft Windows NT 10.0.22635.0
Command Line: C:\Starward\app-0.13.2\Starward.dll

[17:23:03.599] [INFO] Starward.Services.DatabaseService
Database path is 'C:\Starward'

[17:23:03.620] [INFO] Starward.Services.DatabaseService
Database version is 10, target version is 10.

[17:23:03.678] [INFO] Starward.Pages.MainPage
Last game region is bh3_cn

[17:23:03.689] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param bh3_cn

[17:23:04.250] [INFO] Starward.Pages.GameLauncherPage
Game install path of bh3_cn: "C:\BH3"

[17:23:04.273] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of bh3_cn is "7.7.0".

[17:23:05.208] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[17:23:06.154] [INFO] Starward.Services.UpdateService
Current version: "0.13.2", latest version: "0.13.2", ignore version: null

[17:23:38.219] [EROR] Starward.Services.Download.InstallGameService
ExecuteTaskItemAsync
System.IO.IOException: The process cannot access the file 'C:\BH3\BH3_Data\StreamingAssets\ThirdPartyNotice\ZFBrowser\ThirdPartyNotices.txt' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String, FileMode, FileAccess, FileShare, FileOptions)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1 )
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.File.Create(String)
   at Starward.SevenZip.ArchiveFile.Extract(Func`2 getOutputPath, CancellationToken Token)
   at Starward.SevenZip.ArchiveFile.Extract(String outputFolder, Boolean overwrite)
   at Starward.Services.Download.InstallGameService.<>c__DisplayClass91_0.<DecompressItemAsync>b__0() in D:\a\Starward\Starward\src\Starward\Services\Download\InstallGameService.cs:line 1313
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
--- End of stack trace from previous location ---
   at Starward.Services.Download.InstallGameService.DecompressItemAsync(InstallGameItem item, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\Download\InstallGameService.cs:line 1302
   at Starward.Services.Download.InstallGameService.ExecuteTaskItemAsync(CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\Download\InstallGameService.cs:line 1131
```

**Comment by Scighost** [comment]
重启计算机

**Comment by herta0426** [comment]
重启之后不显示更新 打不开游戏 有进程
 然后我点击了修复报错未知 然后我点击了三角形下载了1G的文件 然后就打开游戏到第二屏就卡死
 `[17:36:18.980] [INFO] 
Welcome to Starward v0.13.2
System: Microsoft Windows NT 10.0.22635.0
Command Line: C:\Starward\app-0.13.2\Starward.dll

[17:36:19.040] [INFO] Starward.Services.DatabaseService
Database path is 'C:\Starward'

[17:36:19.094] [INFO] Starward.Services.DatabaseService
Database version is 10, target version is 10.

[17:36:19.229] [INFO] Starward.Pages.MainPage
Last game region is bh3_cn

[17:36:19.256] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param bh3_cn

[17:36:20.052] [INFO] Starward.Pages.GameLauncherPage
Game install path of bh3_cn: "C:\BH3"

[17:36:20.071] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of bh3_cn is "7.8.0".

[17:36:20.983] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[17:36:22.107] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (bh3_cn)
path: "C:\BH3\BH3.exe"
arg: null

[17:36:24.053] [INFO] Starward.Services.Launcher.GameLauncherService
Start game operation canceled.

[17:36:24.807] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (bh3_cn)
path: "C:\BH3\BH3.exe"
arg: null

[17:36:25.893] [INFO] Starward.Pages.GameLauncherPage
Game started ("BH3", 12924)

[17:36:27.903] [INFO] Starward.Services.PlayTimeService
Game process (bh3_cn, 12924) has no window

[17:36:29.923] [INFO] Starward.Services.PlayTimeService
Game process (bh3_cn, 12924) has no window

[17:36:31.931] [INFO] Starward.Services.PlayTimeService
Game process (bh3_cn, 12924) has no window

[17:36:33.940] [INFO] Starward.Services.PlayTimeService
Game process (bh3_cn, 12924) has no window

[17:36:35.948] [INFO] Starward.Services.PlayTimeService
Game process (bh3_cn, 12924) has no window

[17:36:37.961] [INFO] Starward.Services.PlayTimeService
Game process (bh3_cn, 12924) has no window

[17:36:39.973] [INFO] Starward.Services.PlayTimeService
Game process (bh3_cn, 12924) has no window

[17:36:41.983] [INFO] Starward.Services.PlayTimeService
Game process (bh3_cn, 12924) has no window

[17:36:43.689] [INFO] Starward.Services.UpdateService
Current version: "0.13.2", latest version: "0.13.2", ignore version: null

[17:36:44.001] [INFO] Starward.Services.PlayTimeService
Game process (bh3_cn, 12924) has no window

[17:36:46.014] [INFO] Starward.Services.PlayTimeService
Game process (bh3_cn, 12924) has no window

[17:37:11.174] [EROR] Starward.Services.Download.InstallGameService
ExecuteTaskItemAsync
System.IO.IOException: The process cannot access the file 'C:\BH3\BH3.exe' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String)
   at Starward.Services.Download.InstallGameService.VerifyItemAsync(InstallGameItem item, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\Download\InstallGameService.cs:line 1256
   at Starward.Services.Download.InstallGameService.ExecuteTaskItemAsync(CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\Download\InstallGameService.cs:line 1123

[17:37:19.017] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[17:37:19.025] [INFO] Starward.Pages.GameLauncherPage
Game is running ("BH3", 12924)

[17:37:20.028] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[17:37:20.034] [INFO] Starward.Pages.GameLauncherPage
Game is running ("BH3", 12924)

[17:37:21.045] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[17:38:00.480] [INFO] Starward.Pages.GameLauncherPage
Game install path of bh3_cn: "C:\BH3"

[17:38:00.482] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of bh3_cn is "7.8.0".

[17:38:00.560] [INFO] Starward.Services.Download.InstallGameService
Write config.ini (game_version="7.8.0")

[17:38:02.828] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (bh3_cn)
path: "C:\BH3\BH3.exe"
arg: null

[17:38:03.667] [INFO] Starward.Pages.GameLauncherPage
Game started ("BH3", 23104)

[17:38:05.683] [INFO] Starward.Services.PlayTimeService
Game process (bh3_cn, 23104) has no window

[17:38:07.700] [INFO] Starward.Services.PlayTimeService
Game process (bh3_cn, 23104) has no window

[17:38:09.711] [INFO] Starward.Services.PlayTimeService
Start to log playtime (bh3_cn, 23104)

[17:41:55.718] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[17:41:55.723] [INFO] Starward.Pages.GameLauncherPage
Game is running ("BH3", 23104)

[17:41:56.726] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[17:42:08.000] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (bh3_cn)
path: "C:\BH3\BH3.exe"
arg: null

[17:42:08.949] [INFO] Starward.Pages.GameLauncherPage
Game started ("BH3", 18616)

[17:42:10.955] [INFO] Starward.Services.PlayTimeService
Game process (bh3_cn, 18616) has no window

[17:42:12.973] [INFO] Starward.Services.PlayTimeService
Game process (bh3_cn, 18616) has no window

[17:42:14.982] [INFO] Starward.Services.PlayTimeService
Game process (bh3_cn, 18616) has no window

[17:42:16.992] [INFO] Starward.Services.PlayTimeService
Start to log playtime (bh3_cn, 18616)

[17:42:41.002] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[17:42:41.007] [INFO] Starward.Pages.GameLauncherPage
Game is running ("BH3", 18616)

[17:42:42.017] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[17:42:42.023] [INFO] Starward.Pages.GameLauncherPage
Game is running ("BH3", 18616)

[17:42:43.036] [INFO] Starward.Pages.GameLauncherPage
Game process exited

`

**Comment by herta0426** [comment]
是不是电脑本身的问题

**Comment by Scighost** [comment]
在崩坏三的游戏文件夹里找到一个7z压缩包，解压它，然后再开游戏。

**Comment by herta0426** [comment]
谢谢
