### ISSUE TITLE
[Bug] Starward 在 Windows 11 24H2 LTSC 版本下无法正常显示'.webp'格式图片的背景。

### ISSUE THREAD

**Issue by Privia2023** [Scighost/Starward#1120]
### Checklist

- [ ] My issue was not mentioned by others, and it is not a duplicate issue.

### **您好！**

  Starward 是一款极其舒适的软件，它显著提升了我玩米家游戏的体验。不过在使用过程中，我遇到了一些问题，希望您能提供帮助。
 ## **问题描述：**
  在 ` Win11 24H2 LTSC（26100.1882) `系统环境下，软件无法正常显示背景。

   如图所示：
![QQ20241007-104026](https://github.com/user-attachments/assets/148d79eb-7a07-4b06-9909-61472f580232)
 
>  即使在旧版本软件（0.13.1和0.13.2）也有同样的情况。

### Reproduction Steps

  Starward的背景图片放在 `Staward.exe` 同目录下的 `bg` 文件夹中，里面的`webp`格式的图片也全都是正常的，我尝试删除此文件夹，再让软件重新加载也没有作用。
  # 我尝试将`bg`文件夹中`webp`格式的图片转换为`jpg` 和 `png`格式，这两种格式都可以在Starward中正常显示。
  如图所示：

![QQ20241007-204659](https://github.com/user-attachments/assets/2c2f7921-8555-4d34-9688-3473f1c8f020)
![QQ20241007-204713](https://github.com/user-attachments/assets/24f8660b-8adf-4029-92f7-f4659c5b682f)

  

## 我希望Starward在未来的版本中加载的壁纸默认为`.jpg`或`.png`格式而不是`.webp`格式，这样可能会占用更多的空间，但会带来更好的兼容性。~~都玩米游了应该也不在乎那几M存储吧。~~

> 感谢您的辛勤付出，在这里预祝您开发顺利！

### PC信息截图

![QQ20241007-105534](https://github.com/user-attachments/assets/3d4465d3-38e7-4361-8288-8df8f4467486)

### Starward版本截图

![QQ20241007-105631](https://github.com/user-attachments/assets/a491e747-cd65-4f7c-89f4-e06c4f816003)

### Starward Version

0.13.3

### Windows Version

26100.1882

### Log

```shell
[20:44:51.700] [INFO] 
Welcome to Starward v0.13.3
System: Microsoft Windows NT 10.0.26100.0
Command Line: D:\Starward\app-0.13.3\Starward.dll

[20:44:51.724] [INFO] Starward.Services.DatabaseService
Database path is 'D:\Starward'

[20:44:51.741] [INFO] Starward.Services.DatabaseService
Database version is 11, target version is 11.

[20:44:51.797] [INFO] Starward.Pages.MainPage
Last game region is hk4e_cn

[20:44:51.806] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[20:44:52.099] [WARN] Starward.Services.Launcher.LauncherBackgroundService
Image file not found '"D:\Starward\bg\5654891ffe29faf96ae228a6b73fc8d1_6347965862737474043.png"'

[20:44:52.292] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "D:\miHoYo Launcher\games\Genshin Impact Game"

[20:44:52.304] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.0.0".

[20:44:52.693] [WARN] Starward.Pages.MainPage
Update background image
System.Runtime.InteropServices.COMException (0x88982F8B)
   at Starward.Pages.MainPage.UpdateBackgroundImageAsync(Boolean force) in D:\a\Starward\Starward\src\Starward\Pages\MainPage.xaml.cs:line 369

[20:44:53.249] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[20:44:53.496] [INFO] Starward.Services.UpdateService
Current version: "0.13.3", latest version: "0.13.3", ignore version: null

[20:44:56.236] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[20:44:56.236] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hkrpg_cn

[20:44:56.306] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "D:\miHoYo Launcher\games\Star Rail Game"

[20:44:56.327] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.5.0".

[20:44:56.800] [WARN] Starward.Pages.MainPage
Update background image
System.Runtime.InteropServices.COMException (0x88982F8B)
   at Starward.Pages.MainPage.UpdateBackgroundImageAsync(Boolean force) in D:\a\Starward\Starward\src\Starward\Pages\MainPage.xaml.cs:line 369

[20:45:55.916] [INFO] Starward.Services.LauncherContentService
Background file is '"D:\FFOutput\1cf14bbb767beb41ee5a1a1283574acc_442317181806551180.jpg"'

[20:45:55.919] [INFO] Starward.Services.LauncherContentService
File copied to '"D:\Starward\bg\1cf14bbb767beb41ee5a1a1283574acc_442317181806551180.jpg"'

[20:46:14.081] [INFO] Starward.Pages.MainPage
Change game region to nap_cn

[20:46:14.082] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param nap_cn

[20:46:14.128] [WARN] Starward.Pages.MainPage
Update background image
System.Runtime.InteropServices.COMException (0x88982F8B)
   at Starward.Pages.MainPage.UpdateBackgroundImageAsync(Boolean force) in D:\a\Starward\Starward\src\Starward\Pages\MainPage.xaml.cs:line 369

[20:46:14.145] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "D:\miHoYo Launcher\games\ZenlessZoneZero Game"

[20:46:14.161] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.2.0".

[20:46:14.921] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[20:46:14.922] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hkrpg_cn

[20:46:14.990] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "D:\miHoYo Launcher\games\Star Rail Game"

[20:46:14.996] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.5.0".

[20:46:15.386] [INFO] Starward.Pages.MainPage
Change game region to nap_cn

[20:46:15.386] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param nap_cn

[20:46:15.398] [WARN] Starward.Pages.MainPage
Update background image
System.Runtime.InteropServices.COMException (0x88982F8B)
   at Starward.Pages.MainPage.UpdateBackgroundImageAsync(Boolean force) in D:\a\Starward\Starward\src\Starward\Pages\MainPage.xaml.cs:line 369

[20:46:15.444] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "D:\miHoYo Launcher\games\ZenlessZoneZero Game"

[20:46:15.457] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.2.0".

[20:46:23.994] [WARN] Starward.Pages.MainPage
Update background image
System.Runtime.InteropServices.COMException (0x88982F8B)
   at Starward.Pages.MainPage.UpdateBackgroundImageAsync(Boolean force) in D:\a\Starward\Starward\src\Starward\Pages\MainPage.xaml.cs:line 369

[20:46:26.745] [INFO] Starward.Services.LauncherContentService
Background file is '"D:\FFOutput\灵砂.png"'

[20:46:26.789] [INFO] Starward.Services.LauncherContentService
File copied to '"D:\Starward\bg\灵砂.png"'

[20:47:08.543] [INFO] Starward.Services.LauncherContentService
Background file is '"D:\FFOutput\凯撒.jpg"'

[20:47:08.546] [INFO] Starward.Services.LauncherContentService
File copied to '"D:\Starward\bg\凯撒.jpg"'


```

### Additional Context

可以加一个自主开关日志记录按钮吗？每次玩完一堆文本怪难受的。

**Comment by Eric-Joker** [comment]
去微软应用商店安装webp扩展

**Comment by Eric-Joker** [comment]
duplicate #1069 #880

**Comment by Privia2023** [comment]
原来是这样，应该是Windows LTSC没有自带这个扩展，导致没显示出来，问题已经解决！谢谢你啦（）

**Comment by Privia2023** [comment]
还有一个，就是可以添加日志记录开关按钮
还有把原神fps帧率解锁放到软件里吗？这个还是挺需要的（）

**Comment by Eric-Joker** [comment]
1.我说的不算，但是日志也不碍事吧？静默写入文件也不体现在UI。
2.所以你为什么不能去实现勾选“My issue was not mentioned by others, and it is not a duplicate issue.”呢？

**Comment by Privia2023** [comment]
好的，谢谢！
