### ISSUE TITLE
[Bug] 游戏版本更新时更新一个区服完成后，另一使用硬链接的区服仍需下载完整更新包进行更新

### ISSUE THREAD

**Issue by Happylifezzq** [Scighost/Starward#1123]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

使用硬链接的同一游戏两个不同区服，游戏版本更新时选择更新其中一个区服，更新完成后，另一区服（使用硬链接）仍需下载完整更新包进行更新

### Reproduction Steps

1. 找到待更新的两个区服（我这里是原神官服和B服，B服是硬链接）
2. 完成官服游戏更新
3. 发现另一区服（B服）状态为待更新，点击更新
4. 启动器开始下载完整更新包

### Expected Behavior

官服更新完成后B服也同步完成更新，**无需再次下载完整更新包**

### Starward Version

0.13.3

### Windows Version

22631.4037

### Log

```shell
[09:00:02.184] [INFO] 
Welcome to Starward v0.13.3
System: Microsoft Windows NT 10.0.22631.0
Command Line: D:\Starward\app-0.13.3\Starward.dll

[09:00:02.242] [INFO] Starward.Services.DatabaseService
Database path is 'D:\Starward'

[09:00:02.284] [INFO] Starward.Services.DatabaseService
Database version is 11, target version is 11.

[09:00:02.357] [INFO] Starward.Pages.MainPage
Last game region is hk4e_bilibili

[09:00:02.371] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_bilibili

[09:00:03.337] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_bilibili: "E:\Program Files\Genshin Impact bilibili\games\Genshin Impact"

[09:00:03.353] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_bilibili is "5.0.0".

[09:00:04.282] [INFO] Starward.Services.UpdateService
Start to check update (Preview: False, Arch: X64)

[09:00:05.179] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[09:00:05.179] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[09:00:05.257] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "E:\Genshin Impact Game"

[09:00:05.267] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.1.0".

[09:00:06.076] [INFO] Starward.Services.UpdateService
Current version: "0.13.3", latest version: "0.13.3", ignore version: null

[09:00:06.147] [INFO] Starward.Pages.MainPage
Change game region to hk4e_bilibili

[09:00:06.148] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_bilibili

[09:00:06.218] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_bilibili: "E:\Program Files\Genshin Impact bilibili\games\Genshin Impact"

[09:00:06.229] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_bilibili is "5.0.0".

[09:00:07.537] [EROR] Starward.Services.HoYoPlayService
Download image: ""
System.InvalidOperationException: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage)
   at System.Net.Http.HttpClient.GetByteArrayAsync(Uri , CancellationToken)
   at Starward.Services.HoYoPlayService.<>c__DisplayClass14_0.<<PrepareImagesAsync>b__0>d.MoveNext() in D:\a\Starward\Starward\src\Starward\Services\HoYoPlayService.cs:line 201

[09:00:21.051] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[09:00:21.051] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[09:00:21.119] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "E:\Genshin Impact Game"

[09:00:21.162] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.1.0".

[09:00:21.900] [INFO] Starward.Pages.MainPage
Change game region to hk4e_bilibili

[09:00:21.901] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_bilibili

[09:00:21.969] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_bilibili: "E:\Program Files\Genshin Impact bilibili\games\Genshin Impact"

[09:00:21.977] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_bilibili is "5.0.0".

[09:00:59.954] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[09:00:59.955] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[09:01:00.025] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "E:\Genshin Impact Game"

[09:01:00.052] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.1.0".

[09:01:00.970] [INFO] Starward.Pages.MainPage
Change game region to hk4e_bilibili

[09:01:00.970] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_bilibili

[09:01:01.038] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_bilibili: "E:\Program Files\Genshin Impact bilibili\games\Genshin Impact"

[09:01:01.046] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_bilibili is "5.0.0".

[09:01:01.778] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[09:01:01.779] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[09:01:01.855] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "E:\Genshin Impact Game"

[09:01:01.881] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.1.0".

[09:01:23.754] [INFO] Starward.Pages.MainPage
Change game region to hk4e_bilibili

[09:01:23.754] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_bilibili

[09:01:23.827] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_bilibili: "E:\Program Files\Genshin Impact bilibili\games\Genshin Impact"

[09:01:23.833] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_bilibili is "5.0.0".

[09:01:24.947] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[09:01:24.948] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[09:01:25.016] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "E:\Genshin Impact Game"

[09:01:25.044] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.1.0".

[09:01:26.035] [INFO] Starward.Pages.MainPage
Change game region to hk4e_bilibili

[09:01:26.035] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_bilibili

[09:01:26.097] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_bilibili: "E:\Program Files\Genshin Impact bilibili\games\Genshin Impact"

[09:01:26.114] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_bilibili is "5.0.0".

[09:01:26.753] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[09:01:26.753] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[09:01:26.821] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "E:\Genshin Impact Game"

[09:01:26.868] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.1.0".

[09:01:27.706] [INFO] Starward.Pages.MainPage
Change game region to hk4e_bilibili

[09:01:27.706] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_bilibili

[09:01:27.781] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_bilibili: "E:\Program Files\Genshin Impact bilibili\games\Genshin Impact"

[09:01:27.788] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_bilibili is "5.0.0".

[09:01:28.676] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[09:01:28.676] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[09:01:28.750] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "E:\Genshin Impact Game"

[09:01:28.773] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.1.0".

[09:01:29.251] [INFO] Starward.Pages.MainPage
Change game region to hk4e_bilibili

[09:01:29.251] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_bilibili

[09:01:29.331] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_bilibili: "E:\Program Files\Genshin Impact bilibili\games\Genshin Impact"

[09:01:29.337] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_bilibili is "5.0.0".

[09:01:30.114] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[09:01:30.114] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hkrpg_cn

[09:01:30.188] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "E:\Star Rail"

[09:01:30.206] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.5.0".

[09:01:30.793] [INFO] Starward.Pages.MainPage
Change game region to bh3_cn

[09:01:30.794] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param bh3_cn

[09:01:30.861] [INFO] Starward.Pages.GameLauncherPage
Game install path of bh3_cn: "E:\Honkai Impact 3\Games"

[09:01:30.880] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of bh3_cn is "7.8.0".

[09:01:31.410] [INFO] Starward.Pages.MainPage
Change game region to nap_cn

[09:01:31.411] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param nap_cn

[09:01:31.474] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "E:\Program Files\miHoYo Launcher\games\ZenlessZoneZero Game"

[09:01:31.499] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.2.0".

[09:01:32.322] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[09:01:32.323] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[09:01:32.404] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "E:\Genshin Impact Game"

[09:01:32.430] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.1.0".

[09:01:33.906] [INFO] Starward.Pages.MainPage
Change game region to hk4e_bilibili

[09:01:33.906] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_bilibili

[09:01:33.970] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_bilibili: "E:\Program Files\Genshin Impact bilibili\games\Genshin Impact"

[09:01:33.982] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_bilibili is "5.0.0".

[09:03:54.257] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[09:03:54.258] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[09:03:54.332] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "E:\Genshin Impact Game"

[09:03:54.379] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.1.0".

[09:08:10.248] [INFO] Starward.Pages.MainPage
Change game region to hk4e_bilibili

[09:08:10.249] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_bilibili

[09:08:10.325] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_bilibili: "E:\Program Files\Genshin Impact bilibili\games\Genshin Impact"

[09:08:10.333] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_bilibili is "5.0.0".

[09:08:17.904] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[09:08:17.904] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[09:08:17.974] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "E:\Genshin Impact Game"

[09:08:18.022] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.1.0".

[09:10:03.526] [EROR] Starward.Services.HoYoPlayService
Download image: ""
System.InvalidOperationException: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage)
   at System.Net.Http.HttpClient.GetByteArrayAsync(Uri , CancellationToken)
   at Starward.Services.HoYoPlayService.<>c__DisplayClass14_0.<<PrepareImagesAsync>b__0>d.MoveNext() in D:\a\Starward\Starward\src\Starward\Services\HoYoPlayService.cs:line 201

[09:10:27.407] [INFO] Starward.Pages.MainPage
Change game region to hk4e_bilibili

[09:10:27.407] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_bilibili

[09:10:27.474] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_bilibili: "E:\Program Files\Genshin Impact bilibili\games\Genshin Impact"

[09:10:27.480] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_bilibili is "5.0.0".

[09:10:29.095] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[09:10:29.096] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[09:10:29.168] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "E:\Genshin Impact Game"

[09:10:29.196] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.1.0".

[09:10:30.169] [INFO] Starward.Pages.MainPage
Change game region to hk4e_bilibili

[09:10:30.170] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_bilibili

[09:10:30.245] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_bilibili: "E:\Program Files\Genshin Impact bilibili\games\Genshin Impact"

[09:10:30.258] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_bilibili is "5.0.0".

[09:10:31.544] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[09:10:31.544] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[09:10:31.617] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "E:\Genshin Impact Game"

[09:10:31.642] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.1.0".

[09:10:32.144] [INFO] Starward.Pages.MainPage
Change game region to hk4e_bilibili

[09:10:32.144] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_bilibili

[09:10:32.215] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_bilibili: "E:\Program Files\Genshin Impact bilibili\games\Genshin Impact"

[09:10:32.222] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_bilibili is "5.0.0".
```

### Additional Context

感觉功能实现上和 #1121 有些联系？

**Comment by link-fgfgui** [comment]
解决方法其实很简单,卸载硬链接的区服并基于已经更新好的区服重新进行 下载-勾选硬链接 操作即可

根据游戏文件夹中的config.ini Starward可以识别此区服是否是硬链接及源区服是谁,建议在程序内部集成此逻辑

**Comment by Scighost** [comment]
已优化
