### ISSUE TITLE
[Bug] 原神5.1版本无法更新

### ISSUE THREAD

**Issue by Starfallan** [Scighost/Starward#1125]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

经搜索，在4.6版本层出现相关问题， #762 

但是issue中显示了已经修复了相关的问题

但是我似乎在5.1版本再次复现了这个问题，在提前预下载完成，在今天点击更新的时候，就是无法点击的。
没有进行任何其他操作，但因为没有别的人提到这个问题，也许是一个个例？

### Reproduction Steps

1.提前进行预下载，顺利完成
2.点击更新游戏，无任何反应

### Starward Version

0.13.3

### Windows Version

24H2  26120.1930

### Log

```shell
[20:08:11.167] [INFO] 
Welcome to Starward v0.13.3
System: Microsoft Windows NT 10.0.26120.0
Command Line: E:\GameTool\Starward\app-0.13.3\Starward.dll

[20:08:11.291] [INFO] Starward.Services.DatabaseService
Database path is 'E:\GameTool\Starward'

[20:08:11.396] [INFO] Starward.Services.DatabaseService
Database version is 11, target version is 11.

[20:08:11.713] [INFO] Starward.Pages.MainPage
Last game region is hk4e_cn

[20:08:11.775] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[20:08:14.022] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "D:\Programs\Genshin Impact\Genshin Impact Game"

[20:08:14.072] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.0.0".

[20:08:14.884] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[20:08:15.616] [INFO] Starward.Services.UpdateService
Current version: "0.13.3", latest version: "0.13.3", ignore version: null

[20:08:29.297] [EROR] Starward.Pages.GameLauncherPage
Update
System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.FileSystem.MoveFile(String, String, Boolean)
   at Starward.Services.Download.GenshinInstallGameService.<>c__DisplayClass5_0.<MoveAudioAssetsFromPersistentToStreamAssetsAsync>b__0() in D:\a\Starward\Starward\src\Starward\Services\Download\GenshinInstallGameService.cs:line 202
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
--- End of stack trace from previous location ---
   at Starward.Services.Download.GenshinInstallGameService.MoveAudioAssetsFromPersistentToStreamAssetsAsync() in D:\a\Starward\Starward\src\Starward\Services\Download\GenshinInstallGameService.cs:line 194
   at Starward.Services.Download.GenshinInstallGameService.StartUpdateGameAsync(CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\Download\GenshinInstallGameService.cs:line 71
   at Starward.Pages.GameLauncherPage.UpdateAsync() in D:\a\Starward\Starward\src\Starward\Pages\GameLauncherPage.xaml.cs:line 940

[20:09:04.179] [EROR] Starward.Pages.GameLauncherPage
Update
System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.FileSystem.MoveFile(String, String, Boolean)
   at Starward.Services.Download.GenshinInstallGameService.<>c__DisplayClass5_0.<MoveAudioAssetsFromPersistentToStreamAssetsAsync>b__0() in D:\a\Starward\Starward\src\Starward\Services\Download\GenshinInstallGameService.cs:line 202
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
--- End of stack trace from previous location ---
   at Starward.Services.Download.GenshinInstallGameService.MoveAudioAssetsFromPersistentToStreamAssetsAsync() in D:\a\Starward\Starward\src\Starward\Services\Download\GenshinInstallGameService.cs:line 194
   at Starward.Services.Download.GenshinInstallGameService.StartUpdateGameAsync(CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\Download\GenshinInstallGameService.cs:line 71
   at Starward.Pages.GameLauncherPage.UpdateAsync() in D:\a\Starward\Starward\src\Starward\Pages\GameLauncherPage.xaml.cs:line 940

[20:18:19.099] [EROR] Starward.Pages.GameLauncherPage
Update
System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.FileSystem.MoveFile(String, String, Boolean)
   at Starward.Services.Download.GenshinInstallGameService.<>c__DisplayClass5_0.<MoveAudioAssetsFromPersistentToStreamAssetsAsync>b__0() in D:\a\Starward\Starward\src\Starward\Services\Download\GenshinInstallGameService.cs:line 202
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
--- End of stack trace from previous location ---
   at Starward.Services.Download.GenshinInstallGameService.MoveAudioAssetsFromPersistentToStreamAssetsAsync() in D:\a\Starward\Starward\src\Starward\Services\Download\GenshinInstallGameService.cs:line 194
   at Starward.Services.Download.GenshinInstallGameService.StartUpdateGameAsync(CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\Download\GenshinInstallGameService.cs:line 71
   at Starward.Pages.GameLauncherPage.UpdateAsync() in D:\a\Starward\Starward\src\Starward\Pages\GameLauncherPage.xaml.cs:line 940

[20:19:47.219] [EROR] Starward.Pages.GameLauncherPage
Update
System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.FileSystem.MoveFile(String, String, Boolean)
   at Starward.Services.Download.GenshinInstallGameService.<>c__DisplayClass5_0.<MoveAudioAssetsFromPersistentToStreamAssetsAsync>b__0() in D:\a\Starward\Starward\src\Starward\Services\Download\GenshinInstallGameService.cs:line 202
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
--- End of stack trace from previous location ---
   at Starward.Services.Download.GenshinInstallGameService.MoveAudioAssetsFromPersistentToStreamAssetsAsync() in D:\a\Starward\Starward\src\Starward\Services\Download\GenshinInstallGameService.cs:line 194
   at Starward.Services.Download.GenshinInstallGameService.StartUpdateGameAsync(CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\Download\GenshinInstallGameService.cs:line 71
   at Starward.Pages.GameLauncherPage.UpdateAsync() in D:\a\Starward\Starward\src\Starward\Pages\GameLauncherPage.xaml.cs:line 940
```

**Comment by Starfallan** [comment]
补充：

在 #762 中提到了可以手动将plugin文件夹进行文件权限的更改，但是我这里在更改完成后，发现文件夹权限自动恢复，仍然无法更新。但是后续尝试中，发现可以正常使用官方启动器进行更新

**Comment by winglai00** [comment]
問題：文件夾的唯讀性自動恢復。
解決方法：
1. 打開遊戲所在磁碟的「內容」
2. 選擇「安全性」
3. 點擊「進階」
4. 選擇「User(你的帳戶\user)」，並選擇「編輯」
5. 勾選「完全控制」
6. 套用並確定
再回到Plugins更改權限後即可在Starward中更新遊戲。
