### ISSUE TITLE
[Bug] 无法查看游戏公告

### ISSUE THREAD

**Issue by S-t-e-v-e-e** [Scighost/Starward#1128]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

点击游戏公告按钮后无法查看游戏内公告

### Reproduction Steps

启动starward，单击游戏公告按钮

### Expected Behavior

查看游戏公告

### Starward Version

0.13.3

### Windows Version

26120.2122

### Log

```shell
[20:44:56.104] [INFO] 
Welcome to Starward v0.13.3
System: Microsoft Windows NT 10.0.26120.0
Command Line: "D:\program files (x86)\starward\app-0.13.3\Starward.dll"

[20:44:56.144] [INFO] Starward.Services.DatabaseService
Database path is 'D:\program files (x86)\starward'

[20:44:56.178] [INFO] Starward.Services.DatabaseService
Database version is 11, target version is 11.

[20:44:56.271] [INFO] Starward.Pages.MainPage
Last game region is nap_cn

[20:44:56.287] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param nap_cn

[20:44:56.989] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "E:\ZZZ"

[20:44:57.011] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.2.0".

[20:44:57.926] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[20:44:58.594] [INFO] Starward.Services.UpdateService
Current version: "0.13.3", latest version: "0.13.3", ignore version: null

[20:45:00.378] [EROR] Starward.MyWindows.GameNoticesWindow
Initialize game notices
System.NullReferenceException: Object reference not set to an instance of an object.
   at Starward.MyWindows.GameNoticesWindow.InitializeWebAsync() in D:\a\Starward\Starward\src\Starward\MyWindows\GameNoticesWindow.xaml.cs:line 144

[20:45:13.571] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[20:45:13.572] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hkrpg_cn

[20:45:13.661] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "N:\Game"

[20:45:13.701] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.5.0".

[20:45:16.469] [EROR] Starward.MyWindows.GameNoticesWindow
Initialize game notices
System.NullReferenceException: Object reference not set to an instance of an object.
   at Starward.MyWindows.GameNoticesWindow.InitializeWebAsync() in D:\a\Starward\Starward\src\Starward\MyWindows\GameNoticesWindow.xaml.cs:line 144

[20:45:30.204] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[20:45:30.204] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[20:45:30.298] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "H:\Genshin Impact Game"

[20:45:30.346] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.0.0".

[20:45:32.956] [EROR] Starward.MyWindows.GameNoticesWindow
Initialize game notices
System.NullReferenceException: Object reference not set to an instance of an object.
   at Starward.MyWindows.GameNoticesWindow.InitializeWebAsync() in D:\a\Starward\Starward\src\Starward\MyWindows\GameNoticesWindow.xaml.cs:line 144

[20:47:05.011] [INFO] Starward.Pages.MainPage
Change game region to nap_cn

[20:47:05.012] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param nap_cn

[20:47:05.098] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "E:\ZZZ"

[20:47:05.138] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.2.0".
```

**Comment by S-t-e-v-e-e** [comment]
捞一下

**Comment by zdg-kinlon** [comment]
我这边是只有官服能查看游戏公告，Bilibili服不行，无法显示游戏公告

![1](https://github.com/user-attachments/assets/5812e0e7-05f0-4b8b-8fde-d45d84ef38f2)
![2](https://github.com/user-attachments/assets/b9b177fe-e533-4468-b822-69e83c14cc1d)
![3](https://github.com/user-attachments/assets/1a68a5fa-b621-4dee-be3e-bb36e980375d)
![4](https://github.com/user-attachments/assets/819f02e9-8b11-4523-8805-6f7f0ce74806)

**Comment by Scighost** [comment]
请安装 WebView2 Runtime

B服没有公告

**Comment by S-t-e-v-e-e** [comment]
> 请安装 WebView2 Runtime
> 
> B服没有公告

能不能显示官服的公告（

**Comment by Scighost** [comment]
期待某天B服能合并到官服吧
