### ISSUE TITLE
[Bug] 开拓月历和旅行者札记登录异常

### ISSUE THREAD

**Issue by xxbhpan** [Scighost/Starward#1132]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

开拓月历和旅行者札记登录异常，其他项目数据获取正常

### Reproduction Steps

点击“开拓月历”或者“旅行者札记”即弹窗，甚至不需要“刷新”

### Screenshots

<img width="629" alt="20241018224832" src="https://github.com/user-attachments/assets/52bfd2b2-efae-4bbe-8f6b-99480fd079f6">

### Starward Version

0.13.3

### Windows Version

19044.5011

### Log

```shell
[22:45:20.123] [INFO] 
Welcome to Starward v0.13.3
System: Microsoft Windows NT 10.0.19044.0
Command Line: D:\miHoYo\Tools\Starward\app-0.13.3\Starward.dll

[22:45:20.147] [INFO] Starward.Services.DatabaseService
Database path is 'D:\miHoYo\Tools\Starward'

[22:45:20.162] [INFO] Starward.Services.DatabaseService
Database version is 11, target version is 11.

[22:45:20.267] [INFO] Starward.Pages.MainPage
Last game region is hkrpg_cn

[22:45:20.313] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hkrpg_cn

[22:45:20.950] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "C:\ProgramMy\Star Rail\Game"

[22:45:20.963] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.5.0".

[22:45:21.901] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[22:45:23.404] [INFO] Starward.Services.UpdateService
Current version: "0.13.3", latest version: "0.13.3", ignore version: null

[22:45:25.436] [EROR] Starward.Pages.Setting.FileSettingPage
Delete folder '"C:\Users\xxbhpan\AppData\Local\Starward\log"'
System.IO.IOException: The process cannot access the file 'Starward_241018_224520.log' because it is being used by another process.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String, WIN32_FIND_DATA&, Boolean)
   at System.IO.FileSystem.RemoveDirectory(String, Boolean)
   at Starward.Pages.Setting.FileSettingPage.<>c__DisplayClass20_0.<DeleteFolderAsync>b__0() in D:\a\Starward\Starward\src\Starward\Pages\Setting\FileSettingPage.xaml.cs:line 368

[22:45:27.839] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hkrpg_cn

[22:45:27.848] [INFO] Starward.Services.GameRecordService
Change region to China.

[22:45:34.164] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[22:45:34.164] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hk4e_cn

[22:45:34.170] [INFO] Starward.Services.GameRecordService
Change region to China.

[22:45:46.750] [EROR] Starward.Pages.HoyolabToolbox.TravelersDiaryPage
Get realtime traveler's diary data details ("hk4e_cn", 打码).
Starward.Core.miHoYoApiException: 未登录 (-100)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 174
   at Starward.Core.GameRecord.HyperionClient.GetTravelsDiarySummaryAsync(GameRecordRole role, Int32 month, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 219
   at Starward.Services.GameRecordService.GetTravelersDiarySummaryAsync(GameRecordRole role, Int32 month) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 317
   at Starward.Pages.HoyolabToolbox.TravelersDiaryPage.GetCurrentSummaryAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\TravelersDiaryPage.xaml.cs:line 125

[22:45:47.172] [EROR] Starward.Pages.HoyolabToolbox.TravelersDiaryPage
Get realtime traveler's diary data details ("hk4e_cn", 打码).
Starward.Core.miHoYoApiException: 未登录 (-100)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 174
   at Starward.Core.GameRecord.HyperionClient.GetTravelsDiarySummaryAsync(GameRecordRole role, Int32 month, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 219
   at Starward.Services.GameRecordService.GetTravelersDiarySummaryAsync(GameRecordRole role, Int32 month) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 317
   at Starward.Pages.HoyolabToolbox.TravelersDiaryPage.GetCurrentSummaryAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\TravelersDiaryPage.xaml.cs:line 125

[22:45:53.200] [EROR] Starward.Pages.HoyolabToolbox.TravelersDiaryPage
Get realtime traveler's diary data details ("hk4e_cn", 打码).
Starward.Core.miHoYoApiException: 未登录 (-100)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 174
   at Starward.Core.GameRecord.HyperionClient.GetTravelsDiarySummaryAsync(GameRecordRole role, Int32 month, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 219
   at Starward.Services.GameRecordService.GetTravelersDiarySummaryAsync(GameRecordRole role, Int32 month) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 317
   at Starward.Pages.HoyolabToolbox.TravelersDiaryPage.GetCurrentSummaryAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\TravelersDiaryPage.xaml.cs:line 125

[22:45:54.611] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[22:45:54.611] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hkrpg_cn

[22:45:54.619] [INFO] Starward.Services.GameRecordService
Change region to China.

[22:45:55.823] [EROR] Starward.Pages.HoyolabToolbox.TrailblazeCalendarPage
Get realtime trailblaze calendar data ("hkrpg_cn", 打码).
Starward.Core.miHoYoApiException: 请先登录 (-100)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 174
   at Starward.Core.GameRecord.HyperionClient.GetTrailblazeCalendarSummaryAsync(GameRecordRole role, String month, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 494
   at Starward.Services.GameRecordService.GetTrailblazeCalendarSummaryAsync(GameRecordRole role, String month) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 750
   at Starward.Pages.HoyolabToolbox.TrailblazeCalendarPage.GetCurrentSummaryAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\TrailblazeCalendarPage.xaml.cs:line 123

[22:45:56.918] [EROR] Starward.Pages.HoyolabToolbox.TrailblazeCalendarPage
Get realtime trailblaze calendar data ("hkrpg_cn", 打码).
Starward.Core.miHoYoApiException: 请先登录 (-100)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 174
   at Starward.Core.GameRecord.HyperionClient.GetTrailblazeCalendarSummaryAsync(GameRecordRole role, String month, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 494
   at Starward.Services.GameRecordService.GetTrailblazeCalendarSummaryAsync(GameRecordRole role, String month) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 750
   at Starward.Pages.HoyolabToolbox.TrailblazeCalendarPage.GetCurrentSummaryAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\TrailblazeCalendarPage.xaml.cs:line 123
```

**Comment by xxbhpan** [comment]
目前的数据似乎停在了10-13，令人匪夷所思的是，绝区零的“绳网日报”数据获取正常。

**Comment by xxbhpan** [comment]
版本0.13.4，该问题仍然存在

**Comment by xxbhpan** [comment]
在重新登录后恢复正常，也不知道是什么原因
