### ISSUE TITLE
[Bug] 原神在添加硬链接后会导致无法正常进入游戏，错误代码31-4302

### ISSUE THREAD

**Issue by em741258** [Scighost/Starward#1133]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

我在昨晚进行队伍配置时突然出现一个弹窗 如图
![41d6c0286fd74b649e71e037193ec53639df260c png@1256w_414h_!web-article-pic](https://github.com/user-attachments/assets/50d5b9ce-9034-4863-9375-e3209174f24a)
我在重新下载游戏后此问题得到解决，但是当我再次重新添加硬链接并且下载安装完毕后此问题又再次出现

### Reproduction Steps

下载原神-全球官方后添加原神-中国官方的硬链接下载安装完毕后启动游戏，登录账号，进门后在加载前就会出现这个弹窗

### Starward Version

0.13.3

### Windows Version

19045.4894

### Log

```shell
[19:00:00.808] [INFO] 
Welcome to Starward v0.13.3
System: Microsoft Windows NT 10.0.19045.0
Command Line: F:\软件\软件\Starward\app-0.13.3\Starward.dll

[19:00:00.837] [INFO] Starward.Services.DatabaseService
Database path is 'F:\软件\软件\Starward'

[19:00:01.162] [INFO] Starward.Services.DatabaseService
Database version is 11, target version is 11.

[19:00:02.643] [INFO] Starward.Pages.MainPage
Last game region is hk4e_cn

[19:00:02.912] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[19:00:08.618] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "F:\Genshin"

[19:00:08.929] [INFO] Starward.Services.UpdateService
Start to check update (Preview: False, Arch: X64)

[19:00:09.742] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.1.0".

[19:00:10.912] [INFO] Starward.Services.UpdateService
Current version: "0.13.3", latest version: "0.13.3", ignore version: null

[19:01:11.130] [INFO] Starward.Pages.MainPage
Change game region to hk4e_global

[19:01:11.131] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_global

[19:01:11.369] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_global: "F:\Genshin"

[19:01:11.396] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_global is "5.1.0".

[19:21:01.822] [INFO] 
Welcome to Starward v0.13.3
System: Microsoft Windows NT 10.0.19045.0
Command Line: F:\软件\软件\Starward\app-0.13.3\Starward.dll

[19:21:01.847] [INFO] Starward.Services.DatabaseService
Database path is 'F:\软件\软件\Starward'

[19:21:01.865] [INFO] Starward.Services.DatabaseService
Database version is 11, target version is 11.

[19:21:05.010] [INFO] Starward.Pages.MainPage
Last game region is hk4e_global

[19:21:05.490] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_global

[19:21:16.295] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_global: "F:\Genshin"

[19:21:16.825] [INFO] Starward.Services.UpdateService
Start to check update (Preview: False, Arch: X64)

[19:21:17.492] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_global is "5.1.0".

[19:21:19.147] [INFO] Starward.Services.UpdateService
Current version: "0.13.3", latest version: "0.13.3", ignore version: null

[19:49:51.710] [INFO] Starward.Services.Download.GenshinInstallGameService
Write config.ini (game_version="5.1.0")

[19:49:52.296] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_global: "F:\Genshin"

[19:49:52.323] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_global is "5.1.0".

[19:50:02.006] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hk4e_global)
path: "F:\Genshin\GenshinImpact.exe"
arg: null

[19:50:06.103] [INFO] Starward.Pages.GameLauncherPage
Game started ("GenshinImpact", 14560)

[19:50:08.177] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hk4e_global, 14560)

[19:52:44.243] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[19:53:10.192] [INFO] Starward.Pages.GameLauncherPage
Start to uninstall game with argu: "uninstall --biz hk4e_global --loc \"F:\Genshin\" --steps 15"

[19:53:20.120] [INFO] Starward.Pages.GameLauncherPage
Uninstall finished.

[19:53:20.264] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_global: null

[19:53:20.264] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_global is null.

[19:53:34.695] [EROR] Starward.Controls.InstallGameDialog
Start installation hk4e_global failed.
System.UnauthorizedAccessException: Access to the path 'F:\System Volume Information' is denied.
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1)
   at System.IO.Directory.GetFiles(String, String, EnumerationOptions)
   at Starward.Services.Download.InstallGameService.<>c__DisplayClass41_0.<InitializeAsync>b__0() in D:\a\Starward\Starward\src\Starward\Services\Download\InstallGameService.cs:line 245
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
--- End of stack trace from previous location ---
   at Starward.Services.Download.InstallGameService.InitializeAsync(GameBiz gameBiz, String installPath) in D:\a\Starward\Starward\src\Starward\Services\Download\InstallGameService.cs:line 239
   at Starward.Controls.InstallGameDialog.StartInstallationAsync() in D:\a\Starward\Starward\src\Starward\Controls\InstallGameDialog.xaml.cs:line 305

[19:53:59.446] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_global: "F:\Genshin Impact"

[19:53:59.446] [WARN] Starward.Services.Launcher.GameLauncherService
config.ini not found: "F:\Genshin Impact\config.ini"

[19:53:59.446] [WARN] Starward.Services.Launcher.GameLauncherService
config.ini not found: "F:\Genshin Impact\config.ini"

[19:53:59.446] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_global is null.

[19:50:10.730] [INFO] 
Welcome to Starward v0.13.3
System: Microsoft Windows NT 10.0.19045.0
Command Line: F:\软件\软件\Starward\app-0.13.3\Starward.dll playtime --biz hk4e_global --pid 14560

[19:50:10.754] [INFO] Starward.Services.DatabaseService
Database path is 'F:\软件\软件\Starward'

[19:50:10.771] [INFO] Starward.Services.DatabaseService
Database version is 11, target version is 11.
[19:53:10.350] [INFO] 
Welcome to Starward v0.13.3
System: Microsoft Windows NT 10.0.19045.0
Command Line: F:\软件\软件\Starward\app-0.13.3\Starward.dll uninstall --biz hk4e_global --loc F:\Genshin --steps 15

[19:53:10.376] [INFO] Starward.Services.DatabaseService
Database path is 'F:\软件\软件\Starward'

[19:53:10.393] [INFO] Starward.Services.DatabaseService
Database version is 11, target version is 11.

[19:53:10.460] [INFO] Starward.Services.GameService
Start to backup screenshot

[19:53:10.461] [WARN] Starward.Services.GameService
Screenshot folder does not exist: "F:\Genshin\ScreenShot"

[19:53:10.461] [INFO] Starward.Services.GameService
Start to clean registry.

[19:53:10.471] [INFO] Starward.Services.GameService
Finished clean registry.

[19:53:10.471] [INFO] Starward.Services.GameService
Start to delete temp files.

[19:53:10.472] [INFO] Starward.Services.GameService
Deleted folder "C:\Users\Administrator\AppData\Local\Temp\miHoYo\Genshin Impact"

[19:53:10.496] [INFO] Starward.Services.GameService
Deleted folder "C:\Users\Administrator\AppData\LocalLow\miHoYo\Genshin Impact"

[19:53:10.496] [INFO] Starward.Services.GameService
Finished deleting temp files.

[19:53:10.496] [INFO] Starward.Services.GameService
Start to delete game assets: "F:\Genshin"

[19:53:20.060] [INFO] Starward.Services.GameService
Finished deleting game assets.

[07:22:43.689] [INFO] 
Welcome to Starward v0.13.3
System: Microsoft Windows NT 10.0.19045.0
Command Line: F:\软件\软件\Starward\app-0.13.3\Starward.dll

[07:22:44.479] [INFO] Starward.Services.DatabaseService
Database path is 'F:\软件\软件\Starward'

[07:22:45.379] [INFO] Starward.Services.DatabaseService
Database version is 11, target version is 11.

[07:22:47.661] [INFO] Starward.Pages.MainPage
Last game region is hk4e_global

[07:22:47.885] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_global

[07:22:52.358] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_global: "F:\Genshin Impact"

[07:22:52.358] [WARN] Starward.Services.Launcher.GameLauncherService
config.ini not found: "F:\Genshin Impact\config.ini"

[07:22:52.359] [WARN] Starward.Services.Launcher.GameLauncherService
config.ini not found: "F:\Genshin Impact\config.ini"

[07:22:52.360] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_global is null.

[07:22:53.466] [INFO] Starward.Services.UpdateService
Start to check update (Preview: False, Arch: X64)

[07:22:54.816] [INFO] Starward.Services.UpdateService
Current version: "0.13.3", latest version: "0.13.3", ignore version: null

[07:23:43.024] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_global: "F:\Genshin Impact"

[07:23:43.024] [WARN] Starward.Services.Launcher.GameLauncherService
config.ini not found: "F:\Genshin Impact\config.ini"

[07:23:43.024] [WARN] Starward.Services.Launcher.GameLauncherService
config.ini not found: "F:\Genshin Impact\config.ini"

[07:23:43.024] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_global is null.

[10:25:03.341] [INFO] Starward.Services.Download.GenshinInstallGameService
Write config.ini (game_version="5.1.0")

[10:25:03.405] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_global: "F:\Genshin Impact"

[10:25:03.474] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_global is "5.1.0".

[10:38:10.758] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hk4e_global)
path: "F:\Genshin Impact\GenshinImpact.exe"
arg: null

[10:38:18.377] [INFO] Starward.Pages.GameLauncherPage
Game started ("GenshinImpact", 14364)

[10:38:20.420] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hk4e_global, 14364)

[10:56:52.515] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[10:56:52.518] [INFO] Starward.Pages.GameLauncherPage
Game is running ("GenshinImpact", 14364)

[10:56:53.524] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[10:57:03.227] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[10:57:03.228] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[10:57:03.434] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: null

[10:57:03.434] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is null.

[10:57:20.901] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "F:\Genshin Impact"

[10:57:20.902] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.1.0".

[10:57:42.749] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "F:\Genshin Impact"

[10:57:42.750] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.1.0".

[11:26:31.664] [INFO] Starward.Services.Download.GenshinInstallGameService
Write config.ini (game_version="5.1.0")

[11:26:31.668] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "F:\Genshin Impact"

[11:26:31.670] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.1.0".

[11:28:41.080] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hk4e_cn)
path: "F:\Genshin Impact\YuanShen.exe"
arg: null

[11:28:41.992] [INFO] Starward.Pages.GameLauncherPage
Game started ("YuanShen", 5964)

[11:28:44.002] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hk4e_cn, 5964)

[11:39:32.005] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[11:39:32.007] [INFO] Starward.Pages.GameLauncherPage
Game is running ("YuanShen", 5964)

[11:39:33.007] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[11:39:45.638] [INFO] Starward.Pages.MainPage
Change game region to hk4e_global

[11:39:45.638] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_global

[11:39:45.742] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_global: "F:\Genshin Impact"

[11:39:45.760] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_global is "5.1.0".

[11:39:46.378] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hk4e_global)
path: "F:\Genshin Impact\GenshinImpact.exe"
arg: null

[11:39:46.504] [INFO] Starward.Pages.GameLauncherPage
Game started ("GenshinImpact", 14456)

[11:39:48.513] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hk4e_global, 14456)

[11:43:12.518] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[11:44:52.564] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[11:44:52.564] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[11:44:52.789] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "F:\Genshin Impact"

[11:44:52.804] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.1.0".

[11:51:41.701] [INFO] Starward.Pages.MainPage
Change game region to hk4e_global

[11:51:41.702] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_global

[11:51:45.371] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_global: "F:\Genshin Impact"

[11:51:46.196] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_global is "5.1.0".
[10:38:23.019] [INFO] 
Welcome to Starward v0.13.3
System: Microsoft Windows NT 10.0.19045.0
Command Line: F:\软件\软件\Starward\app-0.13.3\Starward.dll playtime --biz hk4e_global --pid 14364

[10:38:23.226] [INFO] Starward.Services.DatabaseService
Database path is 'F:\软件\软件\Starward'

[10:38:23.354] [INFO] Starward.Services.DatabaseService
Database version is 11, target version is 11.

[11:28:45.972] [INFO] 
Welcome to Starward v0.13.3
System: Microsoft Windows NT 10.0.19045.0
Command Line: F:\软件\软件\Starward\app-0.13.3\Starward.dll playtime --biz hk4e_cn --pid 5964

[11:28:46.114] [INFO] Starward.Services.DatabaseService
Database path is 'F:\软件\软件\Starward'

[11:28:46.247] [INFO] Starward.Services.DatabaseService
Database version is 11, target version is 11.

[11:39:51.002] [INFO] 
Welcome to Starward v0.13.3
System: Microsoft Windows NT 10.0.19045.0
Command Line: F:\软件\软件\Starward\app-0.13.3\Starward.dll playtime --biz hk4e_global --pid 14456

[11:39:51.166] [INFO] Starward.Services.DatabaseService
Database path is 'F:\软件\软件\Starward'

[11:39:51.283] [INFO] Starward.Services.DatabaseService
Database version is 11, target version is 11.
```

**Comment by NaraRaa525** [comment]
硬链接的路径放哪都成，但就是不能放在游戏路径（比如含有YuanShen.exe的文件夹）里，不然报错。
推荐放在starwards文件夹里
重新下了90G下得想吐orz
