### ISSUE TITLE
[Bug] Screenshot Drag and Drop function crashes the launcher

### ISSUE THREAD

**Issue by studiobutter** [Scighost/Starward#1150]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

The Screenshot Drag and Drop no longer works and crash the launcher instead

### Reproduction Steps

Drag the Screenshot

### Expected Behavior

There should be a preview on the cursor allowing you to drop it in other apps

### Starward Version

0.13.4

### Windows Version

26100.1882

### Log

```shell
[21:25:11.138] [INFO] 
Welcome to Starward v0.13.4
System: Microsoft Windows NT 10.0.26100.0
Command Line: C:\Launchers\Starward\app-0.13.4\Starward.dll

[21:25:11.200] [INFO] Starward.Services.DatabaseService
Database path is 'C:\Launchers\Starward'

[21:25:11.240] [INFO] Starward.Services.DatabaseService
Database version is 11, target version is 11.

[21:25:11.404] [INFO] Starward.Pages.MainPage
Last game region is hk4e_global

[21:25:11.435] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_global

[21:25:12.855] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_global: "C:\Program Files\Games\HoYoPlay\games\Genshin Impact game"

[21:25:12.910] [INFO] Starward.Pages.GameLauncherPage
Game is running ("GenshinImpact", 23204)

[21:25:12.942] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_global is "5.1.0".

[21:25:13.864] [INFO] Starward.Services.UpdateService
Start to check update (Preview: False, Arch: X64)

[21:25:14.228] [INFO] Starward.Services.UpdateService
Current version: "0.13.4", latest version: "0.13.4", ignore version: null

[21:25:21.969] [INFO] Starward.Services.UpdateService
Start to check update (Preview: False, Arch: X64)

[21:25:22.019] [INFO] Starward.Services.UpdateService
Current version: "0.13.4", latest version: "0.13.4", ignore version: null

[21:25:23.165] [EROR] Starward.Services.HoYoPlayService
Download image: ""
System.InvalidOperationException: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage)
   at System.Net.Http.HttpClient.GetByteArrayAsync(Uri , CancellationToken)
   at Starward.Services.HoYoPlayService.<>c__DisplayClass14_0.<<PrepareImagesAsync>b__0>d.MoveNext() in D:\a\Starward\Starward\src\Starward\Services\HoYoPlayService.cs:line 201

[21:25:23.167] [EROR] Starward.Services.HoYoPlayService
Download image: ""
System.InvalidOperationException: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage)
   at System.Net.Http.HttpClient.GetByteArrayAsync(Uri , CancellationToken)
   at Starward.Services.HoYoPlayService.<>c__DisplayClass14_0.<<PrepareImagesAsync>b__0>d.MoveNext() in D:\a\Starward\Starward\src\Starward\Services\HoYoPlayService.cs:line 201
```

**Comment by Scighost** [comment]
Thanks for your feedback. This is because of a bug in WinUI3 in administrator mode. In the latest version, drag and drop is disabled in administrator mode.
