### ISSUE TITLE
[Bug] 星穹铁道预下载更新到2.7后游戏损坏

### ISSUE THREAD

**Issue by YYl04** [Scighost/Starward#1177]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

![image](https://github.com/user-attachments/assets/f7f8bdd7-dc5c-48dc-adfa-6d2a0c7431ed)

### Reproduction Steps

只是进行了更新，正常通过了校验和解压

### Starward Version

0.13.5

### Windows Version

26100.2454

### Log

```shell
[22:55:43.067] [INFO] 
Welcome to Starward v0.13.5
System: Microsoft Windows NT 10.0.26100.0
Command Line: E:\Downloads\Starward\app-0.13.5\Starward.dll

[22:55:43.093] [INFO] Starward.Services.DatabaseService
Database path is 'E:\Downloads\Starward'

[22:55:43.114] [INFO] Starward.Services.DatabaseService
Database version is 11, target version is 11.

[22:55:43.199] [INFO] Starward.Pages.MainPage
Last game region is hk4e_cn

[22:55:43.215] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[22:55:43.748] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "D:\miHoYo Launcher\games\Genshin Impact"

[22:55:43.774] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.2.0".

[22:55:44.708] [INFO] Starward.Services.UpdateService
Start to check update (Preview: False, Arch: X64)

[22:55:44.934] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[22:55:44.934] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hkrpg_cn

[22:55:44.989] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "D:\miHoYo Launcher\games\Star Rail"

[22:55:45.008] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.6.0".

[22:55:45.752] [INFO] Starward.Services.UpdateService
Current version: "0.13.5", latest version: "0.13.5", ignore version: null

[22:55:45.949] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[22:55:45.950] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[22:55:46.014] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "D:\miHoYo Launcher\games\Genshin Impact"

[22:55:46.042] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.2.0".

[22:56:00.550] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hk4e_cn)
path: "D:\miHoYo Launcher\games\Genshin Impact\YuanShen.exe"
arg: null

[22:56:01.980] [INFO] Starward.Pages.GameLauncherPage
Game started ("YuanShen", 42100)

[22:56:03.997] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hk4e_cn, 42100)

[23:25:05.011] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[23:25:05.019] [INFO] Starward.Pages.GameLauncherPage
Game is running ("YuanShen", 42100)

[23:25:06.021] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[23:25:06.029] [INFO] Starward.Pages.GameLauncherPage
Game is running ("YuanShen", 42100)

[23:25:07.044] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[23:25:11.135] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[23:25:11.135] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hkrpg_cn

[23:25:11.190] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "D:\miHoYo Launcher\games\Star Rail"

[23:25:11.212] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.6.0".

[23:26:34.858] [INFO] Starward.Services.Download.InstallGameService
Write config.ini (game_version="2.7.0")

[23:26:34.862] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "D:\miHoYo Launcher\games\Star Rail"

[23:26:34.865] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.7.0".

[23:26:39.553] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hkrpg_cn)
path: "D:\miHoYo Launcher\games\Star Rail\StarRail.exe"
arg: null

[23:26:39.578] [EROR] Starward.Pages.GameLauncherPage
Start game
System.ComponentModel.Win32Exception (193): An error occurred trying to start process 'D:\miHoYo Launcher\games\Star Rail\StarRail.exe' with working directory 'D:\miHoYo Launcher\games\Star Rail'. The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo)
   at Starward.Services.Launcher.GameLauncherService.StartGame(GameBiz biz, Boolean ignoreRunningGame, String installPath) in D:\a\Starward\Starward\src\Starward\Services\Launcher\GameLauncherService.cs:line 399
   at Starward.Pages.GameLauncherPage.StartGameAsync() in D:\a\Starward\Starward\src\Starward\Pages\GameLauncherPage.xaml.cs:line 446

[23:26:41.059] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hkrpg_cn)
path: "D:\miHoYo Launcher\games\Star Rail\StarRail.exe"
arg: null

[23:26:41.065] [EROR] Starward.Pages.GameLauncherPage
Start game
System.ComponentModel.Win32Exception (193): An error occurred trying to start process 'D:\miHoYo Launcher\games\Star Rail\StarRail.exe' with working directory 'D:\miHoYo Launcher\games\Star Rail'. The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo)
   at Starward.Services.Launcher.GameLauncherService.StartGame(GameBiz biz, Boolean ignoreRunningGame, String installPath) in D:\a\Starward\Starward\src\Starward\Services\Launcher\GameLauncherService.cs:line 399
   at Starward.Pages.GameLauncherPage.StartGameAsync() in D:\a\Starward\Starward\src\Starward\Pages\GameLauncherPage.xaml.cs:line 446

[23:26:42.403] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hkrpg_cn)
path: "D:\miHoYo Launcher\games\Star Rail\StarRail.exe"
arg: null

[23:26:42.409] [EROR] Starward.Pages.GameLauncherPage
Start game
System.ComponentModel.Win32Exception (193): An error occurred trying to start process 'D:\miHoYo Launcher\games\Star Rail\StarRail.exe' with working directory 'D:\miHoYo Launcher\games\Star Rail'. The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo)
   at Starward.Services.Launcher.GameLauncherService.StartGame(GameBiz biz, Boolean ignoreRunningGame, String installPath) in D:\a\Starward\Starward\src\Starward\Services\Launcher\GameLauncherService.cs:line 399
   at Starward.Pages.GameLauncherPage.StartGameAsync() in D:\a\Starward\Starward\src\Starward\Pages\GameLauncherPage.xaml.cs:line 446

[23:26:43.275] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hkrpg_cn)
path: "D:\miHoYo Launcher\games\Star Rail\StarRail.exe"
arg: null

[23:26:43.281] [EROR] Starward.Pages.GameLauncherPage
Start game
System.ComponentModel.Win32Exception (193): An error occurred trying to start process 'D:\miHoYo Launcher\games\Star Rail\StarRail.exe' with working directory 'D:\miHoYo Launcher\games\Star Rail'. The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo)
   at Starward.Services.Launcher.GameLauncherService.StartGame(GameBiz biz, Boolean ignoreRunningGame, String installPath) in D:\a\Starward\Starward\src\Starward\Services\Launcher\GameLauncherService.cs:line 399
   at Starward.Pages.GameLauncherPage.StartGameAsync() in D:\a\Starward\Starward\src\Starward\Pages\GameLauncherPage.xaml.cs:line 446

[23:26:48.940] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hkrpg_cn)
path: "D:\miHoYo Launcher\games\Star Rail\StarRail.exe"
arg: null

[23:26:48.947] [EROR] Starward.Pages.GameLauncherPage
Start game
System.ComponentModel.Win32Exception (193): An error occurred trying to start process 'D:\miHoYo Launcher\games\Star Rail\StarRail.exe' with working directory 'D:\miHoYo Launcher\games\Star Rail'. The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo)
   at Starward.Services.Launcher.GameLauncherService.StartGame(GameBiz biz, Boolean ignoreRunningGame, String installPath) in D:\a\Starward\Starward\src\Starward\Services\Launcher\GameLauncherService.cs:line 399
   at Starward.Pages.GameLauncherPage.StartGameAsync() in D:\a\Starward\Starward\src\Starward\Pages\GameLauncherPage.xaml.cs:line 446

[23:26:49.090] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hkrpg_cn)
path: "D:\miHoYo Launcher\games\Star Rail\StarRail.exe"
arg: null

[23:26:49.096] [EROR] Starward.Pages.GameLauncherPage
Start game
System.ComponentModel.Win32Exception (193): An error occurred trying to start process 'D:\miHoYo Launcher\games\Star Rail\StarRail.exe' with working directory 'D:\miHoYo Launcher\games\Star Rail'. The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo)
   at Starward.Services.Launcher.GameLauncherService.StartGame(GameBiz biz, Boolean ignoreRunningGame, String installPath) in D:\a\Starward\Starward\src\Starward\Services\Launcher\GameLauncherService.cs:line 399
   at Starward.Pages.GameLauncherPage.StartGameAsync() in D:\a\Starward\Starward\src\Starward\Pages\GameLauncherPage.xaml.cs:line 446

[23:26:49.248] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hkrpg_cn)
path: "D:\miHoYo Launcher\games\Star Rail\StarRail.exe"
arg: null

[23:26:49.254] [EROR] Starward.Pages.GameLauncherPage
Start game
System.ComponentModel.Win32Exception (193): An error occurred trying to start process 'D:\miHoYo Launcher\games\Star Rail\StarRail.exe' with working directory 'D:\miHoYo Launcher\games\Star Rail'. The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo)
   at Starward.Services.Launcher.GameLauncherService.StartGame(GameBiz biz, Boolean ignoreRunningGame, String installPath) in D:\a\Starward\Starward\src\Starward\Services\Launcher\GameLauncherService.cs:line 399
   at Starward.Pages.GameLauncherPage.StartGameAsync() in D:\a\Starward\Starward\src\Starward\Pages\GameLauncherPage.xaml.cs:line 446

[23:26:49.398] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hkrpg_cn)
path: "D:\miHoYo Launcher\games\Star Rail\StarRail.exe"
arg: null

[23:26:49.403] [EROR] Starward.Pages.GameLauncherPage
Start game
System.ComponentModel.Win32Exception (193): An error occurred trying to start process 'D:\miHoYo Launcher\games\Star Rail\StarRail.exe' with working directory 'D:\miHoYo Launcher\games\Star Rail'. The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo)
   at Starward.Services.Launcher.GameLauncherService.StartGame(GameBiz biz, Boolean ignoreRunningGame, String installPath) in D:\a\Starward\Starward\src\Starward\Services\Launcher\GameLauncherService.cs:line 399
   at Starward.Pages.GameLauncherPage.StartGameAsync() in D:\a\Starward\Starward\src\Starward\Pages\GameLauncherPage.xaml.cs:line 446

[23:26:52.992] [INFO] 
Welcome to Starward v0.13.5
System: Microsoft Windows NT 10.0.26100.0
Command Line: E:\Downloads\Starward\app-0.13.5\Starward.dll

[23:26:53.014] [INFO] Starward.Services.DatabaseService
Database path is 'E:\Downloads\Starward'

[23:26:53.030] [INFO] Starward.Services.DatabaseService
Database version is 11, target version is 11.

[23:26:53.083] [INFO] Starward.Pages.MainPage
Last game region is hkrpg_cn

[23:26:53.092] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hkrpg_cn

[23:26:53.571] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "D:\miHoYo Launcher\games\Star Rail"

[23:26:53.588] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.7.0".

[23:26:54.456] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hkrpg_cn)
path: "D:\miHoYo Launcher\games\Star Rail\StarRail.exe"
arg: null

[23:26:54.520] [EROR] Starward.Pages.GameLauncherPage
Start game
System.ComponentModel.Win32Exception (193): An error occurred trying to start process 'D:\miHoYo Launcher\games\Star Rail\StarRail.exe' with working directory 'D:\miHoYo Launcher\games\Star Rail'. The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo)
   at Starward.Services.Launcher.GameLauncherService.StartGame(GameBiz biz, Boolean ignoreRunningGame, String installPath) in D:\a\Starward\Starward\src\Starward\Services\Launcher\GameLauncherService.cs:line 399
   at Starward.Pages.GameLauncherPage.StartGameAsync() in D:\a\Starward\Starward\src\Starward\Pages\GameLauncherPage.xaml.cs:line 446

[23:26:54.545] [INFO] Starward.Services.UpdateService
Start to check update (Preview: False, Arch: X64)

[23:26:55.336] [INFO] Starward.Services.UpdateService
Current version: "0.13.5", latest version: "0.13.5", ignore version: null

[23:26:55.363] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hkrpg_cn)
path: "D:\miHoYo Launcher\games\Star Rail\StarRail.exe"
arg: null

[23:26:55.375] [EROR] Starward.Pages.GameLauncherPage
Start game
System.ComponentModel.Win32Exception (193): An error occurred trying to start process 'D:\miHoYo Launcher\games\Star Rail\StarRail.exe' with working directory 'D:\miHoYo Launcher\games\Star Rail'. The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo)
   at Starward.Services.Launcher.GameLauncherService.StartGame(GameBiz biz, Boolean ignoreRunningGame, String installPath) in D:\a\Starward\Starward\src\Starward\Services\Launcher\GameLauncherService.cs:line 399
   at Starward.Pages.GameLauncherPage.StartGameAsync() in D:\a\Starward\Starward\src\Starward\Pages\GameLauncherPage.xaml.cs:line 446

[23:26:55.504] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hkrpg_cn)
path: "D:\miHoYo Launcher\games\Star Rail\StarRail.exe"
arg: null

[23:26:55.509] [EROR] Starward.Pages.GameLauncherPage
Start game
System.ComponentModel.Win32Exception (193): An error occurred trying to start process 'D:\miHoYo Launcher\games\Star Rail\StarRail.exe' with working directory 'D:\miHoYo Launcher\games\Star Rail'. The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo)
   at Starward.Services.Launcher.GameLauncherService.StartGame(GameBiz biz, Boolean ignoreRunningGame, String installPath) in D:\a\Starward\Starward\src\Starward\Services\Launcher\GameLauncherService.cs:line 399
   at Starward.Pages.GameLauncherPage.StartGameAsync() in D:\a\Starward\Starward\src\Starward\Pages\GameLauncherPage.xaml.cs:line 446

[23:26:55.643] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hkrpg_cn)
path: "D:\miHoYo Launcher\games\Star Rail\StarRail.exe"
arg: null

[23:26:55.648] [EROR] Starward.Pages.GameLauncherPage
Start game
System.ComponentModel.Win32Exception (193): An error occurred trying to start process 'D:\miHoYo Launcher\games\Star Rail\StarRail.exe' with working directory 'D:\miHoYo Launcher\games\Star Rail'. The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo)
   at Starward.Services.Launcher.GameLauncherService.StartGame(GameBiz biz, Boolean ignoreRunningGame, String installPath) in D:\a\Starward\Starward\src\Starward\Services\Launcher\GameLauncherService.cs:line 399
   at Starward.Pages.GameLauncherPage.StartGameAsync() in D:\a\Starward\Starward\src\Starward\Pages\GameLauncherPage.xaml.cs:line 446

[23:26:55.806] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hkrpg_cn)
path: "D:\miHoYo Launcher\games\Star Rail\StarRail.exe"
arg: null

[23:26:55.811] [EROR] Starward.Pages.GameLauncherPage
Start game
System.ComponentModel.Win32Exception (193): An error occurred trying to start process 'D:\miHoYo Launcher\games\Star Rail\StarRail.exe' with working directory 'D:\miHoYo Launcher\games\Star Rail'. The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo)
   at Starward.Services.Launcher.GameLauncherService.StartGame(GameBiz biz, Boolean ignoreRunningGame, String installPath) in D:\a\Starward\Starward\src\Starward\Services\Launcher\GameLauncherService.cs:line 399
   at Starward.Pages.GameLauncherPage.StartGameAsync() in D:\a\Starward\Starward\src\Starward\Pages\GameLauncherPage.xaml.cs:line 446

[23:27:04.670] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[23:27:04.670] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[23:27:04.735] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "D:\miHoYo Launcher\games\Genshin Impact"

[23:27:04.765] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.2.0".

[23:27:06.565] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[23:27:06.566] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hkrpg_cn

[23:27:06.630] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "D:\miHoYo Launcher\games\Star Rail"

[23:27:06.652] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.7.0".

[23:27:10.398] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hkrpg_cn)
path: "D:\miHoYo Launcher\games\Star Rail\StarRail.exe"
arg: null

[23:27:10.403] [EROR] Starward.Pages.GameLauncherPage
Start game
System.ComponentModel.Win32Exception (193): An error occurred trying to start process 'D:\miHoYo Launcher\games\Star Rail\StarRail.exe' with working directory 'D:\miHoYo Launcher\games\Star Rail'. The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo)
   at Starward.Services.Launcher.GameLauncherService.StartGame(GameBiz biz, Boolean ignoreRunningGame, String installPath) in D:\a\Starward\Starward\src\Starward\Services\Launcher\GameLauncherService.cs:line 399
   at Starward.Pages.GameLauncherPage.StartGameAsync() in D:\a\Starward\Starward\src\Starward\Pages\GameLauncherPage.xaml.cs:line 446

[23:27:10.729] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hkrpg_cn)
path: "D:\miHoYo Launcher\games\Star Rail\StarRail.exe"
arg: null

[23:27:10.734] [EROR] Starward.Pages.GameLauncherPage
Start game
System.ComponentModel.Win32Exception (193): An error occurred trying to start process 'D:\miHoYo Launcher\games\Star Rail\StarRail.exe' with working directory 'D:\miHoYo Launcher\games\Star Rail'. The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo)
   at Starward.Services.Launcher.GameLauncherService.StartGame(GameBiz biz, Boolean ignoreRunningGame, String installPath) in D:\a\Starward\Starward\src\Starward\Services\Launcher\GameLauncherService.cs:line 399
   at Starward.Pages.GameLauncherPage.StartGameAsync() in D:\a\Starward\Starward\src\Starward\Pages\GameLauncherPage.xaml.cs:line 446

[23:27:10.862] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hkrpg_cn)
path: "D:\miHoYo Launcher\games\Star Rail\StarRail.exe"
arg: null

[23:27:10.867] [EROR] Starward.Pages.GameLauncherPage
Start game
System.ComponentModel.Win32Exception (193): An error occurred trying to start process 'D:\miHoYo Launcher\games\Star Rail\StarRail.exe' with working directory 'D:\miHoYo Launcher\games\Star Rail'. The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo)
   at Starward.Services.Launcher.GameLauncherService.StartGame(GameBiz biz, Boolean ignoreRunningGame, String installPath) in D:\a\Starward\Starward\src\Starward\Services\Launcher\GameLauncherService.cs:line 399
   at Starward.Pages.GameLauncherPage.StartGameAsync() in D:\a\Starward\Starward\src\Starward\Pages\GameLauncherPage.xaml.cs:line 446

[23:27:10.998] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hkrpg_cn)
path: "D:\miHoYo Launcher\games\Star Rail\StarRail.exe"
arg: null

[23:27:11.003] [EROR] Starward.Pages.GameLauncherPage
Start game
System.ComponentModel.Win32Exception (193): An error occurred trying to start process 'D:\miHoYo Launcher\games\Star Rail\StarRail.exe' with working directory 'D:\miHoYo Launcher\games\Star Rail'. The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo)
   at Starward.Services.Launcher.GameLauncherService.StartGame(GameBiz biz, Boolean ignoreRunningGame, String installPath) in D:\a\Starward\Starward\src\Starward\Services\Launcher\GameLauncherService.cs:line 399
   at Starward.Pages.GameLauncherPage.StartGameAsync() in D:\a\Starward\Starward\src\Starward\Pages\GameLauncherPage.xaml.cs:line 446
```

**Comment by Eric-Joker** [comment]
若校验正常通过，那就是解压问题，在确保硬盘正常的情况下，运行修复模式。
