### ISSUE TITLE
[Bug] Not enough storage causes app to bug, and resuming afterwards causes the app to think it was successful

### ISSUE THREAD

**Issue by Flyingbacen** [Scighost/Starward#1183]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

When extracting pre-downloaded update data for Zenless Zone Zero, I ran out of storage space, causing the app to display unknown error with the reason of not enough storage space. I made sufficient space, and resumed. The app immediately said it was entirely successful, despite only having extracted ~1.6/16GB. Repairing the game caused it to download the remaining files.

### Reproduction Steps

- download pre-install data
- not have enough space to extract all the data
- extract the data
- non-fatal error occurs

### Expected Behavior

After resuming, the app to try re-extracting the data, continuing from where it errored out.

### Screenshots

Didn't think to make a bug report until after resuming, so no screenshots were taken.

### Starward Version

0.13.5

### Windows Version

19045.5247

### Log

```shell
[21:56:32.598] [EROR] Starward.Services.Download.ZZZInstallGameService
ExecuteTaskItemAsync
System.IO.IOException: There is not enough space on the disk. : 'D:\MiHoYo\Zenless Zone Zero\ZenlessZoneZero_Data\StreamingAssets\Blocks\1394799786.blk'
   at System.IO.Strategies.BufferedFileStreamStrategy.WriteSpan(ReadOnlySpan`1, ArraySegment`1)
   at System.IO.Stream.CopyTo(Stream, Int32)
   at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestination()
   at System.IO.Compression.DeflateStream.CopyTo(Stream, Int32)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry, String, Boolean)
   at Starward.Services.Download.InstallGameService.<>c__DisplayClass91_0.<<DecompressItemAsync>b__1>d.MoveNext() in D:\a\Starward\Starward\src\Starward\Services\Download\InstallGameService.cs:line 1344
--- End of stack trace from previous location ---
   at Starward.Services.Download.InstallGameService.DecompressItemAsync(InstallGameItem item, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\Download\InstallGameService.cs:line 1311
   at Starward.Services.Download.InstallGameService.ExecuteTaskItemAsync(CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\Download\InstallGameService.cs:line 1136

[21:56:32.615] [EROR] Starward.Services.Download.ZZZInstallGameService
ExecuteTaskItemAsync
System.IO.IOException: There is not enough space on the disk. : 'D:\MiHoYo\Zenless Zone Zero\ZenlessZoneZero_Data\StreamingAssets\Audio\Windows\Full\En\External_En_0.pck.hdiff'
   at System.IO.Strategies.BufferedFileStreamStrategy.WriteSpan(ReadOnlySpan`1, ArraySegment`1)
   at System.IO.Stream.CopyTo(Stream, Int32)
   at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestination()
   at System.IO.Compression.DeflateStream.CopyTo(Stream, Int32)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry, String, Boolean)
   at Starward.Services.Download.InstallGameService.<>c__DisplayClass91_0.<<DecompressItemAsync>b__1>d.MoveNext() in D:\a\Starward\Starward\src\Starward\Services\Download\InstallGameService.cs:line 1344
--- End of stack trace from previous location ---
   at Starward.Services.Download.InstallGameService.DecompressItemAsync(InstallGameItem item, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\Download\InstallGameService.cs:line 1311
   at Starward.Services.Download.InstallGameService.ExecuteTaskItemAsync(CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\Download\InstallGameService.cs:line 1136
```

### Additional Context

Starward was also installed on the D: drive, which ran out of space.

**Comment by Flyingbacen** [comment]
Didn't realize this until now, but the 1.3.0-1.4.0 diff zip file was not deleted either.

**Comment by Scighost** [comment]
Starward will warn you that you are running low on storage space, but it will not stop you from doing anything. It will only report an error if it can no longer write files.
