### ISSUE TITLE
[Bug] Unable to access Genshin Impact's pull draw history

### ISSUE THREAD

**Issue by HKLHaoBin** [Scighost/Starward#1185]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

Local games and cloud games are both inaccessible

HttpRequestException
TheSSLconnectioncouldnotbeestablished,seeinnerexception.

### Reproduction Steps

It's just normally opening the gacha and clicking to update the gacha log.

### Expected Behavior

"Naturally, it successfully updates the gacha log.

### Screenshots

![PixPin_2024-12-19_00-20-40](https://github.com/user-attachments/assets/4e549e3b-fb12-4e65-8dd8-83d4df6e8370)

### Starward Version

0.13.5

### Windows Version

22635.4655

### Log

```shell
[00:04:05.827] [EROR] Starward.Pages.GachaLogPage
Update gacha log
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean, Byte[], CancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions, HttpRequestMessage, Boolean, Stream, CancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions, HttpRequestMessage, Boolean, Stream, CancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(QueueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage, Boolean, Boolean, CancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage, HttpCompletionOption, CancellationTokenSource, Boolean, CancellationTokenSource, CancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.<FromJsonAsyncCore>g__Core|12_0[TValue,TJsonOptions](HttpClient, Task`1, Boolean, CancellationTokenSource, Func`4, TJsonOptions, CancellationToken)
   at Starward.Core.Gacha.ZZZ.ZZZGachaClient.GetGachaLogByQueryAsync[T](String gachaUrlPrefix, GachaLogQuery param, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\Gacha\ZZZ\ZZZGachaClient.cs:line 95
   at Starward.Core.Gacha.GachaLogClient.GetUidByGachaUrlAsync(String gachaUrl) in D:\a\Starward\Starward\src\Starward.Core\Gacha\GachaLogClient.cs:line 95
   at Starward.Services.Gacha.GachaLogService.GetUidFromGachaLogUrl(String url) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GachaLogService.cs:line 103
   at Starward.Pages.GachaLogPage.UpdateGachaLogInternalAsync(String url, Boolean all) in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 376
   at Starward.Pages.GachaLogPage.UpdateGachaLogAsync(String param) in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 360

[00:04:27.628] [EROR] Starward.Pages.GachaLogPage
Update wiki data hkrpg_cn
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean, Byte[], CancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions, HttpRequestMessage, Boolean, Stream, CancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions, HttpRequestMessage, Boolean, Stream, CancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(QueueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage, Boolean, Boolean, CancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage, HttpCompletionOption, CancellationTokenSource, Boolean, CancellationTokenSource, CancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.<FromJsonAsyncCore>g__Core|12_0[TValue,TJsonOptions](HttpClient, Task`1, Boolean, CancellationTokenSource, Func`4, TJsonOptions, CancellationToken)
   at Starward.Core.Gacha.GachaLogClient.CommonGetAsync[T](String url, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\Gacha\GachaLogClient.cs:line 231
   at Starward.Core.Gacha.GachaLogClient.GetStarRailGachaInfoAsync(GameBiz gameBiz, String lang, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\Gacha\GachaLogClient.cs:line 387
   at Starward.Services.Gacha.StarRailGachaService.UpdateGachaInfoAsync(GameBiz gameBiz, String lang, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\Gacha\StarRailGachaService.cs:line 157
   at Starward.Pages.GachaLogPage.UpdateWikiDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 286

[00:04:56.642] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[00:04:56.643] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_cn

[00:05:16.417] [INFO] Starward.Pages.MainPage
Change game region to nap_cn

[00:05:16.418] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param nap_cn

[00:05:48.401] [INFO] Starward.Services.Gacha.ZZZGachaService
Last gacha log id of uid 15029346 is 0

[00:06:21.476] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[00:06:21.476] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_cn

[00:06:52.391] [EROR] Starward.Pages.GachaLogPage
Update wiki data hk4e_cn
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean, Byte[], CancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions, HttpRequestMessage, Boolean, Stream, CancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions, HttpRequestMessage, Boolean, Stream, CancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage, Boolean, Boolean, CancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage, HttpCompletionOption, CancellationTokenSource, Boolean, CancellationTokenSource, CancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.<FromJsonAsyncCore>g__Core|12_0[TValue,TJsonOptions](HttpClient, Task`1, Boolean, CancellationTokenSource, Func`4, TJsonOptions, CancellationToken)
   at Starward.Core.Gacha.GachaLogClient.CommonGetAsync[T](String url, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\Gacha\GachaLogClient.cs:line 231
   at Starward.Core.Gacha.GachaLogClient.GetGenshinGachaInfoAsync(GameBiz gameBiz, String lang, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\Gacha\GachaLogClient.cs:line 368
   at Starward.Services.Gacha.GenshinGachaService.UpdateGachaInfoAsync(GameBiz gameBiz, String lang, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GenshinGachaService.cs:line 158
   at Starward.Pages.GachaLogPage.UpdateWikiDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 286

```
```


### Additional Context

_No response_

**Comment by Scighost** [comment]
There is a problem with your network environment. I'm sorry I can't help you.
