### ISSUE TITLE
[Bug] 星穹铁道跃迁记录从JSON导入出现问题

### ISSUE THREAD

**Issue by 1498551989** [Scighost/Starward#1191]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

我使用的是star-rail-warp-export v0.1.13（https://github.com/biuuu/star-rail-warp-export）导出的JSON文件
[UIGF_100159394_202412252305.json](https://github.com/user-attachments/files/18246479/UIGF_100159394_202412252305.json)
是UIGFv4.0版本的。
导入之后就报错NullReferenceException        Object reference not set to an instance of an object.

### Reproduction Steps

如以上描述

### Expected Behavior

希望可以正常导入星铁的抽卡记录。感谢大佬们开发了。

### Screenshots

![屏幕截图(211)](https://github.com/user-attachments/assets/ffeb49fe-9eae-4791-b500-5285109daa86)

### Starward Version

0.13.5

### Windows Version

22631.4602

### Log

```shell
[23:05:26.877] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hkrpg_cn

[23:05:46.459] [EROR] Starward.Pages.GachaLogPage
Import gacha log
System.NullReferenceException: Object reference not set to an instance of an object.
   at Starward.Services.Gacha.StarRailGachaService.ImportGachaLog(String file) in D:\a\Starward\Starward\src\Starward\Services\Gacha\StarRailGachaService.cs:line 135
   at Starward.Pages.GachaLogPage.ImportGachaLogAsync() in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 723

[23:06:00.934] [EROR] Starward.Pages.GachaLogPage
Import gacha log
System.NullReferenceException: Object reference not set to an instance of an object.
   at Starward.Services.Gacha.StarRailGachaService.ImportGachaLog(String file) in D:\a\Starward\Starward\src\Starward\Services\Gacha\StarRailGachaService.cs:line 135
   at Starward.Pages.GachaLogPage.ImportGachaLogAsync() in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 723
```

**Comment by Eric-Joker** [comment]
并未仔细看，但大概率是Starward仍不兼容UIGFv4导致的。我已提交过PR，但基于feature分支且该分支仍在开发中，无法及时上线。

**Comment by 1498551989** [comment]
> 并未仔细看，但大概率是Starward仍不兼容UIGFv4导致的。我已提交过PR，但基于feature分支且该分支仍在开发中，无法及时上线。

感谢回复，期待更新
