### ISSUE TITLE
[Bug] 关于原神多服通过超链接共存问题

### ISSUE THREAD

**Issue by Dinnerbonex3rd** [Scighost/Starward#1195]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

原神国服为主体，国际服创建了超链接，原本的国服却不能正常进入（即文件有问题，请从官方渠道下载），在修复之后也有可能国服的启动器文件直接丢失。

### Reproduction Steps

我在通过原神国际服进行超链接行为（国服为主题），且弄完原神国际服之后，我再回去登录原神国服，结果提示文件有问题，请从官方渠道进行下载。在我进行修复的时候，原神居然启动不了了，在我重新启动starward之后，原神国服那里的“启动游戏”变成了“安装游戏”，我去原神目录的时候，就只剩下了国际服原神的启动器文件。当我继续通过原神国服修复文件时候，变成了重新下载而不是进行修复，在原神国际服那里，修复完成之后变成了“硬链接-原神-全球官方”的提醒，原神国服那里怎么没有超链接呢？

### Expected Behavior

期盼的结果是：原神国服和原神国际服都能正常启动，且有超链接相互（即原神国服能通过原神国际服超链接下载，反过来也可以）

### Screenshots

![image](https://github.com/user-attachments/assets/5e0a4211-643f-47bf-ab91-09b5e2972711)
![image](https://github.com/user-attachments/assets/4bcd7cf0-7ff5-4f0f-a032-77eac4ebb510)
![image](https://github.com/user-attachments/assets/b876dfa1-ab97-4e0c-aec9-a892b10d834b)

### Starward Version

0.13.5

### Windows Version

26100.2605

### Log

```shell
[23:50:07.762] [INFO] 
Welcome to Starward v0.13.5
System: Microsoft Windows NT 10.0.26100.0
Command Line: "D:\Program Files\Starward\app-0.13.5\Starward.dll"

[23:50:07.796] [INFO] Starward.Services.DatabaseService
Database path is 'D:\Program Files\Starward'

[23:50:07.822] [INFO] Starward.Services.DatabaseService
Database version is 11, target version is 11.

[23:50:07.898] [INFO] Starward.Pages.MainPage
Last game region is hk4e_cn

[23:50:07.912] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[23:50:08.743] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "E:\Genshin Impact Game"

[23:50:08.763] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.2.0".

[23:50:09.705] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[23:50:11.936] [INFO] Starward.Services.UpdateService
Current version: "0.13.5", latest version: "0.13.5", ignore version: null

[23:50:13.553] [EROR] Starward.Services.HoYoPlayService
PrepareImagesAsync
System.NullReferenceException: Object reference not set to an instance of an object.
   at Starward.Services.HoYoPlayService.PrepareImagesAsync() in D:\a\Starward\Starward\src\Starward\Services\HoYoPlayService.cs:line 184

[23:50:20.449] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "E:\Genshin Impact Game"

[23:50:20.451] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.2.0".

[23:50:25.547] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "E:\Genshin Impact Game"

[23:50:25.548] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.2.0".

[23:52:33.331] [EROR] Starward.Pages.Setting.FileSettingPage
Update cache size
System.UnauthorizedAccessException: Access to the path 'C:\Users\23371\AppData\Local\Starward\webview\EBWebView\AutoLaunchProtocolsComponent\1.0.0.8' is denied.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateRelativeDirectoryHandle(ReadOnlySpan`1, String)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1)
   at System.IO.Directory.GetFiles(String, String, EnumerationOptions)
   at Starward.Pages.Setting.FileSettingPage.<>c__DisplayClass18_0.<GetFolderSizeStringAsync>b__0() in D:\a\Starward\Starward\src\Starward\Pages\Setting\FileSettingPage.xaml.cs:line 321
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
--- End of stack trace from previous location ---
   at Starward.Pages.Setting.FileSettingPage.GetFolderSizeStringAsync(String folder) in D:\a\Starward\Starward\src\Starward\Pages\Setting\FileSettingPage.xaml.cs:line 317
   at Starward.Pages.Setting.FileSettingPage.UpdateCacheSizeAsync() in D:\a\Starward\Starward\src\Starward\Pages\Setting\FileSettingPage.xaml.cs:line 306
```

**Comment by 111inhistory** [comment]
我没看错的话，你是把两个服都放在同一个文件夹了对吧？游戏路径是要分开来的，而不是混在一起。

**Comment by Dinnerbonex3rd** [comment]
> 我没看错的话，你是把两个服都放在同一个文件夹了对吧？游戏路径是要分开来的，而不是混在一起。

是放在一块了，哦谢谢解答。
