### ISSUE TITLE
[Bug] 预下载校验失败后重新下载进度不重置

### ISSUE THREAD

**Issue by Eric-Joker** [Scighost/Starward#136]
### Description

预下载校验失败后重新下载进度不重置

### Reproduction Steps

预下载，校验失败，点击重新下载

### Expected Behavior

进度正常显示

### Screenshots

![8caa0baeb495c87bee8772d95589351](https://github.com/Scighost/Starward/assets/60310368/6eba8430-defb-4a91-9823-486ba10f4da7)

### Starward Version

0.8.0

### Windows Version

22621.1848

### Log

<details>

[11:08:43.038] [INFO]
Request head: "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[11:52:51.531] [INFO]
Change game region to hkrpg_cn

[11:52:51.946] [INFO]
Navigate to "LauncherPage" with param null

[11:13:53.994] [INFO]
Request head: "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/ja-jp_3.7.0_3.8.0_hdiff_sjdfOIWbuHG4PE9h.zip"

[11:13:53.994] [INFO]
Request head: "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[11:13:53.994] [INFO]
Request head: "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/zh-cn_3.7.0_3.8.0_hdiff_UYKG07P2EINceiZV.zip"

[11:13:54.223] [INFO]
Download Slice: FileName "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip.slice.000", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[11:13:54.223] [INFO]
Download Slice: FileName "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip.slice.004", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[11:13:54.223] [INFO]
Download Slice: FileName "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip.slice.003", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[11:13:54.223] [INFO]
Download Slice: FileName "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip.slice.001", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[11:13:54.223] [INFO]
Download Slice: FileName "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip.slice.005", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[11:13:54.224] [INFO]
Download Slice: FileName "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip.slice.006", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[11:13:54.225] [INFO]
Download Slice: FileName "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip.slice.002", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[11:13:54.230] [INFO]
Download Slice: FileName "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip.slice.007", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[11:26:36.678] [INFO]
Download Slice: FileName "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip.slice.008", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[11:26:36.979] [INFO]
Download Slice: FileName "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip.slice.009", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[11:26:38.219] [INFO]
Download Slice: FileName "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip.slice.010", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[11:26:38.574] [INFO]
Download Slice: FileName "zh-cn_3.7.0_3.8.0_hdiff_UYKG07P2EINceiZV.zip.slice.000", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/zh-cn_3.7.0_3.8.0_hdiff_UYKG07P2EINceiZV.zip"

[11:26:38.818] [INFO]
Download Slice: FileName "ja-jp_3.7.0_3.8.0_hdiff_sjdfOIWbuHG4PE9h.zip.slice.000", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/ja-jp_3.7.0_3.8.0_hdiff_sjdfOIWbuHG4PE9h.zip"

[11:31:17.119] [INFO]
Verify file "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[11:32:30.953] [WARN]
File checksum failure: "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[11:32:30.979] [INFO]
Verify file "zh-cn_3.7.0_3.8.0_hdiff_UYKG07P2EINceiZV.zip"

[11:32:32.881] [INFO]
Verify file "ja-jp_3.7.0_3.8.0_hdiff_sjdfOIWbuHG4PE9h.zip"

[11:32:35.815] [EROR]
Show error message
System.Runtime.InteropServices.COMException (0x80000019): 某个异步操作没有正常启动。

   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32)
   at ABI.Microsoft.UI.Xaml.Controls.IContentDialogMethods.ShowAsync(IObjectReference)
   at Starward.Pages.DownloadGamePage.ShowErrorMessage() in D:\a\Starward\Starward\Starward\Pages\DownloadGamePage.xaml.cs:line 413

[11:37:53.502] [INFO]
Download Slice: FileName "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip.slice.000", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[11:37:53.506] [INFO]
Download Slice: FileName "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip.slice.001", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[11:37:53.509] [INFO]
Download Slice: FileName "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip.slice.002", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[11:37:53.512] [INFO]
Download Slice: FileName "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip.slice.003", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[11:37:53.516] [INFO]
Download Slice: FileName "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip.slice.005", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[11:37:53.516] [INFO]
Download Slice: FileName "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip.slice.006", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[11:37:53.516] [INFO]
Download Slice: FileName "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip.slice.004", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[11:37:53.517] [INFO]
Download Slice: FileName "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip.slice.007", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[11:44:55.174] [INFO]
Download Slice: FileName "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip.slice.008", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[11:45:03.952] [INFO]
Download Slice: FileName "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip.slice.009", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[11:47:44.879] [INFO]
Download Slice: FileName "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip.slice.010", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[11:53:31.396] [INFO]
Verify file "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[11:54:44.898] [WARN]
File checksum failure: "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[11:54:44.899] [INFO]
Verify file "zh-cn_3.7.0_3.8.0_hdiff_UYKG07P2EINceiZV.zip"

[11:54:46.863] [INFO]
Verify file "ja-jp_3.7.0_3.8.0_hdiff_sjdfOIWbuHG4PE9h.zip"

[11:54:50.141] [EROR]
Show error message
System.Runtime.InteropServices.COMException (0x80000019): 某个异步操作没有正常启动。

   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32)
   at ABI.Microsoft.UI.Xaml.Controls.IContentDialogMethods.ShowAsync(IObjectReference)
   at Starward.Pages.DownloadGamePage.ShowErrorMessage() in D:\a\Starward\Starward\Starward\Pages\DownloadGamePage.xaml.cs:line 413

[12:08:02.285] [INFO]
Download Slice: FileName "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip.slice.002", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[12:08:02.285] [INFO]
Download Slice: FileName "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip.slice.006", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[12:08:02.285] [INFO]
Download Slice: FileName "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip.slice.001", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[12:08:02.285] [INFO]
Download Slice: FileName "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip.slice.000", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[12:08:02.285] [INFO]
Download Slice: FileName "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip.slice.003", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[12:08:02.285] [INFO]
Download Slice: FileName "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip.slice.007", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[12:08:02.285] [INFO]
Download Slice: FileName "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip.slice.005", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[12:08:02.285] [INFO]
Download Slice: FileName "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip.slice.004", Url "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

</details>

**Comment by Scighost** [comment]
请发一下日志

**Comment by Eric-Joker** [comment]
> 请发一下日志

改了

**Comment by Scighost** [comment]
日志中没有指明问题来源，但是我回顾代码之后发现了下载过程中的流程错误。当网络环境不好，不能 一次下载完成时，就会出现这种问题。

**Comment by Eric-Joker** [comment]
> 日志中没有指明问题来源，但是我回顾代码之后发现了下载过程中的流程错误。当网络环境不好，不能 一次下载完成时，就会出现这种问题。

呃，我用starward下载就没校验成功过，试了七八次了，也没有更多日志，忽略校验解压到一半的时候提示The archive entry was compressed using an unsupported compression method.所以是下载器确实有问题还是真的只是我的问题，我用官方启动器正常。。没试过修复模式

**Comment by Eric-Joker** [comment]
> 日志中没有指明问题来源，但是我回顾代码之后发现了下载过程中的流程错误。当网络环境不好，不能 一次下载完成时，就会出现这种问题。


[13:30:09.215] [WARN]
File checksum failure: "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[13:30:09.215] [INFO]
Verify file "zh-cn_3.7.0_3.8.0_hdiff_UYKG07P2EINceiZV.zip"

[13:31:17.869] [INFO]
Move audio assets.

[13:31:17.886] [INFO]
Decompress "game_3.7.0_3.8.0_hdiff_9NyUn6a8I2Og7eVD.zip"

[13:32:39.268] [EROR]
Decompress file
System.IO.InvalidDataException: The archive entry was compressed using an unsupported compression method.
   at System.IO.Compression.Inflater.Inflate(FlushCode)
   at System.IO.Compression.Inflater.ReadInflateOutput(Byte*, Int32, FlushCode, Int32& )
   at System.IO.Compression.Inflater.InflateVerified(Byte*, Int32)
   at System.IO.Compression.DeflateStream.CopyToStream.Write(Byte[], Int32, Int32)
   at System.IO.Stream.CopyTo(Stream, Int32)
   at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestination()
   at System.IO.Compression.DeflateStream.CopyTo(Stream, Int32)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry, String, Boolean)
   at Starward.Services.DownloadGameService.<>c__DisplayClass62_0.<DecompressAsync>b__1() in D:\a\Starward\Starward\Starward\Services\DownloadGameService.cs:line 1208
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
--- End of stack trace from previous location ---
   at Starward.Services.DownloadGameService.DecompressAsync(IEnumerable`1 files, Boolean use7zip) in D:\a\Starward\Starward\Starward\Services\DownloadGameService.cs:line 1193
   at Starward.Services.DownloadGameService.DecompressAsync() in D:\a\Starward\Starward\Starward\Services\DownloadGameService.cs:line 1102
