### ISSUE TITLE
[Bug] 系统托盘图标无效

### ISSUE THREAD

**Issue by mlrsyz** [Scighost/Starward#251]
### Description

[0.9.0 Preview 1]的托盘图标是没问题的   
更新到[0.9.0 - Kafka]就无法挂起托盘图标了
![image](https://github.com/Scighost/Starward/assets/44489042/181f6d87-86f7-4351-a274-a7cf7d72e6b4)

### Reproduction Steps

[Starward 0.9.0 - Kafka]的系统托盘功能打开无效

### Starward Version

0.9.0 - Kafka

### Windows Version

19045.3271

**Comment by mlrsyz** [comment]
看了下日志  不知道是否有帮助



[10:49:03.128] [INFO] 
Welcome to Starward v0.9.0
System: Microsoft Windows NT 10.0.19045.0
Command Line: C:\Game\Starward\app-0.9.0\Starward.dll

[10:49:26.771] [INFO] Starward.Pages.Welcome.SelectDirectoryPage
Select directory is '"C:\Game\Starward"'

[10:49:43.267] [INFO] Starward.Pages.Welcome.SelectDirectoryPage
Select directory is '"C:\Game\Starward"'

[10:50:10.251] [INFO] Starward.Pages.Welcome.SelectGamePage
Change game region to hkrpg_cn

[10:50:13.214] [INFO] Starward.Services.DatabaseService
Database path is 'C:\Game\Starward'

[10:50:13.231] [INFO] Starward.Services.DatabaseService
Database version is 6, target version is {DatabaseSqls.Count}.

[10:50:16.290] [INFO] Starward.Pages.MainPage
Select game region is hkrpg_cn

[10:50:16.290] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_cn

[10:50:16.413] [EROR] Starward.Services.SystemTrayService
Initialize system tray
System.InvalidOperationException: TryCreate failed.
   at H.NotifyIcon.Core.TrayIcon.Create() in /_/src/libs/H.NotifyIcon/Core/TrayIcon.cs:line 324
   at H.NotifyIcon.TaskbarIcon.ForceCreate(Boolean ) in /_/src/libs/H.NotifyIcon.Shared/TaskbarIcon.cs:line 134
   at Starward.Services.SystemTrayService.Initialize(GameBiz gameBiz) in D:\a\Starward\Starward\Starward\Services\SystemTrayService.cs:line 72

[10:50:16.535] [INFO] Starward.Pages.LauncherPage
Game install path hkrpg_cn: "C:\Game\Star Rail\Game"

[10:50:16.554] [INFO] Starward.Pages.LauncherPage
Game is running ("StarRail", 13764)

[10:50:16.710] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[10:50:17.631] [INFO] Starward.Services.UpdateService
Current version: "0.9.0", latest version: "0.9.0-preview.1", ignore version: null

[10:50:21.370] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[10:50:21.380] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[10:50:21.440] [INFO] Starward.Pages.LauncherPage
Game install path hk4e_cn: "C:\Game\Genshin Impact\Genshin Impact Game"

[10:50:41.989] [INFO] Starward.Pages.MainPage
Navigate to "SettingPage" with param hk4e_cn

**Comment by phucho0237** [comment]
Same bug

**Comment by Scighost** [comment]
日志显示 [H.NotifyIcon](https://github.com/HavenDV/H.NotifyIcon) 的内部方法在创建托盘图标时出错了，但是它没有提供更多的信息，我无法确认错误原因。你可以选择回退到 0.9.0-preview.1 版本。

The logs show that the internal method of [H.NotifyIcon](https://github.com/HavenDV/H.NotifyIcon) has an error when creating a tray icon, but it doesn't provide any more information and I can't confirm the cause of the error. You cloud roll back to 0.9.0-preview.1.

**Comment by mxia9416** [comment]
我也是这个问题，然后通过issue主和我自己的log对比，我有一个不太成熟的猜想：
at Starward.Services.SystemTrayService.Initialize(GameBiz gameBiz) in D:\a\Starward\Starward\Starward\Services\SystemTrayService.cs:line 72
这里，我的也是这个路径，但是我是没有d盘的！所以是不是这个路径是hard code在这里的，然后调用不了就失败了？

**Comment by mxia9416** [comment]
不太懂c#，有点不成熟的猜想：
我是把starward放在e盘，楼主是c盘，但是我和他的错误日志都指向了d盘，是不是因为这个原因，找不到路径所以报错了？
我的是：
at Starward.Services.SystemTrayService.Initialize(GameBiz gameBiz) in D:\a\Starward\Starward\src\Starward\Services\SystemTrayService.cs:line 72

**Comment by BillionKang** [comment]
我在0.9.0 Preview 1更新到0.9.0，和0.9.0更新到0.9.1时都遇到了这个问题，都是启动器内完成的更新。
然后在执行了如下清理缩略图用的脚本后恢复正常，主要应该是注册表那两行
` 
taskkill /f /im explorer.exe
del /f /s /q /a "%LocalAppData%\IconCache.db"
cd /d "%LocalAppData%\Microsoft\Windows\Explorer"
del /f /s /q /a thumbcache_*.db
del /f /s /q /a iconcache_*.db
reg delete "HKCR\Local Settings\Software\Microsoft\Windows\CurrentVersion\TrayNotify" /v IconStreams /f
reg delete "HKCR\Local Settings\Software\Microsoft\Windows\CurrentVersion\TrayNotify" /v PastIconsStream /f
start explorer
`
希望能有所帮助 改bug用不上能帮人治个标也成

**Comment by Scighost** [comment]
根据我的测试，在 Windows 10 上应用更新一次后此问题就会出现。也就是说，即使运行了上述命令，应用更新后仍然会出现相同的问题。现在我无法确定原因，也没有一劳永逸的解决办法。

According my test, this issue occurs after the app updates to any new version on Windows 10. So even though run the above script, the issue will still happen. Now I cannot locate the reason and resolve permanently.

**Comment by Lightczx** [comment]
更新一次之后连开始菜单的图标都变糊了，可能和这个问题相关

**Comment by xiaoxingruo** [comment]
> 我在0.9.0 Preview 1更新到0.9.0，和0.9.0更新到0.9.1时都遇到了这个问题，都是启动器内完成的更新。 然后在执行了如下清理缩略图用的脚本后恢复正常，主要应该是注册表那两行
> 
> ```batchfile
> taskkill /f /im explorer.exe
> del /f /s /q /a "%LocalAppData%\IconCache.db"
> cd /d "%LocalAppData%\Microsoft\Windows\Explorer"
> del /f /s /q /a thumbcache_*.db
> del /f /s /q /a iconcache_*.db
> reg delete "HKCR\Local Settings\Software\Microsoft\Windows\CurrentVersion\TrayNotify" /v IconStreams /f
> reg delete "HKCR\Local Settings\Software\Microsoft\Windows\CurrentVersion\TrayNotify" /v PastIconsStream /f
> start explorer
> ```
> 
> 希望能有所帮助 改bug用不上能帮人治个标也成

这个脚本要怎么用呀？

**Comment by xiaoxingruo** [comment]
> 我在0.9.0 Preview 1更新到0.9.0，和0.9.0更新到0.9.1时都遇到了这个问题，都是启动器内完成的更新。 然后在执行了如下清理缩略图用的脚本后恢复正常，主要应该是注册表那两行
> 
> ```batchfile
> taskkill /f /im explorer.exe
> del /f /s /q /a "%LocalAppData%\IconCache.db"
> cd /d "%LocalAppData%\Microsoft\Windows\Explorer"
> del /f /s /q /a thumbcache_*.db
> del /f /s /q /a iconcache_*.db
> reg delete "HKCR\Local Settings\Software\Microsoft\Windows\CurrentVersion\TrayNotify" /v IconStreams /f
> reg delete "HKCR\Local Settings\Software\Microsoft\Windows\CurrentVersion\TrayNotify" /v PastIconsStream /f
> start explorer
> ```
> 
> 希望能有所帮助 改bug用不上能帮人治个标也成

会用了，谢谢你的脚本！

**Comment by Scighost** [comment]
Starting from [0.10.0-preview.1](https://github.com/Scighost/Starward/releases/tag/0.10.0-preview.1), you could solve it by click **Repair System Tray**.

<img width="250" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/3d019042-70f8-4d69-b8aa-858955fb297f">

**Comment by lijian12345** [comment]
```
[21:17:40.722] [EROR] Starward.Services.SystemTrayService
Initialize system tray
System.InvalidOperationException: TryCreate failed.
   at H.NotifyIcon.Core.TrayIcon.Create() in /_/src/libs/H.NotifyIcon/Core/TrayIcon.cs:line 324
   at H.NotifyIcon.TaskbarIcon.ForceCreate(Boolean ) in /_/src/libs/H.NotifyIcon.Shared/TaskbarIcon.cs:line 134
   at Starward.Services.SystemTrayService.Initialize(GameBiz gameBiz) in D:\a\Starward\Starward\src\Starward\Services\SystemTrayService.cs:line 72

[21:17:52.784] [INFO] Starward.Pages.SettingPage
Repair system tray log:
"Remove-ItemProperty : 路径 HKEY_CLASSES_ROOT\Local Settings\Software\Microsoft\Windows\CurrentVersion\TrayNotify 处不存
在属性 IconStreams。
所在位置 行:3 字符: 1
+ Remove-ItemProperty -Path $key -Name IconStreams -ErrorAction Continu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (IconStreams:String) [Remove-ItemProperty]，PSArgumentException
    + FullyQualifiedErrorId : System.Management.Automation.PSArgumentException,Microsoft.PowerShell.Commands.RemoveIte 
   mPropertyCommand
 
Remove-ItemProperty : 路径 HKEY_CLASSES_ROOT\Local Settings\Software\Microsoft\Windows\CurrentVersion\TrayNotify 处不存
在属性 PastIconsStream。
所在位置 行:4 字符: 1
+ Remove-ItemProperty -Path $key -Name PastIconsStream -ErrorAction Con ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (PastIconsStream:String) [Remove-ItemProperty]，PSArgumentException
    + FullyQualifiedErrorId : System.Management.Automation.PSArgumentException,Microsoft.PowerShell.Commands.RemoveIte 
   mPropertyCommand
 
"

[21:17:53.799] [EROR] Starward.Pages.SettingPage
Repair system tray
System.ApplicationException: Object synchronization method was called from an unsynchronized block of code.
   at System.Threading.Mutex.ReleaseMutex()
   at Starward.Services.SystemTrayService.Initialize(GameBiz gameBiz) in D:\a\Starward\Starward\src\Starward\Services\SystemTrayService.cs:line 91
   at Starward.Pages.SettingPage.RepairSystemTray() in D:\a\Starward\Starward\src\Starward\Pages\SettingPage.xaml.cs:line 330
```

很奇怪，我这注册表没有那两项，但是托盘还是不显示。。。

**Comment by hhelibeb** [comment]
> ```
> [21:17:40.722] [EROR] Starward.Services.SystemTrayService
> Initialize system tray
> System.InvalidOperationException: TryCreate failed.
>    at H.NotifyIcon.Core.TrayIcon.Create() in /_/src/libs/H.NotifyIcon/Core/TrayIcon.cs:line 324
>    at H.NotifyIcon.TaskbarIcon.ForceCreate(Boolean ) in /_/src/libs/H.NotifyIcon.Shared/TaskbarIcon.cs:line 134
>    at Starward.Services.SystemTrayService.Initialize(GameBiz gameBiz) in D:\a\Starward\Starward\src\Starward\Services\SystemTrayService.cs:line 72
> 
> [21:17:52.784] [INFO] Starward.Pages.SettingPage
> Repair system tray log:
> "Remove-ItemProperty : 路径 HKEY_CLASSES_ROOT\Local Settings\Software\Microsoft\Windows\CurrentVersion\TrayNotify 处不存
> 在属性 IconStreams。
> 所在位置 行:3 字符: 1
> + Remove-ItemProperty -Path $key -Name IconStreams -ErrorAction Continu ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidArgument: (IconStreams:String) [Remove-ItemProperty]，PSArgumentException
>     + FullyQualifiedErrorId : System.Management.Automation.PSArgumentException,Microsoft.PowerShell.Commands.RemoveIte 
>    mPropertyCommand
>  
> Remove-ItemProperty : 路径 HKEY_CLASSES_ROOT\Local Settings\Software\Microsoft\Windows\CurrentVersion\TrayNotify 处不存
> 在属性 PastIconsStream。
> 所在位置 行:4 字符: 1
> + Remove-ItemProperty -Path $key -Name PastIconsStream -ErrorAction Con ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidArgument: (PastIconsStream:String) [Remove-ItemProperty]，PSArgumentException
>     + FullyQualifiedErrorId : System.Management.Automation.PSArgumentException,Microsoft.PowerShell.Commands.RemoveIte 
>    mPropertyCommand
>  
> "
> 
> [21:17:53.799] [EROR] Starward.Pages.SettingPage
> Repair system tray
> System.ApplicationException: Object synchronization method was called from an unsynchronized block of code.
>    at System.Threading.Mutex.ReleaseMutex()
>    at Starward.Services.SystemTrayService.Initialize(GameBiz gameBiz) in D:\a\Starward\Starward\src\Starward\Services\SystemTrayService.cs:line 91
>    at Starward.Pages.SettingPage.RepairSystemTray() in D:\a\Starward\Starward\src\Starward\Pages\SettingPage.xaml.cs:line 330
> ```
> 
> 很奇怪，我这注册表没有那两项，但是托盘还是不显示。。。

我也失败了，和你一样的报错

**Comment by Scighost** [comment]
@lijian12345 @hhelibeb 我也不知道怎么办

**Comment by lijian12345** [comment]
> @lijian12345 @hhelibeb 我也不知道怎么办

大佬问题不大，不影响使用哈哈
