### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by animalsBeef** [Scighost/Starward#256]
### Description

祈愿记录-导出Excel文档时报错
KeyNotFoundException
The given key ldText' was not present in the dictionary

### Reproduction Steps

祈愿记录-导出Excel文档时报错

### Expected Behavior

导出Excel文档时提示，字典中缺少关键字“IdText”

### Screenshots

![报错信息](https://github.com/Scighost/Starward/assets/12947893/96631b03-5291-42f9-9c37-f858f1c2d913)

### Starward Version

0.9.0

### Windows Version

Windows 11 专业版

### Log

```shell
fail: Starward.Pages.GachaLogPage[0]
      Export gacha log
      System.Collections.Generic.KeyNotFoundException: The given key 'IdText' was not present in the dictionary.
         at System.Collections.Generic.Dictionary`2.get_Item(TKey)
         at MiniExcelLibs.OpenXml.ExcelOpenXmlTemplate.UpdateDimensionAndGetRowsInfo(Dictionary`2 inputMaps, XmlDocument& doc, XmlNodeList& rows, Boolean changeRowIndex)
         at MiniExcelLibs.OpenXml.ExcelOpenXmlTemplate.GenerateSheetXmlImpl(ZipArchiveEntry sheetZipEntry, Stream stream, Stream sheetStream, Dictionary`2 inputMaps, IDictionary`2 sharedStrings, Boolean mergeCells)
         at MiniExcelLibs.OpenXml.ExcelOpenXmlTemplate.SaveAsByTemplateImpl(Stream templateStream, Object value)
         at MiniExcelLibs.OpenXml.ExcelOpenXmlTemplate.SaveAsByTemplate(String templatePath, Object value)
         at MiniExcelLibs.MiniExcel.SaveAsByTemplate(String path, String templatePath, Object value, IConfiguration configuration)
         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
      --- End of stack trace from previous location ---
         at MiniExcelLibs.MiniExcel.SaveAsByTemplateAsync(String path, String templatePath, Object value, IConfiguration configuration, CancellationToken cancellationToken)
         at Starward.Services.Gacha.StarRailGachaService.ExportAsExcelAsync(Int64 uid, String output) in D:\a\Starward\Starward\Starward\Services\Gacha\StarRailGachaService.cs:line 120
         at Starward.Services.Gacha.StarRailGachaService.ExportGachaLogAsync(Int64 uid, String file, String format) in D:\a\Starward\Starward\Starward\Services\Gacha\StarRailGachaService.cs:line 93
         at Starward.Pages.GachaLogPage.ExportGachaLogAsync(String format) in D:\a\Starward\Starward\Starward\Pages\GachaLogPage.xaml.cs:line 527
```

**Comment by Scighost** [comment]
Closed for no title or content.
