### ISSUE TITLE
[Bug]崩坏星穹铁道 忘却之庭无法刷新(1034)

### ISSUE THREAD

**Issue by AdmireLinK** [Scighost/Starward#265]
### Description

崩坏星穹铁道
在绑定米游社账号后模拟宇宙和开拓月历均能正常刷新 但刷新忘却之庭提示1034

### Reproduction Steps

使用网页登录 然后刷新忘却之庭

### Expected Behavior

账号异常(1034)

### Screenshots

![image](https://github.com/Scighost/Starward/assets/64939678/987a104b-f7fc-4f59-9249-6b28b1ebf71f)
![image](https://github.com/Scighost/Starward/assets/64939678/fc830e89-2119-40fc-a84f-6230026f7c3c)
![image](https://github.com/Scighost/Starward/assets/64939678/28c8e0d5-c115-4d8a-a2ae-d388364ceeb7)

### Starward Version

0.9.0

### Windows Version

22621.2134

### Log

```shell
[23:59:13.651] [INFO] 
Welcome to Starward v0.9.0
System: Microsoft Windows NT 10.0.22621.0
Command Line: C:\Users\35407\Downloads\Starward09\Starward\win10-x64\Starward.dll

[23:59:13.741] [INFO] Starward.Services.DatabaseService
Database path is 'C:\Users\35407\Downloads\Starward09\Starward'

[23:59:13.793] [INFO] Starward.Services.DatabaseService
Database version is 6, target version is {DatabaseSqls.Count}.

[23:59:13.914] [INFO] Starward.Pages.MainPage
Select game region is hkrpg_cn

[23:59:13.915] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_cn

[23:59:14.591] [INFO] Starward.Pages.LauncherPage
Game install path hkrpg_cn: "E:\Honkai Star Rail\Game"

[23:59:14.650] [INFO] Starward.Pages.LauncherPage
Game is running ("StarRail", 32400)

[23:59:15.197] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[23:59:16.929] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hkrpg_cn

[23:59:16.946] [INFO] Starward.Services.GameRecordService
Change region to China.

[23:59:18.492] [INFO] Starward.Services.UpdateService
Current version: "0.9.0", latest version: "0.9.0", ignore version: null

[23:59:35.632] [EROR] Starward.Pages.HoyolabToolbox.ForgottenHallPage
Refresh forgotten hall data ("hkrpg_cn", 113436771).
Starward.Core.miHoYoApiException:  (1034)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in C:\Users\19118\Desktop\Starward-0.9.0\Starward.Core\GameRecord\GameRecordClient.cs:line 162
   at Starward.Core.GameRecord.HyperionClient.GetForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in C:\Users\19118\Desktop\Starward-0.9.0\Starward.Core\GameRecord\HyperionClient.cs:line 268
   at Starward.Services.GameRecordService.RefreshForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in C:\Users\19118\Desktop\Starward-0.9.0\Starward\Services\GameRecordService.cs:line 447
   at Starward.Pages.HoyolabToolbox.ForgottenHallPage.RefreshDataAsync() in C:\Users\19118\Desktop\Starward-0.9.0\Starward\Pages\HoyolabToolbox\ForgottenHallPage.xaml.cs:line 110

[00:00:34.411] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[00:00:34.414] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hk4e_cn

[00:00:34.425] [INFO] Starward.Services.GameRecordService
Change region to China.

[00:02:21.121] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[00:02:21.122] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hkrpg_cn

[00:02:21.131] [INFO] Starward.Services.GameRecordService
Change region to China.

[00:02:25.601] [EROR] Starward.Pages.HoyolabToolbox.ForgottenHallPage
Refresh forgotten hall data ("hkrpg_cn", 113436771).
Starward.Core.miHoYoApiException:  (1034)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in C:\Users\19118\Desktop\Starward-0.9.0\Starward.Core\GameRecord\GameRecordClient.cs:line 162
   at Starward.Core.GameRecord.HyperionClient.GetForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in C:\Users\19118\Desktop\Starward-0.9.0\Starward.Core\GameRecord\HyperionClient.cs:line 268
   at Starward.Services.GameRecordService.RefreshForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in C:\Users\19118\Desktop\Starward-0.9.0\Starward\Services\GameRecordService.cs:line 447
   at Starward.Pages.HoyolabToolbox.ForgottenHallPage.RefreshDataAsync() in C:\Users\19118\Desktop\Starward-0.9.0\Starward\Pages\HoyolabToolbox\ForgottenHallPage.xaml.cs:line 110

[00:04:20.995] [EROR] Starward.Pages.HoyolabToolbox.ForgottenHallPage
Refresh forgotten hall data ("hkrpg_cn", 113436771).
Starward.Core.miHoYoApiException:  (1034)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in C:\Users\19118\Desktop\Starward-0.9.0\Starward.Core\GameRecord\GameRecordClient.cs:line 162
   at Starward.Core.GameRecord.HyperionClient.GetForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in C:\Users\19118\Desktop\Starward-0.9.0\Starward.Core\GameRecord\HyperionClient.cs:line 268
   at Starward.Services.GameRecordService.RefreshForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in C:\Users\19118\Desktop\Starward-0.9.0\Starward\Services\GameRecordService.cs:line 447
   at Starward.Pages.HoyolabToolbox.ForgottenHallPage.RefreshDataAsync() in C:\Users\19118\Desktop\Starward-0.9.0\Starward\Pages\HoyolabToolbox\ForgottenHallPage.xaml.cs:line 110

[00:05:46.262] [EROR] Starward.Pages.HoyolabToolbox.ForgottenHallPage
Refresh forgotten hall data ("hkrpg_cn", 113436771).
Starward.Core.miHoYoApiException:  (1034)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in C:\Users\19118\Desktop\Starward-0.9.0\Starward.Core\GameRecord\GameRecordClient.cs:line 162
   at Starward.Core.GameRecord.HyperionClient.GetForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in C:\Users\19118\Desktop\Starward-0.9.0\Starward.Core\GameRecord\HyperionClient.cs:line 268
   at Starward.Services.GameRecordService.RefreshForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in C:\Users\19118\Desktop\Starward-0.9.0\Starward\Services\GameRecordService.cs:line 447
   at Starward.Pages.HoyolabToolbox.ForgottenHallPage.RefreshDataAsync() in C:\Users\19118\Desktop\Starward-0.9.0\Starward\Pages\HoyolabToolbox\ForgottenHallPage.xaml.cs:line 110

[00:06:29.054] [INFO] Starward.Pages.MainPage
Navigate to "SettingPage" with param hkrpg_cn
```

**Comment by AdmireLinK** [comment]
已解决 是我账号风控了 过一下验证码就好了
