### ISSUE TITLE
[Bug] 原神的祈愿记录无法获取

### ISSUE THREAD

**Issue by hlx31** [Scighost/Starward#271]
### Description

在我单击原神-祈愿记录-获取记录后，显示"Authkey timeout 请在游戏中打开抽卡记录界面后再重试"

我很确信我已经在游戏中打开了抽卡记录的界面

但是无论我是否使用管理员模式打开”Starward“，都无法获取到祈愿记录

后来我在“寻空”中启动代理获取到了祈愿记录的URL，并将其复制到”Starward“后才得以更新祈愿记录

### Reproduction Steps

步骤：原神-祈愿记录-获取记录

设置：………………也不存在什么特殊的样子

           或者是数据文件夹带中文的问题？（猜一个）但是之前好像没问题的样子

其他的……好像真的没什么可以写的

### Expected Behavior

需要抽卡记录可以被正确获取并添加。:)

或者搞个代理也可以……

### Starward Version

0.9.0

### Windows Version

25926.1000

### Log

```shell
Starward:
[23:40:28.047] [INFO] 
Welcome to Starward v0.9.0
System: Microsoft Windows NT 10.0.25926.0
Command Line: D:\Software\Starward\app-0.9.0\Starward.dll

[23:40:28.105] [INFO] Starward.Services.DatabaseService
Database path is 'E:\个人\Starward'

[23:40:28.133] [INFO] Starward.Services.DatabaseService
Database version is 6, target version is {DatabaseSqls.Count}.

[23:40:28.196] [INFO] Starward.Pages.MainPage
Select game region is hk4e_cn

[23:40:28.196] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[23:40:28.646] [INFO] Starward.Pages.LauncherPage
Game install path hk4e_cn: "F:\Mihoyo\Genshin Impact"

[23:40:28.674] [INFO] Starward.Pages.LauncherPage
Game is running ("YuanShen", 7844)

[23:40:28.733] [WARN] Starward.Services.GameService
Game uninstalled (hk4e_global)

[23:40:28.733] [WARN] Starward.Services.GameService
Game uninstalled (hk4e_cloud)

[23:40:28.734] [WARN] Starward.Services.GameService
Game uninstalled (hkrpg_global)

[23:40:28.735] [WARN] Starward.Services.GameService
Game uninstalled (bh3_global)

[23:40:28.735] [WARN] Starward.Services.GameService
Game uninstalled (bh3_jp)

[23:40:28.736] [WARN] Starward.Services.GameService
Game uninstalled (bh3_kr)

[23:40:28.736] [WARN] Starward.Services.GameService
Game uninstalled (bh3_overseas)

[23:40:28.737] [WARN] Starward.Services.GameService
Game uninstalled (bh3_tw)

[23:40:28.980] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[23:40:29.795] [INFO] Starward.Services.UpdateService
Current version: "0.9.0", latest version: "0.9.0", ignore version: null

[23:40:35.245] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_cn

[23:40:36.769] [WARN] Starward.Pages.GachaLogPage
Request mihoyo api error: "authkey timeout (-101)"

[23:40:44.137] [WARN] Starward.Pages.GachaLogPage
Request mihoyo api error: "authkey timeout (-101)"

[23:42:00.269] [INFO] Starward.Pages.MainPage
Navigate to "SettingPage" with param hk4e_cn

[23:42:03.790] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[23:42:04.302] [INFO] Starward.Services.UpdateService
Current version: "0.9.0", latest version: "0.9.0", ignore version: null

[23:45:19.298] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_cn

[23:45:25.555] [INFO] Starward.Services.Gacha.GenshinGachaService
Last gacha log id of uid 150439905 is 1691067960001624505

[23:45:41.553] [WARN] Starward.Pages.GachaLogPage
Request mihoyo api error: "authkey timeout (-101)"

[23:45:47.524] [INFO] Starward.Pages.MainPage
Navigate to "SettingPage" with param hk4e_cn

[23:49:33.622] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_cn

[23:49:36.005] [WARN] Starward.Pages.GachaLogPage
Request mihoyo api error: "authkey timeout (-101)"

[23:49:46.368] [WARN] Starward.Pages.GachaLogPage
Request mihoyo api error: "authkey timeout (-101)"

[00:06:38.361] [INFO] Starward.Pages.MainPage
Navigate to "SettingPage" with param hk4e_cn

[00:06:42.437] [INFO] Starward.Pages.SettingPage
Open folder '"E:\个人\Starward"'

以上是8月15日全部的log了

寻空的……单击获取记录也没能在Everythig里修改时间排序找到相应的文件。应该是没找到，在相应的log文件夹……不知道是不是以下这些………………
[23:53:24.468] [INFO] 
寻空 1.4.0.0
D5329ED2EC7A426835839CD9A4A9C2F5
"C:\Program Files\WindowsApps\40418Scighost.Xunkong_1.4.0.0_x64__db3crskbcera8\Xunkong.Desktop\Xunkong.Desktop.dll"

[23:53:24.472] [EROR] Xunkong.Desktop.Pages.WishlogSummaryPage2+<>c__DisplayClass26_0+<<_proxyService_GotWishlogUrl>b__0>d._proxyService_GotWishlogUrl
--->
System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard 失败 (0x800401D0 (CLIPBRD_E_CANT_OPEN))
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.DataTransfer.IClipboardStaticsMethods.Flush(IObjectReference _obj)
   at Xunkong.Desktop.Pages.WishlogSummaryPage2.<>c__DisplayClass26_0.<<_proxyService_GotWishlogUrl>b__0>d.MoveNext() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\WishlogSummaryPage2.xaml.cs:line 394

至于原神的………………嘛，咱更找不到在哪里了。。。
```

**Comment by phucho0237** [comment]
I used to get this error with Honkai: Star Rail.

**Comment by Scighost** [comment]
你需要这样做

<img width="176" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/f1fcfe80-4707-4c65-abf3-bb0ad6644cff">

**Comment by hlx31** [comment]
> 你需要这样做
> 
> <img alt="image" width="176" src="https://user-images.githubusercontent.com/61003590/260877669-f1fcfe80-4707-4c65-abf3-bb0ad6644cff.png">

好的，谢谢。

我发现今天原神本体版本更新以后，好像又可以直接进行获取了。
很迷，不会是本体那边清空了一次缓存文件吧。或者是其他的……

**Comment by Pizazz-stack** [comment]
有可能是因为config.ini不与游戏本体处于同一文件夹，我就是这种。此原因上述办法都是不行的（亲身实践）如果是用官方启动器下载的，就没有这种问题。直接下本体，没有启动器的就要将这个放置与本体同一文件夹（不过没有这个也用不了所有启动器，我是自定义程序）
[1.zip](https://github.com/Scighost/Starward/files/13928191/1.zip)
