### ISSUE TITLE
[Bug] 崩坏3公告和更新界面消失

### ISSUE THREAD

**Issue by fbzr2007** [Scighost/Starward#278]
### Description

现在是早上2023/8/17 9:36（UTC+8）
启动器现在公告和更新界面都消失了（前两天还预下载完成来着....今天只能重新更新了）
稍微看了一下log似乎是返回不了查询的信息？麻烦看下下方的log
【官方启动器更新正常 - 截图4】

### Reproduction Steps

目前在我现有的两台台式设备上都出现了这个情况，具体也不需要怎么复现，打开就这样了
截图2是在我删除设置后打开显示的
有尝试过修复数据，但有错误提示 - 截图3

### Screenshots

![image](https://github.com/Scighost/Starward/assets/116995140/7a967643-cef4-4513-9166-cdec17bb8863)
![image](https://github.com/Scighost/Starward/assets/116995140/76dcafdc-9403-4948-a228-9106bbfb7643)
![image](https://github.com/Scighost/Starward/assets/116995140/055262fb-e18a-427e-9e88-c3b7a7cc0afa)
![image](https://github.com/Scighost/Starward/assets/116995140/c000e2fa-f44c-408a-ae5e-7db6bbe24260)

### Starward Version

0.9.0

### Windows Version

19045.3208; 19045.3324

### Log

```shell
[09:42:35.464] [INFO] 
Welcome to Starward v0.9.0
System: Microsoft Windows NT 10.0.19045.0
Command Line: E:\DL_by_bdyun\tools\Starward\app-0.9.0\Starward.dll repair --biz bh3_cn --loc "C:\Program Files\MHY\Honkai Impact 3\Games" --lang 0

[09:42:35.518] [INFO] Starward.Services.DatabaseService
Database path is 'E:\DL_by_bdyun\tools\Starward'

[09:42:35.579] [INFO] Starward.Services.DatabaseService
Database version is 6, target version is {DatabaseSqls.Count}.

[09:42:36.125] [EROR] Starward.Services.DownloadGameService
Prepare for repair
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Starward.Core.Launcher.LauncherClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\Starward.Core\Launcher\LauncherClient.cs:line 27
   at Starward.Core.Launcher.LauncherClient.GetLauncherResourceAsync(GameBiz biz, CancellationToken cancellationToken) in D:\a\Starward\Starward\Starward.Core\Launcher\LauncherClient.cs:line 98
   at Starward.Services.DownloadGameService.GetLauncherResourceAsync(GameBiz biz) in D:\a\Starward\Starward\Starward\Services\DownloadGameService.cs:line 93
   at Starward.Services.DownloadGameService.PrepareForRepairAsync(GameBiz biz, String installPath, VoiceLanguage language) in D:\a\Starward\Starward\Starward\Services\DownloadGameService.cs:line 615

[09:42:36.193] [EROR] Starward.Pages.DownloadGamePage
Show error message
System.NullReferenceException: Object reference not set to an instance of an object.
   at Starward.Pages.DownloadGamePage.StopProgressAnimation() in D:\a\Starward\Starward\Starward\Pages\DownloadGamePage.xaml.cs:line 328
   at Starward.Pages.DownloadGamePage.ShowErrorMessage() in D:\a\Starward\Starward\Starward\Pages\DownloadGamePage.xaml.cs:line 579

[09:42:40.022] [EROR] Starward.Services.DownloadGameService
Prepare for repair
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Starward.Core.Launcher.LauncherClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\Starward.Core\Launcher\LauncherClient.cs:line 27
   at Starward.Core.Launcher.LauncherClient.GetLauncherResourceAsync(GameBiz biz, CancellationToken cancellationToken) in D:\a\Starward\Starward\Starward.Core\Launcher\LauncherClient.cs:line 98
   at Starward.Services.DownloadGameService.GetLauncherResourceAsync(GameBiz biz) in D:\a\Starward\Starward\Starward\Services\DownloadGameService.cs:line 93
   at Starward.Services.DownloadGameService.PrepareForRepairAsync(GameBiz biz, String installPath, VoiceLanguage language) in D:\a\Starward\Starward\Starward\Services\DownloadGameService.cs:line 615
```

**Comment by Scighost** [comment]
谢谢你的反馈，崩坏3国服在今天更新了相关api接口，游戏更新和游戏资讯都受到了影响，此问题将在下个版本中修复，请耐心等待。

**Comment by safesaffawa** [comment]
我也遇到了这个问题 我觉得可以先挂起来

**Comment by Xzhao233** [comment]
我还以为是我的问题呢（
