### ISSUE TITLE
[Bug] 星穹鐵道多帳號躍遷更新紀錄結果顯示異常

### ISSUE THREAD

**Issue by tony8077616** [Scighost/Starward#287]
### Description

我有兩個國際服的帳號，一個是透過米哈遊帳號註冊登入(80開頭)，另一個是透過 Google 帳號登入(82開頭)。
躍遷紀錄分別為 49 次(80開頭)和 38 次紀錄(82開頭)。
![image](https://github.com/Scighost/Starward/assets/9822340/806e46ef-b8d5-41cc-ab06-1466e5018695)

### Reproduction Steps

一開始我先登入的米哈遊帳號，並且有了一次以上的更新紀錄，之後我新增了我另一個 Google 帳號的紀錄。
當我在 82 開頭的躍遷紀錄時，點選 **更新紀錄** ，提示 UID 82 的帳號取得了 60 次紀錄
![Starward_2023-08-20_14-31-32-392](https://github.com/Scighost/Starward/assets/9822340/366b6310-96a3-41c2-8bd1-a8157887a713)

當我在 82 開頭的躍遷紀錄時，點選 **更新紀錄(全部)** ，提示 UID 82 的帳號取得了 76 次紀錄
![Starward_2023-08-20_14-35-19-140](https://github.com/Scighost/Starward/assets/9822340/2c4c3316-fab2-4f08-a80d-16872b7f4d72)

當我在 80 開頭的躍遷紀錄時，點選 **更新紀錄** ，畫面被切回到 82 開頭的躍遷紀錄並提示 UID 82 的帳號取得了 60 次紀錄
![Starward_2023-08-20_14-36-19-617](https://github.com/Scighost/Starward/assets/9822340/c1fd7ede-4074-4c77-82c6-16efdda2779e)

當我在 82 開頭的躍遷紀錄時，點選 **更新紀錄(全部)** ，畫面被切回到 82 開頭的躍遷紀錄並提示 UID 82 的帳號取得了 76 次紀錄
![Starward_2023-08-20_14-38-10-918](https://github.com/Scighost/Starward/assets/9822340/3b3a296e-7a97-4514-b54c-268bc7918815)

### Expected Behavior

在 82 按 更新紀錄 只會更新 82
在 82 按 更新紀錄(全部) 要更新 80 和 82 的紀錄，並且正確提示個別的紀錄和新增的紀錄
在 80 按 更新紀錄 只會更新 80，畫面不會跳轉回 82
在 80 按 更新紀錄(全部) 要更新 80 和 82 的紀錄，並且正確提示個別的紀錄和新增的紀錄，畫面不會跳轉回 82

### Starward Version

0.9.0

### Windows Version

10.0.25931.1000

### Log

```shell
[12:23:02.030] [INFO] 
Welcome to Starward v0.9.0
System: Microsoft Windows NT 10.0.25931.0
Command Line: E:\Game\Starward\app-0.9.0\Starward.dll

[12:23:02.086] [INFO] Starward.Services.DatabaseService
Database path is 'E:\Game\Starward'

[12:23:02.116] [INFO] Starward.Services.DatabaseService
Database version is 6, target version is {DatabaseSqls.Count}.

[12:23:02.165] [INFO] Starward.Pages.MainPage
Select game region is hk4e_global

[12:23:02.165] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_global

[12:23:02.718] [INFO] Starward.Pages.LauncherPage
Game install path hk4e_global: "E:\Game\Genshin Impact\Genshin Impact game"

[12:23:03.310] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[12:23:03.564] [INFO] Starward.Services.UpdateService
Current version: "0.9.0", latest version: "0.9.0", ignore version: null

[12:23:05.035] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_global

[12:23:05.041] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_global

[12:23:05.122] [INFO] Starward.Pages.LauncherPage
Game install path hkrpg_global: "E:\Game\Star Rail\Games"

[12:23:06.687] [INFO] Starward.Services.GameService
Start game (hkrpg_global)
path: "E:\Game\Star Rail\Games\StarRail.exe"
arg: ""

[12:23:06.869] [INFO] Starward.Pages.LauncherPage
Game started ("StarRail", 23160)

[12:23:08.889] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hkrpg_global, 23160)

[12:23:19.656] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hkrpg_global

[12:23:19.671] [INFO] Starward.Services.GameRecordService
Change region to Global.

[12:26:08.383] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hkrpg_global

[12:26:10.680] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 802447348 is 1691583000003564248

[12:28:41.745] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 802447348 is 1692454200000042648

[12:32:13.216] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 802447348 is 1692454200000042648

[12:35:15.684] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_global

[12:35:15.685] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hkrpg_global

[12:35:17.670] [INFO] Starward.Pages.MainPage
Navigate to "GameSettingPage" with param hkrpg_global

[12:35:19.588] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_global

[12:35:19.673] [INFO] Starward.Pages.LauncherPage
Game install path hkrpg_global: "E:\Game\Star Rail\Games"

[12:35:19.681] [INFO] Starward.Pages.LauncherPage
Game is running ("StarRail", 23160)

[12:35:21.881] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hkrpg_global

[12:35:21.887] [INFO] Starward.Services.GameRecordService
Change region to Global.

[12:38:10.095] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hkrpg_global

[12:38:13.243] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 0

[12:39:25.334] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692371400000003293

[12:39:35.119] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692371400000003293

[12:41:32.034] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692371400000003293

[12:46:15.158] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692371400000003293

[12:56:48.651] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692371400000003293

[13:00:29.501] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692371400000003293

[13:05:55.510] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692371400000003293

[13:09:09.029] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692371400000003293

[13:15:28.823] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692371400000003293

[13:15:32.727] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692371400000003293

[13:15:38.309] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692371400000003293

[13:16:04.720] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692371400000003293

[13:20:12.558] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692371400000003293

[13:21:42.556] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692504600000252993

[13:24:17.803] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692504600000252993

[13:24:37.240] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692504600000252993

[13:25:02.593] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hkrpg_global

[13:25:02.604] [INFO] Starward.Services.GameRecordService
Change region to Global.

[13:26:49.869] [INFO] Starward.Pages.MainPage
Change game region to hk4e_global

[13:26:49.871] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hk4e_global

[13:26:49.878] [INFO] Starward.Services.GameRecordService
Change region to Global.

[13:26:50.767] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_global

[13:26:50.768] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hkrpg_global

[13:26:50.774] [INFO] Starward.Services.GameRecordService
Change region to Global.

[13:30:57.051] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_global

[13:30:57.141] [INFO] Starward.Pages.LauncherPage
Game install path hkrpg_global: "E:\Game\Star Rail\Games"

[13:30:57.147] [INFO] Starward.Pages.LauncherPage
Game is running ("StarRail", 23160)

[13:31:00.111] [INFO] Starward.Pages.MainPage
Navigate to "GameSettingPage" with param hkrpg_global

[13:31:01.599] [INFO] Starward.Pages.MainPage
Navigate to "ScreenshotPage" with param hkrpg_global

[13:31:01.672] [WARN] Starward.Pages.ScreenshotPage
Cannot find screenshot folder

[13:31:02.973] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hkrpg_global

[13:31:08.378] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692504600000252993

[13:31:13.132] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692504600000252993

[13:31:17.839] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692504600000252993

[13:32:09.822] [EROR] Starward.Pages.GachaLogPage
Export gacha log
System.Collections.Generic.KeyNotFoundException: The given key 'IdText' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey)
   at MiniExcelLibs.OpenXml.ExcelOpenXmlTemplate.UpdateDimensionAndGetRowsInfo(Dictionary`2 inputMaps, XmlDocument& doc, XmlNodeList& rows, Boolean changeRowIndex)
   at MiniExcelLibs.OpenXml.ExcelOpenXmlTemplate.GenerateSheetXmlImpl(ZipArchiveEntry sheetZipEntry, Stream stream, Stream sheetStream, Dictionary`2 inputMaps, IDictionary`2 sharedStrings, Boolean mergeCells)
   at MiniExcelLibs.OpenXml.ExcelOpenXmlTemplate.SaveAsByTemplateImpl(Stream templateStream, Object value)
   at MiniExcelLibs.OpenXml.ExcelOpenXmlTemplate.SaveAsByTemplate(String templatePath, Object value)
   at MiniExcelLibs.MiniExcel.SaveAsByTemplate(String path, String templatePath, Object value, IConfiguration configuration)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
--- End of stack trace from previous location ---
   at MiniExcelLibs.MiniExcel.SaveAsByTemplateAsync(String path, String templatePath, Object value, IConfiguration configuration, CancellationToken cancellationToken)
   at Starward.Services.Gacha.StarRailGachaService.ExportAsExcelAsync(Int64 uid, String output) in D:\a\Starward\Starward\Starward\Services\Gacha\StarRailGachaService.cs:line 120
   at Starward.Services.Gacha.StarRailGachaService.ExportGachaLogAsync(Int64 uid, String file, String format) in D:\a\Starward\Starward\Starward\Services\Gacha\StarRailGachaService.cs:line 93
   at Starward.Pages.GachaLogPage.ExportGachaLogAsync(String format) in D:\a\Starward\Starward\Starward\Pages\GachaLogPage.xaml.cs:line 527

[13:32:58.224] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692504600000252993

[13:33:07.333] [INFO] Starward.Pages.MainPage
Navigate to "SettingPage" with param hkrpg_global

[13:37:15.178] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_global

[13:37:15.270] [INFO] Starward.Pages.LauncherPage
Game install path hkrpg_global: "E:\Game\Star Rail\Games"

[13:37:15.278] [INFO] Starward.Pages.LauncherPage
Game is running ("StarRail", 23160)

[13:37:18.423] [INFO] Starward.Pages.MainPage
Navigate to "GameSettingPage" with param hkrpg_global

[13:37:25.259] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hkrpg_global

[13:39:12.145] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692504600000252993

[13:39:32.088] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692504600000252993

[13:39:56.215] [INFO] Starward.Pages.MainPage
Navigate to "SettingPage" with param hkrpg_global

[13:39:59.153] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_global

[13:39:59.239] [INFO] Starward.Pages.LauncherPage
Game install path hkrpg_global: "E:\Game\Star Rail\Games"

[13:39:59.244] [INFO] Starward.Pages.LauncherPage
Game is running ("StarRail", 23160)

[13:41:50.338] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hkrpg_global

[13:45:18.471] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692504600000252993

[13:45:23.426] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692504600000252993

[13:45:28.364] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692504600000252993

[13:46:12.971] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692504600000252993

[13:47:26.537] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692504600000252993

[13:50:35.229] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692504600000252993

[13:53:15.119] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692504600000252993

[13:56:14.792] [INFO] Starward.Pages.MainPage
Navigate to "SettingPage" with param hkrpg_global

[13:57:23.592] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hkrpg_global

[13:57:36.377] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692504600000252993

[13:58:17.709] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692504600000252993

[14:25:36.910] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692504600000252993

[14:29:41.913] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692508200000089493

[14:31:28.677] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692508200000089493

[14:33:32.480] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692508200000089493

[14:34:01.466] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692508200000089493

[14:34:11.126] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692508200000089493

[14:36:15.820] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692508200000089493

[14:39:29.020] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 823952893 is 1692508200000089493

[14:41:20.717] [INFO] Starward.Pages.MainPage
Navigate to "SettingPage" with param hkrpg_global
```

**Comment by Scighost** [comment]
游戏内最后一次登录的哪个账号，更新记录时获取的就是哪个账号的抽卡记录。如果你要指定某一个账号，请使用**更新记录（缓存的 URL）**。

**Comment by tony8077616** [comment]
> 游戏内最后一次登录的哪个账号，更新记录时获取的就是哪个账号的抽卡记录。如果你要指定某一个账号，请使用**更新记录（缓存的 URL）**。

瞭解，感謝答覆
這筆我就先Close了
