### ISSUE TITLE
[Bug] 启动器无法查看星铁忘却之庭

### ISSUE THREAD

**Issue by lingfengyu-dreaming** [Scighost/Starward#294]
### Description

在连续多天在星穹铁道米游社工具箱中的忘却之庭界面弹出账号异常弹窗后，出现无法在忘却之庭查询界面登录账号的问题。  
同时在工具箱中其他页面也偶尔出现需要重登账号情况。  
疑似使用启动器登录账号查询米游社工具箱导致仅在启动器处被风控。其他平台登录账号无问题。

### Reproduction Steps

1. 在忘却之庭登录查询记录。
2. 观察到多天出现账号异常提示，需要手动进入浏览器模式过验证码。
3. 出现截图中所示情况，无法在忘却之庭界面中查看登录账号。

### Expected Behavior

和之前一样正常读取信息并更新记录。

### Screenshots

![image](https://github.com/Scighost/Starward/assets/61617417/7f35038d-4809-4b25-9157-066c317a29a3)
![image](https://github.com/Scighost/Starward/assets/61617417/84b6632f-c35b-4770-b8a0-82c2b8b0946d)

### Starward Version

0.9.0

### Windows Version

22631.2199

### Log

```shell
发现文件不能拖进来，以下是当时的错误log:  
[17:36:37.853] [EROR] Starward.Pages.HoyolabToolbox.ForgottenHallPage
Refresh forgotten hall data ("hkrpg_cn", 113254641).
Starward.Core.miHoYoApiException:  (1034)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\Starward.Core\GameRecord\GameRecordClient.cs:line 162
   at Starward.Core.GameRecord.HyperionClient.GetForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\Starward.Core\GameRecord\HyperionClient.cs:line 268
   at Starward.Services.GameRecordService.RefreshForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\Starward\Services\GameRecordService.cs:line 447
   at Starward.Pages.HoyolabToolbox.ForgottenHallPage.RefreshDataAsync() in D:\a\Starward\Starward\Starward\Pages\HoyolabToolbox\ForgottenHallPage.xaml.cs:line 110

[17:37:22.236] [EROR] Starward.Pages.HoyolabToolbox.ForgottenHallPage
Refresh forgotten hall data ("hkrpg_cn", 113254641).
Starward.Core.miHoYoApiException:  (1034)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\Starward.Core\GameRecord\GameRecordClient.cs:line 162
   at Starward.Core.GameRecord.HyperionClient.GetForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\Starward.Core\GameRecord\HyperionClient.cs:line 268
   at Starward.Services.GameRecordService.RefreshForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\Starward\Services\GameRecordService.cs:line 447
   at Starward.Pages.HoyolabToolbox.ForgottenHallPage.RefreshDataAsync() in D:\a\Starward\Starward\Starward\Pages\HoyolabToolbox\ForgottenHallPage.xaml.cs:line 110

[17:37:48.395] [EROR] Starward.Pages.HoyolabToolbox.ForgottenHallPage
Refresh forgotten hall data ("hkrpg_cn", 113254641).
Starward.Core.miHoYoApiException:  (1034)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\Starward.Core\GameRecord\GameRecordClient.cs:line 162
   at Starward.Core.GameRecord.HyperionClient.GetForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\Starward.Core\GameRecord\HyperionClient.cs:line 268
   at Starward.Services.GameRecordService.RefreshForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\Starward\Services\GameRecordService.cs:line 447
   at Starward.Pages.HoyolabToolbox.ForgottenHallPage.RefreshDataAsync() in D:\a\Starward\Starward\Starward\Pages\HoyolabToolbox\ForgottenHallPage.xaml.cs:line 110

[17:41:07.078] [EROR] Starward.Pages.HoyolabToolbox.ForgottenHallPage
Refresh forgotten hall data ("hkrpg_cn", 113254641).
Starward.Core.miHoYoApiException:  (1034)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\Starward.Core\GameRecord\GameRecordClient.cs:line 162
   at Starward.Core.GameRecord.HyperionClient.GetForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\Starward.Core\GameRecord\HyperionClient.cs:line 268
   at Starward.Services.GameRecordService.RefreshForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\Starward\Services\GameRecordService.cs:line 447
   at Starward.Pages.HoyolabToolbox.ForgottenHallPage.RefreshDataAsync() in D:\a\Starward\Starward\Starward\Pages\HoyolabToolbox\ForgottenHallPage.xaml.cs:line 110
```

**Comment by Scighost** [comment]
目前工具箱使用的不是米哈游通行证相关的 `stoken`，风控的问题无法避免，我也不知道怎么解决。
