### ISSUE TITLE
[Bug] 托盘图标创建失败

### ISSUE THREAD

**Issue by mlrsyz** [Scighost/Starward#297]
### Description

[22:45:08.204] [INFO] 
Welcome to Starward v0.9.1-preview.1
System: Microsoft Windows NT 10.0.19045.0
Command Line: C:\Game\Starward\app-0.9.1-preview.1\Starward.dll

[22:45:08.246] [INFO] Starward.Services.DatabaseService
Database path is 'C:\Game\Starward'

[22:45:08.264] [INFO] Starward.Services.DatabaseService
Database version is 6, target version is {DatabaseSqls.Count}.

[22:45:08.310] [INFO] Starward.Pages.MainPage
Select game region is hkrpg_cn

[22:45:08.310] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_cn

[22:45:08.502] [EROR] Starward.Services.SystemTrayService
Initialize system tray
System.InvalidOperationException: TryCreate failed.
   at H.NotifyIcon.Core.TrayIcon.Create() in /_/src/libs/H.NotifyIcon/Core/TrayIcon.cs:line 324
   at H.NotifyIcon.TaskbarIcon.ForceCreate(Boolean ) in /_/src/libs/H.NotifyIcon.Shared/TaskbarIcon.cs:line 134
   at Starward.Services.SystemTrayService.Initialize(GameBiz gameBiz) in D:\a\Starward\Starward\src\Starward\Services\SystemTrayService.cs:line 72

[22:45:08.664] [INFO] Starward.Pages.LauncherPage
Game install path hkrpg_cn: "C:\Game\Star Rail\Game"

[22:45:08.890] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[22:45:09.894] [INFO] Starward.Services.UpdateService
Current version: "0.9.1-preview.1", latest version: "0.9.1-preview.1", ignore version: null

### Reproduction Steps

开启托盘图标100%复现

版本	Windows 10 专业工作站版
版本号	22H2
安装日期	‎2022/‎3/‎13
操作系统内部版本	19045.3324
体验	Windows Feature Experience Pack 1000.19041.1000.0

### Starward Version

0.9.1-preview.1

### Windows Version

19045.3324

**Comment by Scighost** [comment]
同 #251
