### ISSUE TITLE
[Bug] 星穹铁道背景图片、公告无法加载 / Cannot load background image and notice page of Honkai: Starrail

### ISSUE THREAD

**Issue by Fachep** [Scighost/Starward#305]
### Description

启动时若在星穹铁道则可正常加载背景，切换至其他游戏或启动时是其他游戏再切回没有正确加载背景。公告无法加载

### Reproduction Steps

-

### Screenshots

![image](https://github.com/Scighost/Starward/assets/31302548/141c62b3-1a2b-41e8-9d83-298ffbdddb7c)
![image](https://github.com/Scighost/Starward/assets/31302548/bb3a8eac-39ba-4c88-a04f-8d6a717793c5)

### Starward Version

0.9.1-preview.2

### Windows Version

22621.2215

### Log

```shell
[13:01:09.812] [INFO] 
Welcome to Starward v0.9.1-preview.2
System: Microsoft Windows NT 10.0.22621.0
Command Line: "C:\Program Files\Starward\app-0.9.1-preview.2\Starward.dll"

[13:01:09.873] [INFO] Starward.Services.DatabaseService
Database path is 'C:\Program Files\Starward\data'

[13:01:09.902] [INFO] Starward.Services.DatabaseService
Database version is 6, target version is {DatabaseSqls.Count}.

[13:01:09.971] [INFO] Starward.Pages.MainPage
Select game region is hkrpg_cn

[13:01:09.979] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_cn

[13:01:10.584] [INFO] Starward.Pages.LauncherPage
Game install path hkrpg_cn: "H:\Star Rail Game"

[13:01:10.656] [WARN] Starward.Services.GameService
Game uninstalled (hk4e_global)

[13:01:10.656] [WARN] Starward.Services.GameService
Game uninstalled (hk4e_cloud)

[13:01:10.657] [WARN] Starward.Services.GameService
Game uninstalled (hkrpg_global)

[13:01:10.657] [WARN] Starward.Services.GameService
Game uninstalled (bh3_cn)

[13:01:10.657] [WARN] Starward.Services.GameService
Game uninstalled (bh3_global)

[13:01:10.657] [WARN] Starward.Services.GameService
Game uninstalled (bh3_jp)

[13:01:10.658] [WARN] Starward.Services.GameService
Game uninstalled (bh3_kr)

[13:01:10.658] [WARN] Starward.Services.GameService
Game uninstalled (bh3_overseas)

[13:01:10.658] [WARN] Starward.Services.GameService
Game uninstalled (bh3_tw)

[13:01:10.797] [EROR] Starward.Pages.MainPage
Update background image
System.NullReferenceException: Object reference not set to an instance of an object.
   at Starward.Services.LauncherService.GetBackgroundImageAsync(GameBiz gameBiz, Boolean disableCustom) in D:\a\Starward\Starward\src\Starward\Services\LauncherService.cs:line 124
   at Starward.Pages.MainPage.UpdateBackgroundImageAsync(Boolean force) in D:\a\Starward\Starward\src\Starward\Pages\MainPage.xaml.cs:line 583

[13:01:10.800] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[13:01:11.186] [INFO] Starward.Services.UpdateService
Current version: "0.9.1-preview.2", latest version: "0.9.1-preview.2", ignore version: null

[13:01:11.754] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[13:01:11.760] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[13:01:11.849] [INFO] Starward.Pages.LauncherPage
Game install path hk4e_cn: "E:\Genshin Impact Game"

[13:01:12.523] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[13:01:12.526] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_cn

[13:01:12.541] [EROR] Starward.Pages.MainPage
Update background image
System.NullReferenceException: Object reference not set to an instance of an object.
   at Starward.Services.LauncherService.GetBackgroundImageAsync(GameBiz gameBiz, Boolean disableCustom) in D:\a\Starward\Starward\src\Starward\Services\LauncherService.cs:line 124
   at Starward.Pages.MainPage.UpdateBackgroundImageAsync(Boolean force) in D:\a\Starward\Starward\src\Starward\Pages\MainPage.xaml.cs:line 583

[13:01:12.622] [INFO] Starward.Pages.LauncherPage
Game install path hkrpg_cn: "H:\Star Rail Game"

[13:01:14.717] [INFO] Starward.Pages.MainPage
Navigate to "GameNoticesPage" with param hkrpg_cn

[13:01:14.750] [EROR] Starward.Pages.GameNoticesPage
Initialize bg
System.NullReferenceException: Object reference not set to an instance of an object.
   at Starward.Services.LauncherService.GetBackgroundImageAsync(GameBiz gameBiz, Boolean disableCustom) in D:\a\Starward\Starward\src\Starward\Services\LauncherService.cs:line 124
   at Starward.Pages.GameNoticesPage.InitializeBgAsync() in D:\a\Starward\Starward\src\Starward\Pages\GameNoticesPage.xaml.cs:line 74

[13:01:15.496] [EROR] Starward.Pages.GameNoticesPage
Insert bg
System.NullReferenceException: Object reference not set to an instance of an object.
   at Starward.Pages.GameNoticesPage.InsertBgAsync() in D:\a\Starward\Starward\src\Starward\Pages\GameNoticesPage.xaml.cs:line 148
```

**Comment by Scighost** [comment]
原因是这个 api 中背景图片数据 `adv` 突然变成了 null，我没有考虑到这个情况（确实也不应该发生这种问题）。

```
https://api-launcher-static.mihoyo.com/hkrpg_cn/mdk/launcher/api/content?filter_adv=false&key=6KcVuOkbcqjJomjZ&language=zh-cn&launcher_id=33
```

**Comment by Scighost** [comment]
已在 0.9.1-preview.3 中修复
