### ISSUE TITLE
[Bug] 0.9.1更新后系统托盘图标设置无效

### ISSUE THREAD

**Issue by diazynez** [Scighost/Starward#335]
### Description

0.9.1更新后系统托盘图标设置无效

### Reproduction Steps

0.9.1更新后系统托盘图标设置无效

### Starward Version

0.9.1

### Windows Version

19045.3271

**Comment by Scighost** [comment]
请提供日志

**Comment by diazynez** [comment]
[20:56:24.296] [INFO] 
Welcome to Starward v0.9.1
System: Microsoft Windows NT 10.0.19045.0
Command Line: E:\miHoYo\Starward\app-0.9.1\Starward.dll

[20:56:24.335] [INFO] Starward.Services.DatabaseService
Database path is 'E:\miHoYo\Starward'

[20:56:24.354] [INFO] Starward.Services.DatabaseService
Database version is 6, target version is {DatabaseSqls.Count}.

[20:56:24.397] [INFO] Starward.Pages.MainPage
Select game region is hk4e_cn

[20:56:24.401] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[20:56:24.682] [EROR] Starward.Services.SystemTrayService
Initialize system tray
System.InvalidOperationException: TryCreate failed.
   at H.NotifyIcon.Core.TrayIcon.Create() in /_/src/libs/H.NotifyIcon/Core/TrayIcon.cs:line 324
   at H.NotifyIcon.TaskbarIcon.ForceCreate(Boolean ) in /_/src/libs/H.NotifyIcon.Shared/TaskbarIcon.cs:line 134
   at Starward.Services.SystemTrayService.Initialize(GameBiz gameBiz) in D:\a\Starward\Starward\src\Starward\Services\SystemTrayService.cs:line 72

[20:56:24.814] [INFO] Starward.Pages.LauncherPage
Game install path hk4e_cn: "E:\miHoYo\Genshin Impact\Genshin Impact Game"

[20:56:26.022] [INFO] Starward.Services.UpdateService
Start to check update (Preview: False, Arch: X64)

[20:56:26.461] [INFO] Starward.Pages.MainPage
Navigate to "SettingPage" with param hk4e_cn

[20:56:26.873] [INFO] Starward.Services.UpdateService
Current version: "0.9.1", latest version: "0.9.1", ignore version: null

[20:56:29.487] [EROR] Starward.Services.SystemTrayService
Initialize system tray
System.InvalidOperationException: TryCreate failed.
   at H.NotifyIcon.Core.TrayIcon.Create() in /_/src/libs/H.NotifyIcon/Core/TrayIcon.cs:line 324
   at H.NotifyIcon.TaskbarIcon.ForceCreate(Boolean ) in /_/src/libs/H.NotifyIcon.Shared/TaskbarIcon.cs:line 134
   at Starward.Services.SystemTrayService.Initialize(GameBiz gameBiz) in D:\a\Starward\Starward\src\Starward\Services\SystemTrayService.cs:line 72

[20:56:32.288] [EROR] Starward.Services.SystemTrayService
Initialize system tray
System.InvalidOperationException: TryCreate failed.
   at H.NotifyIcon.Core.TrayIcon.Create() in /_/src/libs/H.NotifyIcon/Core/TrayIcon.cs:line 324
   at H.NotifyIcon.TaskbarIcon.ForceCreate(Boolean ) in /_/src/libs/H.NotifyIcon.Shared/TaskbarIcon.cs:line 134
   at Starward.Services.SystemTrayService.Initialize(GameBiz gameBiz) in D:\a\Starward\Starward\src\Starward\Services\SystemTrayService.cs:line 72

**Comment by Scighost** [comment]
同 #251，因为第三方库的内部错误，我无法确定具体原因。

**Comment by YIMUYONG** [comment]
也是遇到了同样的问题，更新之后，系统托盘失效了。

[11:19:46.560] [INFO] 
Welcome to Starward v0.9.1
System: Microsoft Windows NT 10.0.19045.0
Command Line: D:\ProgramData\MiHoYo\Starward\app-0.9.1\Starward.dll

[11:19:46.638] [INFO] Starward.Services.DatabaseService
Database path is 'D:\ProgramData\MiHoYo\Starward'

[11:19:46.669] [INFO] Starward.Services.DatabaseService
Database version is 6, target version is {DatabaseSqls.Count}.

[11:19:46.742] [INFO] Starward.Pages.MainPage
Select game region is hkrpg_cn

[11:19:46.749] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_cn

[11:19:47.028] [EROR] Starward.Services.SystemTrayService
Initialize system tray
System.InvalidOperationException: TryCreate failed.
   at H.NotifyIcon.Core.TrayIcon.Create() in /_/src/libs/H.NotifyIcon/Core/TrayIcon.cs:line 324
   at H.NotifyIcon.TaskbarIcon.ForceCreate(Boolean ) in /_/src/libs/H.NotifyIcon.Shared/TaskbarIcon.cs:line 134
   at Starward.Services.SystemTrayService.Initialize(GameBiz gameBiz) in D:\a\Starward\Starward\src\Starward\Services\SystemTrayService.cs:line 72

[11:19:47.076] [INFO] Starward.Pages.LauncherPage
Game install path hkrpg_cn: "D:\ProgramData\MiHoYo\CHN\Star Rail\Game"

[11:19:47.480] [INFO] Starward.Services.UpdateService
Start to check update (Preview: False, Arch: X64)

[11:19:48.450] [INFO] Starward.Services.UpdateService
Current version: "0.9.1", latest version: "0.9.1", ignore version: null

[11:19:51.786] [INFO] Starward.Pages.MainPage
Navigate to "SettingPage" with param hkrpg_cn

**Comment by diazynez** [comment]
在出错的库https://github.com/HavenDV/H.NotifyIcon/issues/103那里也反馈了一下，不过好像目前没法解决

**Comment by diazynez** [comment]
在出错的库
https://github.com/HavenDV/H.NotifyIcon/issues/103
那里也反馈了一下，不过好像目前没法解决

**Comment by diazynez** [comment]
使用[mlrsyz](https://github.com/mlrsyz)提供的方法成功解决问题，有同类问题的可以试试:D
https://github.com/HavenDV/H.NotifyIcon/issues/103#issuecomment-1705989614
