### ISSUE TITLE
[Bug] 打开游戏公告后，程序上的控件全部消失

### ISSUE THREAD

**Issue by diazynez** [Scighost/Starward#338]
### Description

打开游戏公告后，程序上的控件全部消失，仅剩背景图，在侧栏切换至其他页面后切回主页后可以恢复

### Reproduction Steps

在启动器主页点击游戏公告的小按钮（图标是有红点的小喇叭？）或在侧栏选择游戏公告均会发生

### Starward Version

0.9.1

### Windows Version

19045.3271

### Log

```shell
14:55:33.178
fail: Starward.Pages.GameNoticesPage[0]
      Ensure core webview2
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Starward.Pages.GameNoticesPage.InitializeWebAsync() in D:\a\Starward\Starward\src\Starward\Pages\GameNoticesPage.xaml.cs:line 108
14:55:33.179
fail: Starward.Pages.GameNoticesPage[0]
      Initialize game notices
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Starward.Pages.GameNoticesPage.InitializeWebAsync() in D:\a\Starward\Starward\src\Starward\Pages\GameNoticesPage.xaml.cs:line 114
```

**Comment by Scighost** [comment]
请安装 WebView2

**Comment by diazynez** [comment]
已安装WebView2，未解决问题

**Comment by diazynez** [comment]
但自查发现将以前在组策略禁用的“管理员批准模式”重新打开后可正常运行了……有点怪:(

**Comment by Scighost** [comment]
虽然不知道为什么，但是解决了就好
