### ISSUE TITLE
[Bug] 忘却之庭记录刷新时校验账号报错

### ISSUE THREAD

**Issue by diazynez** [Scighost/Starward#360]
### Description

忘却之庭记录刷新时校验账号报错，弹出的米游社网页显示正常，但无法点击登录

### Reproduction Steps

米游社工具箱→忘却之庭→刷新→校验账号

### Expected Behavior

仅星穹铁道的忘却之庭存在刷新错误，模拟宇宙，深境螺旋，月历均不存在问题

### Screenshots

<img width="954" alt="Snipaste_2023-09-10_23-13-03" src="https://github.com/Scighost/Starward/assets/21095959/d8d551b2-9522-4ee9-81ba-d2433a685dc0">

### Starward Version

0.9.1

### Windows Version

19045.3271

### Log

```shell
23:13:56.054
fail: Starward.Pages.HoyolabToolbox.ForgottenHallPage[0]
      Refresh forgotten hall data (hkrpg_cn, 102765815).
      Starward.Core.miHoYoApiException:  (1034)
         at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\Starward.Core\GameRecord\GameRecordClient.cs:line 162
         at Starward.Core.GameRecord.HyperionClient.GetForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\Starward.Core\GameRecord\HyperionClient.cs:line 268
         at Starward.Services.GameRecordService.RefreshForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\Starward\Services\GameRecordService.cs:line 447
         at Starward.Pages.HoyolabToolbox.ForgottenHallPage.RefreshDataAsync() in D:\a\Starward\Starward\Starward\Pages\HoyolabToolbox\ForgottenHallPage.xaml.cs:line 110
```

**Comment by diazynez** [comment]
<img width="954" alt="Snipaste_2023-09-10_23-20-20" src="https://github.com/Scighost/Starward/assets/21095959/37073481-8558-48bb-8f1e-91c6e8a37724">

**Comment by Eric-Joker** [comment]
网络问题或者你需要在左上角重新登录下（

**Comment by Scighost** [comment]
抱歉，我无法解答关于米游社账号相关的问题。

**Comment by diazynez** [comment]
找到解决方法了（大概）
各种网页打不开的原因是Edge和MacType存在冲突，所以WebView2也一起出问题了，把msedge.exe和msedgewebview2.exe加到MacType的排除列表里面就解决了
