### ISSUE TITLE
[Bug] 星穹铁道跃迁记录无法更新导入和删除

### ISSUE THREAD

**Issue by cheng1nuo** [Scighost/Starward#366]
### Description

当我点击更新记录 导入JSON 和删除记录时 会有SQL的报错提示数据库磁盘映像格式错误

### Reproduction Steps

星穹铁道跃迁记录无法更新导入和删除

### Screenshots

![](https://article.biliimg.com/bfs/article/003b848bf271718c14dfbcb3afc2af474109241.png)

### Starward Version

0.9.2-perview.1

### Windows Version

22621.0

### Log

```shell
[13:21:34.666] [INFO] 
Welcome to Starward v0.9.2-preview.1
System: Microsoft Windows NT 10.0.22621.0
Command Line: C:\Users\cheng\OneDrive\应用\Starward\app-0.9.2-preview.1\Starward.dll

[13:21:34.915] [INFO] Starward.Services.DatabaseService
Database path is 'C:\Users\cheng\OneDrive\应用\Starward'

[13:21:35.069] [INFO] Starward.Services.DatabaseService
Database version is 6, target version is 6.

[13:21:35.197] [INFO] Starward.Pages.MainPage
Select game region is hk4e_cn

[13:21:35.203] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[13:21:35.760] [INFO] Starward.Pages.LauncherPage
Game install path hk4e_cn: "D:\Genshin Impact\Genshin Impact Game"

[13:21:35.846] [WARN] Starward.Services.GameService
Game uninstalled (hk4e_global)

[13:21:35.846] [WARN] Starward.Services.GameService
Game uninstalled (hk4e_cloud)

[13:21:35.847] [WARN] Starward.Services.GameService
Game uninstalled (hkrpg_global)

[13:21:35.847] [WARN] Starward.Services.GameService
Game uninstalled (bh3_cn)

[13:21:35.847] [WARN] Starward.Services.GameService
Game uninstalled (bh3_global)

[13:21:35.847] [WARN] Starward.Services.GameService
Game uninstalled (bh3_jp)

[13:21:35.848] [WARN] Starward.Services.GameService
Game uninstalled (bh3_kr)

[13:21:35.848] [WARN] Starward.Services.GameService
Game uninstalled (bh3_overseas)

[13:21:35.848] [WARN] Starward.Services.GameService
Game uninstalled (bh3_tw)

[13:21:36.311] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[13:21:36.825] [INFO] Starward.Services.UpdateService
Current version: "0.9.2-preview.1", latest version: "0.9.2-preview.1", ignore version: null

[13:21:47.032] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[13:21:47.036] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_cn

[13:21:47.095] [INFO] Starward.Pages.LauncherPage
Game install path hkrpg_cn: "D:\Star Rail\Game"

[13:21:50.026] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hkrpg_cn

[13:21:50.209] [EROR] Starward.Pages.GachaLogPage
UpdateGachaTypeStats
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataRecord.Read()
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1178
   at System.Collections.Generic.List`1..ctor(IEnumerable`1)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 801
   at Starward.Services.Gacha.StarRailGachaService.GetGachaLogItemEx(Int64 uid) in D:\a\Starward\Starward\src\Starward\Services\Gacha\StarRailGachaService.cs:line 51
   at Starward.Services.Gacha.GachaLogService.GetGachaTypeStats(Int64 uid) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GachaLogService.cs:line 170
   at Starward.Pages.GachaLogPage.UpdateGachaTypeStats(Nullable`1 uid) in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 203

[13:21:52.018] [WARN] Starward.Pages.GachaLogPage
Request mihoyo api error: "authkey timeout (-101)"

[13:21:57.904] [EROR] Starward.Pages.GachaLogPage
Import gacha log
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 630
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 519
   at Starward.Services.Gacha.StarRailGachaService.InsertGachaLogItems(List`1 items) in D:\a\Starward\Starward\src\Starward\Services\Gacha\StarRailGachaService.cs:line 78
   at Starward.Services.Gacha.StarRailGachaService.ImportGachaLog(String file) in D:\a\Starward\Starward\src\Starward\Services\Gacha\StarRailGachaService.cs:line 146
   at Starward.Pages.GachaLogPage.ImportGachaLogAsync() in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 552

[13:23:18.728] [EROR] Starward.Pages.GachaLogPage
Delete uid
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2928
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 648
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 519
   at Starward.Services.Gacha.GachaLogService.DeleteUid(Int64 uid) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GachaLogService.cs:line 232
   at Starward.Pages.GachaLogPage.DeleteUidAsync() in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 459

[13:23:27.996] [INFO] Starward.Pages.MainPage
Navigate to "SettingPage" with param hkrpg_cn

[13:23:32.981] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[13:23:32.981] [INFO] Starward.Pages.MainPage
Navigate to "SettingPage" with param hkrpg_cn

[13:23:34.682] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_global

[13:23:34.689] [INFO] Starward.Pages.MainPage
Navigate to "SettingPage" with param hkrpg_global

[13:23:35.840] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[13:23:35.848] [INFO] Starward.Pages.MainPage
Navigate to "SettingPage" with param hkrpg_cn

[13:23:39.475] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[13:23:39.478] [INFO] Starward.Pages.MainPage
Navigate to "SettingPage" with param hk4e_cn

[13:23:40.424] [INFO] Starward.Pages.MainPage
Change game region to bh3_cn

[13:23:40.434] [INFO] Starward.Pages.MainPage
Navigate to "SettingPage" with param bh3_cn

[13:23:41.300] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[13:23:41.305] [INFO] Starward.Pages.MainPage
Navigate to "SettingPage" with param hk4e_cn

[13:23:42.191] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[13:23:42.194] [INFO] Starward.Pages.MainPage
Navigate to "SettingPage" with param hkrpg_cn

[13:27:43.958] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hkrpg_cn

[13:27:44.010] [EROR] Starward.Pages.GachaLogPage
UpdateGachaTypeStats
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataRecord.Read()
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1207
   at System.Collections.Generic.List`1..ctor(IEnumerable`1)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 801
   at Starward.Services.Gacha.StarRailGachaService.GetGachaLogItemEx(Int64 uid) in D:\a\Starward\Starward\src\Starward\Services\Gacha\StarRailGachaService.cs:line 51
   at Starward.Services.Gacha.GachaLogService.GetGachaTypeStats(Int64 uid) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GachaLogService.cs:line 170
   at Starward.Pages.GachaLogPage.UpdateGachaTypeStats(Nullable`1 uid) in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 203

[13:27:48.837] [EROR] Starward.Pages.GachaLogPage
Delete uid
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2928
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 648
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 519
   at Starward.Services.Gacha.GachaLogService.DeleteUid(Int64 uid) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GachaLogService.cs:line 232
   at Starward.Pages.GachaLogPage.DeleteUidAsync() in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 459
```

**Comment by Scighost** [comment]
数据库已损坏，请使用相关软件修复。
