### ISSUE TITLE
每次登录原神之后账号下面都会多一个0，明明之前已经保存了[Bug] 

### ISSUE THREAD

**Issue by xiaoxingruo** [Scighost/Starward#419]
### Description

原神每次开始游戏之后登录器都会多个新的账户

### Reproduction Steps

点击开始游戏之后

### Expected Behavior

不要再给我生成新的账户了，每次都要自己删掉好麻烦的

### Starward Version

0.10.0

### Windows Version

windows10

### Log

```shell
[11:20:29.437] [INFO] 
Welcome to Starward v0.10.0
System: Microsoft Windows NT 10.0.19045.0
Command Line: G:\Starward091\app-0.10.0\Starward.dll

[11:20:29.493] [INFO] Starward.Services.DatabaseService
Database path is 'G:\Starward091'

[11:20:29.518] [INFO] Starward.Services.DatabaseService
Database version is 7, target version is 7.

[11:20:29.582] [INFO] Starward.Pages.MainPage
Select game region is hkrpg_global

[11:20:29.588] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_global

[11:20:30.077] [INFO] Starward.Pages.LauncherPage
Game install path hkrpg_global: "D:\Game\Star Rail\Games"

[11:20:30.134] [WARN] Starward.Services.GameService
Game uninstalled (bh3_global)

[11:20:30.134] [WARN] Starward.Services.GameService
Game uninstalled (bh3_kr)

[11:20:30.134] [WARN] Starward.Services.GameService
Game uninstalled (bh3_overseas)

[11:20:30.135] [WARN] Starward.Services.GameService
Game uninstalled (bh3_tw)

[11:20:39.941] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[11:20:40.002] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[11:20:40.153] [INFO] Starward.Pages.LauncherPage
Game install path hk4e_cn: "d:\Program Files\Genshin Impact\Genshin Impact Game"

[11:20:40.390] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[11:20:42.325] [INFO] Starward.Services.GameService
Start game (hk4e_cn)
path: "d:\Program Files\Genshin Impact\Genshin Impact Game\YuanShen.exe"
arg: null

[11:20:42.540] [INFO] Starward.Pages.LauncherPage
Game started ("YuanShen", 18904)

[11:20:44.553] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hk4e_cn, 18904)

[11:21:02.974] [INFO] Starward.Services.UpdateService
Current version: "0.10.0", latest version: "0.10.0", ignore version: null

[11:21:39.370] [INFO] Starward.Pages.MainPage
Change game region to bh3_cn

[11:21:39.441] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param bh3_cn

[11:21:39.526] [INFO] Starward.Pages.LauncherPage
Game install path bh3_cn: "E:\Games\Honkai Impact 3\Games"

[11:21:40.417] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[11:21:40.452] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[11:21:40.533] [INFO] Starward.Pages.LauncherPage
Game install path hk4e_cn: "d:\Program Files\Genshin Impact\Genshin Impact Game"

[11:21:50.683] [INFO] Starward.Services.GameService
Change account "筱星若" (hk4e_cn) successfully!

[11:21:52.096] [INFO] Starward.Services.GameService
Start game (hk4e_cn)
path: "d:\Program Files\Genshin Impact\Genshin Impact Game\YuanShen.exe"
arg: null

[11:21:52.309] [INFO] Starward.Pages.LauncherPage
Game started ("YuanShen", 25268)

[11:21:54.317] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hk4e_cn, 25268)

[11:22:10.338] [EROR] Starward.Pages.LauncherPage
Get game launcher content (hkrpg_global)
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage, Boolean, Boolean, CancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage, HttpCompletionOption, CancellationTokenSource, Boolean, CancellationTokenSource, CancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception, Boolean, HttpResponseMessage, CancellationTokenSource, CancellationToken, CancellationTokenSource)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage, HttpCompletionOption, CancellationTokenSource, Boolean, CancellationTokenSource, CancellationToken)
   at Starward.Core.Launcher.LauncherClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\Launcher\LauncherClient.cs:line 27
   at Starward.Core.Launcher.LauncherClient.GetLauncherContentAsync(GameBiz biz, String lang, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\Launcher\LauncherClient.cs:line 61
   at Starward.Services.LauncherService.GetLauncherContentAsync(GameBiz gameBiz, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\LauncherService.cs:line 51
   at Starward.Pages.LauncherPage.GetLauncherContentAsync() in D:\a\Starward\Starward\src\Starward\Pages\LauncherPage.xaml.cs:line 182

[11:22:10.340] [EROR] Starward.Pages.LauncherPage
Check game version
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage, Boolean, Boolean, CancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage, HttpCompletionOption, CancellationTokenSource, Boolean, CancellationTokenSource, CancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception, Boolean, HttpResponseMessage, CancellationTokenSource, CancellationToken, CancellationTokenSource)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage, HttpCompletionOption, CancellationTokenSource, Boolean, CancellationTokenSource, CancellationToken)
   at Starward.Core.Launcher.LauncherClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\Launcher\LauncherClient.cs:line 27
   at Starward.Core.Launcher.LauncherClient.GetLauncherResourceAsync(GameBiz biz, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\Launcher\LauncherClient.cs:line 98
   at Starward.Services.DownloadGameService.GetLauncherResourceAsync(GameBiz biz) in D:\a\Starward\Starward\src\Starward\Services\DownloadGameService.cs:line 93
   at Starward.Services.DownloadGameService.GetGameVersionAsync(GameBiz biz) in D:\a\Starward\Starward\src\Starward\Services\DownloadGameService.cs:line 104
   at Starward.Pages.LauncherPage.UpdateGameVersion() in D:\a\Starward\Starward\src\Starward\Pages\LauncherPage.xaml.cs:line 506

[11:22:23.733] [INFO] Starward.Services.GameService
Change account null (hk4e_cn) successfully!

[11:22:40.672] [INFO] Starward.Services.GameService
Delete account "筱星若" (hk4e_cn) successfully!

[11:22:40.687] [INFO] Starward.Services.GameService
Save account "筱星若" (hk4e_cn) successfully!

[11:22:47.702] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_global

[11:22:47.719] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_global

[11:22:47.808] [INFO] Starward.Pages.LauncherPage
Game install path hkrpg_global: "D:\Game\Star Rail\Games"

[11:22:48.413] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[11:22:48.424] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[11:22:48.521] [INFO] Starward.Pages.LauncherPage
Game install path hk4e_cn: "d:\Program Files\Genshin Impact\Genshin Impact Game"

[11:22:52.058] [INFO] Starward.Services.GameService
Start game (hk4e_cn)
path: "d:\Program Files\Genshin Impact\Genshin Impact Game\YuanShen.exe"
arg: null

[11:22:52.223] [INFO] Starward.Pages.LauncherPage
Game started ("YuanShen", 22972)

[11:22:54.234] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hk4e_cn, 22972)

[11:34:00.374] [INFO] Starward.Pages.MainPage
Change game region to bh3_cn

[11:34:00.475] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param bh3_cn

[11:34:00.558] [INFO] Starward.Pages.LauncherPage
Game install path bh3_cn: "E:\Games\Honkai Impact 3\Games"

[11:34:04.800] [INFO] Starward.Services.GameService
Start game (bh3_cn)
path: "E:\Games\Honkai Impact 3\Games\BH3.exe"
arg: null

[11:34:04.964] [INFO] Starward.Pages.LauncherPage
Game started ("BH3", 14856)

[11:34:06.968] [INFO] Starward.Services.PlayTimeService
Game process (bh3_cn, 14856) has no window

[11:34:08.979] [INFO] Starward.Services.PlayTimeService
Game process (bh3_cn, 14856) has no window

[11:34:10.984] [INFO] Starward.Services.PlayTimeService
Game process (bh3_cn, 14856) has no window

[11:34:12.995] [INFO] Starward.Services.PlayTimeService
Game process (bh3_cn, 14856) has no window

[11:34:15.006] [INFO] Starward.Services.PlayTimeService
Start to log playtime (bh3_cn, 14856)

[11:35:04.752] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[11:35:05.612] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[11:35:05.704] [INFO] Starward.Pages.LauncherPage
Game install path hk4e_cn: "d:\Program Files\Genshin Impact\Genshin Impact Game"

[11:35:06.871] [INFO] Starward.Pages.MainPage
Change game region to bh3_cn

[11:35:06.909] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param bh3_cn

[11:35:06.996] [INFO] Starward.Pages.LauncherPage
Game install path bh3_cn: "E:\Games\Honkai Impact 3\Games"

[11:35:16.971] [INFO] Starward.Services.GameService
Delete account "筱星若" (bh3_cn) successfully!

[11:35:16.987] [INFO] Starward.Services.GameService
Save account "筱星若" (bh3_cn) successfully!

[11:35:20.247] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[11:35:20.830] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[11:35:21.020] [INFO] Starward.Pages.LauncherPage
Game install path hk4e_cn: "d:\Program Files\Genshin Impact\Genshin Impact Game"

[11:35:21.622] [INFO] Starward.Pages.MainPage
Change game region to bh3_cn

[11:35:21.843] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param bh3_cn

[11:35:21.937] [INFO] Starward.Pages.LauncherPage
Game install path bh3_cn: "E:\Games\Honkai Impact 3\Games"

[12:13:38.417] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_global

[12:13:38.559] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_global

[12:13:38.645] [INFO] Starward.Pages.LauncherPage
Game install path hkrpg_global: "D:\Game\Star Rail\Games"

[12:13:43.608] [INFO] Starward.Services.GameService
Start game (hkrpg_global)
path: "G:\星铁加载器\GameStarter\GameStarter-x64.exe"
arg: null

[12:13:44.196] [INFO] Starward.Pages.LauncherPage
Game started ("GameStarter-x64", 20460)

[12:13:46.213] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hkrpg_global, 14840)

[12:34:42.860] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[12:34:42.927] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[12:34:43.008] [INFO] Starward.Pages.LauncherPage
Game install path hk4e_cn: "d:\Program Files\Genshin Impact\Genshin Impact Game"

[12:34:43.718] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_global

[12:34:45.009] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_global

[12:34:45.092] [INFO] Starward.Pages.LauncherPage
Game install path hkrpg_global: "D:\Game\Star Rail\Games"

[12:34:54.681] [INFO] Starward.Services.GameService
Delete account "墨" (hkrpg_global) successfully!

[12:34:54.696] [INFO] Starward.Services.GameService
Save account "墨" (hkrpg_global) successfully!

[12:34:58.339] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[12:34:58.702] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[12:34:58.799] [INFO] Starward.Pages.LauncherPage
Game install path hk4e_cn: "d:\Program Files\Genshin Impact\Genshin Impact Game"

[12:35:11.001] [INFO] Starward.Services.GameService
Change account "筱星若" (hk4e_cn) successfully!

[12:35:11.916] [INFO] Starward.Services.GameService
Start game (hk4e_cn)
path: "d:\Program Files\Genshin Impact\Genshin Impact Game\YuanShen.exe"
arg: null

[12:35:12.087] [INFO] Starward.Pages.LauncherPage
Game started ("YuanShen", 17780)

[12:35:14.105] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hk4e_cn, 17780)

[12:35:42.031] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_global

[12:35:42.051] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_global

[12:35:42.147] [INFO] Starward.Pages.LauncherPage
Game install path hkrpg_global: "D:\Game\Star Rail\Games"

[12:35:42.620] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[12:35:42.640] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[12:35:42.724] [INFO] Starward.Pages.LauncherPage
Game install path hk4e_cn: "d:\Program Files\Genshin Impact\Genshin Impact Game"

[12:35:46.801] [INFO] Starward.Services.GameService
Change account "筱星若" (hk4e_cn) successfully!

[12:35:50.827] [INFO] Starward.Services.GameService
Delete account null (hk4e_cn) successfully!

[12:35:52.937] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_global

[12:35:52.956] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_global

[12:35:53.047] [INFO] Starward.Pages.LauncherPage
Game install path hkrpg_global: "D:\Game\Star Rail\Games"

[12:35:55.952] [INFO] Starward.Pages.MainPage
Change game region to bh3_cn

[12:35:57.029] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param bh3_cn

[12:35:57.114] [INFO] Starward.Pages.LauncherPage
Game install path bh3_cn: "E:\Games\Honkai Impact 3\Games"

[12:36:00.317] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[12:36:00.356] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[12:36:00.438] [INFO] Starward.Pages.LauncherPage
Game install path hk4e_cn: "d:\Program Files\Genshin Impact\Genshin Impact Game"

[12:36:01.845] [INFO] Starward.Services.GameService
Start game (hk4e_cn)
path: "d:\Program Files\Genshin Impact\Genshin Impact Game\YuanShen.exe"
arg: null

[12:36:02.010] [INFO] Starward.Pages.LauncherPage
Game started ("YuanShen", 12648)

[12:36:04.028] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hk4e_cn, 12648)

[12:36:25.546] [EROR] Starward.Pages.LauncherPage
Game notices alert
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage, Boolean, Boolean, CancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage, HttpCompletionOption, CancellationTokenSource, Boolean, CancellationTokenSource, CancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception, Boolean, HttpResponseMessage, CancellationTokenSource, CancellationToken, CancellationTokenSource)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage, HttpCompletionOption, CancellationTokenSource, Boolean, CancellationTokenSource, CancellationToken)
   at Starward.Core.Launcher.LauncherClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\Launcher\LauncherClient.cs:line 39
   at Starward.Core.Launcher.LauncherClient.IsNoticesAlertAsync(GameBiz biz, Int64 uid, String lang, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\Launcher\LauncherClient.cs:line 139
   at Starward.Services.LauncherService.IsNoticesAlertAsync(GameBiz gameBiz, Int64 uid, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\LauncherService.cs:line 61
   at Starward.Pages.LauncherPage.GetGameNoticesAlertAsync() in D:\a\Starward\Starward\src\Starward\Pages\LauncherPage.xaml.cs:line 294

[12:36:31.256] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_global

[12:36:31.269] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_global

[12:36:31.350] [INFO] Starward.Pages.LauncherPage
Game install path hkrpg_global: "D:\Game\Star Rail\Games"

[12:36:31.777] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[12:36:31.796] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[12:36:31.878] [INFO] Starward.Pages.LauncherPage
Game install path hk4e_cn: "d:\Program Files\Genshin Impact\Genshin Impact Game"

[12:36:34.697] [EROR] Starward.Pages.LauncherPage
Game notices alert
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage, Boolean, Boolean, CancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage, HttpCompletionOption, CancellationTokenSource, Boolean, CancellationTokenSource, CancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception, Boolean, HttpResponseMessage, CancellationTokenSource, CancellationToken, CancellationTokenSource)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage, HttpCompletionOption, CancellationTokenSource, Boolean, CancellationTokenSource, CancellationToken)
   at Starward.Core.Launcher.LauncherClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\Launcher\LauncherClient.cs:line 39
   at Starward.Core.Launcher.LauncherClient.IsNoticesAlertAsync(GameBiz biz, Int64 uid, String lang, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\Launcher\LauncherClient.cs:line 139
   at Starward.Services.LauncherService.IsNoticesAlertAsync(GameBiz gameBiz, Int64 uid, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\LauncherService.cs:line 61
   at Starward.Pages.LauncherPage.GetGameNoticesAlertAsync() in D:\a\Starward\Starward\src\Starward\Pages\LauncherPage.xaml.cs:line 294

[12:36:46.441] [INFO] Starward.Pages.MainPage
Navigate to "SettingPage" with param hk4e_cn

[12:36:48.535] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[12:37:10.529] [INFO] Starward.Services.UpdateService
Current version: "0.10.0", latest version: "0.10.0", ignore version: null
```

**Comment by yyIntsuki** [comment]
是的，并且每次重新打开都会需要我重新登录账号... 感觉这个切账号的功能是肯定有BUG的

**Comment by Scighost** [comment]
关于这个问题，请参考 #159
