### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by vyquaquay** [Scighost/Starward#429]
### Description

gacha record doesn't work, it pop out the fuxuan banner when check the url

### Reproduction Steps

click on the setting at gacha record and then copy the url and paste in to any browser

### Screenshots

![image](https://github.com/Scighost/Starward/assets/77006338/5b8228f6-5a67-4635-bf17-8154e6337d75)

### Starward Version

0.10.0

### Windows Version

10.0.19043

### Log

```shell
[15:30:50.892] [EROR] Starward.Pages.HoyolabToolbox.TrailblazeCalendarPage
Get realtime trailblaze calendar data ("hkrpg_global", 800470910).
Starward.Core.miHoYoApiException: 请先登录 (-100)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 162
   at Starward.Core.GameRecord.HoyolabClient.GetTrailblazeCalendarSummaryAsync(GameRecordRole role, String month, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HoyolabClient.cs:line 303
   at Starward.Services.GameRecordService.GetTrailblazeCalendarSummaryAsync(GameRecordRole role, String month) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 511
   at Starward.Pages.HoyolabToolbox.TrailblazeCalendarPage.GetCurrentSummaryAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\TrailblazeCalendarPage.xaml.cs:line 121

[15:30:58.450] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hkrpg_global

[15:31:11.677] [WARN] Starward.Pages.GachaLogPage
Request mihoyo api error: "authkey timeout (-101)"

[15:31:32.294] [WARN] Starward.Pages.GachaLogPage
Request mihoyo api error: "authkey timeout (-101)"

[15:32:00.998] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_global

[15:32:01.074] [INFO] Starward.Pages.LauncherPage
Game install path hkrpg_global: "C:\Program Files\Star Rail\Games"

[15:32:10.543] [INFO] Starward.Services.GameService
Start game (hkrpg_global)
path: "C:\Program Files\Star Rail\Games\StarRail.exe"
arg: ""

[15:32:10.607] [INFO] Starward.Pages.LauncherPage
Game started ("StarRail", 17348)

[15:32:12.609] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hkrpg_global, 17348)

[15:33:31.988] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hkrpg_global

[15:34:22.098] [WARN] Starward.Pages.GachaLogPage
Request mihoyo api error: "app id error (-109)"

[15:35:44.257] [WARN] Starward.Pages.GachaLogPage
Request mihoyo api error: "authkey timeout (-101)"

[15:35:58.232] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_global

[15:35:58.297] [INFO] Starward.Pages.LauncherPage
Game install path hkrpg_global: "C:\Program Files\Star Rail\Games"

[15:35:59.056] [INFO] Starward.Services.GameService
Start game (hkrpg_global)
path: "C:\Program Files\Star Rail\Games\StarRail.exe"
arg: ""

[15:35:59.110] [INFO] Starward.Pages.LauncherPage
Game started ("StarRail", 10100)

[15:36:01.112] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hkrpg_global, 10100)

[15:36:47.713] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hkrpg_global

[15:36:57.514] [WARN] Starward.Pages.GachaLogPage
Request mihoyo api error: "app id error (-109)"
```

**Comment by Scighost** [comment]
Closed for no title or content.
