### ISSUE TITLE
[Bug] 单账号的时候，默认选择会变成0

### ISSUE THREAD

**Issue by Whuihuan** [Scighost/Starward#436]
### Description

即使我事先设置好了账号并且设置成默认了，但是在每次重开软件的时候，发现账号选择都是个“0”，下拉会看到有“0”和我设置的账号。但当我选中我设置的账号再设置为默认的时候，下拉选项就不会出现“0”了

### Reproduction Steps

打开软件就能看到

### Starward Version

0.10.1

### Windows Version

23565.1000

### Log

```shell
[02:03:38.345] [INFO] 
Welcome to Starward v0.10.1
System: Microsoft Windows NT 10.0.23565.0
Command Line: E:\Games\OL\Starward\app-0.10.1\Starward.dll

[02:03:38.421] [INFO] Starward.Services.DatabaseService
Database path is 'E:\Games\OL\Starward'

[02:03:38.463] [INFO] Starward.Services.DatabaseService
Database version is 7, target version is 7.

[02:03:38.562] [INFO] Starward.Pages.MainPage
Select game region is hk4e_cn

[02:03:38.572] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[02:03:39.417] [INFO] Starward.Pages.LauncherPage
Game install path hk4e_cn: "E:\Games\OL\Genshin Impact Game"

[02:03:39.481] [INFO] Starward.Services.DownloadGameService
Local game version is "4.1.0" (gameBiz: hk4e_cn)

[02:03:39.514] [WARN] Starward.Services.GameService
Game uninstalled path not found (hk4e_global)

[02:03:39.514] [WARN] Starward.Services.GameService
Game uninstalled path not found (hk4e_cloud)

[02:03:39.514] [WARN] Starward.Services.GameService
Game uninstalled path not found (hkrpg_cn)

[02:03:39.515] [WARN] Starward.Services.GameService
Game uninstalled path not found (hkrpg_global)

[02:03:39.515] [WARN] Starward.Services.GameService
Game uninstalled path not found (bh3_cn)

[02:03:39.516] [WARN] Starward.Services.GameService
Game uninstalled path not found (bh3_global)

[02:03:39.516] [WARN] Starward.Services.GameService
Game uninstalled path not found (bh3_jp)

[02:03:39.517] [WARN] Starward.Services.GameService
Game uninstalled path not found (bh3_kr)

[02:03:39.517] [WARN] Starward.Services.GameService
Game uninstalled path not found (bh3_overseas)

[02:03:39.518] [WARN] Starward.Services.GameService
Game uninstalled path not found (bh3_tw)

[02:03:39.802] [INFO] Starward.Services.UpdateService
Start to check update (Preview: False, Arch: X64)

[02:03:40.148] [INFO] Starward.Services.UpdateService
Current version: "0.10.1", latest version: "0.10.1", ignore version: null

[02:03:52.231] [INFO] Starward.Services.GameService
Change account "西瓜" (hk4e_cn) successfully!

[02:03:55.908] [INFO] Starward.Services.GameService
Start game (hk4e_cn)
path: "E:\Games\OL\Genshin Impact Game\YuanShen.exe"
arg: null

[02:03:57.905] [INFO] Starward.Pages.LauncherPage
Game started ("YuanShen", 22920)

[02:03:59.928] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hk4e_cn, 22920)

[03:42:13.491] [INFO] Starward.Pages.LauncherPage
Game process exited

[13:20:26.286] [INFO] Starward.Services.GameService
Change account "西瓜" (hk4e_cn) successfully!

[13:20:34.214] [INFO] Starward.Pages.MainPage
Navigate to "SettingPage" with param hk4e_cn

[13:21:21.655] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hk4e_cn

[13:21:21.678] [INFO] Starward.Services.GameRecordService
Change region to China.

[13:21:48.509] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[13:21:48.546] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hkrpg_cn

[13:21:48.556] [INFO] Starward.Services.GameRecordService
Change region to China.

[13:21:51.195] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[13:21:51.227] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hk4e_cn

[13:21:51.235] [INFO] Starward.Services.GameRecordService
Change region to China.

[13:21:53.644] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[13:21:53.688] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hkrpg_cn

[13:21:53.696] [INFO] Starward.Services.GameRecordService
Change region to China.

[13:21:54.780] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[13:21:54.811] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hk4e_cn

[13:21:54.816] [INFO] Starward.Services.GameRecordService
Change region to China.

[13:22:00.292] [EROR] Starward.Pages.HoyolabToolbox.SpiralAbyssPage
Refresh abyss data ("hk4e_cn", 129413858).
Starward.Core.miHoYoApiException:  (1034)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 165
   at Starward.Core.GameRecord.HyperionClient.GetSpiralAbyssInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 135
   at Starward.Services.GameRecordService.RefreshSpiralAbyssInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 227
   at Starward.Pages.HoyolabToolbox.SpiralAbyssPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SpiralAbyssPage.xaml.cs:line 119

[13:22:22.547] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[13:22:22.665] [INFO] Starward.Pages.LauncherPage
Game install path hk4e_cn: "E:\Games\OL\Genshin Impact Game"

[13:22:22.691] [INFO] Starward.Services.DownloadGameService
Local game version is "4.1.0" (gameBiz: hk4e_cn)

[13:25:30.368] [INFO] Starward.Pages.MainPage
Navigate to "SettingPage" with param hk4e_cn
```

**Comment by Whuihuan** [comment]
又试了下，暂时又没出现了，我等下次出现了再截张图吧

**Comment by Scighost** [comment]
请你在发 issue 前，搜索一下相关的问题 #159 。
