### ISSUE TITLE
[Bug] 点击备份数据库会显示错误，备份数据也是0KB大小

### ISSUE THREAD

**Issue by laurelcafe** [Scighost/Starward#468]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

点击备份数据库会显示错误，备份数据也是0KB大小。
上次成功备份的时间是10月9号，今天尝试备份的时候就报错了。

### Reproduction Steps

点击备份就报错

### Screenshots

![image](https://github.com/Scighost/Starward/assets/43950231/c49e63ad-0af3-4d29-bb4e-82ffea3f995e)

![image](https://github.com/Scighost/Starward/assets/43950231/0d1cb155-9fd1-4896-a193-2b383ca89488)

### Starward Version

0.10.2

### Windows Version

22621.2428

### Log

```shell
[00:53:18.556] [EROR] Starward.Pages.SettingPage
Backup database
System.ArgumentException: The CommandType 'StoredProcedure' is not supported.
   at Microsoft.Data.Sqlite.SqliteCommand.set_CommandType(CommandType value)
   at Dapper.CommandDefinition.SetupCommand(IDbConnection cnn, Action`2 paramReader) in /_/Dapper/CommandDefinition.cs:line 143
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2958
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 656
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 527
   at Starward.Services.DatabaseService.BackupDatabase(String file) in D:\a\Starward\Starward\src\Starward\Services\DatabaseService.cs:line 101
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
--- End of stack trace from previous location ---
   at Starward.Pages.SettingPage.BackupDatabaseAsync() in D:\a\Starward\Starward\src\Starward\Pages\SettingPage.xaml.cs:line 595
```

**Comment by Scighost** [comment]
谢谢你的反馈，是 https://github.com/DapperLib/Dapper/issues/1984 造成的错误。建议在下个版本修复前通过手动复制文件的方式备份。

**Comment by Scighost** [comment]
新版本已发布
