### ISSUE TITLE
[Bug] 系统托盘图标失效，重新打开启动器也没出现托盘图标

### ISSUE THREAD

**Issue by HangHorn1354** [Scighost/Starward#470]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

刚更新到0.10.2这个版本之后，我没注意到托盘图标消失了，直到我玩完星穹铁道后才发现的，不管我重启这个启动器还是重新开启系统托盘图标也没有出现，这算是BUG吗？

### Reproduction Steps

从0.10.1更新到0.10.2后，系统托盘图标就消失了，以及同时失效了

### Screenshots

![没有图标](https://github.com/Scighost/Starward/assets/32638312/223a2eb7-fbbc-4204-af40-9e05a914e666)
![已确定是开启状态](https://github.com/Scighost/Starward/assets/32638312/f9814204-97d8-4541-a407-75e5d111f796)

### Starward Version

0.10.2

### Windows Version

19045.3570

### Log

```shell
[16:46:12.378] [EROR] Starward.Services.SystemTrayService
Initialize system tray
System.InvalidOperationException: TryCreate failed.
   at H.NotifyIcon.Core.TrayIcon.Create() in /_/src/libs/H.NotifyIcon/Core/TrayIcon.cs:line 324
   at H.NotifyIcon.TaskbarIcon.ForceCreate(Boolean ) in /_/src/libs/H.NotifyIcon.Shared/TaskbarIcon.cs:line 134
   at Starward.Services.SystemTrayService.Initialize(GameBiz gameBiz) in D:\a\Starward\Starward\src\Starward\Services\SystemTrayService.cs:line 72
```

**Comment by Scighost** [comment]
#251
