### ISSUE TITLE
[Question] 主程序启动过慢

### ISSUE THREAD

**Issue by CHSXuan** [Scighost/Starward#484]
### Checklist

- [x] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

最近有感知，启动Starward启动特别缓慢，可以说如果用官启，可能已经启动了22.5个原神了，Starward才缓慢启动

### Starward Version

 0.10.2

### Windows Version

？

**Comment by chenlz** [comment]
确实，用管理员打开不慢，否则第一次打开超级慢。

**Comment by Scighost** [comment]
~~哪里慢了。。。~~

我先排除软件放在机械硬盘或电脑硬件配置不足等原因

根据我的个人体验，因为 Starward 没有代码签名，每次开机后的首次启动时，Windows Defender 都会对其扫描，这个过程会显著地拖慢启动速度。我换了火绒之后不会出现此现象，其他安全软件没有测试过。

**Comment by CHSXuan** [comment]
确实，我的电脑里没有安装任何其他杀毒软件，用的是Windows Defender，所以，我去装个火绒测试一下

**Comment by chen274** [comment]
装的火绒 软件在固态 980pro里 CPU是14700...开机第一次启动差不多要十秒左右。。

**Comment by chen274** [comment]
火绒不管用的 试试别的方法完全禁用WD。。。除了火绒之外 我单独完全禁用了WD，确实秒启动了。。

**Comment by 1712279249** [comment]
之前一直没啥问题，最近几天打开得越来越慢，一开始十秒钟，然后半分钟，后面一分钟，到现在没个几分钟根本启动不了，看到上面有说禁用WD的，但真禁了还是有点心虚，希望下版本能够改善

**Comment by Scighost** [comment]
> 之前一直没啥问题，最近几天打开得越来越慢，一开始十秒钟，然后半分钟，后面一分钟，到现在没个几分钟根本启动不了，看到上面有说禁用WD的，但真禁了还是有点心虚，希望下版本能够改善

虽然不知道你的说辞中有几分夸张的表述，但是我还是建议你别用了，官方启动器挺好的。

<img src="https://github.com/Scighost/Starward/assets/61003590/7fd631f9-9149-4e01-9430-68d46a165936" width="200px" />

**Comment by LaoshuBaby** [comment]
之前一直用Collapse没用过这个（所以或许符合干净启动），听群友说到这个我就来测了一下，恰好我这边也是嫌Windows Defender太傻逼了所以用火绒代替让它闭嘴

电脑高负荷跑BOINC的情况下，本来打算手机掐秒表测[0.10.4-Furina](https://github.com/Scighost/Starward/releases/tag/0.10.4)这个版本，结果马上就开了

用别怂，怂别用
![035320e43697c48ddd7208e029ec2850 image](https://github.com/Scighost/Starward/assets/42690037/eda8c76e-70e5-4ee2-a8ab-26d9a12b2edc)

**Comment by 1712279249** [comment]
> 之前一直用崩溃没用过这个（所以也许符合干净启动），听群友说这个我就来测一下，正好我布拉格也很嫌Windows Defender太傻了所以用火绒代替代替闭嘴
> 
> 电脑高负担跑BOINC的情况下，本来打算掐手机秒表测[0.10.4-Furina](https://github.com/Scighost/Starward/releases/tag/0.10.4)这个版本，结果现在就开了
> 
> 用别怂，别用 <img alt="" width="200px" src="https://user-images.githubusercontent.com/61003590/284126871-7fd631f9-9149-4e01-9430-68d46a165936.jpg">

？？？？？我跟你情况一模一样。一点钟的时候我拿秒表掐了一下，启动整整花了十三分钟。然后下载好屏幕录制软件准备录制，结果跟你一样，立马秒开了。

**Comment by 1712279249** [comment]
> > 之前一直没啥问题，最近几天打开得越来越慢，一开始十秒钟，然后半分钟，后面一分钟，到现在没个几分钟根本启动不了，看到上面有说禁用WD的，但真禁了还是有点心虚，希望下版本能够改善
> 
> 虽然不知道你的说辞中有几分夸张的表述，但是我还是建议你别用了，官方启动器挺好的。
> 
> <img alt="" width="200px" src="https://user-images.githubusercontent.com/61003590/284126871-7fd631f9-9149-4e01-9430-68d46a165936.jpg">

没夸张，我甚至怕说太狠伤你感情，昨天开了三次印象里都是七八分钟，还会窗口黑屏显示未响应，吃完饭开秒表测了一下，启动花了十三分钟。怕你又说我乱编我还去下载了个屏幕录制软件准备录屏，然后就跟上面那个一样，莫名其妙直接秒开。本来我电脑上的bandizip解压也会有四五秒延迟的，现在也没了，全是秒开。

**Comment by Lightczx** [comment]
> 没夸张，我甚至怕说太狠伤你感情

这到底是夸张了还是没夸张

**Comment by 1712279249** [comment]
> > 没夸张，我甚至怕说太狠伤你感情
> 
> 这到底是夸张了还是没夸张

啊这，不是说了没夸张吗，所有话都没夸张。前一次发言用“几分钟”隐去了确数“七八分钟”，模糊了一下范围，是故意说轻了。你这语言理解着实有点着急

**Comment by Lightczx** [comment]
如果你真想反馈就要给出具体的时间，以及你觉得可能的原因之类的，对于我们开发来说，越具体越详细就越容易解决问题

**Comment by 1712279249** [comment]
> 如果你真想反馈就要给出具体的时间，以及你觉得可能的原因之类的，对于我们开发来说，越具体越详细就越容易解决问题

主要是这个问题上面已经有两三个人反映过了，我主要也就是在下面跟着发言表示“附议”罢了，结果另外一位上来就说我是夸张，还让我别用了，我认真测了时间，又把过程完整准确复述，你又来说我是不是夸张。
况且我上面的第一次反映，只把“三四分钟到七八分钟”这一步省略整合成了“几分钟”，前面过程中的“几秒钟”、“十几秒”、“半分钟”，都是准确到秒的认真回复，已经给出了具体时间，现在又要只抓着“最大值没说清楚”说我不是来“真心反馈问题”的，我觉得不太行

**Comment by Lightczx** [comment]
![image](https://github.com/Scighost/Starward/assets/36357191/a3915ed7-3d4d-4f53-95e1-c38d997fcfaa)

**Comment by CHSXuan** [comment]
抱歉，在这条反馈下边出现了一些不和谐声音，这边就先关掉了，停止这个话题，如果作者有需要来了解问题详情，可以来随时联系我，邮箱391111874@qq.com，非常感谢作者能给我们带来这么好的作品。

**Comment by Lightczx** [comment]
@CHSXuan 你是怎么判断启动很慢的
观察任务管理器 还是 程序打开黑屏 过很久才有画面？

**Comment by CHSXuan** [comment]
打开以后在任务管理器中可以看到StarWard在运行，大概在47秒左右时间显示主程序黑屏画面，在52秒左右显示主程序页面，以上数据为某两次不合法计时，电脑系统是WIn11-23H2，在Issuse中别人推荐管理员方式运行和替换掉WindwosDefender都无效

**Comment by CHSXuan** [comment]
补充，启动慢是开机后第一次会这样，在此之后都是秒开了，以前怀疑是中文用户名文件夹的问题，换成了英文文件夹之后问题依旧

**Comment by Lightczx** [comment]
@Scighost 应该是Mutex的问题

**Comment by CHSXuan** [comment]
咱们有什么QQ交流群之类的么，我感觉在那上边可以更方便的交流

**Comment by Lightczx** [comment]
468874328

**Comment by Scighost** [comment]
这里有一个在启动过程中加入了详细日志的编译版本，麻烦你测试一下 @CHSXuan
https://starward.scighost.com/release/package/Starward_Portable_0.10.5-alpha.1_x64.7z

**Comment by CHSXuan** [comment]
怪事.......在下载了0.10.5测试版之后，第一次启动47秒，随后无论如何重新开机启动时间一直都是在十秒以内，开发者大大受累了！如果再有问题随时日志反馈。

**Comment by Lightczx** [comment]
发日志

**Comment by CHSXuan** [comment]
稍微看了一下，没有任何营养
```
[18:18:23.272] [INFO] 
Welcome to Starward v0.10.5-alpha.1
System: Microsoft Windows NT 10.0.22631.0
Command Line: "D:\Program Files (x86)\StarwardBeta\app-0.10.5-alpha.1\Starward.dll"

[18:18:23.315] [INFO] Starward.Services.DatabaseService
Database path is 'D:\Program Files (x86)\StarwardBeta'

[18:18:23.338] [INFO] Starward.Services.DatabaseService
Database version is 7, target version is 7.

[18:18:23.338] [INFO] Starward.App
Start OnLauncher

[18:18:23.342] [INFO] Starward.App
Before "GetSyncMutex"

[18:18:23.342] [INFO] Starward.App
Before "WaitOne"

[18:18:23.343] [INFO] Starward.App
After "WaitOne"

[18:18:23.343] [INFO] Starward.App
If false "IsSignalMutexExisting"

[18:18:23.343] [INFO] Starward.App
Before "ReleaseMutex"

[18:18:23.343] [INFO] Starward.App
After "ReleaseMutex"

[18:18:23.343] [INFO] Starward.App
After "FindOrRegisterForKey"

[18:18:23.550] [INFO] Starward.Pages.MainPage
Select game region is hk4e_cn

[18:18:23.555] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[18:18:23.602] [INFO] Starward.App
After "MainWindow"

[18:18:23.624] [INFO] Starward.App
After "Activate"

[18:18:23.624] [INFO] Starward.App
End OnLauncher

[18:18:23.975] [INFO] Starward.Pages.LauncherPage
Game install path hk4e_cn: "I:\Program Files\Genshin Impact Game"

[18:18:23.998] [INFO] Starward.Services.DownloadGameService
Local game version is "4.2.0" (gameBiz: hk4e_cn)

[18:18:24.338] [INFO] Starward.Services.UpdateService
Start to check update (Preview: False, Arch: X64)

[18:18:25.753] [INFO] Starward.Services.UpdateService
Current version: "0.10.5-alpha.1", latest version: "0.10.4", ignore version: null

[18:18:27.188] [INFO] Starward.Pages.MainPage
Navigate to "SettingPage" with param hk4e_cn

```

**Comment by Lightczx** [comment]
还是需要时间较长的日志

**Comment by CHSXuan** [comment]
不过我在翻0.10.4的日志时看到了一行比较奇怪的，感觉像是定位的路径错了
```
[01:06:32.409] [INFO] 
Welcome to Starward v0.10.4
System: Microsoft Windows NT 10.0.22631.0
Command Line: "D:\Program Files\Starward\app-0.10.4\Starward.dll"

[01:06:38.785] [INFO] Starward.Services.DatabaseService
Database path is 'D:\Program Files\Starward'

[01:06:42.158] [INFO] Starward.Services.DatabaseService
Database version is 7, target version is 7.

[01:06:44.375] [INFO] Starward.Pages.MainPage
Select game region is None

[01:06:47.487] [EROR] Starward.Pages.MainPage
Update background image
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unknown region None')
   at Starward.Core.Launcher.LauncherClient.GetLauncherContentAsync(GameBiz biz, String lang, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\Launcher\LauncherClient.cs:line 58
   at Starward.Services.LauncherService.GetLauncherContentAsync(GameBiz gameBiz, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\LauncherService.cs:line 51
   at Starward.Services.LauncherService.GetBackgroundImageAsync(GameBiz gameBiz, Boolean disableCustom) in D:\a\Starward\Starward\src\Starward\Services\LauncherService.cs:line 124
   at Starward.Pages.MainPage.UpdateBackgroundImageAsync(Boolean force) in D:\a\Starward\Starward\src\Starward\Pages\MainPage.xaml.cs:line 582

[01:06:47.488] [INFO] Starward.Services.UpdateService
Start to check update (Preview: False, Arch: X64)

[01:06:53.980] [INFO] Starward.Services.UpdateService
Current version: "0.10.4", latest version: "0.10.4", ignore version: null

[01:07:14.268] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[01:07:14.279] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_cn

[01:07:14.524] [INFO] Starward.Pages.LauncherPage
Game install path hkrpg_cn: "E:\Program Files\Star Rail\Game"

[01:07:15.641] [INFO] Starward.Services.DownloadGameService
Local game version is "1.5.0" (gameBiz: hkrpg_cn)

[01:07:19.176] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[01:07:19.179] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[01:07:19.259] [INFO] Starward.Pages.LauncherPage
Game install path hk4e_cn: "I:\Program Files\Genshin Impact Game"

[01:07:19.267] [INFO] Starward.Services.DownloadGameService
Local game version is "4.2.0" (gameBiz: hk4e_cn)

[01:07:20.335] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[01:07:20.337] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_cn

[01:07:20.412] [INFO] Starward.Pages.LauncherPage
Game install path hkrpg_cn: "E:\Program Files\Star Rail\Game"

[01:07:20.433] [INFO] Starward.Services.DownloadGameService
Local game version is "1.5.0" (gameBiz: hkrpg_cn)

[01:07:22.219] [INFO] Starward.Services.GameService
Start game (hkrpg_cn)
path: "E:\Program Files\Star Rail\Game\StarRail.exe"
arg: null

[01:07:22.341] [INFO] Starward.Pages.LauncherPage
Game started ("StarRail", 13708)

[01:07:24.340] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hkrpg_cn, 13708)

```

**Comment by CHSXuan** [comment]
应该不是，翻了翻以前的日志都没有，再观望观望（

**Comment by Scighost** [comment]
从日志中看到，启动过程中和 Mutex 有关的逻辑耗时不超过 1ms，从记录下日志到点击设置页面耗时大约 4s，可以判断出 Starward 主程序的启动耗时不长。
耗时长的过程可能出现在 `app-version` 文件夹外的 Starward.exe (C++) 运行文件夹内的 Starward.exe (C#) 的过程中，但我无法确认操作系统或安全软件在这个过程中的影响有多大。

**Comment by Scighost** [comment]
因为已删除和无意义的评论打乱了时间线，我将关闭此 issue。
