### ISSUE TITLE
[Bug] 0.10.5beta1 星铁工具箱报错

### ISSUE THREAD

**Issue by lingfengyu-dreaming** [Scighost/Starward#497]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

星铁工具箱出现`InvalidOpreationException`报错，无法获取原有数据和拉取新数据，校验账号也无法使用。

### Reproduction Steps

1. 更新启动器至0.10.5beta1
2. 打开星铁米游社工具箱
3. 获得报错

### Expected Behavior

像之前版本一样显示内容

### Screenshots

![image](https://github.com/Scighost/Starward/assets/61617417/c0ddd61e-482f-4ac4-8218-77f8570dc1ca)

### Starward Version

0.10.5beta1

### Windows Version

22635.2771

### Log

```shell
sorry, UID hidden.

[21:43:52.324] [EROR] Starward.Pages.HoyolabToolbox.SimulatedUniversePage
Get stimulated record (Uid *, ScheduleId 70)
System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions, Type)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String , JsonSerializerOptions )
   at Starward.Services.GameRecordService.GetSimulatedUniverseRecord(GameRecordRole role, Int32 scheduleId) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 431
   at Starward.Pages.HoyolabToolbox.SimulatedUniversePage.GetSimulatedUniverseRecord(SimulatedUniverseRecordBasic data) in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SimulatedUniversePage.xaml.cs:line 185

[21:43:53.335] [EROR] Starward.Pages.HoyolabToolbox.SimulatedUniversePage
Get simulated universe data ("hkrpg_cn", *).
System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions, Type)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue, JsonSerializerOptions )
   at Starward.Services.GameRecordService.GetSimulatedUniverseInfoAsync(GameRecordRole role, Boolean detail) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 376
   at Starward.Pages.HoyolabToolbox.SimulatedUniversePage.GetSimulatedUniverseInfoBasicAsync(Boolean detail) in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SimulatedUniversePage.xaml.cs:line 136

[21:43:53.337] [EROR] Starward.Pages.HoyolabToolbox.SimulatedUniversePage
Get stimulated record (Uid *, ScheduleId 70)
System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions, Type)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String , JsonSerializerOptions )
   at Starward.Services.GameRecordService.GetSimulatedUniverseRecord(GameRecordRole role, Int32 scheduleId) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 431
   at Starward.Pages.HoyolabToolbox.SimulatedUniversePage.GetSimulatedUniverseRecord(SimulatedUniverseRecordBasic data) in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SimulatedUniversePage.xaml.cs:line 185

[21:44:00.232] [EROR] Starward.Pages.HoyolabToolbox.ForgottenHallPage
Selection changed ("hkrpg_cn", *).
System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions, Type)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String , JsonSerializerOptions )
   at Starward.Services.GameRecordService.GetForgottenHallInfo(GameRecordRole role, Int32 scheduleId) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 495
   at Starward.Pages.HoyolabToolbox.ForgottenHallPage.ListView_ForgottenHall_SelectionChanged(Object sender, SelectionChangedEventArgs e) in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\ForgottenHallPage.xaml.cs:line 151

[21:44:06.393] [EROR] Starward.Pages.HoyolabToolbox.SimulatedUniversePage
Get stimulated record (Uid *, ScheduleId 70)
System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions, Type)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String , JsonSerializerOptions )
   at Starward.Services.GameRecordService.GetSimulatedUniverseRecord(GameRecordRole role, Int32 scheduleId) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 431
   at Starward.Pages.HoyolabToolbox.SimulatedUniversePage.GetSimulatedUniverseRecord(SimulatedUniverseRecordBasic data) in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SimulatedUniversePage.xaml.cs:line 185

[21:44:07.105] [EROR] Starward.Pages.HoyolabToolbox.SimulatedUniversePage
Get simulated universe data ("hkrpg_cn", *).
System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions, Type)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue, JsonSerializerOptions )
   at Starward.Services.GameRecordService.GetSimulatedUniverseInfoAsync(GameRecordRole role, Boolean detail) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 376
   at Starward.Pages.HoyolabToolbox.SimulatedUniversePage.GetSimulatedUniverseInfoBasicAsync(Boolean detail) in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SimulatedUniversePage.xaml.cs:line 136

[21:44:07.106] [EROR] Starward.Pages.HoyolabToolbox.SimulatedUniversePage
Get stimulated record (Uid *, ScheduleId 70)
System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions, Type)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String , JsonSerializerOptions )
   at Starward.Services.GameRecordService.GetSimulatedUniverseRecord(GameRecordRole role, Int32 scheduleId) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 431
   at Starward.Pages.HoyolabToolbox.SimulatedUniversePage.GetSimulatedUniverseRecord(SimulatedUniverseRecordBasic data) in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SimulatedUniversePage.xaml.cs:line 185

[21:44:14.409] [EROR] Starward.Pages.HoyolabToolbox.ForgottenHallPage
Selection changed ("hkrpg_cn", *).
System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions, Type)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String , JsonSerializerOptions )
   at Starward.Services.GameRecordService.GetForgottenHallInfo(GameRecordRole role, Int32 scheduleId) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 495
   at Starward.Pages.HoyolabToolbox.ForgottenHallPage.ListView_ForgottenHall_SelectionChanged(Object sender, SelectionChangedEventArgs e) in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\ForgottenHallPage.xaml.cs:line 151

[21:44:15.849] [EROR] Starward.Pages.HoyolabToolbox.ForgottenHallPage
Refresh forgotten hall data ("hkrpg_cn", *).
Starward.Core.miHoYoApiException:  (1034)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 162
   at Starward.Core.GameRecord.HyperionClient.GetForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 270
   at Starward.Services.GameRecordService.RefreshForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 447
   at Starward.Pages.HoyolabToolbox.ForgottenHallPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\ForgottenHallPage.xaml.cs:line 110

[21:44:33.967] [EROR] Starward.Pages.HoyolabToolbox.SimulatedUniversePage
Get stimulated record (Uid *, ScheduleId 70)
System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions, Type)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String , JsonSerializerOptions )
   at Starward.Services.GameRecordService.GetSimulatedUniverseRecord(GameRecordRole role, Int32 scheduleId) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 431
   at Starward.Pages.HoyolabToolbox.SimulatedUniversePage.GetSimulatedUniverseRecord(SimulatedUniverseRecordBasic data) in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SimulatedUniversePage.xaml.cs:line 185

[21:44:34.775] [EROR] Starward.Pages.HoyolabToolbox.ForgottenHallPage
Selection changed ("hkrpg_cn", *).
System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions, Type)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String , JsonSerializerOptions )
   at Starward.Services.GameRecordService.GetForgottenHallInfo(GameRecordRole role, Int32 scheduleId) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 495
   at Starward.Pages.HoyolabToolbox.ForgottenHallPage.ListView_ForgottenHall_SelectionChanged(Object sender, SelectionChangedEventArgs e) in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\ForgottenHallPage.xaml.cs:line 151

[21:44:35.444] [EROR] Starward.Pages.HoyolabToolbox.ForgottenHallPage
Refresh forgotten hall data ("hkrpg_cn", *).
Starward.Core.miHoYoApiException:  (1034)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 162
   at Starward.Core.GameRecord.HyperionClient.GetForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 270
   at Starward.Services.GameRecordService.RefreshForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 447
   at Starward.Pages.HoyolabToolbox.ForgottenHallPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\ForgottenHallPage.xaml.cs:line 110

[21:44:37.257] [EROR] Starward.Pages.HoyolabToolbox.TrailblazeCalendarPage
Get realtime trailblaze calendar data ("hkrpg_cn", *).
System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions, Type)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue, JsonSerializerOptions )
   at Starward.Services.DatabaseService.DapperSqlMapper.TrailblazeCalendarMonthDataGroupByListHandler.SetValue(IDbDataParameter parameter, List`1 value) in D:\a\Starward\Starward\src\Starward\Services\DatabaseService.cs:line 641
   at ParamInfo36e6c417-dc73-4a4f-90c1-d208711663c5(IDbCommand, Object)
   at Dapper.CommandDefinition.SetupCommand(IDbConnection cnn, Action`2 paramReader)
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader)
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
   at Starward.Services.GameRecordService.GetTrailblazeCalendarSummaryAsync(GameRecordRole role, String month)
   at Starward.Pages.HoyolabToolbox.TrailblazeCalendarPage.GetCurrentSummaryAsync()

[21:44:37.266] [EROR] Starward.Pages.HoyolabToolbox.TrailblazeCalendarPage
Load trailblaze calendar month data ("hkrpg_cn", *).
System.Data.DataException: Error parsing column 8 (GroupBy=[{"action":"daily_reward","num":520,"percent":32,"action_name":"每日活跃"},{"action":"space_reward","num":450,"percent":27,"action_name":"模拟宇宙奖励"},{"action":"mail_reward","num":340,"percent":21,"action_name":"邮件奖励"},{"action":"abyss_reward","num":180,"percent":11,"action_name":"忘却之庭奖励"},{"action":"event_reward","num":120,"percent":7,"action_name":"活动奖励"},{"action":"other","num":0,"percent":2,"action_name":"其他"},{"action":"adventure_reward","num":5,"percent":0,"action_name":"冒险奖励"}] - String)
 ---> System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions, Type)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String , JsonSerializerOptions )
   at Dapper.SqlMapper.TypeHandler`1.Dapper.SqlMapper.ITypeHandler.Parse(Type destinationType, Object value) in /_/Dapper/SqlMapper.TypeHandler.cs:line 42
   at Deserialize79c53028-b937-4057-a763-9ed3d60596e8(DbDataReader)
   --- End of inner exception stack trace ---
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3906
   at Deserialize79c53028-b937-4057-a763-9ed3d60596e8(DbDataReader)
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
   at Starward.Services.GameRecordService.GetTrailblazeCalendarMonthDataList(GameRecordRole role)
   at Starward.Pages.HoyolabToolbox.TrailblazeCalendarPage.GetMonthDataList()
```

**Comment by Scighost** [comment]
感谢你的反馈

**Comment by Scighost** [comment]
已修复
