### ISSUE TITLE
[Bug] Decompressing Failed

### ISSUE THREAD

**Issue by BeatSeat** [Scighost/Starward#529]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

"End of Central Directory record could not be found." error in decompressing.

Is there any ways to fix it without download the file again?

By the way, even after Starward have downloaded 100% of the file, the official laucher would still continue from the time we break from the official laucher.

### Reproduction Steps

1. use an official laucher of genshin impact to download part of the game(~40G out of 70G)
2. then use Starward to resume downloading the rest
3. decompressing yields an error

### Expected Behavior

1. Starward could some what fix the issue of compression file, after validation
2. Official laucher could continue from the Starward

### Starward Version

0.10.6-preview.1 and 0.10.4

### Windows Version

19045.3448

### Log

```shell
[14:13:51.316] [INFO] Starward.Services.DownloadGameService
Verify file "YuanShen_4.2.0.zip.001"

[14:14:47.259] [INFO] Starward.Services.DownloadGameService
Verify file "YuanShen_4.2.0.zip.002"

[14:17:03.892] [INFO] Starward.Services.DownloadGameService
Verify file "YuanShen_4.2.0.zip.003"

[14:17:05.888] [INFO] Starward.Services.DownloadGameService
Decompress "YuanShen_4.2.0.zip.001"

[14:17:05.909] [EROR] Starward.Services.DownloadGameService
Decompress file
System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive..ctor(Stream, ZipArchiveMode, Boolean, Encoding )
   at System.IO.Compression.ZipArchive..ctor(Stream, ZipArchiveMode, Boolean)
   at Starward.Services.DownloadGameService.<>c__DisplayClass62_0.<DecompressAsync>b__1() in D:\a\Starward\Starward\src\Starward\Services\DownloadGameService.cs:line 1305
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
--- End of stack trace from previous location ---
   at Starward.Services.DownloadGameService.DecompressAsync(IEnumerable`1 files, Boolean use7zip) in D:\a\Starward\Starward\src\Starward\Services\DownloadGameService.cs:line 1285
   at Starward.Services.DownloadGameService.DecompressAsync() in D:\a\Starward\Starward\src\Starward\Services\DownloadGameService.cs:line 1203
```

**Comment by Scighost** [comment]
Same as #169, this issue occurs after downloading part of files by the official launcher. The best way is to delete files downloaded by the official launcher (file name with out `slice`). It is a little complex if you don't want to download again.

Find the file downloaded from the official launcher like `YuanShen_4.2.0.zip.001`, then slice the file into 1GB chunks and name them respectively `YuanShen_4.2.0.zip.001.slice.000`, `YuanShen_4.2.0.zip.001.slice.001`... Then delete this file. Now you could use Starward to install game continuously.
