### ISSUE TITLE
CDN维护/质量不一？

### ISSUE THREAD

**Issue by zhengliw** [Scighost/Starward#557]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

我先用普通启动器下载了一部分，遇到#169，根据提出的方案试了一下，但是我的里面竟然没有不带slice的zip文件。。。
于是我把所有文件删了，重新下载，选择cloudflare cdn，但是这次提示其他错误，日志如下。
现在正在用修复模式重新安装，但是使用jsdelivr。这次就莫名可以了。
这些cdn资源由谁来维护呢？是定期自动从米哈游抓取吗？还是本来就是米哈游的cdn？

I first downloaded part of the game with the official launcher and encountered #169, so I went to attempt the suggested fix, which didn't work for me due to missing unsliced files. So I removed all game files and proceeded to redownload with Cloudflare's cdn, but this time it's throwing another error, as seen below. By the time of writing, I managed to download a full working copy with jsdelivr's cdn.
Who is maintaining these CDNs? Are resources fetched from MiHoYo automatically, or do these cdns belong to Mihoyo anyways?

谢谢！
Thanks!

### Starward Version

0.10.4

### Windows Version

22000.2538

### Log

```shell
[17:29:30.452] [INFO] Starward.Services.DownloadGameService
Verify file "YuanShen_4.3.0.zip.001"

[17:29:35.261] [INFO] Starward.Services.DownloadGameService
Decompress "YuanShen_4.3.0.zip.001"

[17:29:35.706] [EROR] Starward.Services.DownloadGameService
Decompress file
System.IO.InvalidDataException: A local file header is corrupt.
   at System.IO.Compression.ZipArchiveEntry.OpenInReadMode(Boolean)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry, String, Boolean)
   at Starward.Services.DownloadGameService.<>c__DisplayClass62_0.<DecompressAsync>b__1() in D:\a\Starward\Starward\src\Starward\Services\DownloadGameService.cs:line 1317
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
--- End of stack trace from previous location ---
   at Starward.Services.DownloadGameService.DecompressAsync(IEnumerable`1 files, Boolean use7zip) in D:\a\Starward\Starward\src\Starward\Services\DownloadGameService.cs:line 1302
   at Starward.Services.DownloadGameService.DecompressAsync() in D:\a\Starward\Starward\src\Starward\Services\DownloadGameService.cs:line 1198
```

**Comment by Scighost** [comment]
谢谢你的反馈，CDN仅用于软件更新，下载游戏过程中遇到的问题都可以归因于你的网络问题。

**Comment by zhengliw** [comment]
就是感觉在jsdelivr放的资源感觉比cloudflare稳定一点。。

**Comment by Scighost** [comment]
忘了说，下载游戏用的是米哈游的cdn，和我无关。

**Comment by zhengliw** [comment]
哦哦好的，谢谢
