### ISSUE TITLE
[Bug] 忘却之庭标题错误

### ISSUE THREAD

**Issue by Fachep** [Scighost/Starward#564]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

星穹铁道 -> 米游社工具箱 -> 忘却之庭
此处“混沌回忆”显示为“虚构叙事”
（铁道这版本开始混沌回忆和虚构叙事俩深渊交替的模式，可能需要更新适配了）

### Reproduction Steps

-

### Screenshots

Starward 截图：
![image](https://github.com/Scighost/Starward/assets/31302548/d5e37399-e62a-4bb9-8a76-ce948e55ea7d)
手机米游社截图：
![image](https://github.com/Scighost/Starward/assets/31302548/f1477792-2696-4f83-aab5-a8ff76b54b11)

### Starward Version

0.10.6-preview.1

### Windows Version

22631.2861

### Log

<details>

```shell
[06:59:59.632] [INFO] 
Welcome to Starward v0.10.6-preview.1
System: Microsoft Windows NT 10.0.22631.0
Command Line: "C:\Program Files\Starward\app-0.10.6-preview.1\Starward.dll"

[06:59:59.679] [INFO] Starward.Services.DatabaseService
Database path is 'C:\Program Files\Starward\data'

[06:59:59.704] [INFO] Starward.Services.DatabaseService
Database version is 7, target version is 7.

[06:59:59.806] [INFO] Starward.Pages.MainPage
Select game region is hkrpg_cn

[06:59:59.821] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_cn

[07:00:00.568] [INFO] Starward.Pages.LauncherPage
Game install path hkrpg_cn: "H:\Star Rail Game"

[07:00:00.656] [INFO] Starward.Services.DownloadGameService
Local game version is "1.6.0" (gameBiz: hkrpg_cn)

[07:00:00.699] [WARN] Starward.Services.GameService
Game uninstalled path not found (hk4e_global)

[07:00:00.699] [WARN] Starward.Services.GameService
Game uninstalled path not found (hk4e_cloud)

[07:00:00.700] [WARN] Starward.Services.GameService
Game uninstalled path not found (hkrpg_global)

[07:00:00.700] [WARN] Starward.Services.GameService
Game uninstalled path not found (bh3_cn)

[07:00:00.700] [WARN] Starward.Services.GameService
Game uninstalled path not found (bh3_global)

[07:00:00.701] [WARN] Starward.Services.GameService
Game uninstalled path not found (bh3_jp)

[07:00:00.701] [WARN] Starward.Services.GameService
Game uninstalled path not found (bh3_kr)

[07:00:00.701] [WARN] Starward.Services.GameService
Game uninstalled path not found (bh3_overseas)

[07:00:00.702] [WARN] Starward.Services.GameService
Game uninstalled path not found (bh3_tw)

[07:00:01.068] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[07:00:02.076] [INFO] Starward.Services.UpdateService
Current version: "0.10.6-preview.1", latest version: "0.10.6-preview.1", ignore version: null

[07:00:44.582] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[07:00:44.586] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[07:00:44.673] [INFO] Starward.Pages.LauncherPage
Game install path hk4e_cn: "E:\Genshin Impact Game"

[07:00:44.682] [INFO] Starward.Services.DownloadGameService
Local game version is "4.3.0" (gameBiz: hk4e_cn)

[07:00:47.068] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[07:00:47.070] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_cn

[07:00:47.146] [INFO] Starward.Pages.LauncherPage
Game install path hkrpg_cn: "H:\Star Rail Game"

[07:00:47.174] [INFO] Starward.Services.DownloadGameService
Local game version is "1.6.0" (gameBiz: hkrpg_cn)

[07:01:04.065] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[07:01:04.067] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[07:01:04.154] [INFO] Starward.Pages.LauncherPage
Game install path hk4e_cn: "E:\Genshin Impact Game"

[07:01:04.186] [INFO] Starward.Services.DownloadGameService
Local game version is "4.3.0" (gameBiz: hk4e_cn)

[07:01:05.144] [INFO] Starward.Services.GameService
Start game (hk4e_cn)
path: "E:\Genshin Impact Game\YuanShen.exe"
arg: "-popupwindow -screen-fullscreen 0 -screen-height 1440 -screen-width 2560"

[07:01:05.294] [INFO] Starward.Pages.LauncherPage
Game started ("YuanShen", 5092)

[07:01:07.309] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hk4e_cn, 5092)

[07:46:03.358] [INFO] Starward.Pages.LauncherPage
Game process exited

[07:46:29.404] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[07:46:29.408] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_cn

[07:46:29.523] [INFO] Starward.Pages.LauncherPage
Game install path hkrpg_cn: "H:\Star Rail Game"

[07:46:29.532] [INFO] Starward.Services.DownloadGameService
Local game version is "1.6.0" (gameBiz: hkrpg_cn)

[07:46:30.805] [INFO] Starward.Services.GameService
Start game (hkrpg_cn)
path: "H:\Star Rail Game\StarRail.exe"
arg: ""

[07:46:30.968] [INFO] Starward.Pages.LauncherPage
Game started ("StarRail", 1148)

[07:46:32.975] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hkrpg_cn, 1148)

[09:10:18.601] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hkrpg_cn

[10:49:43.371] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[10:49:43.381] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_cn

[10:49:45.002] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[10:49:45.097] [INFO] Starward.Pages.LauncherPage
Game install path hk4e_cn: "E:\Genshin Impact Game"

[10:49:45.108] [INFO] Starward.Services.DownloadGameService
Local game version is "4.3.0" (gameBiz: hk4e_cn)

[10:49:46.266] [INFO] Starward.Services.GameService
Start game (hk4e_cn)
path: "E:\Genshin Impact Game\YuanShen.exe"
arg: "-popupwindow -screen-fullscreen 0 -screen-height 1440 -screen-width 2560"

[10:49:46.420] [INFO] Starward.Pages.LauncherPage
Game started ("YuanShen", 22216)

[10:49:48.434] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hk4e_cn, 22216)

[11:03:06.032] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_cn

[11:03:07.457] [INFO] Starward.Pages.MainPage
Navigate to "SelfQueryPage" with param hk4e_cn

[11:03:08.611] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hk4e_cn

[11:03:08.622] [INFO] Starward.Services.GameRecordService
Change region to China.

[11:03:11.947] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[11:03:11.949] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hkrpg_cn

[11:03:11.962] [INFO] Starward.Services.GameRecordService
Change region to China.

[11:03:15.640] [EROR] Starward.Pages.HoyolabToolbox.ForgottenHallPage
Refresh forgotten hall data ("hkrpg_cn", 100071852).
Starward.Core.miHoYoApiException:  (1034)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 162
   at Starward.Core.GameRecord.HyperionClient.GetForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 270
   at Starward.Services.GameRecordService.RefreshForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 447
   at Starward.Pages.HoyolabToolbox.ForgottenHallPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\ForgottenHallPage.xaml.cs:line 110

[11:10:38.231] [INFO] Starward.Pages.MainPage
Navigate to "SettingPage" with param hkrpg_cn
```

</details>

**Comment by Scighost** [comment]
仅有标题错误吗，数据获取有没有问题

**Comment by Fachep** [comment]
这个标题错误好像是只会在验证页出现的，忘却之庭/混沌回忆的数据目前没有问题。虚构叙事下下周上线，不知道到时候是否会影响

**Comment by Fachep** [comment]
这周开虚构叙事了，需要我提供个Cookie更新么

**Comment by Scighost** [comment]
不用了，如果没办法获取到虚构叙事的数据，给我 cookie 也没用。

**Comment by Fachep** [comment]
![_-455360312__b3aa926890509493f6fb18876c6b0110_-1582261082_Screenshot_2024-01-10-14-47-25-394_com mihoyo hyperion_0_wifi_0](https://github.com/Scighost/Starward/assets/31302548/eb9a524d-588c-4664-b634-c240039928eb)
米游社倒是有这东西

**Comment by Scighost** [comment]
已适配虚构叙事
