### ISSUE TITLE
[Bug] 原神页签中使用米游社工具箱深境螺旋功能获取数据异常

### ISSUE THREAD

**Issue by ruanjunhao0717** [Scighost/Starward#568]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

原神页签中使用米游社工具箱深境螺旋功能获取数据异常，获取时提示“当前帐号存在风险，暂无数据”，而在崩坏：星穹铁道页签中使用米游社工具箱忘却之庭功能获取数据依然可通过米哈游官方图像验证后继续获取数据，在此之前原神也可通过星穹铁道同方法获取数据，现原神无法通过验证获取数据，可能是米哈游原神的api改动无法访问

### Reproduction Steps

原神页签中使用米游社工具箱深境螺旋功能

### Expected Behavior

获取原神米游社深境螺旋详细数据

### Screenshots

![屏幕截图 2024-01-03 011352](https://github.com/Scighost/Starward/assets/54653814/09080f6d-eb9b-4e35-a35c-621de861bbad)
![屏幕截图 2024-01-03 011804](https://github.com/Scighost/Starward/assets/54653814/3c32f37f-3f28-4f8c-b2c4-64b27cb7be02)

### Starward Version

0.10.6-preview.1

### Windows Version

win10 22H2 19045.3803

### Log

```shell
[01:12:06.827] [INFO] 
Welcome to Starward v0.10.6-preview.1
System: Microsoft Windows NT 10.0.19045.0
Command Line: D:\Starward\app-0.10.6-preview.1\Starward.dll

[01:12:07.521] [INFO] Starward.Services.DatabaseService
Database path is 'D:\Starward'

[01:12:07.918] [INFO] Starward.Services.DatabaseService
Database version is 7, target version is 7.

[01:12:08.274] [INFO] Starward.Pages.MainPage
Select game region is hkrpg_cn

[01:12:08.290] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_cn

[01:12:09.485] [INFO] Starward.Pages.LauncherPage
Game install path hkrpg_cn: "D:\Star Rail\Game"

[01:12:09.639] [INFO] Starward.Services.DownloadGameService
Local game version is "1.6.0" (gameBiz: hkrpg_cn)

[01:12:10.571] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[01:12:11.533] [INFO] Starward.Services.UpdateService
Current version: "0.10.6-preview.1", latest version: "0.10.6-preview.1", ignore version: null

[01:12:25.417] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[01:12:25.425] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[01:12:25.530] [INFO] Starward.Pages.LauncherPage
Game install path hk4e_cn: "D:\Genshin Impact\Genshin Impact Game"

[01:12:25.550] [INFO] Starward.Services.DownloadGameService
Local game version is "4.3.0" (gameBiz: hk4e_cn)

[01:12:26.230] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_cn

[01:12:27.686] [INFO] Starward.Pages.MainPage
Navigate to "ScreenshotPage" with param hk4e_cn

[01:12:27.748] [INFO] Starward.Pages.ScreenshotPage
Screenshot folder is "D:\Genshin Impact\Genshin Impact Game\ScreenShot"

[01:12:29.605] [INFO] Starward.Pages.MainPage
Navigate to "GameSettingPage" with param hk4e_cn

[01:12:29.668] [INFO] Starward.Services.DownloadGameService
Local game version is "4.3.0" (gameBiz: hk4e_cn)

[01:12:30.181] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hk4e_cn

[01:12:30.194] [INFO] Starward.Services.GameRecordService
Change region to China.

[01:12:34.308] [EROR] Starward.Pages.HoyolabToolbox.SpiralAbyssPage
Refresh abyss data ("hk4e_cn", 502667612).
Starward.Core.miHoYoApiException:  (1034)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 162
   at Starward.Core.GameRecord.HyperionClient.GetSpiralAbyssInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 137
   at Starward.Services.GameRecordService.RefreshSpiralAbyssInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 227
   at Starward.Pages.HoyolabToolbox.SpiralAbyssPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SpiralAbyssPage.xaml.cs:line 119

[01:12:53.407] [EROR] Starward.Pages.HoyolabToolbox.SpiralAbyssPage
Refresh abyss data ("hk4e_cn", 502667612).
Starward.Core.miHoYoApiException:  (1034)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 162
   at Starward.Core.GameRecord.HyperionClient.GetSpiralAbyssInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 137
   at Starward.Services.GameRecordService.RefreshSpiralAbyssInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 227
   at Starward.Pages.HoyolabToolbox.SpiralAbyssPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SpiralAbyssPage.xaml.cs:line 119

[01:13:15.415] [EROR] Starward.Pages.HoyolabToolbox.SpiralAbyssPage
Refresh abyss data ("hk4e_cn", 502667612).
Starward.Core.miHoYoApiException:  (1034)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 162
   at Starward.Core.GameRecord.HyperionClient.GetSpiralAbyssInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 137
   at Starward.Services.GameRecordService.RefreshSpiralAbyssInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 227
   at Starward.Pages.HoyolabToolbox.SpiralAbyssPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SpiralAbyssPage.xaml.cs:line 119

[01:13:23.651] [INFO] Starward.Pages.MainPage
Navigate to "SettingPage" with param hk4e_cn

[01:13:26.337] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[01:13:27.577] [INFO] Starward.Services.UpdateService
Current version: "0.10.6-preview.1", latest version: "0.10.6-preview.1", ignore version: null

[01:13:37.604] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_cn

[01:13:39.078] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hk4e_cn

[01:13:39.097] [INFO] Starward.Services.GameRecordService
Change region to China.

[01:13:40.924] [EROR] Starward.Pages.HoyolabToolbox.SpiralAbyssPage
Refresh abyss data ("hk4e_cn", 502667612).
Starward.Core.miHoYoApiException:  (1034)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 162
   at Starward.Core.GameRecord.HyperionClient.GetSpiralAbyssInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 137
   at Starward.Services.GameRecordService.RefreshSpiralAbyssInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 227
   at Starward.Pages.HoyolabToolbox.SpiralAbyssPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SpiralAbyssPage.xaml.cs:line 119

[01:14:35.348] [INFO] Starward.Pages.MainPage
Navigate to "SelfQueryPage" with param hk4e_cn

[01:14:36.752] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hk4e_cn

[01:14:36.765] [INFO] Starward.Services.GameRecordService
Change region to China.

[01:14:37.491] [INFO] Starward.Pages.MainPage
Navigate to "SettingPage" with param hk4e_cn

[01:15:00.145] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[01:15:00.149] [INFO] Starward.Pages.MainPage
Navigate to "SettingPage" with param hkrpg_cn

[01:15:01.261] [INFO] Starward.Pages.MainPage
Navigate to "GameSettingPage" with param hkrpg_cn

[01:15:01.316] [INFO] Starward.Services.DownloadGameService
Local game version is "1.6.0" (gameBiz: hkrpg_cn)

[01:15:01.697] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hkrpg_cn

[01:15:01.709] [INFO] Starward.Services.GameRecordService
Change region to China.

[01:15:05.934] [EROR] Starward.Pages.HoyolabToolbox.ForgottenHallPage
Refresh forgotten hall data ("hkrpg_cn", 106899081).
Starward.Core.miHoYoApiException:  (1034)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 162
   at Starward.Core.GameRecord.HyperionClient.GetForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 270
   at Starward.Services.GameRecordService.RefreshForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 447
   at Starward.Pages.HoyolabToolbox.ForgottenHallPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\ForgottenHallPage.xaml.cs:line 110

[01:15:22.836] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[01:15:22.839] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hk4e_cn

[01:15:22.848] [INFO] Starward.Services.GameRecordService
Change region to China.

[01:15:25.079] [EROR] Starward.Pages.HoyolabToolbox.SpiralAbyssPage
Refresh abyss data ("hk4e_cn", 502667612).
Starward.Core.miHoYoApiException:  (1034)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 162
   at Starward.Core.GameRecord.HyperionClient.GetSpiralAbyssInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 137
   at Starward.Services.GameRecordService.RefreshSpiralAbyssInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 227
   at Starward.Pages.HoyolabToolbox.SpiralAbyssPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SpiralAbyssPage.xaml.cs:line 119

[01:19:23.763] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[01:19:23.772] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hkrpg_cn

[01:19:23.780] [INFO] Starward.Services.GameRecordService
Change region to China.

[01:22:47.135] [INFO] Starward.Pages.MainPage
Navigate to "SelfQueryPage" with param hkrpg_cn

[01:22:48.739] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hkrpg_cn

[01:22:48.748] [INFO] Starward.Services.GameRecordService
Change region to China.

[01:22:49.540] [INFO] Starward.Pages.MainPage
Navigate to "SettingPage" with param hkrpg_cn
```

**Comment by Scighost** [comment]
谢谢你的反馈，但是你的账号问题我无法帮你解决。

**Comment by ruanjunhao0717** [comment]
这个我一直都是要验证的，难道是我账号的问题吗😨

在 2024-01-03 17:29:39，Scighost ***@***.***> 写道：


谢谢你的反馈，但是你的账号问题我无法帮你解决。
