### ISSUE TITLE
[Bug] Starward的“原神-米游社工具箱-深境螺旋”的数据无法获取

### ISSUE THREAD

**Issue by living-alive** [Scighost/Starward#607]
### Checklist

- [x] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

如题，显示“账号异常”，点击“校验账号”弹出“当前账号存在风险，暂无数据”窗口且几秒后关闭。
其余功能一切正常，米游社app内未报错。
同一开发者的软件《寻空》的部分类似功能同样无法正常使用，显示“HoyolabException 5003”。

### Reproduction Steps

点击对应功能即弹出该窗口

### Expected Behavior

正常弹出验证窗口，完成后显示数据

### Screenshots

![Starward 2024-01-26 下午 4_08_24](https://github.com/Scighost/Starward/assets/63293483/1f5da3db-4013-440f-a4df-d96a21eeadc4)
![寻空 侧载版 2024-01-26 下午 4_08_55](https://github.com/Scighost/Starward/assets/63293483/bb4541f2-5b61-47e4-9e4b-93de273fc98b)

### Starward Version

0.10.7preview1

### Windows Version

26020.1000

### Log

```shell
[16:03:33.453] [INFO] 
Welcome to Starward v0.10.7-preview.1
System: Microsoft Windows NT 10.0.26020.0
Command Line: E:\download\Compressed\app-0.10.7-preview.1\Starward.dll

[16:03:33.547] [INFO] Starward.Services.DatabaseService
Database path is 'E:\download\Compressed'

[16:03:33.634] [INFO] Starward.Services.DatabaseService
Database version is 8, target version is 8.

[16:03:33.823] [INFO] Starward.Pages.MainPage
Last game region is hk4e_cn

[16:03:33.855] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[16:03:34.396] [WARN] Starward.Services.GameService
Game uninstalled path not found (hk4e_global)

[16:03:34.397] [WARN] Starward.Services.GameService
Game uninstalled path not found (hk4e_cloud)

[16:03:34.399] [WARN] Starward.Services.GameService
Game uninstalled path not found (hkrpg_global)

[16:03:34.399] [WARN] Starward.Services.GameService
Game uninstalled path not found (bh3_global)

[16:03:34.400] [WARN] Starward.Services.GameService
Game uninstalled path not found (bh3_jp)

[16:03:34.400] [WARN] Starward.Services.GameService
Game uninstalled path not found (bh3_kr)

[16:03:34.400] [WARN] Starward.Services.GameService
Game uninstalled path not found (bh3_overseas)

[16:03:34.401] [WARN] Starward.Services.GameService
Game uninstalled path not found (bh3_tw)

[16:03:35.296] [WARN] Starward.Services.GameService
Game uninstalled path not found (hk4e_global)

[16:03:35.297] [WARN] Starward.Services.GameService
Game uninstalled path not found (hk4e_cloud)

[16:03:35.297] [WARN] Starward.Services.GameService
Game uninstalled path not found (hkrpg_global)

[16:03:35.298] [WARN] Starward.Services.GameService
Game uninstalled path not found (bh3_global)

[16:03:35.299] [WARN] Starward.Services.GameService
Game uninstalled path not found (bh3_jp)

[16:03:35.299] [WARN] Starward.Services.GameService
Game uninstalled path not found (bh3_kr)

[16:03:35.299] [WARN] Starward.Services.GameService
Game uninstalled path not found (bh3_overseas)

[16:03:35.300] [WARN] Starward.Services.GameService
Game uninstalled path not found (bh3_tw)

[16:03:35.345] [INFO] Starward.Pages.LauncherPage
Game install path hk4e_cn: "E:\Genshin Impact\Genshin Impact Game"

[16:03:35.396] [INFO] Starward.Services.DownloadGameService
Local game version is "4.3.0" (gameBiz: hk4e_cn)

[16:03:37.341] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[16:03:37.720] [INFO] Starward.Services.UpdateService
Current version: "0.10.7-preview.1", latest version: "0.10.7-preview.1", ignore version: null

[16:03:38.907] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hk4e_cn

[16:03:38.933] [INFO] Starward.Services.GameRecordService
Change region to China.

[16:03:41.994] [EROR] Starward.Pages.HoyolabToolbox.SpiralAbyssPage
Refresh abyss data ("hk4e_cn", 188936862).
Starward.Core.miHoYoApiException:  (1034)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetSpiralAbyssInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 138
   at Starward.Services.GameRecordService.RefreshSpiralAbyssInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 212
   at Starward.Pages.HoyolabToolbox.SpiralAbyssPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SpiralAbyssPage.xaml.cs:line 120

[16:08:09.698] [EROR] Starward.Pages.HoyolabToolbox.SpiralAbyssPage
Refresh abyss data ("hk4e_cn", 188936862).
Starward.Core.miHoYoApiException:  (1034)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetSpiralAbyssInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 138
   at Starward.Services.GameRecordService.RefreshSpiralAbyssInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 212
   at Starward.Pages.HoyolabToolbox.SpiralAbyssPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SpiralAbyssPage.xaml.cs:line 120

[16:08:19.411] [EROR] Starward.Pages.HoyolabToolbox.SpiralAbyssPage
Refresh abyss data ("hk4e_cn", 188936862).
Starward.Core.miHoYoApiException:  (1034)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetSpiralAbyssInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 138
   at Starward.Services.GameRecordService.RefreshSpiralAbyssInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 212
   at Starward.Pages.HoyolabToolbox.SpiralAbyssPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SpiralAbyssPage.xaml.cs:line 120

[16:09:17.565] [INFO] Starward.Pages.MainPage
Change game region to StarRail

[16:09:17.577] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hkrpg_cn

[16:09:17.586] [INFO] Starward.Services.GameRecordService
Change region to China.

[16:09:23.258] [EROR] Starward.Pages.HoyolabToolbox.ForgottenHallPage
Refresh forgotten hall data ("hkrpg_cn", 102859128).
Starward.Core.miHoYoApiException:  (1034)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 271
   at Starward.Services.GameRecordService.RefreshForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 432
   at Starward.Pages.HoyolabToolbox.ForgottenHallPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\ForgottenHallPage.xaml.cs:line 111

[16:14:49.954] [INFO] Starward.Pages.MainPage
Change game region to GenshinImpact

[16:14:49.965] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hk4e_cn

[16:14:49.975] [INFO] Starward.Services.GameRecordService
Change region to China.

[16:14:53.163] [EROR] Starward.Pages.HoyolabToolbox.SpiralAbyssPage
Refresh abyss data ("hk4e_cn", 188936862).
Starward.Core.miHoYoApiException:  (1034)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetSpiralAbyssInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 138
   at Starward.Services.GameRecordService.RefreshSpiralAbyssInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 212
   at Starward.Pages.HoyolabToolbox.SpiralAbyssPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SpiralAbyssPage.xaml.cs:line 120

[16:19:12.405] [EROR] Starward.Pages.HoyolabToolbox.SpiralAbyssPage
Refresh abyss data ("hk4e_cn", 188936862).
Starward.Core.miHoYoApiException:  (1034)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetSpiralAbyssInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 138
   at Starward.Services.GameRecordService.RefreshSpiralAbyssInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 212
   at Starward.Pages.HoyolabToolbox.SpiralAbyssPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SpiralAbyssPage.xaml.cs:line 120
```

**Comment by Scighost** [comment]
很遗憾，米游社账号的问题我没有办法帮你解决，只能建议你清理缓存后重新登录。

**Comment by lijian12345** [comment]
> 很遗憾，米游社账号的问题我没有办法帮你解决，只能建议你清理缓存后重新登录。

我也出现了这个问题，而且星铁的数据能获取，原神不能😂清楚缓存重新登录也不行

**Comment by zhuoxin-lzk** [comment]
> > 很遗憾，米游社账号的问题我没有办法帮你解决，只能建议你清理缓存后重新登录。
> 
> 我也出现了这个问题，而且星铁的数据能获取，原神不能😂清除缓存重新登录也不行

+1，我也遇到了，从一两周前开始，清理浏览器缓存也一样不行

**Comment by lijian12345** [comment]
> > > 很遗憾，米游社账号的问题我没有办法帮你解决，只能建议你清理缓存后重新登录。
> > 
> > 
> > 我也出现了这个问题，而且星铁的数据能获取，原神不能😂清除缓存重新登录也不行
> 
> +1，我也遇到了，从一两周前开始，清理浏览器缓存也一样不行

感觉有可能是接口改了，或者风控策略改了😂

**Comment by DalaSketchi** [comment]
我也遇到了

**Comment by Sunnyjiayou** [comment]
有人解决了吗
