### ISSUE TITLE
[Bug] 在预下载时与Microsoft PowerToys的某些组件/功能有冲突

### ISSUE THREAD

**Issue by Emm-GOOD** [Scighost/Starward#620]
### Checklist

- [x] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

在预下载时如果不关闭power toys下载速度会非常缓慢大约小于0.2MB/s

### Reproduction Steps

我的电脑设置自动启动power toys，启动电脑后没有任何操作直接打开starward，打开启动器之后预下载有可能会无法下载，有可能下载速度非常慢，此时power toys弹窗

### Screenshots

![image](https://github.com/Scighost/Starward/assets/154535858/332f70d1-092e-4931-9ebe-8facbd04487a)

### Starward Version

0.10.7-preview.2

### Windows Version

19045.3930

### Log

```shell
[07:48:16.568] [INFO] 
Welcome to Starward v0.10.7-preview.2
System: Microsoft Windows NT 10.0.19045.0
Command Line: E:\Starward_Portable_0.9.1_x64\Starward\app-0.10.7-preview.2\Starward.dll download --biz hk4e_cn --loc "F:\Genshin Impact Game" --lang 3

[07:48:16.714] [INFO] Starward.Services.DatabaseService
Database path is 'E:\mihoyo'

[07:48:16.832] [INFO] Starward.Services.DatabaseService
Database version is 8, target version is 8.

[07:48:17.966] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Initialize install game service
biz: hk4e_cn
path: "F:\Genshin Impact Game"
lang: Chinese, English
repair: False
reinstall: False

[07:48:18.073] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Start install game, skipVerify: False

[07:48:18.077] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Prepare for download.

[07:48:18.113] [INFO] Starward.Services.GameResourceService
Local game version is "4.3.0" (gameBiz: hk4e_cn)

[07:49:01.446] [EROR] Starward.Services.InstallGame.GenshinInstallGameService
Install game error.
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean, Byte[], CancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions, HttpRequestMessage, Boolean, Stream, CancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions, HttpRequestMessage, Boolean, Stream, CancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(QueueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage, Boolean, Boolean, CancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage, HttpCompletionOption, CancellationTokenSource, Boolean, CancellationTokenSource, CancellationToken)
   at Starward.Core.Launcher.LauncherClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\Launcher\LauncherClient.cs:line 27
   at Starward.Core.Launcher.LauncherClient.GetLauncherGameResourceAsync(GameBiz biz, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\Launcher\LauncherClient.cs:line 104
   at Starward.Services.GameResourceService.GetGameResourceAsync(GameBiz biz) in D:\a\Starward\Starward\src\Starward\Services\GameResourceService.cs:line 144
   at Starward.Services.InstallGame.InstallGameService.PrepareForDownloadAsync() in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 295
   at Starward.Services.InstallGame.InstallGameService.StartAsync(Boolean skipVerify) in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 224

[07:49:47.000] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Start install game, skipVerify: False

[07:49:47.000] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Prepare for download.

[07:49:47.007] [INFO] Starward.Services.GameResourceService
Local game version is "4.3.0" (gameBiz: hk4e_cn)
```

### Additional Context

前几个版本也有此问题
power toys版本：0.76.2
刚更新完0.77.0还没测试是否能复现该问题，等待星穹铁道更新2.0时会有更多补充

**Comment by Emm-GOOD** [comment]
了解更多里面的链接：https://learn.microsoft.com/zh-cn/windows/powertoys/administrator

**Comment by Scighost** [comment]
没有特别的原因，单纯是因为你的网络不好。
