### ISSUE TITLE
[Bug] 程序选择网络连接方式的逻辑不正确

### ISSUE THREAD

**Issue by Xionghaizi001** [Scighost/Starward#642]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

Starward支持国服与国际服的游戏启动和资源更新，但在中国国内更新中国服仍然使用了代理，导致启动或关闭代理软件时，starward出现网络异常。并且由于预下载和更新文件时仍然使用了代理，导致了不必要的流量消耗。

### Reproduction Steps

1. 启动代理软件
2. 设置连接方式为系统代理
3. 启动预下载

### Expected Behavior

自动选择连接方式，或用户手动选择是否启用代理/启用IE代理/启用自定义代理

### Starward Version

0.11.0

### Windows Version

19045.3693

### Log

```shell
[18:20:50.033] [INFO] 
Welcome to Starward v0.11.0
System: Microsoft Windows NT 10.0.19045.0
Command Line: D:\Programs\Starward\app-0.11.0\Starward.dll download --biz hkrpg_cn --loc "D:\0\Games\Star Rail\Game" --lang 1

[18:20:50.065] [INFO] Starward.Services.DatabaseService
Database path is 'D:\Data\Starward'

[18:20:50.091] [INFO] Starward.Services.DatabaseService
Database version is 8, target version is 8.

[18:20:50.342] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
Initialize install game service
biz: hkrpg_cn
path: "D:\0\Games\Star Rail\Game"
lang: Chinese
repair: False
reinstall: False

[18:20:50.370] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
Start install game, skipVerify: False

[18:20:50.373] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
Prepare for download.

[18:20:50.788] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
Pre install game.

[18:20:50.793] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
Request head: "https://autopatchcn.bhsr.com/client/hkrpg_cn/33/game_1.6.0_2.0.0_hdiff_mT4gkop1jCKyVuD0.zip"

[18:20:50.793] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
Request head: "https://autopatchcn.bhsr.com/client/hkrpg_cn/33/zh-cn_1.6.0_2.0.0_hdiff_YCNdkg2V5MjX8v3B.zip"

[18:20:51.094] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
Start download files.

[18:20:51.094] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
2 files need to download.

[18:20:51.097] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
Download: FileName "game_1.6.0_2.0.0_hdiff_mT4gkop1jCKyVuD0.zip", Url "https://autopatchcn.bhsr.com/client/hkrpg_cn/33/game_1.6.0_2.0.0_hdiff_mT4gkop1jCKyVuD0.zip"

[18:20:51.097] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
Download: FileName "zh-cn_1.6.0_2.0.0_hdiff_YCNdkg2V5MjX8v3B.zip", Url "https://autopatchcn.bhsr.com/client/hkrpg_cn/33/zh-cn_1.6.0_2.0.0_hdiff_YCNdkg2V5MjX8v3B.zip"

[18:21:00.240] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
Download Successfully: FileName "zh-cn_1.6.0_2.0.0_hdiff_YCNdkg2V5MjX8v3B.zip"

[18:32:37.868] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
Start install game, skipVerify: False

[18:32:37.877] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
Start download files.

[18:32:37.877] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
2 files need to download.

[18:32:37.877] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
Download: FileName "game_1.6.0_2.0.0_hdiff_mT4gkop1jCKyVuD0.zip", Url "https://autopatchcn.bhsr.com/client/hkrpg_cn/33/game_1.6.0_2.0.0_hdiff_mT4gkop1jCKyVuD0.zip"

[18:32:43.350] [EROR] Starward.Services.InstallGame.StarRailInstallGameService
Install game error.
System.IO.IOException: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
 ---> System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError, CancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1)
   at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1, CancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken, Int32)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1, CancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1, CancellationToken)
   at Starward.Services.InstallGame.InstallGameService.DownloadFileAsync(DownloadFileTask task, CancellationToken cancellationToken, Boolean noTmp) in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 843
   at Starward.Services.InstallGame.InstallGameService.<>c__DisplayClass74_0.<<DownloadAsync>b__2>d.MoveNext() in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 572
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__53`1.<<ForEachAsync>b__53_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Starward.Services.InstallGame.InstallGameService.DownloadAsync(CancellationToken cancellationToken, Boolean noTmp) in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 566
   at Starward.Services.InstallGame.InstallGameService.StartAsync(Boolean skipVerify) in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 241

[18:32:45.535] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
Start install game, skipVerify: False

[18:32:45.537] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
Start download files.

[18:32:45.537] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
2 files need to download.

[18:32:45.539] [INFO] Starward.Services.InstallGame.StarRailInstallGameService
Download: FileName "game_1.6.0_2.0.0_hdiff_mT4gkop1jCKyVuD0.zip", Url "https://autopatchcn.bhsr.com/client/hkrpg_cn/33/game_1.6.0_2.0.0_hdiff_mT4gkop1jCKyVuD0.zip"

[18:32:47.575] [EROR] Starward.Services.InstallGame.StarRailInstallGameService
Install game error.
System.Net.Http.HttpRequestException: 由于目标计算机积极拒绝，无法连接。 (127.0.0.1:18868)
 ---> System.Net.Sockets.SocketException (10061): 由于目标计算机积极拒绝，无法连接。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError, CancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs, ValueTask, CancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String, Int32, HttpRequestMessage, Boolean, CancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String, Int32, HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage, Boolean, Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage, Boolean, Boolean, CancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage, HttpCompletionOption, CancellationTokenSource, Boolean, CancellationTokenSource, CancellationToken)
   at Starward.Services.InstallGame.InstallGameService.DownloadFileAsync(DownloadFileTask task, CancellationToken cancellationToken, Boolean noTmp) in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 838
   at Starward.Services.InstallGame.InstallGameService.<>c__DisplayClass74_0.<<DownloadAsync>b__2>d.MoveNext() in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 572
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__53`1.<<ForEachAsync>b__53_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Starward.Services.InstallGame.InstallGameService.DownloadAsync(CancellationToken cancellationToken, Boolean noTmp) in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 566
   at Starward.Services.InstallGame.InstallGameService.StartAsync(Boolean skipVerify) in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 241
```

**Comment by Scighost** [comment]
新年好

.NET 只会在首次连接时使用系统代理，并且后续不会响应系统代理的更改。如果有国际服资源下载的需求，请修改系统代理后重启软件。
