### ISSUE TITLE
[Bug] 工具箱里星穹铁道无法更新忘却之庭和虚构叙事的战绩

### ISSUE THREAD

**Issue by dfdfwff** [Scighost/Starward#650]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

工具箱里能加载开拓月历，然后其他三个功能好像都不行，显示“账号异常10035”

### Reproduction Steps

就是打开工具箱加载不出来，然后我尝试了删除账号重新登录也不行

### Screenshots

![_LQ(S$EW)5M}{W`UBY%NDL0](https://github.com/Scighost/Starward/assets/102846037/b3745e28-c219-4a68-a27b-15be265e9f95)

### Starward Version

0.11.0

### Windows Version

22621.1344

### Log

```shell
[11:03:34.682] [EROR] Starward.Pages.HoyolabToolbox.PureFictionPage
Refresh pure fiction data ("hkrpg_cn", 100412421).
Starward.Core.miHoYoApiException:  (10035)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetPureFictionInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 296
   at Starward.Services.GameRecordService.RefreshPureFictionInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 496
   at Starward.Pages.HoyolabToolbox.PureFictionPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\PureFictionPage.xaml.cs:line 111

[11:03:36.566] [EROR] Starward.Pages.HoyolabToolbox.ForgottenHallPage
Refresh forgotten hall data ("hkrpg_cn", 100412421).
Starward.Core.miHoYoApiException:  (10035)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 271
   at Starward.Services.GameRecordService.RefreshForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 432
   at Starward.Pages.HoyolabToolbox.ForgottenHallPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\ForgottenHallPage.xaml.cs:line 111

[11:03:38.091] [EROR] Starward.Pages.HoyolabToolbox.ForgottenHallPage
Refresh forgotten hall data ("hkrpg_cn", 100412421).
Starward.Core.miHoYoApiException:  (10035)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 271
   at Starward.Services.GameRecordService.RefreshForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 432
   at Starward.Pages.HoyolabToolbox.ForgottenHallPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\ForgottenHallPage.xaml.cs:line 111

[11:03:39.701] [EROR] Starward.Pages.HoyolabToolbox.PureFictionPage
Refresh pure fiction data ("hkrpg_cn", 100412421).
Starward.Core.miHoYoApiException:  (10035)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetPureFictionInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 296
   at Starward.Services.GameRecordService.RefreshPureFictionInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 496
   at Starward.Pages.HoyolabToolbox.PureFictionPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\PureFictionPage.xaml.cs:line 111

[11:03:41.404] [EROR] Starward.Pages.HoyolabToolbox.PureFictionPage
Refresh pure fiction data ("hkrpg_cn", 100412421).
Starward.Core.miHoYoApiException:  (10035)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetPureFictionInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 296
   at Starward.Services.GameRecordService.RefreshPureFictionInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 496
   at Starward.Pages.HoyolabToolbox.PureFictionPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\PureFictionPage.xaml.cs:line 111
```

**Comment by yecongjia** [comment]
顶，我也是这个问题。

**Comment by teammitsuha** [comment]
加1，原神有验证按钮但点进去无法验证（通过hutao的实时便笺可以验证），铁道无验证按钮

**Comment by ahshy1996** [comment]
+1

**Comment by raging-flames** [comment]
加一

**Comment by tony3071** [comment]
類似的問題
但我有忘卻資料沒有虛構的 也沒有報錯(國際服)
![image](https://github.com/Scighost/Starward/assets/31728017/0f29d943-dfd0-439e-a58c-409bacc898a9)
![image](https://github.com/Scighost/Starward/assets/31728017/55b89c2c-4be3-424b-bcae-a8c76e81c68e)

**Comment by dfdfwff** [comment]
> 類似的問題 但我有忘卻資料沒有虛構的 也沒有報錯(國際服) ![image](https://private-user-images.githubusercontent.com/31728017/305712632-0f29d943-dfd0-439e-a58c-409bacc898a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTk1NzEsIm5iZiI6MTcwODMxOTI3MSwicGF0aCI6Ii8zMTcyODAxNy8zMDU3MTI2MzItMGYyOWQ5NDMtZGZkMC00MzllLWE1OGMtNDA5YmFjYzg5OGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDA1MDc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1YWU3YmU1NmMyOTFkYjhiMGViMTQzZTg0NDY5MDkyOGNkMTcwYjliNTQ2OTM5YmYyYTBmMThlMzgzNzk0OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6QpZWR_GqrQDZQKfGdiCxHcJGwL129MeI0bqZGNraU4) ![image](https://private-user-images.githubusercontent.com/31728017/305712656-55b89c2c-4be3-424b-bcae-a8c76e81c68e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTk1NzEsIm5iZiI6MTcwODMxOTI3MSwicGF0aCI6Ii8zMTcyODAxNy8zMDU3MTI2NTYtNTViODljMmMtNGJlMy00MjRiLWJjYWUtYThjNzZlODFjNjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDA1MDc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNDA0ZWUwNjI0MDMzMmU3M2E3ZmQ4MmQ0ZWFkMWM0ZDBhM2M3MTFjYjJkZjA0MmJjNDg5Njg2NmI1YjdhMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kFVyQQKUY8At2Vx4xqPQa4RT331pdODxKI3HfKRmIJw)



> 類似的問題 但我有忘卻資料沒有虛構的 也沒有報錯(國際服) ![image](https://private-user-images.githubusercontent.com/31728017/305712632-0f29d943-dfd0-439e-a58c-409bacc898a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTk1NzEsIm5iZiI6MTcwODMxOTI3MSwicGF0aCI6Ii8zMTcyODAxNy8zMDU3MTI2MzItMGYyOWQ5NDMtZGZkMC00MzllLWE1OGMtNDA5YmFjYzg5OGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDA1MDc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1YWU3YmU1NmMyOTFkYjhiMGViMTQzZTg0NDY5MDkyOGNkMTcwYjliNTQ2OTM5YmYyYTBmMThlMzgzNzk0OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6QpZWR_GqrQDZQKfGdiCxHcJGwL129MeI0bqZGNraU4) ![image](https://private-user-images.githubusercontent.com/31728017/305712656-55b89c2c-4be3-424b-bcae-a8c76e81c68e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTk1NzEsIm5iZiI6MTcwODMxOTI3MSwicGF0aCI6Ii8zMTcyODAxNy8zMDU3MTI2NTYtNTViODljMmMtNGJlMy00MjRiLWJjYWUtYThjNzZlODFjNjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDA1MDc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNDA0ZWUwNjI0MDMzMmU3M2E3ZmQ4MmQ0ZWFkMWM0ZDBhM2M3MTFjYjJkZjA0MmJjNDg5Njg2NmI1YjdhMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kFVyQQKUY8At2Vx4xqPQa4RT331pdODxKI3HfKRmIJw)

请问你的模拟宇宙加载的了吗，我的模拟宇宙也没有

**Comment by Scighost** [comment]
参考 #704
