### ISSUE TITLE
[Question] 使用starward的修复模式安装原神官服时报错

### ISSUE THREAD

**Issue by Lu-AO** [Scighost/Starward#656]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

未知错误： Could not find a part of the path 'C:\Games\GenshinImpact\YuanShen_Data\Native\Data\Metadata\global-metadata.dat'.

### Starward Version

0.11.0

### Windows Version

win11 23H2

### Log

```shell
[23:30:15.813] [EROR] Starward.Services.InstallGame.GenshinInstallGameService
Install game error.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Games\GenshinImpact\YuanShen_Data\Native\Data\Metadata\global-metadata.dat'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String, FileMode, FileAccess, FileShare, FileOptions)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1 )
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.FileStream..ctor(String, FileMode, FileAccess, FileShare, Int32, FileOptions, Int64)
   at System.IO.File.Open(String, FileMode)
   at Starward.Services.InstallGame.InstallGameService.DownloadFileAsync(DownloadFileTask task, CancellationToken cancellationToken, Boolean noTmp) in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 827
   at Starward.Services.InstallGame.InstallGameService.<>c__DisplayClass74_0.<<DownloadAsync>b__2>d.MoveNext() in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 572
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__53`1.<<ForEachAsync>b__53_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Starward.Services.InstallGame.InstallGameService.DownloadAsync(CancellationToken cancellationToken, Boolean noTmp) in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 566
   at Starward.Services.InstallGame.InstallGameService.StartAsync(Boolean skipVerify) in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 241
```

**Comment by Scighost** [comment]
新年好，感谢你的反馈
