### ISSUE TITLE
[Bug] Records import

### ISSUE THREAD

**Issue by GhostVPN1** [Scighost/Starward#691]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

After i update the gacha i get extra ??? 
Log and cache delete dont helps

### Reproduction Steps

Gacha update 

### Screenshots

![image](https://github.com/Scighost/Starward/assets/104172787/b3a208c3-7d89-46bd-b018-d2013a4a7953)

### Starward Version

0.11.1

### Windows Version

Latest

### Log

```shell
[23:17:41.508] [INFO] 
Welcome to Starward v0.11.1
System: Microsoft Windows NT 10.0.22631.0
Command Line: E:\Starward_Portable_0.10.4_x64\Starward\app-0.11.1\Starward.dll

[23:17:41.530] [INFO] Starward.Services.DatabaseService
Database path is 'E:\Starward_Portable_0.10.4_x64\Starward'

[23:17:41.547] [INFO] Starward.Services.DatabaseService
Database version is 8, target version is 8.

[23:17:41.593] [INFO] Starward.Pages.MainPage
Last game region is hkrpg_global

[23:17:41.598] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_global

[23:17:41.983] [INFO] Starward.Pages.LauncherPage
Game install path of hkrpg_global: "E:\Star Rail\Games"

[23:17:42.009] [INFO] Starward.Pages.LauncherPage
Acutal version and gamebiz of hkrpg_global is "2.0.0", None.

[23:17:43.118] [INFO] Starward.Services.UpdateService
Start to check update (Preview: False, Arch: X64)

[23:17:43.483] [INFO] Starward.Services.UpdateService
Current version: "0.11.1", latest version: "0.11.1", ignore version: null

[23:17:51.349] [EROR] Starward.Pages.Setting.FileSettingPage
Delete folder '"C:\Users\wawie\AppData\Local\Starward\log"'
System.IO.IOException: The process cannot access the file 'Starward_240308_231741.log' because it is being used by another process.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String, WIN32_FIND_DATA&, Boolean)
   at System.IO.FileSystem.RemoveDirectory(String, Boolean)
   at Starward.Pages.Setting.FileSettingPage.<>c__DisplayClass20_0.<DeleteFolderAsync>b__0() in D:\a\Starward\Starward\src\Starward\Pages\Setting\FileSettingPage.xaml.cs:line 368

[23:17:53.257] [EROR] Starward.Pages.Setting.FileSettingPage
Delete folder '"C:\Users\wawie\AppData\Local\Starward\log"'
System.IO.IOException: The process cannot access the file 'Starward_240308_231741.log' because it is being used by another process.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String, WIN32_FIND_DATA&, Boolean)
   at System.IO.FileSystem.RemoveDirectory(String, Boolean)
   at Starward.Pages.Setting.FileSettingPage.<>c__DisplayClass20_0.<DeleteFolderAsync>b__0() in D:\a\Starward\Starward\src\Starward\Pages\Setting\FileSettingPage.xaml.cs:line 368

[23:17:53.843] [EROR] Starward.Pages.Setting.FileSettingPage
Delete folder '"C:\Users\wawie\AppData\Local\Starward\log"'
System.IO.IOException: The process cannot access the file 'Starward_240308_231741.log' because it is being used by another process.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String, WIN32_FIND_DATA&, Boolean)
   at System.IO.FileSystem.RemoveDirectory(String, Boolean)
   at Starward.Pages.Setting.FileSettingPage.<>c__DisplayClass20_0.<DeleteFolderAsync>b__0() in D:\a\Starward\Starward\src\Starward\Pages\Setting\FileSettingPage.xaml.cs:line 368

[23:17:54.212] [EROR] Starward.Pages.Setting.FileSettingPage
Delete folder '"C:\Users\wawie\AppData\Local\Starward\log"'
System.IO.IOException: The process cannot access the file 'Starward_240308_231741.log' because it is being used by another process.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String, WIN32_FIND_DATA&, Boolean)
   at System.IO.FileSystem.RemoveDirectory(String, Boolean)
   at Starward.Pages.Setting.FileSettingPage.<>c__DisplayClass20_0.<DeleteFolderAsync>b__0() in D:\a\Starward\Starward\src\Starward\Pages\Setting\FileSettingPage.xaml.cs:line 368

[23:17:54.437] [EROR] Starward.Pages.Setting.FileSettingPage
Delete folder '"C:\Users\wawie\AppData\Local\Starward\log"'
System.IO.IOException: The process cannot access the file 'Starward_240308_231741.log' because it is being used by another process.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String, WIN32_FIND_DATA&, Boolean)
   at System.IO.FileSystem.RemoveDirectory(String, Boolean)
   at Starward.Pages.Setting.FileSettingPage.<>c__DisplayClass20_0.<DeleteFolderAsync>b__0() in D:\a\Starward\Starward\src\Starward\Pages\Setting\FileSettingPage.xaml.cs:line 368

[23:17:54.602] [EROR] Starward.Pages.Setting.FileSettingPage
Delete folder '"C:\Users\wawie\AppData\Local\Starward\log"'
System.IO.IOException: The process cannot access the file 'Starward_240308_231741.log' because it is being used by another process.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String, WIN32_FIND_DATA&, Boolean)
   at System.IO.FileSystem.RemoveDirectory(String, Boolean)
   at Starward.Pages.Setting.FileSettingPage.<>c__DisplayClass20_0.<DeleteFolderAsync>b__0() in D:\a\Starward\Starward\src\Starward\Pages\Setting\FileSettingPage.xaml.cs:line 368

[23:17:54.780] [EROR] Starward.Pages.Setting.FileSettingPage
Delete folder '"C:\Users\wawie\AppData\Local\Starward\log"'
System.IO.IOException: The process cannot access the file 'Starward_240308_231741.log' because it is being used by another process.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String, WIN32_FIND_DATA&, Boolean)
   at System.IO.FileSystem.RemoveDirectory(String, Boolean)
   at Starward.Pages.Setting.FileSettingPage.<>c__DisplayClass20_0.<DeleteFolderAsync>b__0() in D:\a\Starward\Starward\src\Starward\Pages\Setting\FileSettingPage.xaml.cs:line 368

[23:17:54.958] [EROR] Starward.Pages.Setting.FileSettingPage
Delete folder '"C:\Users\wawie\AppData\Local\Starward\log"'
System.IO.IOException: The process cannot access the file 'Starward_240308_231741.log' because it is being used by another process.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String, WIN32_FIND_DATA&, Boolean)
   at System.IO.FileSystem.RemoveDirectory(String, Boolean)
   at Starward.Pages.Setting.FileSettingPage.<>c__DisplayClass20_0.<DeleteFolderAsync>b__0() in D:\a\Starward\Starward\src\Starward\Pages\Setting\FileSettingPage.xaml.cs:line 368

[23:17:55.315] [EROR] Starward.Pages.Setting.FileSettingPage
Delete folder '"C:\Users\wawie\AppData\Local\Starward\log"'
System.IO.IOException: The process cannot access the file 'Starward_240308_231741.log' because it is being used by another process.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String, WIN32_FIND_DATA&, Boolean)
   at System.IO.FileSystem.RemoveDirectory(String, Boolean)
   at Starward.Pages.Setting.FileSettingPage.<>c__DisplayClass20_0.<DeleteFolderAsync>b__0() in D:\a\Starward\Starward\src\Starward\Pages\Setting\FileSettingPage.xaml.cs:line 368

[23:17:55.515] [EROR] Starward.Pages.Setting.FileSettingPage
Delete folder '"C:\Users\wawie\AppData\Local\Starward\log"'
System.IO.IOException: The process cannot access the file 'Starward_240308_231741.log' because it is being used by another process.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String, WIN32_FIND_DATA&, Boolean)
   at System.IO.FileSystem.RemoveDirectory(String, Boolean)
   at Starward.Pages.Setting.FileSettingPage.<>c__DisplayClass20_0.<DeleteFolderAsync>b__0() in D:\a\Starward\Starward\src\Starward\Pages\Setting\FileSettingPage.xaml.cs:line 368

[23:17:55.705] [EROR] Starward.Pages.Setting.FileSettingPage
Delete folder '"C:\Users\wawie\AppData\Local\Starward\log"'
System.IO.IOException: The process cannot access the file 'Starward_240308_231741.log' because it is being used by another process.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String, WIN32_FIND_DATA&, Boolean)
   at System.IO.FileSystem.RemoveDirectory(String, Boolean)
   at Starward.Pages.Setting.FileSettingPage.<>c__DisplayClass20_0.<DeleteFolderAsync>b__0() in D:\a\Starward\Starward\src\Starward\Pages\Setting\FileSettingPage.xaml.cs:line 368

[23:17:55.904] [EROR] Starward.Pages.Setting.FileSettingPage
Delete folder '"C:\Users\wawie\AppData\Local\Starward\log"'
System.IO.IOException: The process cannot access the file 'Starward_240308_231741.log' because it is being used by another process.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String, WIN32_FIND_DATA&, Boolean)
   at Starward.Pages.Setting.FileSettingPage.<>c__DisplayClass20_0.<DeleteFolderAsync>b__0() in D:\a\Starward\Starward\src\Starward\Pages\Setting\FileSettingPage.xaml.cs:line 368

[23:17:56.102] [EROR] Starward.Pages.Setting.FileSettingPage
Delete folder '"C:\Users\wawie\AppData\Local\Starward\log"'
System.IO.IOException: The process cannot access the file 'Starward_240308_231741.log' because it is being used by another process.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String, WIN32_FIND_DATA&, Boolean)
   at Starward.Pages.Setting.FileSettingPage.<>c__DisplayClass20_0.<DeleteFolderAsync>b__0() in D:\a\Starward\Starward\src\Starward\Pages\Setting\FileSettingPage.xaml.cs:line 368

[23:18:06.981] [INFO] Starward.Pages.MainPage
Last game region is hkrpg_global

[23:18:06.982] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_global

[23:18:07.223] [INFO] Starward.Pages.LauncherPage
Game install path of hkrpg_global: "E:\Star Rail\Games"

[23:18:07.229] [INFO] Starward.Pages.LauncherPage
Acutal version and gamebiz of hkrpg_global is "2.0.0", None.

[23:18:08.367] [INFO] Starward.Services.UpdateService
Start to check update (Preview: False, Arch: X64)

[23:18:08.487] [INFO] Starward.Services.UpdateService
Current version: "0.11.1", latest version: "0.11.1", ignore version: null

[23:18:09.482] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hkrpg_global

[23:18:30.171] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 714607074 is 0

[23:18:36.931] [INFO] Starward.Pages.MainPage
Change game region to GenshinImpact

[23:18:36.932] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_global

[23:18:41.152] [INFO] Starward.Services.Gacha.GenshinGachaService
Last gacha log id of uid
```

**Comment by Scighost** [comment]
This is the number of times you have pull but have not yet obtained 5-star item.

**Comment by GhostVPN1** [comment]
> This is the number of times you have pull but have not yet obtained 5-star item.

Ye, but is that supposed to show in the "item list"?
