### ISSUE TITLE
游戏时间统计错误-Game time tracking error.

### ISSUE THREAD

**Issue by Sakura1145** [Scighost/Starward#694]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

![ea418cae1829af26e5245aa157c43d96](https://github.com/Scighost/Starward/assets/137955819/49f41f53-55c4-45c1-9239-f08f332491a2)
如图所示，崩坏：星穹铁道游戏本日时间大于本周和本月时间，且发现时为当日（2024年3月11日）13:00，刷新无效，其他游戏时间正常
As shown in the image, for the game "Honkai: Star Rail", today's playtime exceeds the playtime of this week and this month. This 
phenomenon was noticed at 13:00 today(3/11/2024), and refreshing did not resolve the issue. Playtime for other games appears normal.

### Reproduction Steps

暂未发现Bug复现方法或步骤
No method or steps for reproducing the bug have been found yet.

### Screenshots

![ea418cae1829af26e5245aa157c43d96](https://github.com/Scighost/Starward/assets/137955819/19553afd-4a3e-4602-aeb9-4a17c3d5e0f7)
![image](https://github.com/Scighost/Starward/assets/137955819/66a1aea6-679f-4c7e-b42a-5ba0ebb1773d)
![image](https://github.com/Scighost/Starward/assets/137955819/9937b01c-34c0-4e0f-8020-f30695868db8)

### Starward Version

0.11.1

### Windows Version

22631.3235

### Log

```shell
下面是可能的事件日志
Below is a possible relevant log.
Originate From: Starward_240310_113423.log
[16:31:01.945] [EROR] Starward.Pages.LauncherPage
Game notices alert
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: NotTimeValid
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean, Byte[], CancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions, HttpRequestMessage, Boolean, Stream, CancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions, HttpRequestMessage, Boolean, Stream, CancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(QueueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage, Boolean, Boolean, CancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage, HttpCompletionOption, CancellationTokenSource, Boolean, CancellationTokenSource, CancellationToken)
   at Starward.Core.Launcher.LauncherClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\Launcher\LauncherClient.cs:line 27
   at Starward.Core.Launcher.LauncherClient.IsNoticesAlertAsync(GameBiz biz, Int64 uid, String lang, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\Launcher\LauncherClient.cs:line 152
   at Starward.Services.LauncherContentService.IsNoticesAlertAsync(GameBiz gameBiz, Int64 uid, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\LauncherContentService.cs:line 60
   at Starward.Pages.LauncherPage.UpdateGameNoticesAlertAsync() in D:\a\Starward\Starward\src\Starward\Pages\LauncherPage.xaml.cs:line 335
```

### Additional Context

于昨日16:00左右更改过系统时间至2019年3月10日，但很快改回时间，期间不确定是否打开过游戏。
The system time was changed to March 10, 2019, around 16:00 yesterday, but it was quickly changed back. It is uncertain whether any games were opened during that time.

**Comment by Scighost** [comment]
谢谢你的反馈，这个问题有点复杂，你能把数据库文件 `StarwardDatabase.db` 发送到我的邮箱吗 scighost@outlook.com ？

**Comment by Sakura1145** [comment]
> 谢谢你的反馈，这个问题有点复杂，你能把数据库文件 `StarwardDatabase.db` 发送到我的邮箱吗 [scighost@outlook.com](mailto:scighost@outlook.com) ？

刚刚测了一下发现修改系统时间再启动游戏直至游戏报错可以稳定触发

**Comment by Scighost** [comment]
在我本地的测试中，正确时间下，只有总时间会出错，其余展示内容没有问题。你提到的能稳定触发当日游戏时间错误的系统时间是多少？

**Comment by Sakura1145** [comment]
2019年3月

**Comment by Sakura1145** [comment]
大概是2019年3月10日12:00左右
