### ISSUE TITLE
反代/代理服务器不支持http/3时更新出错

### ISSUE THREAD

**Issue by Fachep** [Scighost/Starward#70]
log:
```
fail: Starward.Pages.UpdatePage[0]
      Update now
      System.Net.Http.HttpRequestException: An error occurred while sending the request.
       ---> System.Net.Http.HttpProtocolException: The HTTP/3 server closed the connection. HTTP/3 error code 'H3_GENERAL_PROTOCOL_ERROR' (0x101).
         --- End of inner exception stack trace ---
         at System.Net.Http.Http3RequestStream.SendAsync(CancellationToken)
         at System.Net.Http.Http3RequestStream.SendAsync(CancellationToken)
         at System.Net.Http.Http3Connection.SendAsync(HttpRequestMessage, Int64, CancellationToken)
         at System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async(HttpRequestMessage, CancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage, Boolean, Boolean, CancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
         at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage, HttpCompletionOption, CancellationTokenSource, Boolean, CancellationTokenSource, CancellationToken)
         at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore(Task`1, Type, JsonSerializerContext, CancellationToken)
         at Starward.Core.Metadata.MetadataClient.CommonGetAsync[T](String url, CancellationToken cancellationToken) in D:\a\Starward\Starward\Starward.Core\Metadata\MetadataClient.cs:line 54
         at Starward.Core.Metadata.MetadataClient.GetReleaseAsync(Boolean isPrerelease, Architecture architecture, CancellationToken cancellationToken) in D:\a\Starward\Starward\Starward.Core\Metadata\MetadataClient.cs:line 116
         at Starward.Pages.UpdatePage.UpdateNowAsync() in D:\a\Starward\Starward\Starward\Pages\UpdatePage.xaml.cs:line 256
```

**Comment by Fachep** [comment]
应该是因为我本地反代了github，反代服务器不支持http/3，能否在设置中添加选项选择使用的http版本？

**Comment by Fachep** [comment]
> 每次尝试都会出现这样的问题吗？
> 
> 我有个疑惑，日志中记录的问题是在**更新页面**中发生的，如果真是 HTTP3 的原因，你甚至不会看到这个页面出现。

我装了一个 [steamcommunity302](https://www.dogfight360.com/blog/686/) ，一个 clash ( [Clash Verge](https://github.com/zzzgydi/clash-verge) )

- steamcommunity302 是用 hosts 解析到 127.0.0.1 的 caddy 服务器然后反代到正确的 ip，设置里的网络测试没有问题。前天每次启动都能正常出现更新页面，报错也是每次点击更新按钮后都有。

- clash 系统代理时会出现点击更新按钮没问题，没报错，出现进度条但是没反应。

我的网络环境当时测的是只有 raw.githubusercontent.com 被污染，最后是关闭上面两种工具改 hosts 正常更新的

没什么必要的话，最好还是用稳定一点的协议吧，或者给个选项

**Comment by Scighost** [comment]
> clash 系统代理时会出现点击更新按钮没问题，没报错，出现进度条但是没反应。

请提供一下出现这个情况时的日志。

另外，你遇到的可能是 Clash 的问题 https://github.com/Dreamacro/clash/issues/2621

**Comment by Fachep** [comment]
clash 的问题在 clash.meta v1.14.4 和 clash premuim 2023.04.16 （和当时一样的环境）都没有复现，这是当时的日志：

```
[03:47:10.674] [INFO]
Welcome to Starward v0.7.0
System: Microsoft Windows NT 10.0.22621.0
Command Line: "C:\Program Files\Starward\app-0.7.0\Starward.dll"

[03:47:10.753] [INFO]
Select game region is hkrpg_cn

[03:47:10.753] [INFO]
Navigate to "LauncherPage" with param null

[03:47:10.756] [INFO]
Database path is 'C:\Program Files\Starward\data\StarwardDatabase.db'

[03:47:10.805] [INFO]
Database version is 2, target version is 2.

[03:47:11.144] [INFO]
Game install path hkrpg_cn: "H:\Star Rail Game"

[03:47:11.429] [INFO]
Start to check update (Preview: True, Arch: X64)

[03:47:11.949] [INFO]
Current version: "0.7.0", latest version: "0.7.1", ignore version: null

```

补充：sc302 的问题依然存在，这是完整日志：（控制台）

```
Welcome to Starward v0.7.0
2023-06-21 04:32:32.223
"C:\Program Files\Starward\app-0.7.0\Starward.dll"

Config Directory is 'C:\Program Files\Starward\data'
04:32:32.471
info: Starward.Pages.MainPage[0]
      Select game region is hkrpg_cn
04:32:32.482
info: Starward.Pages.MainPage[0]
      Navigate to LauncherPage with param (null)
04:32:32.484
info: Starward.Services.DatabaseService[0]
      Database path is 'C:\Program Files\Starward\data\StarwardDatabase.db'
04:32:32.531
info: Starward.Services.DatabaseService[0]
      Database version is 3, target version is 2.
04:32:32.836
info: Starward.Pages.LauncherPage[0]
      Game install path hkrpg_cn: H:\Star Rail Game
04:32:33.107
info: Starward.Services.UpdateService[0]
      Start to check update (Preview: True, Arch: X64)
04:32:33.244
info: Starward.Services.UpdateService[0]
      Current version: 0.7.0, latest version: 0.7.1, ignore version: (null)
04:32:33.807
warn: Starward.Pages.UpdatePage[0]
      Cannot get latest release: An error occurred while sending the request.
04:32:49.436
fail: Starward.Pages.UpdatePage[0]
      Update now
      System.Net.Http.HttpRequestException: An error occurred while sending the request.
       ---> System.Net.Http.HttpProtocolException: The HTTP/3 server closed the connection. HTTP/3 error code 'H3_GENERAL_PROTOCOL_ERROR' (0x101).
         --- End of inner exception stack trace ---
         at System.Net.Http.Http3RequestStream.SendAsync(CancellationToken)
         at System.Net.Http.Http3RequestStream.SendAsync(CancellationToken)
         at System.Net.Http.Http3Connection.SendAsync(HttpRequestMessage, Int64, CancellationToken)
         at System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async(HttpRequestMessage, CancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage, Boolean, Boolean, CancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
         at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage, HttpCompletionOption, CancellationTokenSource, Boolean, CancellationTokenSource, CancellationToken)
         at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore(Task`1, Type, JsonSerializerContext, CancellationToken)
         at Starward.Core.Metadata.MetadataClient.CommonGetAsync[T](String url, CancellationToken cancellationToken) in D:\a\Starward\Starward\Starward.Core\Metadata\MetadataClient.cs:line 54
         at Starward.Core.Metadata.MetadataClient.GetReleaseAsync(Boolean isPrerelease, Architecture architecture, CancellationToken cancellationToken) in D:\a\Starward\Starward\Starward.Core\Metadata\MetadataClient.cs:line 116
         at Starward.Pages.UpdatePage.UpdateNowAsync() in D:\a\Starward\Starward\Starward\Pages\UpdatePage.xaml.cs:line 256

```
