### ISSUE TITLE
[Bug] 清理缓存时无法清除日志

### ISSUE THREAD

**Issue by gadfly3173** [Scighost/Starward#708]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

`应用设置`-`文件管理`-`缓存`-`清理缓存` 按钮点击后观察到日志大小没有归零，且多次点击后会不断增加。进入日志文件目录查看后发现应用在试图删除当前占用的日志文件时会发生异常并记录。

```log
[19:46:48.353] [EROR] Starward.Pages.Setting.FileSettingPage
Delete folder '"C:\Users\[username]\AppData\Local\Starward\log"'
System.IO.IOException: The process cannot access the file 'Starward_240313_194638.log' because it is being used by another process.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String, WIN32_FIND_DATA&, Boolean)
   at System.IO.FileSystem.RemoveDirectory(String, Boolean)
   at Starward.Pages.Setting.FileSettingPage.<>c__DisplayClass20_0.<DeleteFolderAsync>b__0() in D:\a\Starward\Starward\src\Starward\Pages\Setting\FileSettingPage.xaml.cs:line 368

```

### Reproduction Steps

点击按钮 `应用设置`-`文件管理`-`缓存`-`清理缓存`

### Expected Behavior

正常清除日志文件或不打印该错误

### Starward Version

0.11.2

### Windows Version

19045.4046

### Log

```shell
[19:46:48.353] [EROR] Starward.Pages.Setting.FileSettingPage
Delete folder '"C:\Users\[username]\AppData\Local\Starward\log"'
System.IO.IOException: The process cannot access the file 'Starward_240313_194638.log' because it is being used by another process.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String, WIN32_FIND_DATA&, Boolean)
   at System.IO.FileSystem.RemoveDirectory(String, Boolean)
   at Starward.Pages.Setting.FileSettingPage.<>c__DisplayClass20_0.<DeleteFolderAsync>b__0() in D:\a\Starward\Starward\src\Starward\Pages\Setting\FileSettingPage.xaml.cs:line 368
```

**Comment by Scighost** [comment]
正常情况，当前进程的日志文件不能被删除。
