### ISSUE TITLE
无法正常使用米游社工具箱

### ISSUE THREAD

**Issue by Eurecka3** [Scighost/Starward#714]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

如标题所述，我的米游社工具箱在登陆账号后无法正常使用，所有数据都无法刷新与查看，包括原神与崩坏：星穹铁道。在2023年还可以正常使用，即使换设备重新登陆也不行。手机端米游社数据全部正常且可查看与刷新

### Reproduction Steps

新设备正常登陆账号  选择“米游社工具箱”  显示“暂无数据”  刷新后崩铁错误码与提示为10035与“账号异常”，无“校验”按钮。原神错误码与提示为5003与“账号异常”，点击"校验"后页面白屏且提示“当前帐号存在风险，暂无数据”。手机端米游社数据全部正常且可查看

### Starward Version

0.11.2

### Windows Version

Windows 11家庭中文版 24H2 26058.1100

### Log

```shell
[13:02:42.318] [INFO] 
Welcome to Starward v0.11.2
System: Microsoft Windows NT 10.0.26058.0
Command Line: D:\Starward_Portable_0.10.4_x64\Starward\app-0.11.2\Starward.dll

[13:02:42.361] [INFO] Starward.Services.DatabaseService
Database path is 'D:\Starward_Portable_0.10.4_x64\Starward'

[13:02:42.393] [INFO] Starward.Services.DatabaseService
Database version is 7, target version is 8.

[13:02:42.477] [INFO] Starward.Pages.MainPage
Last game region is None

[13:02:43.026] [EROR] Starward.Pages.MainPage
Update background image
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unknown region None')
   at Starward.Core.Launcher.LauncherClient.GetLauncherContentAsync(GameBiz biz, String lang, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\Launcher\LauncherClient.cs:line 60
   at Starward.Services.LauncherContentService.GetLauncherContentAsync(GameBiz gameBiz, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\LauncherContentService.cs:line 51
   at Starward.Services.LauncherContentService.GetBackgroundImageAsync(GameBiz gameBiz, Boolean disableCustom) in D:\a\Starward\Starward\src\Starward\Services\LauncherContentService.cs:line 124
   at Starward.Pages.MainPage.UpdateBackgroundImageAsync(Boolean force) in D:\a\Starward\Starward\src\Starward\Pages\MainPage.xaml.cs:line 374

[13:02:44.053] [INFO] Starward.Services.UpdateService
Start to check update (Preview: False, Arch: X64)

[13:02:44.877] [INFO] Starward.Services.UpdateService
Current version: "0.11.2", latest version: "0.11.2", ignore version: null

[13:02:51.186] [INFO] Starward.Pages.MainPage
Change game region to StarRail

[13:02:51.193] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_cn

[13:02:51.313] [INFO] Starward.Pages.LauncherPage
Game install path of hkrpg_cn: "D:\崩坏：星穹铁道"

[13:02:51.358] [INFO] Starward.Pages.LauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.0.0", None.

[13:03:17.282] [INFO] Starward.Pages.MainPage
Change game region to GenshinImpact

[13:03:17.285] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[13:03:17.390] [INFO] Starward.Pages.LauncherPage
Game install path of hk4e_cn: null

[13:03:17.392] [INFO] Starward.Pages.LauncherPage
Acutal version and gamebiz of hk4e_cn is null, None.

[13:03:20.074] [INFO] Starward.Pages.MainPage
Change game region to Honkai3rd

[13:03:20.076] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param bh3_cn

[13:03:20.203] [INFO] Starward.Pages.LauncherPage
Game install path of bh3_cn: null

[13:03:20.204] [INFO] Starward.Pages.LauncherPage
Acutal version and gamebiz of bh3_cn is null, None.

[13:03:22.024] [INFO] Starward.Pages.MainPage
Change game region to StarRail

[13:03:22.027] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_cn

[13:03:22.143] [INFO] Starward.Pages.LauncherPage
Game install path of hkrpg_cn: "D:\崩坏：星穹铁道"

[13:03:22.173] [INFO] Starward.Pages.LauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.0.0", None.

[13:03:47.023] [INFO] Starward.Services.GameService
Start game (hkrpg_cn)
path: "D:\崩坏：星穹铁道\StarRail.exe"
arg: null

[13:03:48.726] [INFO] Starward.Pages.LauncherPage
Game started ("StarRail", 1788)

[13:03:50.739] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hkrpg_cn, 1788)

[14:02:19.983] [INFO] Starward.Pages.MainPage
Change game region to GenshinImpact

[14:02:19.994] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[14:02:20.301] [INFO] Starward.Pages.LauncherPage
Game install path of hk4e_cn: null

[14:02:20.303] [INFO] Starward.Pages.LauncherPage
Acutal version and gamebiz of hk4e_cn is null, None.

[14:02:21.014] [INFO] Starward.Pages.MainPage
Change game region to StarRail

[14:02:21.021] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_cn

[14:02:21.273] [INFO] Starward.Pages.LauncherPage
Game install path of hkrpg_cn: "D:\崩坏：星穹铁道"

[14:02:21.285] [INFO] Starward.Pages.LauncherPage
Game is running ("StarRail", 1788)

[14:02:21.295] [INFO] Starward.Pages.LauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.0.0", None.

[14:02:22.982] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hkrpg_cn

[14:02:26.432] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 116444408 is 1710493800000195708

[14:03:03.096] [INFO] Starward.Pages.MainPage
Last game region is hkrpg_cn

[14:03:03.103] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_cn

[14:03:04.107] [INFO] Starward.Pages.LauncherPage
Game install path of hkrpg_cn: "D:\崩坏：星穹铁道"

[14:03:04.126] [INFO] Starward.Pages.LauncherPage
Game is running ("StarRail", 1788)

[14:03:04.137] [INFO] Starward.Pages.LauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.0.0", None.

[14:03:05.855] [INFO] Starward.Services.UpdateService
Start to check update (Preview: False, Arch: X64)

[14:03:18.618] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hkrpg_cn

[14:04:45.866] [EROR] Starward.Pages.MainPage
Check update
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.Http2Connection.Http2Stream.<>c.<WaitForDataAsync>b__88_0(Object s, CancellationToken cancellationToken)
   at System.Threading.CancellationTokenSource.Invoke(Delegate, Object, CancellationTokenSource)
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean)
   at System.Threading.TimerQueueTimer.Fire(Boolean )
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
--- End of stack trace from previous location ---
   at System.Net.Http.Http2Connection.Http2Stream.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16)
   at System.Net.Http.Http2Connection.Http2Stream.ReadDataAsync(Memory`1, HttpResponseMessage, CancellationToken)
   at System.IO.Compression.BrotliStream.<ReadAsync>g__Core|25_0(Memory`1, CancellationToken)
   at System.Net.Http.Json.LengthLimitReadStream.<ReadAsync>g__Core|13_0(ValueTask`1)
   at System.Text.Json.Serialization.ReadBufferState.ReadFromStreamAsync(Stream, CancellationToken, Boolean )
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream, CancellationToken)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObjectAsync(Stream, CancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.<FromJsonAsyncCore>g__Core|12_0[TValue,TJsonOptions](HttpClient, Task`1, Boolean, CancellationTokenSource, Func`4, TJsonOptions, CancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.Json.HttpClientJsonExtensions.<FromJsonAsyncCore>g__Core|12_0[TValue,TJsonOptions](HttpClient, Task`1, Boolean, CancellationTokenSource, Func`4, TJsonOptions, CancellationToken)
   at Starward.Core.Metadata.MetadataClient.CommonGetAsync[T](String url, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\Metadata\MetadataClient.cs:line 55
   at Starward.Core.Metadata.MetadataClient.GetVersionAsync(Boolean isPrerelease, Architecture architecture, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\Metadata\MetadataClient.cs:line 98
   at Starward.Services.UpdateService.CheckUpdateAsync(Boolean disableIgnore) in D:\a\Starward\Starward\src\Starward\Services\UpdateService.cs:line 42
   at Starward.Pages.MainPage.CheckUpdateAsync() in D:\a\Starward\Starward\src\Starward\Pages\MainPage.xaml.cs:line 116

[14:23:00.119] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 116444408 is 1710551400000847608

[14:23:06.153] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_cn

[14:23:06.225] [INFO] Starward.Pages.LauncherPage
Game install path of hkrpg_cn: "D:\崩坏：星穹铁道"

[14:23:06.231] [INFO] Starward.Pages.LauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.0.0", None.

[14:23:07.547] [INFO] Starward.Pages.MainPage
Navigate to "GameSettingPage" with param hkrpg_cn

[14:23:07.605] [INFO] Starward.Services.GameSettingService
Voice language of game hkrpg_cn is null

[14:23:14.749] [INFO] Starward.Pages.MainPage
Change game region to GenshinImpact

[14:23:14.755] [INFO] Starward.Pages.MainPage
Navigate to "GameSettingPage" with param hk4e_cn

[14:23:15.580] [INFO] Starward.Pages.MainPage
Change game region to Honkai3rd

[14:23:15.582] [INFO] Starward.Pages.MainPage
Navigate to "GameSettingPage" with param bh3_cn

[14:23:17.180] [INFO] Starward.Pages.MainPage
Change game region to GenshinImpact

[14:23:17.185] [INFO] Starward.Pages.MainPage
Navigate to "GameSettingPage" with param hk4e_cn

[14:23:17.716] [INFO] Starward.Pages.MainPage
Change game region to StarRail

[14:23:17.722] [INFO] Starward.Pages.MainPage
Navigate to "GameSettingPage" with param hkrpg_cn

[14:23:17.751] [INFO] Starward.Services.GameSettingService
Voice language of game hkrpg_cn is null

[14:23:25.296] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hkrpg_cn

[14:23:25.311] [INFO] Starward.Services.GameRecordService
Change region to China.

[14:24:15.200] [EROR] Starward.Pages.HoyolabToolbox.LoginPage
Log in (web mode)
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
 ---> System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError, CancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken, Int32)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1, CancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16)
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage, Boolean, Boolean, CancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage, HttpCompletionOption, CancellationTokenSource, Boolean, CancellationTokenSource, CancellationToken)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 149
   at Starward.Core.GameRecord.HyperionClient.GetGenshinGameRolesAsync(String cookie, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 113
   at Starward.Core.GameRecord.HyperionClient.GetAllGameRolesAsync(String cookie, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 81
   at Starward.Services.GameRecordService.AddGameRolesAsync(String cookie, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 100
   at Starward.Pages.HoyolabToolbox.LoginPage.Button_Finish_Click(Object sender, RoutedEventArgs e) in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\LoginPage.xaml.cs:line 244

[14:24:27.594] [EROR] Starward.Pages.HoyolabToolbox.SimulatedUniversePage
Get simulated universe data ("hkrpg_cn", 116444408).
Starward.Core.miHoYoApiException:  (10035)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetSimulatedUniverseInfoAsync(GameRecordRole role, Boolean detail, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 335
   at Starward.Services.GameRecordService.GetSimulatedUniverseInfoAsync(GameRecordRole role, Boolean detail) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 356
   at Starward.Pages.HoyolabToolbox.SimulatedUniversePage.GetSimulatedUniverseInfoBasicAsync(Boolean detail) in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SimulatedUniversePage.xaml.cs:line 128

[14:24:31.356] [EROR] Starward.Pages.HoyolabToolbox.ForgottenHallPage
Refresh forgotten hall data ("hkrpg_cn", 116444408).
Starward.Core.miHoYoApiException:  (10035)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 271
   at Starward.Services.GameRecordService.RefreshForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 432
   at Starward.Pages.HoyolabToolbox.ForgottenHallPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\ForgottenHallPage.xaml.cs:line 111

[14:24:38.160] [EROR] Starward.Pages.HoyolabToolbox.PureFictionPage
Refresh pure fiction data ("hkrpg_cn", 116444408).
Starward.Core.miHoYoApiException:  (10035)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetPureFictionInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 296
   at Starward.Services.GameRecordService.RefreshPureFictionInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 496
   at Starward.Pages.HoyolabToolbox.PureFictionPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\PureFictionPage.xaml.cs:line 111

[14:24:41.513] [INFO] Starward.Pages.MainPage
Change game region to GenshinImpact

[14:24:41.516] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hk4e_cn

[14:24:41.527] [INFO] Starward.Services.GameRecordService
Change region to China.

[14:24:43.526] [EROR] Starward.Pages.HoyolabToolbox.SpiralAbyssPage
Refresh abyss data ("hk4e_cn", 262870134).
Starward.Core.miHoYoApiException:  (5003)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetSpiralAbyssInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 138
   at Starward.Services.GameRecordService.RefreshSpiralAbyssInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 212
   at Starward.Pages.HoyolabToolbox.SpiralAbyssPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SpiralAbyssPage.xaml.cs:line 120

[14:24:54.627] [EROR] Starward.Pages.HoyolabToolbox.SpiralAbyssPage
Refresh abyss data ("hk4e_cn", 262870134).
Starward.Core.miHoYoApiException:  (5003)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetSpiralAbyssInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 138
   at Starward.Services.GameRecordService.RefreshSpiralAbyssInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 212
   at Starward.Pages.HoyolabToolbox.SpiralAbyssPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SpiralAbyssPage.xaml.cs:line 120

[14:25:03.469] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[14:25:03.547] [INFO] Starward.Pages.LauncherPage
Game install path of hk4e_cn: null

[14:25:03.548] [INFO] Starward.Pages.LauncherPage
Acutal version and gamebiz of hk4e_cn is null, None.

[14:25:05.572] [INFO] Starward.Pages.MainPage
Change game region to StarRail

[14:25:05.574] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_cn

[14:25:05.644] [INFO] Starward.Pages.LauncherPage
Game install path of hkrpg_cn: "D:\崩坏：星穹铁道"

[14:25:05.652] [INFO] Starward.Pages.LauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.0.0", None.

[14:28:08.588] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hkrpg_cn

[14:28:08.598] [INFO] Starward.Services.GameRecordService
Change region to China.

[14:30:31.895] [EROR] Starward.Pages.HoyolabToolbox.SimulatedUniversePage
Get simulated universe data ("hkrpg_cn", 116444408).
Starward.Core.miHoYoApiException:  (10035)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetSimulatedUniverseInfoAsync(GameRecordRole role, Boolean detail, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 335
   at Starward.Services.GameRecordService.GetSimulatedUniverseInfoAsync(GameRecordRole role, Boolean detail) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 356
   at Starward.Pages.HoyolabToolbox.SimulatedUniversePage.GetSimulatedUniverseInfoBasicAsync(Boolean detail) in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SimulatedUniversePage.xaml.cs:line 128

[14:31:04.339] [EROR] Starward.Pages.HoyolabToolbox.SimulatedUniversePage
Get simulated universe data ("hkrpg_cn", 116444408).
Starward.Core.miHoYoApiException:  (10035)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetSimulatedUniverseInfoAsync(GameRecordRole role, Boolean detail, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 335
   at Starward.Services.GameRecordService.GetSimulatedUniverseInfoAsync(GameRecordRole role, Boolean detail) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 356
   at Starward.Pages.HoyolabToolbox.SimulatedUniversePage.GetSimulatedUniverseInfoBasicAsync(Boolean detail) in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SimulatedUniversePage.xaml.cs:line 128

[14:31:12.410] [EROR] Starward.Pages.HoyolabToolbox.SimulatedUniversePage
Get simulated universe data ("hkrpg_cn", 116444408).
Starward.Core.miHoYoApiException:  (10035)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetSimulatedUniverseInfoAsync(GameRecordRole role, Boolean detail, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 335
   at Starward.Services.GameRecordService.GetSimulatedUniverseInfoAsync(GameRecordRole role, Boolean detail) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 356
   at Starward.Pages.HoyolabToolbox.SimulatedUniversePage.GetSimulatedUniverseInfoBasicAsync(Boolean detail) in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SimulatedUniversePage.xaml.cs:line 128

[14:31:18.436] [EROR] Starward.Pages.HoyolabToolbox.SimulatedUniversePage
Get simulated universe data ("hkrpg_cn", 116444408).
Starward.Core.miHoYoApiException:  (10035)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetSimulatedUniverseInfoAsync(GameRecordRole role, Boolean detail, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 335
   at Starward.Services.GameRecordService.GetSimulatedUniverseInfoAsync(GameRecordRole role, Boolean detail) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 356
   at Starward.Pages.HoyolabToolbox.SimulatedUniversePage.GetSimulatedUniverseInfoBasicAsync(Boolean detail) in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SimulatedUniversePage.xaml.cs:line 128

[14:31:20.433] [EROR] Starward.Pages.HoyolabToolbox.ForgottenHallPage
Refresh forgotten hall data ("hkrpg_cn", 116444408).
Starward.Core.miHoYoApiException:  (10035)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 271
   at Starward.Services.GameRecordService.RefreshForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 432
   at Starward.Pages.HoyolabToolbox.ForgottenHallPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\ForgottenHallPage.xaml.cs:line 111

[14:32:08.721] [INFO] Starward.Pages.MainPage
Change game region to GenshinImpact

[14:32:08.726] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hk4e_cn

[14:32:08.734] [INFO] Starward.Services.GameRecordService
Change region to China.

[14:32:10.604] [EROR] Starward.Pages.HoyolabToolbox.SpiralAbyssPage
Refresh abyss data ("hk4e_cn", 262870134).
Starward.Core.miHoYoApiException:  (5003)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetSpiralAbyssInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 138
   at Starward.Services.GameRecordService.RefreshSpiralAbyssInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 212
   at Starward.Pages.HoyolabToolbox.SpiralAbyssPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SpiralAbyssPage.xaml.cs:line 120

[14:34:36.571] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[14:34:36.658] [INFO] Starward.Pages.LauncherPage
Game install path of hk4e_cn: null

[14:34:36.659] [INFO] Starward.Pages.LauncherPage
Acutal version and gamebiz of hk4e_cn is null, None.
```

**Comment by Scighost** [comment]
参考 #669
