### ISSUE TITLE
[Bug] 跃迁记录获取不全

### ISSUE THREAD

**Issue by 3281221832** [Scighost/Starward#722]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

使用Starward每个池子只能获取最近310抽(即16页)的记录,其他程序无该问题(URL从Starward 跃迁记录 设置 中复制),经过多次更新仍然重置该问题
![image](https://github.com/Scighost/Starward/assets/71533480/ba22a77b-e667-4bbf-8925-334455ebc686)
![image](https://github.com/Scighost/Starward/assets/71533480/6b00f791-5108-4b1d-8a64-f08cf16c9443)

### Reproduction Steps

打开崩坏星穹铁道角色互动跃迁后点击Starward 跃迁记录中的更新记录

### Starward Version

0.11-0.11.2

### Windows Version

Windows10 专业工作站版22H2 ;Windows Feature Experience Pack 1000.19054.1000.0

### Log

```shell
[21:58:46.945] [INFO] 
Welcome to Starward v0.11.2
System: Microsoft Windows NT 10.0.19045.0
Command Line: H:\Starward\app-0.11.2\Starward.dll

[21:58:47.845] [INFO] Starward.Services.DatabaseService
Database path is 'H:\Starward'

[21:58:49.484] [INFO] Starward.Services.DatabaseService
Database version is 8, target version is 8.

[21:58:49.957] [INFO] Starward.Pages.MainPage
Last game region is hkrpg_cn

[21:58:50.384] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_cn

[21:58:51.721] [INFO] Starward.Pages.LauncherPage
Game install path of hkrpg_cn: "H:\Starward\Games\Star Rail"

[21:58:51.748] [INFO] Starward.Pages.LauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.0.0", hkrpg_cn.

[21:58:53.360] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[21:58:53.768] [INFO] Starward.Services.UpdateService
Current version: "0.11.2", latest version: "0.11.2", ignore version: null

[21:58:54.028] [INFO] Starward.Services.GameService
Start game (hkrpg_cn)
path: "H:\Starward\Games\Star Rail\StarRail.exe"
arg: null

[21:58:54.072] [INFO] Starward.Pages.LauncherPage
Game started ("StarRail", 5652)

[21:58:56.089] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hkrpg_cn, 5652)

[21:59:11.108] [INFO] Starward.Pages.LauncherPage
Game process exited

[21:59:26.020] [INFO] Starward.Services.GameService
Start game (hkrpg_cn)
path: "H:\Starward\Games\Star Rail\StarRail.exe"
arg: null

[21:59:26.041] [INFO] Starward.Pages.LauncherPage
Game started ("StarRail", 33096)

[21:59:28.057] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hkrpg_cn, 33096)

[22:06:00.062] [INFO] Starward.Pages.LauncherPage
Game process exited

[22:06:05.325] [INFO] Starward.Services.GameService
Start game (hkrpg_cn)
path: "H:\Starward\Games\Star Rail\StarRail.exe"
arg: null

[22:06:05.352] [INFO] Starward.Pages.LauncherPage
Game started ("StarRail", 11992)

[22:06:07.354] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hkrpg_cn, 11992)

[22:48:36.844] [INFO] Starward.Pages.MainPage
Navigate to "SelfQueryPage" with param hkrpg_cn

[22:48:40.078] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hkrpg_cn

[22:48:40.085] [INFO] Starward.Services.GameRecordService
Change region to China.

[22:48:44.255] [EROR] Starward.Pages.HoyolabToolbox.SimulatedUniversePage
Get simulated universe data ("hkrpg_cn", 129432772).
Starward.Core.miHoYoApiException: Please login (10001)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetSimulatedUniverseInfoAsync(GameRecordRole role, Boolean detail, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 335
   at Starward.Services.GameRecordService.GetSimulatedUniverseInfoAsync(GameRecordRole role, Boolean detail) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 356
   at Starward.Pages.HoyolabToolbox.SimulatedUniversePage.GetSimulatedUniverseInfoBasicAsync(Boolean detail) in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SimulatedUniversePage.xaml.cs:line 128

[22:48:46.245] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hkrpg_cn

[22:48:47.869] [WARN] Starward.Pages.GachaLogPage
Request mihoyo api error: "authkey timeout (-101)"

[22:48:57.798] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 129432772 is 1709741400000530272

[22:49:13.232] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 129432772 is 0

[23:07:24.111] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 129432772 is 1710601800001889372

[23:07:32.218] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 129432772 is 0
```

**Comment by Scighost** [comment]
星穹铁道只开放半年的抽卡记录查询
