### ISSUE TITLE
[Question] 星铁工具箱无法获取模拟宇宙等数据

### ISSUE THREAD

**Issue by wwl27** [Scighost/Starward#734]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

![屏幕截图 2024-03-22 101030](https://github.com/Scighost/Starward/assets/162520660/60996f0c-637c-4a27-867c-d2e827528357)
星铁模拟宇宙、虚构叙事、混沌都不能获取
在0.11.3版本之前原神深渊和星铁的都不能获取，0.11.3版本原神深渊可以正常获取但是星铁仍然不能

### Starward Version

0.11.3

### Windows Version

22635.3350

### Log

```shell
[10:07:24.655] [EROR] Starward.Pages.HoyolabToolbox.SimulatedUniversePage
Get simulated universe data ("hkrpg_cn", 100485987).
Starward.Core.miHoYoApiException:  (10035)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetSimulatedUniverseInfoAsync(GameRecordRole role, Boolean detail, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 335
   at Starward.Services.GameRecordService.GetSimulatedUniverseInfoAsync(GameRecordRole role, Boolean detail) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 356
   at Starward.Pages.HoyolabToolbox.SimulatedUniversePage.GetSimulatedUniverseInfoBasicAsync(Boolean detail) in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SimulatedUniversePage.xaml.cs:line 128

[10:08:05.787] [EROR] Starward.Pages.Setting.FileSettingPage
Delete folder '"C:\Users\45006\AppData\Local\Starward\log"'
System.IO.IOException: The process cannot access the file 'Starward_240322_100710.log' because it is being used by another process.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String, WIN32_FIND_DATA&, Boolean)
   at System.IO.FileSystem.RemoveDirectory(String, Boolean)
   at Starward.Pages.Setting.FileSettingPage.<>c__DisplayClass20_0.<DeleteFolderAsync>b__0() in D:\a\Starward\Starward\src\Starward\Pages\Setting\FileSettingPage.xaml.cs:line 368

[10:08:20.495] [EROR] Starward.Pages.HoyolabToolbox.SimulatedUniversePage
Get simulated universe data ("hkrpg_cn", 100485987).
Starward.Core.miHoYoApiException:  (10035)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetSimulatedUniverseInfoAsync(GameRecordRole role, Boolean detail, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 335
   at Starward.Services.GameRecordService.GetSimulatedUniverseInfoAsync(GameRecordRole role, Boolean detail) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 356
   at Starward.Pages.HoyolabToolbox.SimulatedUniversePage.GetSimulatedUniverseInfoBasicAsync(Boolean detail) in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SimulatedUniversePage.xaml.cs:line 128

[10:08:22.927] [EROR] Starward.Pages.HoyolabToolbox.ForgottenHallPage
Refresh forgotten hall data ("hkrpg_cn", 100485987).
Starward.Core.miHoYoApiException:  (10035)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 271
   at Starward.Services.GameRecordService.RefreshForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 432
   at Starward.Pages.HoyolabToolbox.ForgottenHallPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\ForgottenHallPage.xaml.cs:line 111

[10:10:07.797] [EROR] Starward.Pages.Setting.FileSettingPage
Delete folder '"C:\Users\45006\AppData\Local\Starward\log"'
System.IO.IOException: The process cannot access the file 'Starward_240322_100710.log' because it is being used by another process.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String, WIN32_FIND_DATA&, Boolean)
   at System.IO.FileSystem.RemoveDirectory(String, Boolean)
   at Starward.Pages.Setting.FileSettingPage.<>c__DisplayClass20_0.<DeleteFolderAsync>b__0() in D:\a\Starward\Starward\src\Starward\Pages\Setting\FileSettingPage.xaml.cs:line 368

[10:10:13.254] [EROR] Starward.Pages.HoyolabToolbox.SimulatedUniversePage
Get simulated universe data ("hkrpg_cn", 100485987).
Starward.Core.miHoYoApiException:  (10035)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetSimulatedUniverseInfoAsync(GameRecordRole role, Boolean detail, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 335
   at Starward.Services.GameRecordService.GetSimulatedUniverseInfoAsync(GameRecordRole role, Boolean detail) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 356
   at Starward.Pages.HoyolabToolbox.SimulatedUniversePage.GetSimulatedUniverseInfoBasicAsync(Boolean detail) in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SimulatedUniversePage.xaml.cs:line 128

[10:10:17.822] [EROR] Starward.Pages.HoyolabToolbox.ForgottenHallPage
Refresh forgotten hall data ("hkrpg_cn", 100485987).
Starward.Core.miHoYoApiException:  (10035)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 271
   at Starward.Services.GameRecordService.RefreshForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 432
   at Starward.Pages.HoyolabToolbox.ForgottenHallPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\ForgottenHallPage.xaml.cs:line 111

[10:10:19.593] [EROR] Starward.Pages.HoyolabToolbox.PureFictionPage
Refresh pure fiction data ("hkrpg_cn", 100485987).
Starward.Core.miHoYoApiException:  (10035)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetPureFictionInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 296
   at Starward.Services.GameRecordService.RefreshPureFictionInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 496
   at Starward.Pages.HoyolabToolbox.PureFictionPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\PureFictionPage.xaml.cs:line 111
```

**Comment by wwl27** [comment]
重登几遍账号发现原神的也出问题了T_T前几天还没这事的
![屏幕截图 2024-03-22 122325](https://github.com/Scighost/Starward/assets/162520660/f74bab5b-0f94-4207-9f59-863e02e3abba)
