### ISSUE TITLE
[Bug] 米游社工具箱功能信息拉取异常

### ISSUE THREAD

**Issue by DrMythical** [Scighost/Starward#747]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

无法正常读取到【深境螺旋】【模拟宇宙】【忘却之庭】【虚构叙事】的数据，在点击刷新后显示“账号异常10035”，而【旅行者札记】【开拓日历】功能则能正常使用并获取信息。

### Reproduction Steps

网页登录->登录成功->重新启动软件->无法获取数据->刷新->账号异常10035

### Expected Behavior

账号内的深境螺旋、模拟宇宙、忘却之庭和虚构叙事的信息

### Screenshots

![深境螺旋](https://github.com/Scighost/Starward/assets/104907432/49034c67-638d-4026-89e8-a91408515d31)
![模拟宇宙](https://github.com/Scighost/Starward/assets/104907432/443be30d-844a-4651-90f1-d7e7c861ae43)
![忘却之庭](https://github.com/Scighost/Starward/assets/104907432/3c8ace8b-9583-466c-8cd4-e79dc87758e7)
![虚构叙事](https://github.com/Scighost/Starward/assets/104907432/07bda314-a1d5-45a6-aa1d-c4c31ba997bd)
![刷新后异常](https://github.com/Scighost/Starward/assets/104907432/2712a226-5211-425a-9c14-7bb88c7019e4)

### Starward Version

0.11.3

### Windows Version

Windows Feature Experience Pack 1000.22688.1000.0

### Log

```shell
[22:45:38.231] [INFO] 
Welcome to Starward v0.11.3
System: Microsoft Windows NT 10.0.22631.0
Command Line: D:\Starward\app-0.11.3\Starward.dll

[22:45:38.251] [INFO] Starward.Services.DatabaseService
Database path is 'D:\Starward'

[22:45:38.265] [INFO] Starward.Services.DatabaseService
Database version is 8, target version is 8.

[22:45:38.306] [INFO] Starward.Pages.MainPage
Last game region is hk4e_cn

[22:45:38.311] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[22:45:38.723] [INFO] Starward.Pages.LauncherPage
Game install path of hk4e_cn: "D:\miHoYo\Genshin Impact\Genshin Impact Game"

[22:45:38.748] [INFO] Starward.Pages.LauncherPage
Acutal version and gamebiz of hk4e_cn is "4.5.0", None.

[22:45:39.847] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[22:45:41.595] [INFO] Starward.Services.UpdateService
Current version: "0.11.3", latest version: "0.11.3", ignore version: null

[22:45:42.499] [INFO] Starward.Pages.MainPage
Change game region to StarRail

[22:45:42.503] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_cn

[22:45:42.561] [INFO] Starward.Pages.LauncherPage
Game install path of hkrpg_cn: "D:\miHoYo\Star Rail\Game"

[22:45:42.581] [INFO] Starward.Pages.LauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.1.0", None.

[22:45:46.654] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hkrpg_cn

[22:45:46.661] [INFO] Starward.Services.GameRecordService
Change region to China.

[22:47:45.572] [EROR] Starward.Pages.HoyolabToolbox.PureFictionPage
Refresh pure fiction data ("hkrpg_cn", 100558099).
Starward.Core.miHoYoApiException:  (10035)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetPureFictionInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 296
   at Starward.Services.GameRecordService.RefreshPureFictionInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 496
   at Starward.Pages.HoyolabToolbox.PureFictionPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\PureFictionPage.xaml.cs:line 111

[22:47:47.594] [EROR] Starward.Pages.HoyolabToolbox.ForgottenHallPage
Refresh forgotten hall data ("hkrpg_cn", 100558099).
Starward.Core.miHoYoApiException:  (10035)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 271
   at Starward.Services.GameRecordService.RefreshForgottenHallInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 432
   at Starward.Pages.HoyolabToolbox.ForgottenHallPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\ForgottenHallPage.xaml.cs:line 111

[22:47:48.996] [EROR] Starward.Pages.HoyolabToolbox.SimulatedUniversePage
Get simulated universe data ("hkrpg_cn", 100558099).
Starward.Core.miHoYoApiException:  (10035)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetSimulatedUniverseInfoAsync(GameRecordRole role, Boolean detail, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 335
   at Starward.Services.GameRecordService.GetSimulatedUniverseInfoAsync(GameRecordRole role, Boolean detail) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 356
   at Starward.Pages.HoyolabToolbox.SimulatedUniversePage.GetSimulatedUniverseInfoBasicAsync(Boolean detail) in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SimulatedUniversePage.xaml.cs:line 128

[22:47:57.612] [INFO] Starward.Pages.MainPage
Change game region to GenshinImpact

[22:47:57.615] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hk4e_cn

[22:47:57.618] [INFO] Starward.Services.GameRecordService
Change region to China.

[22:55:17.338] [INFO] Starward.Pages.MainPage
Change game region to StarRail

[22:55:17.343] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hkrpg_cn

[22:55:17.347] [INFO] Starward.Services.GameRecordService
Change region to China.

[22:56:39.294] [EROR] Starward.Pages.HoyolabToolbox.PureFictionPage
Refresh pure fiction data ("hkrpg_cn", 100558099).
Starward.Core.miHoYoApiException:  (10035)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetPureFictionInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 296
   at Starward.Services.GameRecordService.RefreshPureFictionInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 496
   at Starward.Pages.HoyolabToolbox.PureFictionPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\PureFictionPage.xaml.cs:line 111

[22:58:50.523] [INFO] Starward.Pages.MainPage
Change game region to GenshinImpact

[22:58:50.526] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hk4e_cn

[22:58:50.530] [INFO] Starward.Services.GameRecordService
Change region to China.
```

### Additional Context

No response

**Comment by DrMythical** [comment]
Why did you adde duplicate and remove triage labels?

**Comment by meng-ru-nan-fa** [comment]
> Why did you add duplicate and remove triage labels?

#669 吧
