### ISSUE TITLE
[Bug] 账号切换功能失效

### ISSUE THREAD

**Issue by shiolife** [Scighost/Starward#754]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

在游戏运行中正常保存账号，关闭游戏后切换账号并开始游戏，但账号并没有被切换

### Reproduction Steps

默认设置

### Starward Version

now

### Windows Version

22631.3374

### Log

```shell
[18:54:04.622] [INFO] 
Welcome to Starward v0.11.3
System: Microsoft Windows NT 10.0.22631.0
Command Line: A:\Tool\Starward\app-0.11.3\Starward.dll

[18:54:04.671] [INFO] Starward.Services.DatabaseService
Database path is 'A:\Tool\Starward'

[18:54:04.715] [INFO] Starward.Services.DatabaseService
Database version is 8, target version is 8.

[18:54:04.811] [INFO] Starward.Pages.MainPage
Last game region is hk4e_cn

[18:54:04.824] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[18:54:05.604] [INFO] Starward.Pages.LauncherPage
Game install path of hk4e_cn: "A:\Genshin Impact Game"

[18:54:05.641] [INFO] Starward.Pages.LauncherPage
Acutal version and gamebiz of hk4e_cn is "4.5.0", None.

[18:54:07.098] [INFO] Starward.Services.UpdateService
Start to check update (Preview: False, Arch: X64)

[18:54:12.215] [WARN] Starward.Pages.MainPage
Check update: "The SSL connection could not be established, see inner exception."

[18:54:14.056] [INFO] Starward.Services.GameAccountService
Change account "fly" (hk4e_cn) successfully!

[18:54:15.478] [INFO] Starward.Services.GameService
Start game (hk4e_cn)
path: "A:\Genshin Impact Game\YuanShen.exe"
arg: null

[18:54:15.622] [INFO] Starward.Pages.LauncherPage
Game started ("YuanShen", 17832)

[18:54:17.629] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hk4e_cn, 17832)

[18:55:44.776] [INFO] Starward.Services.GameAccountService
Save account "神奇" (hk4e_cn) successfully!

[18:55:53.647] [INFO] Starward.Pages.LauncherPage
Game process exited

[18:55:53.653] [INFO] Starward.Pages.LauncherPage
Game is running ("YuanShen", 17832)

[18:55:54.664] [INFO] Starward.Pages.LauncherPage
Game process exited

[18:55:54.670] [INFO] Starward.Pages.LauncherPage
Game is running ("YuanShen", 17832)

[18:55:55.673] [INFO] Starward.Pages.LauncherPage
Game process exited

[18:57:14.705] [INFO] Starward.Services.GameAccountService
Save account "fly" (hk4e_cn) successfully!

[18:59:55.829] [INFO] Starward.Services.GameAccountService
Save account "fly" (hk4e_cn) successfully!

[19:00:10.186] [INFO] Starward.Services.GameAccountService
Change account "神奇" (hk4e_cn) successfully!

[19:00:11.903] [INFO] Starward.Services.GameService
Start game (hk4e_cn)
path: "A:\Genshin Impact Game\YuanShen.exe"
arg: null

[19:00:12.039] [INFO] Starward.Pages.LauncherPage
Game started ("YuanShen", 6028)

[19:00:14.058] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hk4e_cn, 6028)

[19:01:18.078] [INFO] Starward.Pages.LauncherPage
Game process exited

[19:01:18.084] [INFO] Starward.Pages.LauncherPage
Game is running ("YuanShen", 6028)

[19:01:19.086] [INFO] Starward.Pages.LauncherPage
Game process exited

[19:01:19.091] [INFO] Starward.Pages.LauncherPage
Game is running ("YuanShen", 6028)

[19:01:20.092] [INFO] Starward.Pages.LauncherPage
Game process exited

[19:01:26.273] [INFO] Starward.Pages.MainPage
Navigate to "GameSettingPage" with param hk4e_cn

[19:01:35.393] [INFO] Starward.Pages.MainPage
Navigate to "ScreenshotPage" with param hk4e_cn

[19:01:35.465] [WARN] Starward.Pages.ScreenshotPage
Cannot find screenshot folder

[19:01:37.046] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_cn

[19:01:40.603] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hk4e_cn

[19:01:40.612] [INFO] Starward.Services.GameRecordService
Change region to China.

[19:02:50.681] [EROR] Starward.Pages.HoyolabToolbox.SpiralAbyssPage
Refresh abyss data ("hk4e_cn", 127523174).
Starward.Core.miHoYoApiException:  (1034)
   at Starward.Core.GameRecord.GameRecordClient.CommonSendAsync[T](HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\GameRecordClient.cs:line 163
   at Starward.Core.GameRecord.HyperionClient.GetSpiralAbyssInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\GameRecord\HyperionClient.cs:line 138
   at Starward.Services.GameRecordService.RefreshSpiralAbyssInfoAsync(GameRecordRole role, Int32 schedule, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\GameRecordService.cs:line 212
   at Starward.Pages.HoyolabToolbox.SpiralAbyssPage.RefreshDataAsync() in D:\a\Starward\Starward\src\Starward\Pages\HoyolabToolbox\SpiralAbyssPage.xaml.cs:line 120

[19:03:38.782] [INFO] Starward.Pages.MainPage
Navigate to "SelfQueryPage" with param hk4e_cn

[19:03:53.244] [INFO] Starward.Pages.MainPage
Navigate to "ScreenshotPage" with param hk4e_cn

[19:03:53.281] [WARN] Starward.Pages.ScreenshotPage
Cannot find screenshot folder

[19:03:55.131] [INFO] Starward.Pages.MainPage
Navigate to "GameSettingPage" with param hk4e_cn

[19:03:56.778] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_cn

[19:04:00.122] [WARN] Starward.Pages.GachaLogPage
Request mihoyo api error: "authkey timeout (-101)"

[19:05:00.767] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[19:05:00.836] [INFO] Starward.Pages.LauncherPage
Game install path of hk4e_cn: "A:\Genshin Impact Game"

[19:05:00.848] [INFO] Starward.Pages.LauncherPage
Acutal version and gamebiz of hk4e_cn is "4.5.0", None.

[19:05:01.732] [INFO] Starward.Services.GameService
Start game (hk4e_cn)
path: "A:\Genshin Impact Game\YuanShen.exe"
arg: null

[19:05:01.830] [INFO] Starward.Pages.LauncherPage
Game started ("YuanShen", 12216)

[19:05:03.836] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hk4e_cn, 12216)

[19:07:42.845] [INFO] Starward.Pages.LauncherPage
Game process exited

[19:07:42.852] [INFO] Starward.Pages.LauncherPage
Game is running ("YuanShen", 12216)

[19:07:43.860] [INFO] Starward.Pages.LauncherPage
Game process exited

[19:07:43.865] [INFO] Starward.Pages.LauncherPage
Game is running ("YuanShen", 12216)

[19:07:44.880] [INFO] Starward.Pages.LauncherPage
Game process exited

[19:45:18.443] [INFO] Starward.Pages.Setting.FileSettingPage
Open folder '"A:\Tool\Starward"'
```

### Additional Context

nothing

**Comment by Scighost** [comment]
因为原神没有在注册表中存储当前已登录账号的uid，所以我无法确认你两次保存的是否为同一账号。

**Comment by Esmge** [comment]
我使用的账号密码，账号切换并不能生效，然后，跃迁记录目前只能使用一个账号的么？

**Comment by Danmo04** [comment]
我用崩铁登录新账号时启动器也会覆盖掉旧账号

**Comment by shiolife** [comment]
> 可能是用米游社扫码登录的吧，切换账号其实保存账号密码给你省掉输账密的阶段，可以试下用密账登录之后切换账号

我是账号密码登录，希望把切换账号改成修改注册表，会很好用的
