### ISSUE TITLE
[Bug] [Genshin] HoyoLab Toolbox and Account Records not updating properly

### ISSUE THREAD

**Issue by ronnywolfy** [Scighost/Starward#759]
### Checklist

- [x] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

* Spiral Abyss data shows "Picked" and "Combat Stats" data as empty. Does not get fixed on Refresh
* Traveler Diary data is missing daily data of most days. Does not get fixed on Refresh
* Account Records throws `ArgumentException - Input URL  Input url is invalid. (Parameter 'url') ` error when pasting the Feedback link as instructed

Issues were also present in 0.11.3

And sorry if there are already tickets about these, but I don't understand Chinese. 🙏

I love this software, thank you!!

### Reproduction Steps

Normal usage of the HoyoLab Toolbox and Account Records

### Starward Version

0.11.4

### Windows Version

10.0.19045

### Log

```shell
[00:59:40.076] [INFO] 
Welcome to Starward v0.11.4
System: Microsoft Windows NT 10.0.19045.0
Command Line: C:\************\Starward\app-0.11.4\Starward.dll

[00:59:40.149] [INFO] Starward.Services.DatabaseService
Database path is 'C:\************\Starward'

[00:59:40.193] [INFO] Starward.Services.DatabaseService
Database version is 8, target version is 8.

[00:59:40.324] [INFO] Starward.Pages.MainPage
Last game region is hk4e_global

[00:59:40.343] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_global

[00:59:41.314] [INFO] Starward.Pages.LauncherPage
Game install path of hk4e_global: "C:\************\Genshin Impact\Genshin Impact game"

[00:59:41.379] [INFO] Starward.Pages.LauncherPage
Acutal version and gamebiz of hk4e_global is "4.5.0", None.

[00:59:43.368] [INFO] Starward.Services.UpdateService
Start to check update (Preview: False, Arch: X64)

[00:59:43.598] [INFO] Starward.Services.UpdateService
Current version: "0.11.4", latest version: "0.11.4", ignore version: null

[00:59:47.472] [INFO] Starward.Pages.MainPage
Navigate to "SelfQueryPage" with param hk4e_global

[00:59:52.373] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_global

[00:59:52.498] [INFO] Starward.Pages.LauncherPage
Game install path of hk4e_global: "C:\************\Genshin Impact\Genshin Impact game"

[00:59:52.509] [INFO] Starward.Pages.LauncherPage
Acutal version and gamebiz of hk4e_global is "4.5.0", None.

[00:59:54.030] [INFO] Starward.Services.GameService
Start game (hk4e_global)
path: "C:\************"
arg: null

[00:59:54.104] [INFO] Starward.Pages.LauncherPage
Game started ("cmd", 5212)

[00:59:56.114] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hk4e_global, 6328)

[01:01:44.978] [INFO] Starward.Pages.MainPage
Navigate to "SelfQueryPage" with param hk4e_global

[01:01:48.811] [EROR] Starward.Pages.SelfQueryPage
Input url
System.ArgumentException: Input url is invalid. (Parameter 'url')
   at Starward.Core.SelfQuery.SelfQueryClient.InitializeAsync(String url, GameBiz gameBiz, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\SelfQuery\SelfQueryClient.cs:line 86
   at Starward.Services.SelfQueryService.InitializeAsync(String url, GameBiz gameBiz) in D:\a\Starward\Starward\src\Starward\Services\SelfQueryService.cs:line 40
   at Starward.Pages.SelfQueryPage.InputURLAsync() in D:\a\Starward\Starward\src\Starward\Pages\SelfQueryPage.xaml.cs:line 308

[01:01:56.033] [EROR] Starward.Pages.SelfQueryPage
Input url
System.ArgumentException: Input url is invalid. (Parameter 'url')
   at Starward.Core.SelfQuery.SelfQueryClient.InitializeAsync(String url, GameBiz gameBiz, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\SelfQuery\SelfQueryClient.cs:line 86
   at Starward.Services.SelfQueryService.InitializeAsync(String url, GameBiz gameBiz) in D:\a\Starward\Starward\src\Starward\Services\SelfQueryService.cs:line 40
   at Starward.Pages.SelfQueryPage.InputURLAsync() in D:\a\Starward\Starward\src\Starward\Pages\SelfQueryPage.xaml.cs:line 308

[01:02:44.656] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hk4e_global

[01:02:44.672] [INFO] Starward.Services.GameRecordService
Change region to Global.

[01:07:04.865] [INFO] Starward.Pages.MainPage
Navigate to "SelfQueryPage" with param hk4e_global

[01:08:01.726] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hk4e_global

[01:08:01.738] [INFO] Starward.Services.GameRecordService
Change region to Global.

[01:09:11.168] [INFO] Starward.Pages.MainPage
Navigate to "SelfQueryPage" with param hk4e_global

[01:09:25.356] [EROR] Starward.Pages.SelfQueryPage
Input url
System.ArgumentException: Input url is invalid. (Parameter 'url')
   at Starward.Core.SelfQuery.SelfQueryClient.InitializeAsync(String url, GameBiz gameBiz, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\SelfQuery\SelfQueryClient.cs:line 86
   at Starward.Services.SelfQueryService.InitializeAsync(String url, GameBiz gameBiz) in D:\a\Starward\Starward\src\Starward\Services\SelfQueryService.cs:line 40
   at Starward.Pages.SelfQueryPage.InputURLAsync() in D:\a\Starward\Starward\src\Starward\Pages\SelfQueryPage.xaml.cs:line 308
```

### Additional Context

Purged some personal info from the log. But I couldn't but notice that it makes references to the D: drive. That's weird, those directories do not exist in my D: drive.

**Comment by Scighost** [comment]
Thanks for your feedback. I didn't play in global server, so some features may not be maintained in time. I need time to confirm the problem.

**Comment by ronnywolfy** [comment]
Thank you!

I must add that a day after I wrote this issue, my cookie expired, so I can't refresh until I log back in. But now the app's browser tells me the following:

```
A suitable version of Microsoft Edge WebView2 Runtime was not detected. 
Download and install WebView2Runtime
```

This is despite having used it in 0.11.3 without a problem! And if I try to install WebView2 it tells me it's already installed.

This is probably a separate issue, but it's somewhat related... So I'm gonna write it here.

**Comment by ronnywolfy** [comment]
Good news :)

* About Issue #1
I realized that the Game Notices had stopped working too. So that made me think I should force reinstall WebView2. It worked, but issue #1 also got fixed! I don't know if it was getting corrupted or if Windows Updated messed it up. But it's good now!

* About Issue #2 
I'm unsure about how Traveler's Diary is supposed to work. Does it keep a record of past daily data, or only for today? So should I check it every day to keep detailed records? I'm not sure what's a bug and what's a feature, lol.

**Comment by ronnywolfy** [comment]
Ok, so about Issue 2: It seems my Starward does detect the primos and mora I got through the day

![image](https://github.com/Scighost/Starward/assets/74449146/f9c5e1c3-48a6-42a4-8c5f-5ff23477b8c8)

But does not update the historical data!

![image](https://github.com/Scighost/Starward/assets/74449146/21b1be4a-9353-4a5d-a75c-17729cf785af)

Hope this helps understand the problem a bit more.

**Comment by Scighost** [comment]
@ronnywolfy Sorry for reply so late.

> Spiral Abyss data shows "Picked" and "Combat Stats" data as empty. Does not get fixed on Refresh

If you skipped a period of abyss, these two sections will be empty, and a Paimon emoji will remind you. If this is not the case, please provide a screenshot.

<img src="https://github.com/Scighost/Starward/assets/61003590/edbcedfb-85c8-462d-8236-548b15573262" width="100" />

---

> Traveler Diary data is missing daily data of most days. Does not get fixed on Refresh


`Read-Time Data` and `Historical Data` is the summary updated by `Refresh` button, but `Daily Data` is not. You should get daily data by clicking `Get Details` button under `Refresh`.


---

> Account Records throws `ArgumentException - Input URL  Input url is invalid. (Parameter 'url')`  error when pasting the Feedback link as instructed

This bug will be fixed the next version.

**Comment by Scighost** [comment]
The issue with incorrect URL has been fixed in the preview release.
