### ISSUE TITLE
[Bug] 无法更新

### ISSUE THREAD

**Issue by Emm-GOOD** [Scighost/Starward#762]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

在更新原神4.6版本时遇到了无法更新的情况

### Reproduction Steps

[Uploading step.zip…]()

### Screenshots

![image](https://github.com/Scighost/Starward/assets/154535858/3a813616-eae0-4087-b4b5-274fe79b4ef1)

### Starward Version

0.11.4

### Windows Version

19045.4291

### Log

```shell
[06:58:05.881] [INFO] 
Welcome to Starward v0.11.4
System: Microsoft Windows NT 10.0.19045.0
Command Line: E:\Starward_Portable_0.9.1_x64\Starward\app-0.11.4\Starward.dll download --biz hk4e_cn --loc "F:\Genshin Impact Game" --lang 3

[06:58:05.931] [INFO] Starward.Services.DatabaseService
Database path is 'E:\mihoyo'

[06:58:05.963] [INFO] Starward.Services.DatabaseService
Database version is 8, target version is 8.

[06:58:06.290] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Initialize install game service
biz: hk4e_cn
path: "F:\Genshin Impact Game"
lang: Chinese, English
repair: False
reinstall: False

[06:58:06.346] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Start install game, skipVerify: False

[06:58:06.348] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Prepare for download.

[06:58:07.910] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Update game.

[06:58:07.916] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Request head: "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/zh-cn_4.5.0_4.6.0_hdiff_2a7jHyNe6YWsM3Ob.zip"

[06:58:07.916] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Request head: "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/en-us_4.5.0_4.6.0_hdiff_zY5rUsWHTdvLp76g.zip"

[06:58:07.916] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Request head: "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_4.5.0_4.6.0_hdiff_kiOtCmQKDxTEojvz.zip"

[06:58:11.182] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Start download files.

[06:58:11.183] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
3 files need to download.

[06:58:11.192] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Verify downloaded files.

[06:59:21.371] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Decompress downloaded files.

[06:59:21.372] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Decompress "game_4.5.0_4.6.0_hdiff_kiOtCmQKDxTEojvz.zip"

[06:59:23.451] [EROR] Starward.Services.InstallGame.GenshinInstallGameService
Install game error.
System.UnauthorizedAccessException: Access to the path 'F:\Genshin Impact Game\YuanShen_Data\Plugins\chrome_100_percent.pak' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String, FileMode, FileAccess, FileShare, FileOptions)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1 )
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.FileStream..ctor(String, FileStreamOptions)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry, String, Boolean)
   at Starward.Services.InstallGame.InstallGameService.<>c__DisplayClass83_0.<DecompressFileAsync>b__1() in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 954
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
--- End of stack trace from previous location ---
   at Starward.Services.InstallGame.InstallGameService.DecompressFileAsync(String[] files) in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 922
   at Starward.Services.InstallGame.InstallGameService.DecompressAndApplyDiffPackagesAsync(CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 665
   at Starward.Services.InstallGame.InstallGameService.StartAsync(Boolean skipVerify) in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 257
```

### Additional Context

除chrome，Starward，华为电脑管家和步骤记录器外的任何程序

**Comment by Emm-GOOD** [comment]
Additional Context这里打错了应该是除去chrome，Starward，华为电脑管家和步骤记录器外未打开任何程序

**Comment by FLIP0103** [comment]
I got the same problem and had to reinstall the game 😞

**Comment by Emm-GOOD** [comment]
我就是用官方启动器更新的

**Comment by FLIP0103** [comment]
> 我就是用官方启动器更新的

I tried to do that too but mine said "Game not found". Any idea how I could fix it?

**Comment by Scighost** [comment]
@Emm-GOOD 谢谢你的反馈，此问题的原因是文件夹内的部分文件被设置为已读文件，在更新流程中没有对此做适配，后续版本中会修复

**Comment by Scighost** [comment]
> I tried to do that too but mine said "Game not found". Any idea how I could fix it?

@FLIP0103 In the official launcher, you should click locate game button and then select folder containing `GenshinImpact.exe`.

<img width="212" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/0fbfe7f5-4e9e-453b-b397-d06bfd6cf20d">

**Comment by FLIP0103** [comment]
> > I tried to do that too but mine said "Game not found". Any idea how I could fix it?
> 
> @FLIP0103 In the official launcher, you should click locate game button and then select folder containing `GenshinImpact.exe`.
> 
> <img alt="image" width="212" src="https://private-user-images.githubusercontent.com/61003590/325061476-0fbfe7f5-4e9e-453b-b397-d06bfd6cf20d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5Mjk5NDgsIm5iZiI6MTcxMzkyOTY0OCwicGF0aCI6Ii82MTAwMzU5MC8zMjUwNjE0NzYtMGZiZmU3ZjUtNGU5ZS00NTNiLWIzOTctZDA2YmZkNmNmMjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDAzMzQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNjJhYTAzMGEzZjEzYmNkOWEyMTUxYzk1MjczY2EwM2M4ZDIxYWQwYzQ1Nzg5OTcxOTQ1ZTdhZjE2ZDA1YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.En9UvAjv5fw3yCK1FEyJHq34gJ34jnJcsYb9-1PjDaU">

I tried to do that also but even when I locate the folder that has GenshinImpact.exe, it won't detect it. Should I try to move the game file to another folder and try again?

**Comment by Fightxing** [comment]
将 Plugins 文件夹的只读属性取消即可解决问题

**Comment by DreamToffee** [comment]
> @Emm-GOOD谢谢您的反馈，此问题的原因是文件夹内的部分文件被设置为已读取文件，在更新流程中没有为此做调整，后续版本中会修复

我将Plugins的所有文件都取消了只读，目前可以更新了，会有问题吗
