### ISSUE TITLE
[Bug] 原神的祈愿记录无法读取

### ISSUE THREAD

**Issue by momoblydblk** [Scighost/Starward#764]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

点击更新记录后提示
“Response status code does not indicate success: 404 (Not Found).”
![图片](https://github.com/Scighost/Starward/assets/21081757/ad0ab060-fb71-48da-ab88-6b4a7152eb2a)

### Reproduction Steps

点击更新记录

### Starward Version

0.11.4

### Windows Version

Windows 10 22H2 19045.4291

### Log

```shell
[01:24:16.154] [INFO] Starward.Pages.LauncherPage
Acutal version and gamebiz of hk4e_cn is "4.6.0", hk4e_cn.

[01:24:42.945] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_cn

[01:24:44.418] [EROR] Starward.Pages.GachaLogPage
Update gacha log
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.Json.HttpClientJsonExtensions.<FromJsonAsyncCore>g__Core|12_0[TValue,TJsonOptions](HttpClient, Task`1, Boolean, CancellationTokenSource, Func`4, TJsonOptions, CancellationToken)
   at Starward.Core.Gacha.GachaLogClient.GetGachaLogByQueryAsync[T](String gachaUrlPrefix, GachaLogQuery param, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\Gacha\GachaLogClient.cs:line 266
   at Starward.Core.Gacha.GachaLogClient.GetUidByGachaUrlAsync(String gachaUrl) in D:\a\Starward\Starward\src\Starward.Core\Gacha\GachaLogClient.cs:line 84
   at Starward.Services.Gacha.GachaLogService.GetUidFromGachaLogUrl(String url) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GachaLogService.cs:line 102
   at Starward.Pages.GachaLogPage.UpdateGachaLogInternalAsync(String url, Boolean all) in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 310
   at Starward.Pages.GachaLogPage.UpdateGachaLogAsync(String param) in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 294
```

**Comment by ctf01am** [comment]
的确，这个问题我也碰到了

**Comment by Scighost** [comment]
谢谢反馈，但是你需要更新到最新版本 0.11.5

**Comment by momoblydblk** [comment]
昨晚没给我推更新lol
更新完就没问题了。
