### ISSUE TITLE
[Bug] 4.5無法更新至4.6

### ISSUE THREAD

**Issue by ghost** [Scighost/Starward#765]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

原神4.5無法更新至4.6

### Reproduction Steps

昨天預下載更新，0.11.5後再更新遊戲，跑滿第一次進度條後，第二次進度條一開始跑就報錯

### Screenshots

![image](https://github.com/Scighost/Starward/assets/107019852/13cf6c0c-468a-4878-83be-777ddea1b66b)

### Starward Version

0.11.5

### Windows Version

19045.2965(WIN10 22H2)

### Log

```shell
[18:00:44.301] [INFO] 
Welcome to Starward v0.11.5
System: Microsoft Windows NT 10.0.19045.0
Command Line: C:\Users\R\Desktop\應用程式\Starward_Portable_0.11.2_x64\Starward\app-0.11.5\Starward.dll download --biz hk4e_global --loc "C:\Program Files\Genshin Impact\Genshin Impact game" --lang 15

[18:00:44.336] [INFO] Starward.Services.DatabaseService
Database path is 'C:\Users\R\Documents\2'

[18:00:44.357] [INFO] Starward.Services.DatabaseService
Database version is 8, target version is 8.

[18:00:44.596] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Initialize install game service
biz: hk4e_global
path: "C:\Program Files\Genshin Impact\Genshin Impact game"
lang: All
repair: False
reinstall: False

[18:00:44.634] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Start install game, skipVerify: False

[18:00:44.635] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Prepare for download.

[18:00:44.900] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Update game.

[18:00:44.908] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Request head: "https://autopatchhk.yuanshen.com/client_app/update/hk4e_global/10/zh-cn_4.5.0_4.6.0_hdiff_q8fZULgOsl1SoipB.zip"

[18:00:44.909] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Request head: "https://autopatchhk.yuanshen.com/client_app/update/hk4e_global/10/game_4.5.0_4.6.0_hdiff_MyQqNZPJWOktACjI.zip"

[18:00:44.908] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Request head: "https://autopatchhk.yuanshen.com/client_app/update/hk4e_global/10/en-us_4.5.0_4.6.0_hdiff_aRk4uMi1H9OALJ7d.zip"

[18:00:44.908] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Request head: "https://autopatchhk.yuanshen.com/client_app/update/hk4e_global/10/ja-jp_4.5.0_4.6.0_hdiff_dNhr1mUeITOnZ76R.zip"

[18:00:44.908] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Request head: "https://autopatchhk.yuanshen.com/client_app/update/hk4e_global/10/ko-kr_4.5.0_4.6.0_hdiff_wrnM3Vumg5xSbKEa.zip"

[18:00:45.212] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Start download files.

[18:00:45.212] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
5 files need to download.

[18:00:45.214] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Verify downloaded files.

[18:01:54.756] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Decompress downloaded files.

[18:01:54.756] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Decompress "game_4.5.0_4.6.0_hdiff_MyQqNZPJWOktACjI.zip"

[18:01:56.608] [EROR] Starward.Services.InstallGame.GenshinInstallGameService
Install game error.
System.UnauthorizedAccessException: Access to the path 'C:\Program Files\Genshin Impact\Genshin Impact game\GenshinImpact_Data\Plugins\chrome_100_percent.pak' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String, FileMode, FileAccess, FileShare, FileOptions)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1 )
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.FileStream..ctor(String, FileStreamOptions)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry, String, Boolean)
   at Starward.Services.InstallGame.InstallGameService.<>c__DisplayClass83_0.<DecompressFileAsync>b__1() in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 954
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
--- End of stack trace from previous location ---
   at Starward.Services.InstallGame.InstallGameService.DecompressFileAsync(String[] files) in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 922
   at Starward.Services.InstallGame.InstallGameService.DecompressAndApplyDiffPackagesAsync(CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 665
   at Starward.Services.InstallGame.InstallGameService.StartAsync(Boolean skipVerify) in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 257

[18:03:13.891] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Start install game, skipVerify: False

[18:03:13.891] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Prepare for download.

[18:03:14.077] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Update game.

[18:03:14.080] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Request head: "https://autopatchhk.yuanshen.com/client_app/update/hk4e_global/10/game_4.5.0_4.6.0_hdiff_MyQqNZPJWOktACjI.zip"

[18:03:14.080] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Request head: "https://autopatchhk.yuanshen.com/client_app/update/hk4e_global/10/zh-cn_4.5.0_4.6.0_hdiff_q8fZULgOsl1SoipB.zip"

[18:03:14.080] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Request head: "https://autopatchhk.yuanshen.com/client_app/update/hk4e_global/10/en-us_4.5.0_4.6.0_hdiff_aRk4uMi1H9OALJ7d.zip"

[18:03:14.080] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Request head: "https://autopatchhk.yuanshen.com/client_app/update/hk4e_global/10/ja-jp_4.5.0_4.6.0_hdiff_dNhr1mUeITOnZ76R.zip"

[18:03:14.080] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Request head: "https://autopatchhk.yuanshen.com/client_app/update/hk4e_global/10/ko-kr_4.5.0_4.6.0_hdiff_wrnM3Vumg5xSbKEa.zip"

[18:03:14.234] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Start download files.

[18:03:14.234] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
5 files need to download.

[18:03:14.234] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Verify downloaded files.

[18:04:16.267] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Decompress downloaded files.

[18:04:16.268] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Decompress "game_4.5.0_4.6.0_hdiff_MyQqNZPJWOktACjI.zip"

[18:04:17.789] [EROR] Starward.Services.InstallGame.GenshinInstallGameService
Install game error.
System.UnauthorizedAccessException: Access to the path 'C:\Program Files\Genshin Impact\Genshin Impact game\GenshinImpact_Data\Plugins\chrome_100_percent.pak' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String, FileMode, FileAccess, FileShare, FileOptions)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1 )
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.FileStream..ctor(String, FileStreamOptions)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry, String, Boolean)
   at Starward.Services.InstallGame.InstallGameService.<>c__DisplayClass83_0.<DecompressFileAsync>b__1() in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 954
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
--- End of stack trace from previous location ---
   at Starward.Services.InstallGame.InstallGameService.DecompressFileAsync(String[] files) in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 922
   at Starward.Services.InstallGame.InstallGameService.DecompressAndApplyDiffPackagesAsync(CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 665
   at Starward.Services.InstallGame.InstallGameService.StartAsync(Boolean skipVerify) in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 257
```

**Comment by Scighost** [comment]
#762
