### ISSUE TITLE
Unable to install the game

### ISSUE THREAD

**Issue by laoxke** [Scighost/Starward#767]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

My file verification is correct, there is sufficient hard drive space, but I cannot decompress it. Please help me, thank you very much!

### Starward Version

v0.11.5

### Windows Version

10.0.19045.0

### Log

```shell
[21:16:23.207] [INFO] 
Welcome to Starward v0.11.5
System: Microsoft Windows NT 10.0.19045.0
Command Line: F:\整合启动器\Starward_Portable_0.10.1_x64_2\Starward\app-0.11.5\Starward.dll download --biz hk4e_cn --loc "F:\微信接受的文件\WeChat Files\wxid_4possjaw63z11\Genshin Impact\Genshin Impact Game" --lang 1

[21:16:23.243] [INFO] Starward.Services.DatabaseService
Database path is 'F:\整合启动器\Starward_Portable_0.10.1_x64_2\Starward'

[21:16:23.264] [INFO] Starward.Services.DatabaseService
Database version is 8, target version is 8.

[21:16:23.515] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Initialize install game service
biz: hk4e_cn
path: "F:\微信接受的文件\WeChat Files\wxid_4possjaw63z11\Genshin Impact\Genshin Impact Game"
lang: Chinese
repair: False
reinstall: False

[21:16:23.538] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Start install game, skipVerify: False

[21:16:23.540] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Prepare for download.

[21:16:23.933] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Update game.

[21:16:23.940] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Request head: "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/zh-cn_4.5.0_4.6.0_hdiff_2a7jHyNe6YWsM3Ob.zip"

[21:16:23.940] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Request head: "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_4.5.0_4.6.0_hdiff_kiOtCmQKDxTEojvz.zip"

[21:16:24.103] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Start download files.

[21:16:24.103] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
2 files need to download.

[21:16:24.108] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Verify downloaded files.

[21:16:25.662] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Start install game, skipVerify: True

[21:16:25.662] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Prepare for download.

[21:16:25.665] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Update game.

[21:16:25.666] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Request head: "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_4.5.0_4.6.0_hdiff_kiOtCmQKDxTEojvz.zip"

[21:16:25.667] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Request head: "https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/zh-cn_4.5.0_4.6.0_hdiff_2a7jHyNe6YWsM3Ob.zip"

[21:16:25.781] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Start download files.

[21:16:25.781] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
2 files need to download.

[21:16:25.783] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Skip verify downloaded files.

[21:16:25.783] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Skip verify: "game_4.5.0_4.6.0_hdiff_kiOtCmQKDxTEojvz.zip"

[21:16:25.784] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Decompress downloaded files.

[21:16:25.785] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Decompress "game_4.5.0_4.6.0_hdiff_kiOtCmQKDxTEojvz.zip"

[21:16:27.865] [EROR] Starward.Services.InstallGame.GenshinInstallGameService
Install game error.
System.UnauthorizedAccessException: Access to the path 'F:\微信接受的文件\WeChat Files\wxid_4possjaw63z11\Genshin Impact\Genshin Impact Game\YuanShen_Data\Plugins\chrome_100_percent.pak' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String, FileMode, FileAccess, FileShare, FileOptions)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1 )
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.FileStream..ctor(String, FileStreamOptions)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry, String, Boolean)
   at Starward.Services.InstallGame.InstallGameService.<>c__DisplayClass83_0.<DecompressFileAsync>b__1() in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 954
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
--- End of stack trace from previous location ---
   at Starward.Services.InstallGame.InstallGameService.DecompressFileAsync(String[] files) in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 922
   at Starward.Services.InstallGame.InstallGameService.DecompressAndApplyDiffPackagesAsync(CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 665
   at Starward.Services.InstallGame.InstallGameService.StartAsync(Boolean skipVerify) in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 257
```

**Comment by Scighost** [comment]
#762
