### ISSUE TITLE
[Bug] 新账号的抽卡记录获取不到

### ISSUE THREAD

**Issue by cangerjun** [Scighost/Starward#780]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

如果24小时内获取过账号抽卡记录，直播扫码登录的新账号无法获取抽卡记录，只会更新原先的账号的抽卡记录。

### Reproduction Steps

登录-打卡抽卡记录-软件获取抽卡记录统计-退出登陆-登录新账号-打卡抽卡记录-软件获取抽卡记录统计

### Expected Behavior

录新账号-打卡抽卡记录-软件获取新账号的抽卡记录数据

### Starward Version

0.115

### Windows Version

26100.268

### Log

```shell
[22:27:35.314] [INFO] 
Welcome to Starward v0.11.5
System: Microsoft Windows NT 10.0.26100.0
Command Line: F:\Starward\app-0.11.5\Starward.dll

[22:27:36.543] [INFO] Starward.Services.DatabaseService
Database path is 'F:\Starward'

[22:27:37.547] [INFO] Starward.Services.DatabaseService
Database version is 8, target version is 8.

[22:27:39.978] [INFO] Starward.Pages.MainPage
Last game region is hk4e_cn

[22:27:40.394] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[22:27:42.448] [WARN] Starward.Services.GameResourceService
config.ini not found: "G:\Genshin Impact Cloud Game\config.ini"

[22:27:43.485] [WARN] Starward.Services.GameResourceService
config.ini not found: "G:\Genshin Impact Cloud Game\config.ini"

[22:27:43.572] [INFO] Starward.Pages.LauncherPage
Game install path of hk4e_cn: "F:\Genshin Impact Game"

[22:27:43.963] [INFO] Starward.Pages.LauncherPage
Acutal version and gamebiz of hk4e_cn is "4.6.0", hk4e_cn.

[22:27:45.724] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[22:27:47.005] [INFO] Starward.Services.GameService
Start game (hk4e_cn)
path: "F:\Genshin Impact Game\YuanShen.exe"
arg: "-popupwindow"

[22:27:47.398] [INFO] Starward.Pages.LauncherPage
Game started ("YuanShen", 8236)

[22:27:49.406] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hk4e_cn, 8236)

[22:27:49.733] [INFO] Starward.Services.UpdateService
Current version: "0.11.5", latest version: "0.11.5", ignore version: null

[22:43:46.656] [INFO] Starward.Pages.MainPage
Navigate to "GameSettingPage" with param hk4e_cn

[22:43:47.763] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_cn

[22:44:00.766] [INFO] Starward.Services.Gacha.GenshinGachaService
Last gacha log id of uid 214472706 is 1714536360005259406

[22:44:43.219] [INFO] Starward.Services.Gacha.GenshinGachaService
Last gacha log id of uid 214472706 is 1714536360005259406

[22:45:21.840] [INFO] Starward.Services.Gacha.GenshinGachaService
Last gacha log id of uid 214472706 is 1714536360005259406

[22:46:03.048] [EROR] Starward.Pages.GachaLogPage
Input url
System.ArgumentException: 无法解析祈愿记录的 URL
   at Starward.Core.Gacha.Genshin.GenshinGachaClient.GetGachaUrlPrefix(String gachaUrl, String lang) in D:\a\Starward\Starward\src\Starward.Core\Gacha\Genshin\GenshinGachaClient.cs:line 63
   at Starward.Core.Gacha.GachaLogClient.GetUidByGachaUrlAsync(String gachaUrl) in D:\a\Starward\Starward\src\Starward.Core\Gacha\GachaLogClient.cs:line 80
   at Starward.Services.Gacha.GachaLogService.GetUidFromGachaLogUrl(String url) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GachaLogService.cs:line 102
   at Starward.Pages.GachaLogPage.UpdateGachaLogInternalAsync(String url, Boolean all) in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 310
   at Starward.Pages.GachaLogPage.InputUrlAsync() in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 410

[22:46:23.375] [EROR] Starward.Pages.GachaLogPage
Input url
System.ArgumentException: 无法解析祈愿记录的 URL
   at Starward.Core.Gacha.Genshin.GenshinGachaClient.GetGachaUrlPrefix(String gachaUrl, String lang) in D:\a\Starward\Starward\src\Starward.Core\Gacha\Genshin\GenshinGachaClient.cs:line 63
   at Starward.Core.Gacha.GachaLogClient.GetUidByGachaUrlAsync(String gachaUrl) in D:\a\Starward\Starward\src\Starward.Core\Gacha\GachaLogClient.cs:line 80
   at Starward.Services.Gacha.GachaLogService.GetUidFromGachaLogUrl(String url) in D:\a\Starward\Starward\src\Starward\Services\Gacha\GachaLogService.cs:line 102
   at Starward.Pages.GachaLogPage.UpdateGachaLogInternalAsync(String url, Boolean all) in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 310
   at Starward.Pages.GachaLogPage.InputUrlAsync() in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 410
```

**Comment by Scighost** [comment]
谢谢你的反馈，请先关闭游戏，然后在抽卡页面的设置中点击**清除URL缓存文件**

<img width="163" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/734d88bb-9adb-4aab-b29e-52987a4a4a0f">
