### ISSUE TITLE
[Question] starward显示本地游戏版本不是最新不让我换b服

### ISSUE THREAD

**Issue by Katsumuxue** [Scighost/Starward#834]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

米哈游启动器已将崩铁更新为最新版本，starward切换服务器界面显示不是本地最新版本不让改b服，点击一键修复以后可以换服务器了，但是版本变成过去游戏版本，无法游玩
![BP09_JUT (K}SAIQ41Y)NM5](https://github.com/Scighost/Starward/assets/154076131/004577b1-0c95-4174-8fc5-2f1ab9722d12)

### Starward Version

0.11.6

### Windows Version

19045.4529

### Log

```shell
[00:46:14.071] [INFO] 
Welcome to Starward v0.11.6
System: Microsoft Windows NT 10.0.19045.0
Command Line: G:\Starward_Portable_0.11.6_x64\Starward\app-0.11.6\Starward.dll

[00:46:33.030] [INFO] Starward.Pages.Welcome.SelectDirectoryPage
Select directory is '"G:\Starward_Portable_0.11.6_x64\Starward"'

[00:46:41.353] [INFO] Starward.Pages.Welcome.SelectGamePage
Change game region to hkrpg_bilibili

[00:46:43.086] [INFO] Starward.Pages.Welcome.SelectGamePage
Change game region to hkrpg_cn

[00:46:46.747] [INFO] Starward.Services.DatabaseService
Database path is 'G:\Starward_Portable_0.11.6_x64\Starward'

[00:46:46.759] [INFO] Starward.Services.DatabaseService
Database version is 0, target version is 8.

[00:46:49.835] [INFO] Starward.Pages.MainPage
Last game region is hkrpg_cn

[00:46:49.838] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_cn

[00:46:50.167] [INFO] Starward.Pages.LauncherPage
Game install path of hkrpg_cn: null

[00:46:50.168] [INFO] Starward.Pages.LauncherPage
Acutal version and gamebiz of hkrpg_cn is null, None.

[00:46:50.214] [WARN] Starward.Services.LauncherContentService
Background of mihoyo api is null (hkrpg_cn)

[00:46:51.157] [INFO] Starward.Services.UpdateService
Start to check update (Preview: False, Arch: X64)

[00:46:53.480] [INFO] Starward.Services.UpdateService
Current version: "0.11.6", latest version: "0.11.6", ignore version: null

[00:47:01.387] [INFO] Starward.Pages.LauncherPage
Change game install path (hkrpg_cn): "G:\miHoYo Launcher\games\Star Rail Game"

[00:47:01.391] [INFO] Starward.Pages.LauncherPage
Game install path of hkrpg_cn: "G:\miHoYo Launcher\games\Star Rail Game"

[00:47:01.396] [INFO] Starward.Pages.LauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.3.0", hkrpg_cn.

[00:47:25.638] [INFO] Starward.Services.GameService
Start game (hkrpg_cn)
path: "G:\miHoYo Launcher\games\Star Rail Game\StarRail.exe"
arg: null

[00:47:25.734] [INFO] Starward.Pages.LauncherPage
Game started ("StarRail", 22108)

[00:47:27.749] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hkrpg_cn, 22108)

[00:47:47.762] [INFO] Starward.Pages.LauncherPage
Game process exited

[00:47:47.767] [INFO] Starward.Pages.LauncherPage
Game is running ("StarRail", 22108)

[00:47:48.771] [INFO] Starward.Pages.LauncherPage
Game process exited

[00:48:07.923] [INFO] Starward.Pages.MainPage
Navigate to "GameSettingPage" with param hkrpg_cn

[00:48:07.954] [INFO] Starward.Services.GameSettingService
Voice language of game hkrpg_cn is null

[00:48:12.382] [INFO] Starward.Pages.MainPage
Navigate to "ScreenshotPage" with param hkrpg_cn

[00:48:12.433] [WARN] Starward.Pages.ScreenshotPage
Cannot find screenshot folder

[00:48:14.086] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hkrpg_cn

[00:48:14.091] [INFO] Starward.Services.GameRecordService
Change region to China.

[00:48:23.294] [INFO] Starward.Pages.MainPage
Navigate to "SelfQueryPage" with param hkrpg_cn

[00:48:43.411] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_cn

[00:48:43.464] [INFO] Starward.Pages.LauncherPage
Game install path of hkrpg_cn: "G:\miHoYo Launcher\games\Star Rail Game"

[00:48:43.474] [INFO] Starward.Pages.LauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.3.0", hkrpg_cn.

[00:52:38.727] [WARN] Starward.Services.LauncherContentService
Background of mihoyo api is null (hkrpg_cn)

[00:52:46.165] [INFO] Starward.Services.LauncherContentService
Background file is '"F:\图片\1697097338272.png"'

[00:52:46.166] [EROR] Starward.Services.LauncherContentService
Change custom background
System.IO.DirectoryNotFoundException: Could not find a part of the path 'G:\Starward_Portable_0.11.6_x64\Starward\bg\1697097338272.png'.
   at System.IO.FileSystem.CopyFile(String, String, Boolean)
   at Starward.Services.LauncherContentService.ChangeCustomBgAsync() in D:\a\Starward\Starward\src\Starward\Services\LauncherContentService.cs:line 222

[00:52:54.141] [INFO] Starward.Services.LauncherContentService
Background file is '"F:\图片\1697097338272.png"'

[00:52:54.142] [EROR] Starward.Services.LauncherContentService
Change custom background
System.IO.DirectoryNotFoundException: Could not find a part of the path 'G:\Starward_Portable_0.11.6_x64\Starward\bg\1697097338272.png'.
   at System.IO.FileSystem.CopyFile(String, String, Boolean)
   at Starward.Services.LauncherContentService.ChangeCustomBgAsync() in D:\a\Starward\Starward\src\Starward\Services\LauncherContentService.cs:line 222

[00:53:00.457] [INFO] Starward.Services.LauncherContentService
Background file is '"F:\图片\1668421052361_edit_53605078385049.jpg"'

[00:53:00.461] [EROR] Starward.Services.LauncherContentService
Change custom background
System.IO.DirectoryNotFoundException: Could not find a part of the path 'G:\Starward_Portable_0.11.6_x64\Starward\bg\1668421052361_edit_53605078385049.jpg'.
   at System.IO.FileSystem.CopyFile(String, String, Boolean)
   at Starward.Services.LauncherContentService.ChangeCustomBgAsync() in D:\a\Starward\Starward\src\Starward\Services\LauncherContentService.cs:line 222

[00:53:04.444] [INFO] Starward.Services.LauncherContentService
Background file is '"F:\图片\Screenshot_20231011_154654_edit_2695723746937622.jpg"'

[00:53:04.445] [EROR] Starward.Services.LauncherContentService
Change custom background
System.IO.DirectoryNotFoundException: Could not find a part of the path 'G:\Starward_Portable_0.11.6_x64\Starward\bg\Screenshot_20231011_154654_edit_2695723746937622.jpg'.
   at System.IO.FileSystem.CopyFile(String, String, Boolean)
   at Starward.Services.LauncherContentService.ChangeCustomBgAsync() in D:\a\Starward\Starward\src\Starward\Services\LauncherContentService.cs:line 222

[01:05:05.613] [WARN] Starward.Services.LauncherContentService
Background of mihoyo api is null (hkrpg_cn)

[01:11:03.488] [INFO] Starward.Pages.SwitchClientPage
Start switching client.

[01:11:06.587] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_bilibili

[01:11:06.591] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_bilibili

[01:11:06.630] [WARN] Starward.Services.LauncherContentService
Background of mihoyo api is null (hkrpg_bilibili)

[01:11:06.643] [INFO] Starward.Pages.LauncherPage
Game install path of hkrpg_bilibili: "G:\miHoYo Launcher\games\Star Rail Game"

[01:11:06.654] [INFO] Starward.Pages.LauncherPage
Acutal version and gamebiz of hkrpg_bilibili is "2.2.0", hkrpg_bilibili.

[01:11:07.812] [INFO] Starward.Services.GameService
Start game (hkrpg_bilibili)
path: "G:\miHoYo Launcher\games\Star Rail Game\StarRail.exe"
arg: null

[01:11:07.892] [INFO] Starward.Pages.LauncherPage
Game started ("StarRail", 6296)

[01:11:09.897] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hkrpg_bilibili, 6296)

[01:11:32.913] [INFO] Starward.Pages.LauncherPage
Game process exited

[01:11:32.919] [INFO] Starward.Pages.LauncherPage
Game is running ("StarRail", 6296)

[01:11:33.921] [INFO] Starward.Pages.LauncherPage
Game process exited

[01:25:10.194] [EROR] Starward.Pages.GameResourcePage
Copy url failed
System.Runtime.InteropServices.COMException (0x800401D0)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32)
   at ABI.Windows.ApplicationModel.DataTransfer.IClipboardStaticsMethods.Flush(IObjectReference)
   at Starward.Pages.GameResourcePage.Button_CopyUrl_Click(Object sender, RoutedEventArgs e) in D:\a\Starward\Starward\src\Starward\Pages\GameResourcePage.xaml.cs:line 221
```

**Comment by Eric-Joker** [comment]
试试https://github.com/Eric-Joker/Starward/actions/runs/9589003640
#830

**Comment by shiroringo** [comment]
官方的崩铁启动器不能用了，改成米哈游启动器了，盲猜是这个原因

**Comment by link-fgfgui** [comment]
不用猜，就是
