### ISSUE TITLE
[Bug] 启动器背景图片无法正常加载

### ISSUE THREAD

**Issue by wtcpython** [Scighost/Starward#880]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

只有原神的背景图能加载出来，切断到其他游戏背景图没有反应。如果在启动器加载的时候启动的不是原神而是其他游戏，那么背景图将变成黑色背景。

### Reproduction Steps

只有原神的背景图能加载出来，切断到其他游戏背景图没有反应。如果在启动器加载的时候启动的不是原神而是其他游戏，那么背景图将变成黑色背景。

### Screenshots

![image](https://github.com/Scighost/Starward/assets/119155053/8fc49f1c-97e1-47e0-a795-5b446330741f)
![image](https://github.com/Scighost/Starward/assets/119155053/82788ac4-4984-452a-9b01-5e05bbaa5cf1)

### Starward Version

0.11.7-preview4

### Windows Version

22631.3810

### Log

```shell
[23:03:16.418] [INFO] 
Welcome to Starward v0.11.7-preview.4
System: Microsoft Windows NT 10.0.22631.0
Command Line: "D:\Program Files\Starward\app-0.11.7-preview.4\Starward.dll"

[23:03:16.451] [INFO] Starward.Services.DatabaseService
Database path is 'D:\Program Files\Starward'

[23:03:16.471] [INFO] Starward.Services.DatabaseService
Database version is 8, target version is 8.

[23:03:16.527] [INFO] Starward.Pages.MainPage
Last game region is hkrpg_cn

[23:03:16.537] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hkrpg_cn

[23:03:17.226] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "D:\Program Files\miHoYo Launcher\games\Star Rail Game"

[23:03:17.249] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.3.0".

[23:03:17.335] [WARN] Starward.Pages.MainPage
Update background image
System.Runtime.InteropServices.COMException (0x88982F8B)
   at Starward.Pages.MainPage.UpdateBackgroundImageAsync(Boolean force) in D:\a\Starward\Starward\src\Starward\Pages\MainPage.xaml.cs:line 362

[23:03:18.224] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[23:03:19.141] [INFO] Starward.Services.UpdateService
Current version: "0.11.7-preview.4", latest version: "0.11.7-preview.4", ignore version: null

[23:03:19.463] [EROR] Starward.MyWindows.UpdateContentWindow
Load recent update content
System.Runtime.InteropServices.COMException (0x8007139F): 组或资源的状态不是执行请求操作的正确状态。

组或资源的状态不是执行请求操作的正确状态。

   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32)
   at ABI.Microsoft.Web.WebView2.Core.ICoreWebView2_13Methods.get_Profile(IObjectReference)
   at Starward.MyWindows.UpdateContentWindow.LoadPageAsync() in D:\a\Starward\Starward\src\Starward\MyWindows\UpdateContentWindow.xaml.cs:line 253
```

**Comment by zqsrios** [comment]
同样的问题

**Comment by zqsrios** [comment]
微软商店安装 Webp 图像扩展 解决

**Comment by gongfuture** [comment]
这个问题在 https://github.com/Scighost/Starward/releases/tag/0.11.7-dev.1 发布详情里有说的

**Comment by xibaibai9527** [comment]
但是，我用的是LTSC版本的windows10，没有微软商店该怎么办哪。。。
以前安装过，不能挂梯子，卡的要死，重装后就再没装过了。。。
