### ISSUE TITLE
[Bug] 绝区零导出调频记录失败，提示The method or operation is not implemented

### ISSUE THREAD

**Issue by Nexar1s** [Scighost/Starward#919]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

绝区零导出调频记录失败，导出为Json或者Excel都会提示**The method or operation is not implemented**。然后指定目录出现一个空的调频记录文件。

### Reproduction Steps

进入调频记录界面从右上角设置点击导出为Json

### Expected Behavior

正常导出调频记录文件

### Screenshots

![9279eb7a4104a3e8b607d77940eff116](https://github.com/Scighost/Starward/assets/101399556/77c7d412-7b4a-4766-b502-e4a663720d3d)

### Starward Version

v0.11.7-preview.7

### Windows Version

22631.0

### Log

```shell
[12:00:05.424] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "D:\Program Files\miHoYo Launcher\games\ZenlessZoneZero Game"

[12:00:05.444] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.0.0".

[12:00:05.944] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param nap_cn

[12:00:26.826] [EROR] Starward.Pages.GachaLogPage
Export gacha log
System.NotImplementedException: The method or operation is not implemented.
   at Starward.Services.Gacha.ZZZGachaService.ExportGachaLogAsync(Int64 uid, String file, String format) in D:\a\Starward\Starward\src\Starward\Services\Gacha\ZZZGachaService.cs:line 210
   at Starward.Pages.GachaLogPage.ExportGachaLogAsync(String format) in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 672

[12:00:41.154] [EROR] Starward.Pages.GachaLogPage
Export gacha log
System.NotImplementedException: The method or operation is not implemented.
   at Starward.Services.Gacha.ZZZGachaService.ExportGachaLogAsync(Int64 uid, String file, String format) in D:\a\Starward\Starward\src\Starward\Services\Gacha\ZZZGachaService.cs:line 210
   at Starward.Pages.GachaLogPage.ExportGachaLogAsync(String format) in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 672

[12:01:05.156] [EROR] Starward.Pages.GachaLogPage
Export gacha log
System.NotImplementedException: The method or operation is not implemented.
   at Starward.Services.Gacha.ZZZGachaService.ExportGachaLogAsync(Int64 uid, String file, String format) in D:\a\Starward\Starward\src\Starward\Services\Gacha\ZZZGachaService.cs:line 210
   at Starward.Pages.GachaLogPage.ExportGachaLogAsync(String format) in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 672

[12:05:19.726] [EROR] Starward.Pages.GachaLogPage
Export gacha log
System.NotImplementedException: The method or operation is not implemented.
   at Starward.Services.Gacha.ZZZGachaService.ExportGachaLogAsync(Int64 uid, String file, String format) in D:\a\Starward\Starward\src\Starward\Services\Gacha\ZZZGachaService.cs:line 210
   at Starward.Pages.GachaLogPage.ExportGachaLogAsync(String format) in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 672

[12:05:31.383] [EROR] Starward.Pages.GachaLogPage
Export gacha log
System.NotImplementedException: The method or operation is not implemented.
   at Starward.Services.Gacha.ZZZGachaService.ExportGachaLogAsync(Int64 uid, String file, String format) in D:\a\Starward\Starward\src\Starward\Services\Gacha\ZZZGachaService.cs:line 210
   at Starward.Pages.GachaLogPage.ExportGachaLogAsync(String format) in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 672

[12:07:45.444] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[12:07:45.445] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hkrpg_cn

[12:08:41.859] [INFO] Starward.Pages.MainPage
Change game region to nap_cn

[12:08:41.859] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param nap_cn

[12:09:17.236] [EROR] Starward.Pages.GachaLogPage
Export gacha log
System.NotImplementedException: The method or operation is not implemented.
   at Starward.Services.Gacha.ZZZGachaService.ExportGachaLogAsync(Int64 uid, String file, String format) in D:\a\Starward\Starward\src\Starward\Services\Gacha\ZZZGachaService.cs:line 210
   at Starward.Pages.GachaLogPage.ExportGachaLogAsync(String format) in D:\a\Starward\Starward\src\Starward\Pages\GachaLogPage.xaml.cs:line 672
```

**Comment by Scighost** [comment]
暂时还不支持导入导出zzz的抽卡记录
