### ISSUE TITLE
[Bug] 无法记录绝区零启动时间

### ISSUE THREAD

**Issue by KongChengs** [Scighost/Starward#922]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

绝区零启动时与启动后点击刷新按钮没有刷新出启动时间与运行时间，且关闭游戏后仍显示”游戏正在运行中“，点击其他游戏页面后切换回来则恢复正常，但是启动时间始终保持为零。原神和星穹铁道时长统计功能正常。

### Reproduction Steps

打开游戏后，点击游戏时长，点击刷新，运行时长和启动时间没有显示。

### Screenshots

![微信图片_20240707163628](https://github.com/Scighost/Starward/assets/56058393/768600ca-eb98-40aa-925f-0e19e2133db9)
点击刷新后没有显示时长

### Starward Version

0.11.7-preview.7

### Windows Version

19045.4529

### Log

```shell
[07:10:13.254] [INFO] 
Welcome to Starward v0.11.7-preview.7
System: Microsoft Windows NT 10.0.19045.0
Command Line: F:\Starward\Starward\app-0.11.7-preview.7\Starward.dll

[07:10:24.896] [INFO] Starward.Pages.Welcome.SelectDirectoryPage
Select directory is '"F:\Starward\Starward"'

[07:10:25.838] [INFO] Starward.Services.DatabaseService
Database path is 'F:\Starward\Starward'

[07:10:25.859] [INFO] Starward.Services.DatabaseService
Database version is 0, target version is 9.

[07:10:27.629] [INFO] Starward.Pages.MainPage
Last game region is None

[07:10:28.062] [EROR] Starward.Pages.MainPage
Update background image
System.ArgumentOutOfRangeException: Unknown launcher id. (Parameter 'launcherId')
   at Starward.Core.HoYoPlay.HoYoPlayClient.BuildUrl(String api, String launcherId, String language) in D:\a\Starward\Starward\src\Starward.Core\HoYoPlay\HoYoPlayClient.cs:line 78
   at Starward.Core.HoYoPlay.HoYoPlayClient.GetGameBackgroundAsync(String launcherId, String language, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\HoYoPlay\HoYoPlayClient.cs:line 109
   at Starward.Services.HoYoPlayService.GetGameBackgroundAsync(GameBiz biz) in D:\a\Starward\Starward\src\Starward\Services\HoYoPlayService.cs:line 274
   at Starward.Services.Launcher.LauncherBackgroundService.GetBackgroundImageUrlAsync(GameBiz gameBiz, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\Launcher\LauncherBackgroundService.cs:line 102
   at Starward.Services.Launcher.LauncherBackgroundService.GetBackgroundImageAsync(GameBiz gameBiz, Boolean disableCustom) in D:\a\Starward\Starward\src\Starward\Services\Launcher\LauncherBackgroundService.cs:line 125
   at Starward.Pages.MainPage.UpdateBackgroundImageAsync(Boolean force) in D:\a\Starward\Starward\src\Starward\Pages\MainPage.xaml.cs:line 340

[07:10:29.138] [INFO] Starward.Services.UpdateService
Start to check update (Preview: False, Arch: X64)

[07:10:29.815] [INFO] Starward.Services.UpdateService
Current version: "0.11.7-preview.7", latest version: "0.11.7-preview.4", ignore version: null

[07:10:40.662] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[07:10:40.663] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hkrpg_cn

[07:10:41.149] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "F:\miHoYo Launcher\games\Star Rail Game"

[07:10:41.170] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.3.0".

[07:10:41.666] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[07:10:41.666] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[07:10:42.069] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "F:\miHoYo Launcher\games\Genshin Impact Game"

[07:10:42.080] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "4.7.0".

[07:10:50.478] [INFO] Starward.Pages.MainPage
Change game region to nap_cn

[07:10:50.480] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param nap_cn

[07:10:50.885] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "F:\miHoYo Launcher\games\ZenlessZoneZero Game"

[07:10:50.912] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.0.0".

[07:10:58.277] [INFO] Starward.Pages.MainPage
Change game region to nap_cn

[07:10:58.277] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param nap_cn

[07:10:58.360] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "F:\miHoYo Launcher\games\ZenlessZoneZero Game"

[07:10:58.389] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.0.0".

[07:11:04.237] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (nap_cn)
path: "F:\miHoYo Launcher\games\ZenlessZoneZero Game\ZenlessZoneZero.exe"
arg: null

[07:11:05.756] [INFO] Starward.Pages.GameLauncherPage
Game started ("ZenlessZoneZero", 39892)

[07:11:07.766] [INFO] Starward.Services.PlayTimeService
Start to log playtime (nap_cn, 34304)

[07:11:30.326] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[07:11:30.327] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hkrpg_cn

[07:11:30.580] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "F:\miHoYo Launcher\games\Star Rail Game"

[07:11:30.626] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.3.0".

[07:11:30.951] [INFO] Starward.Pages.MainPage
Change game region to nap_cn

[07:11:30.953] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param nap_cn

[07:11:31.178] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "F:\miHoYo Launcher\games\ZenlessZoneZero Game"

[07:11:31.206] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.0.0".

[07:11:36.874] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "F:\miHoYo Launcher\games\ZenlessZoneZero Game"

[07:11:36.875] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.0.0".

[07:11:41.179] [INFO] Starward.Pages.GameLauncherPage
Change game install path (nap_cn): "F:\miHoYo Launcher\games\ZenlessZoneZero Game"

[07:11:41.179] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "F:\miHoYo Launcher\games\ZenlessZoneZero Game"

[07:11:41.187] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.0.0".

[07:11:42.981] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[07:11:42.982] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hkrpg_cn

[07:11:43.146] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "F:\miHoYo Launcher\games\Star Rail Game"

[07:11:43.184] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.3.0".

[07:11:46.566] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[07:11:46.566] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[07:11:46.766] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "F:\miHoYo Launcher\games\Genshin Impact Game"

[07:11:46.805] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "4.7.0".

[07:11:50.446] [INFO] Starward.Pages.MainPage
Change game region to nap_cn

[07:11:50.447] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param nap_cn

[07:11:50.612] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "F:\miHoYo Launcher\games\ZenlessZoneZero Game"

[07:11:50.691] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.0.0".

[07:12:28.207] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[07:12:28.943] [INFO] Starward.Services.UpdateService
Current version: "0.11.7-preview.7", latest version: "0.11.7-preview.7", ignore version: null

[07:12:31.502] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[07:12:31.503] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[07:12:31.758] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "F:\miHoYo Launcher\games\Genshin Impact Game"

[07:12:31.795] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "4.7.0".

[07:12:33.268] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hk4e_cn)
path: "F:\miHoYo Launcher\games\Genshin Impact Game\YuanShen.exe"
arg: null

[07:12:34.940] [INFO] Starward.Services.Launcher.GameLauncherService
Start game operation canceled.

[07:12:44.935] [INFO] Starward.Services.GameAccountService
Save account "倾城" (hk4e_cn) successfully!

[07:12:47.372] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hk4e_cn)
path: "F:\miHoYo Launcher\games\Genshin Impact Game\YuanShen.exe"
arg: null

[07:12:49.017] [INFO] Starward.Pages.GameLauncherPage
Game started ("YuanShen", 48160)

[07:12:51.035] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hk4e_cn, 48160)

[07:27:12.051] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[07:27:12.062] [INFO] Starward.Pages.GameLauncherPage
Game is running ("YuanShen", 48160)

[07:27:13.079] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[07:27:13.087] [INFO] Starward.Pages.GameLauncherPage
Game is running ("YuanShen", 48160)

[07:27:14.088] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[07:43:28.500] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[07:43:28.500] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hkrpg_cn

[07:43:29.368] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "F:\miHoYo Launcher\games\Star Rail Game"

[07:43:29.409] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.3.0".

[07:43:30.324] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hkrpg_cn)
path: "F:\miHoYo Launcher\games\Star Rail Game\StarRail.exe"
arg: null

[07:43:31.827] [INFO] Starward.Services.Launcher.GameLauncherService
Start game operation canceled.

[07:43:32.645] [INFO] Starward.Pages.MainPage
Change game region to nap_cn

[07:43:32.646] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param nap_cn

[07:43:32.920] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "F:\miHoYo Launcher\games\ZenlessZoneZero Game"

[07:43:32.951] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.0.0".

[07:43:33.638] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (nap_cn)
path: "F:\miHoYo Launcher\games\ZenlessZoneZero Game\ZenlessZoneZero.exe"
arg: null

[07:43:43.634] [INFO] Starward.Services.Launcher.GameLauncherService
Start game operation canceled.

[07:43:44.843] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[07:43:44.845] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[07:43:45.128] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "F:\miHoYo Launcher\games\Genshin Impact Game"

[07:43:45.167] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "4.7.0".

[07:43:45.862] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hk4e_cn)
path: "F:\miHoYo Launcher\games\Genshin Impact Game\YuanShen.exe"
arg: null

[07:43:47.685] [INFO] Starward.Services.Launcher.GameLauncherService
Start game operation canceled.

[07:43:48.572] [INFO] Starward.Pages.MainPage
Change game region to nap_cn

[07:43:48.573] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param nap_cn

[07:43:48.881] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "F:\miHoYo Launcher\games\ZenlessZoneZero Game"

[07:43:48.917] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.0.0".

[07:43:51.220] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (nap_cn)
path: "F:\miHoYo Launcher\games\ZenlessZoneZero Game\ZenlessZoneZero.exe"
arg: null

[07:43:56.880] [INFO] Starward.Services.Launcher.GameLauncherService
Start game operation canceled.

[07:43:57.732] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[07:43:57.733] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hkrpg_cn

[07:43:58.023] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "F:\miHoYo Launcher\games\Star Rail Game"

[07:43:58.062] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.3.0".

[07:43:59.013] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hkrpg_cn)
path: "F:\miHoYo Launcher\games\Star Rail Game\StarRail.exe"
arg: null

[07:44:00.530] [INFO] Starward.Services.Launcher.GameLauncherService
Start game operation canceled.

[07:44:01.220] [INFO] Starward.Pages.MainPage
Change game region to nap_cn

[07:44:01.221] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param nap_cn

[07:44:01.519] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "F:\miHoYo Launcher\games\ZenlessZoneZero Game"

[07:44:01.549] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.0.0".

[07:44:07.317] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (nap_cn)
path: "F:\miHoYo Launcher\games\ZenlessZoneZero Game\ZenlessZoneZero.exe"
arg: null

[07:44:15.541] [INFO] Starward.Services.Launcher.GameLauncherService
Start game operation canceled.

[07:44:17.021] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param nap_cn

[07:44:20.579] [INFO] Starward.Pages.MainPage
Navigate to "ScreenshotPage" with param nap_cn

[07:44:21.076] [WARN] Starward.Pages.ScreenshotPage
Cannot find screenshot folder

[07:44:23.452] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param nap_cn

[07:44:23.523] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "F:\miHoYo Launcher\games\ZenlessZoneZero Game"

[07:44:23.552] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.0.0".

[07:44:27.028] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (nap_cn)
path: "F:\miHoYo Launcher\games\ZenlessZoneZero Game\ZenlessZoneZero.exe"
arg: null

[07:44:28.252] [INFO] Starward.Services.Launcher.GameLauncherService
Start game operation canceled.

[07:44:35.476] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (nap_cn)
path: "F:\miHoYo Launcher\games\ZenlessZoneZero Game\ZenlessZoneZero.exe"
arg: null

[07:44:36.609] [INFO] Starward.Pages.GameLauncherPage
Game started ("ZenlessZoneZero", 19104)

[07:44:38.627] [INFO] Starward.Services.PlayTimeService
Start to log playtime (nap_cn, 34304)

[07:47:44.155] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param nap_cn

[07:47:49.219] [INFO] Starward.Services.Gacha.ZZZGachaService
Last gacha log id of uid 11392576 is 0

[07:48:24.428] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param nap_cn

[07:48:24.529] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "F:\miHoYo Launcher\games\ZenlessZoneZero Game"

[07:48:24.539] [INFO] Starward.Pages.GameLauncherPage
Game is running ("ZenlessZoneZero", 19104)

[07:48:24.541] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.0.0".

[07:49:40.812] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[07:49:40.813] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hkrpg_cn

[07:49:41.096] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "F:\miHoYo Launcher\games\Star Rail Game"

[07:49:41.151] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.3.0".

[07:49:41.414] [INFO] Starward.Pages.MainPage
Change game region to nap_cn

[07:49:41.415] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param nap_cn

[07:49:41.544] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "F:\miHoYo Launcher\games\ZenlessZoneZero Game"

[07:49:41.553] [INFO] Starward.Pages.GameLauncherPage
Game is running ("ZenlessZoneZero", 19104)

[07:49:41.584] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.0.0".

[07:52:16.827] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[07:52:16.828] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hkrpg_cn

[07:52:17.047] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "F:\miHoYo Launcher\games\Star Rail Game"

[07:52:17.089] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.3.0".

[07:52:21.419] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[07:52:21.420] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[07:52:21.557] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "F:\miHoYo Launcher\games\Genshin Impact Game"

[07:52:21.731] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "4.7.0".

[07:55:12.523] [INFO] Starward.Pages.MainPage
Change game region to nap_cn

[07:55:12.525] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param nap_cn

[07:55:12.891] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "F:\miHoYo Launcher\games\ZenlessZoneZero Game"

[07:55:12.900] [INFO] Starward.Pages.GameLauncherPage
Game is running ("ZenlessZoneZero", 19104)

[07:55:12.923] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.0.0".

[08:01:00.902] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[08:01:00.910] [INFO] Starward.Pages.GameLauncherPage
Game is running ("ZenlessZoneZero", 19104)

[08:01:01.921] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[08:01:01.929] [INFO] Starward.Pages.GameLauncherPage
Game is running ("ZenlessZoneZero", 19104)

[08:01:02.936] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[11:25:35.327] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param nap_cn

[11:25:36.264] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[11:25:36.266] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hkrpg_cn

[11:25:38.845] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 101268026 is 0

[11:25:38.929] [INFO] Starward.Pages.MainPage
Change game region to nap_cn

[11:25:38.930] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param nap_cn

[11:25:41.120] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param nap_cn

[11:25:41.313] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "F:\miHoYo Launcher\games\ZenlessZoneZero Game"

[11:25:41.344] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.0.0".

[11:25:46.056] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[11:25:46.057] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hkrpg_cn

[11:25:46.330] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "F:\miHoYo Launcher\games\Star Rail Game"

[11:25:46.341] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.3.0".

[11:25:48.311] [INFO] Starward.Pages.MainPage
Navigate to "GameSettingPage" with param hkrpg_cn

[11:25:53.801] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hkrpg_cn

[11:26:06.508] [INFO] Starward.Services.Gacha.StarRailGachaService
Last gacha log id of uid 101268026 is 1720307400000057526

[11:26:14.752] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[11:26:14.753] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_cn

[11:26:15.649] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[11:26:15.650] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hkrpg_cn

[11:26:17.584] [INFO] Starward.Pages.MainPage
Change game region to nap_cn

[11:26:17.585] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param nap_cn

[11:26:19.760] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param nap_cn

[11:26:19.833] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "F:\miHoYo Launcher\games\ZenlessZoneZero Game"

[11:26:19.866] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.0.0".

[11:42:37.653] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (nap_cn)
path: "F:\miHoYo Launcher\games\ZenlessZoneZero Game\ZenlessZoneZero.exe"
arg: null

[11:42:39.260] [INFO] Starward.Pages.GameLauncherPage
Game started ("ZenlessZoneZero", 6228)

[11:42:41.276] [INFO] Starward.Services.PlayTimeService
Start to log playtime (nap_cn, 34304)

[16:17:20.903] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[16:17:20.905] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[16:17:21.141] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "F:\miHoYo Launcher\games\Genshin Impact Game"

[16:17:21.231] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "4.7.0".

[16:17:21.480] [INFO] Starward.Pages.MainPage
Change game region to nap_cn

[16:17:21.481] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param nap_cn

[16:17:21.635] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "F:\miHoYo Launcher\games\ZenlessZoneZero Game"

[16:17:21.669] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.0.0".

[16:17:27.736] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[16:17:27.737] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hkrpg_cn

[16:17:27.948] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "F:\miHoYo Launcher\games\Star Rail Game"

[16:17:27.989] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.3.0".

[16:17:28.610] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hkrpg_cn)
path: "F:\miHoYo Launcher\games\Star Rail Game\StarRail.exe"
arg: null

[16:17:30.292] [INFO] Starward.Pages.GameLauncherPage
Game started ("StarRail", 52660)

[16:17:32.304] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hkrpg_cn, 52660)

[16:27:12.318] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[16:27:12.326] [INFO] Starward.Pages.GameLauncherPage
Game is running ("StarRail", 52660)

[16:27:13.334] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[16:27:13.342] [INFO] Starward.Pages.GameLauncherPage
Game is running ("StarRail", 52660)

[16:27:14.344] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[16:28:06.270] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[16:28:06.271] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[16:28:06.536] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "F:\miHoYo Launcher\games\Genshin Impact Game"

[16:28:06.572] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "4.7.0".

[16:28:09.495] [INFO] Starward.Pages.MainPage
Change game region to nap_cn

[16:28:09.496] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param nap_cn

[16:28:09.763] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "F:\miHoYo Launcher\games\ZenlessZoneZero Game"

[16:28:09.940] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.0.0".
```

### Additional Context

原神与星穹铁道功能都正常，绝区零抽卡分析功能正常，时长统计出现问题。

**Comment by CreeperAWA** [comment]
我的是正常的，你重新装一下看看？

**Comment by KongChengs** [comment]
> 我的是正常的，你重新装一下看看？

重装过了，好像没用？

**Comment by CreeperAWA** [comment]
> > 我的是正常的，你重新装一下看看？
> 
> 重装过了，好像没用？

你pre-6正常吗

**Comment by KongChengs** [comment]
> > > 我的是正常的，你重新装一下看看？
> > 
> > 
> > 重装过了，好像没用？
> 
> 你pre-6正常吗

我昨天才装的starward，就是pre6，也不行，更新到pre7也不行。

**Comment by KongChengs** [comment]
> > > > 我的是正常的，你重新装一下看看？
> > > 
> > > 
> > > 重装过了，好像没用？
> > 
> > 
> > 你pre-6正常吗
> 
> 我昨天才装的starward，就是pre6，也不行，更新到pre7也不行。

不知道是什么问题，别人好像也没出过这个问题。

**Comment by CreeperAWA** [comment]
> > > > > 我的是正常的，你重新装一下看看？
> > > > 
> > > > 
> > > > 重装过了，好像没用？
> > > 
> > > 
> > > 你pre-6正常吗
> > 
> > 
> > 我昨天才装的starward，就是pre6，也不行，更新到pre7也不行。
> 
> 不知道是什么问题，别人好像也没出过这个问题。

看开发者怎么说吧，搞不懂(

**Comment by Eric-Joker** [comment]
我这也有这个问题 但是没debug，因为没时间）

**Comment by Scighost** [comment]
```
[07:44:36.609] [INFO] Starward.Pages.GameLauncherPage
Game started ("ZenlessZoneZero", 19104)

[07:44:38.627] [INFO] Starward.Services.PlayTimeService
Start to log playtime (nap_cn, 34304)


[11:42:39.260] [INFO] Starward.Pages.GameLauncherPage
Game started ("ZenlessZoneZero", 6228)

[11:42:41.276] [INFO] Starward.Services.PlayTimeService
Start to log playtime (nap_cn, 34304)
```

我在日志中发现了一个问题，启动的ZZZ进程和记录游戏时间的进程不一致，猜测是有相同名称 `ZenlessZoneZero` 的进程存在。

**Comment by KongChengs** [comment]
> ```
> [07:44:36.609] [INFO] Starward.Pages.GameLauncherPage
> Game started ("ZenlessZoneZero", 19104)
> 
> [07:44:38.627] [INFO] Starward.Services.PlayTimeService
> Start to log playtime (nap_cn, 34304)
> 
> 
> [11:42:39.260] [INFO] Starward.Pages.GameLauncherPage
> Game started ("ZenlessZoneZero", 6228)
> 
> [11:42:41.276] [INFO] Starward.Services.PlayTimeService
> Start to log playtime (nap_cn, 34304)
> ```
> 
> 我在日志中发现了一个问题，启动的ZZZ进程和记录游戏时间的进程不一致，猜测是有相同名称 `ZenlessZoneZero` 的进程存在。

晚上突然就正常了，不知道怎么回事，触发和恢复都一脸懵逼。（

**Comment by devil233-ui** [comment]
> > ```
> > [07:44:36.609] [INFO] Starward.Pages.GameLauncherPage
> > Game started ("ZenlessZoneZero", 19104)
> > 
> > [07:44:38.627] [INFO] Starward.Services.PlayTimeService
> > Start to log playtime (nap_cn, 34304)
> > 
> > 
> > [11:42:39.260] [INFO] Starward.Pages.GameLauncherPage
> > Game started ("ZenlessZoneZero", 6228)
> > 
> > [11:42:41.276] [INFO] Starward.Services.PlayTimeService
> > Start to log playtime (nap_cn, 34304)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我在日志中发现了一个问题，启动的ZZZ进程和记录游戏时间的进程不一致，猜测是有相同名称 `ZenlessZoneZero` 的进程存在。
> 
> 晚上突然就正常了，不知道怎么回事，触发和恢复都一脸懵逼。（

唉，我怎么没这么好运……从11.6还7开始我就所有游戏都用不了计时功能了至今也没回复，今晚触发了个绝区零抽卡功能出问题，索性直接一起初始化掉了
