### ISSUE TITLE
[Bug] 应用设置-窗口大小选项丢失

### ISSUE THREAD

**Issue by AcE77505** [Scighost/Starward#945]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

这是最新版0.12.0应用设置-外观的界面
![image](https://github.com/user-attachments/assets/e90f4ec0-bcb3-410d-a1dd-e86089581b3a)
这是0.11.7-dev应用设置-外观的界面
![image](https://github.com/user-attachments/assets/6f5b0f4a-b54c-454e-8fea-903cae345080)
从这个版本开始，这个选项就消失了

### Reproduction Steps

直接打开启动器设置即可发现，即使重新下载最新版本也会出现这种情况

### Starward Version

0.12.0

### Windows Version

22000.1817

### Log

```shell
[18:30:22.807] [INFO] 
Welcome to Starward v0.12.0
System: Microsoft Windows NT 10.0.22000.0
Command Line: E:\Starward\app-0.12.0\Starward.dll

[18:30:22.837] [INFO] Starward.Services.DatabaseService
Database path is 'E:\Starward'

[18:30:22.858] [INFO] Starward.Services.DatabaseService
Database version is 9, target version is 9.

[18:30:22.925] [INFO] Starward.Pages.MainPage
Last game region is None

[18:30:23.433] [EROR] Starward.Pages.MainPage
Update background image
System.ArgumentOutOfRangeException: Unknown launcher id. (Parameter 'launcherId')
   at Starward.Core.HoYoPlay.HoYoPlayClient.BuildUrl(String api, String launcherId, String language) in D:\a\Starward\Starward\src\Starward.Core\HoYoPlay\HoYoPlayClient.cs:line 78
   at Starward.Core.HoYoPlay.HoYoPlayClient.GetGameBackgroundAsync(String launcherId, String language, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\HoYoPlay\HoYoPlayClient.cs:line 109
   at Starward.Services.HoYoPlayService.GetGameBackgroundAsync(GameBiz biz) in D:\a\Starward\Starward\src\Starward\Services\HoYoPlayService.cs:line 274
   at Starward.Services.Launcher.LauncherBackgroundService.GetBackgroundImageUrlAsync(GameBiz gameBiz, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward\Services\Launcher\LauncherBackgroundService.cs:line 102
   at Starward.Services.Launcher.LauncherBackgroundService.GetBackgroundImageAsync(GameBiz gameBiz, Boolean disableCustom) in D:\a\Starward\Starward\src\Starward\Services\Launcher\LauncherBackgroundService.cs:line 125
   at Starward.Pages.MainPage.UpdateBackgroundImageAsync(Boolean force) in D:\a\Starward\Starward\src\Starward\Pages\MainPage.xaml.cs:line 347

[18:30:24.694] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[18:30:25.578] [INFO] Starward.Services.UpdateService
Current version: "0.12.0", latest version: "0.12.0", ignore version: null

[18:30:27.414] [EROR] Starward.MyWindows.UpdateContentWindow
Load recent update content
System.Runtime.InteropServices.COMException (0x8007139F)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32)
   at ABI.Microsoft.Web.WebView2.Core.ICoreWebView2_13Methods.get_Profile(IObjectReference)
   at Starward.MyWindows.UpdateContentWindow.LoadPageAsync() in D:\a\Starward\Starward\src\Starward\MyWindows\UpdateContentWindow.xaml.cs:line 249
```

**Comment by Scighost** [comment]
新版本不再支持调整窗口大小
