### ISSUE TITLE
[Bug] Unable To Download GenshinImpact (International server)

### ISSUE THREAD

**Issue by Morcery** [Scighost/Starward#957]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

The download process is abruptly interrupted and an error log is thrown

### Reproduction Steps

<img width="891" alt="屏幕截图 2024-07-17 132649" src="https://github.com/user-attachments/assets/2f97c680-6466-44f9-8086-a359b764ce9d">

### Starward Version

0.12.0

### Windows Version

Windows 11  22631.3880

### Log

```shell
[13:03:52.235] [INFO] 
Welcome to Starward v0.12.0
System: Microsoft Windows NT 10.0.22631.0
Command Line: D:\Starward\app-0.12.0\Starward.dll download --biz hk4e_global --loc D:\Starward\GameFiles\GenhinImpact --lang 15

[13:03:52.254] [INFO] Starward.Services.DatabaseService
Database path is 'D:\Starward'

[13:03:52.268] [INFO] Starward.Services.DatabaseService
Database version is 9, target version is 9.

[13:03:52.422] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Initialize install game service
biz: hk4e_global
path: "D:\Starward\GameFiles\GenhinImpact"
lang: All
repair: False
reinstall: False

[13:03:52.443] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Start install game, skipVerify: False

[13:03:52.444] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Prepare for download.

[13:03:53.748] [WARN] Starward.Services.Launcher.GameLauncherService
config.ini not found: "D:\Starward\GameFiles\GenhinImpact\config.ini"

[13:03:54.400] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Request head: "https://autopatchhk.yuanshen.com/client_app/download/pc_zip/20240705190845_sEVV7ebRBuMrOheE/GenshinImpact_4.8.0.zip.001"

[13:03:54.400] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Request head: "https://autopatchhk.yuanshen.com/client_app/download/pc_zip/20240705190845_sEVV7ebRBuMrOheE/GenshinImpact_4.8.0.zip.003"

[13:03:54.400] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Request head: "https://autopatchhk.yuanshen.com/client_app/download/pc_zip/20240705190845_sEVV7ebRBuMrOheE/GenshinImpact_4.8.0.zip.002"

[13:03:54.401] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Request head: "https://autopatchhk.yuanshen.com/client_app/download/pc_zip/20240705190845_sEVV7ebRBuMrOheE/GenshinImpact_4.8.0.zip.004"

[13:03:54.401] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Request head: "https://autopatchhk.yuanshen.com/client_app/download/pc_zip/20240705190845_sEVV7ebRBuMrOheE/GenshinImpact_4.8.0.zip.005"

[13:03:54.401] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Request head: "https://autopatchhk.yuanshen.com/client_app/download/pc_zip/20240705190845_sEVV7ebRBuMrOheE/GenshinImpact_4.8.0.zip.006"

[13:03:54.401] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Request head: "https://autopatchhk.yuanshen.com/client_app/download/pc_zip/20240705190845_sEVV7ebRBuMrOheE/Audio_Chinese_4.8.0.zip"

[13:03:54.401] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Request head: "https://autopatchhk.yuanshen.com/client_app/download/pc_zip/20240705190845_sEVV7ebRBuMrOheE/Audio_English(US)_4.8.0.zip"

[13:03:54.401] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Request head: "https://autopatchhk.yuanshen.com/client_app/download/pc_zip/20240705190845_sEVV7ebRBuMrOheE/Audio_Japanese_4.8.0.zip"

[13:03:54.401] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Request head: "https://autopatchhk.yuanshen.com/client_app/download/pc_zip/20240705190845_sEVV7ebRBuMrOheE/Audio_Korean_4.8.0.zip"

[13:03:54.679] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Start download files.

[13:03:54.679] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
10 files need to download.

[13:03:54.682] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Download: FileName "GenshinImpact_4.8.0.zip.001", Url "https://autopatchhk.yuanshen.com/client_app/download/pc_zip/20240705190845_sEVV7ebRBuMrOheE/GenshinImpact_4.8.0.zip.001"

[13:03:54.683] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Download: FileName "GenshinImpact_4.8.0.zip.002", Url "https://autopatchhk.yuanshen.com/client_app/download/pc_zip/20240705190845_sEVV7ebRBuMrOheE/GenshinImpact_4.8.0.zip.002"

[13:03:54.690] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Download: FileName "GenshinImpact_4.8.0.zip.003", Url "https://autopatchhk.yuanshen.com/client_app/download/pc_zip/20240705190845_sEVV7ebRBuMrOheE/GenshinImpact_4.8.0.zip.003"

[13:03:54.690] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Download: FileName "GenshinImpact_4.8.0.zip.005", Url "https://autopatchhk.yuanshen.com/client_app/download/pc_zip/20240705190845_sEVV7ebRBuMrOheE/GenshinImpact_4.8.0.zip.005"

[13:03:54.690] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Download: FileName "GenshinImpact_4.8.0.zip.004", Url "https://autopatchhk.yuanshen.com/client_app/download/pc_zip/20240705190845_sEVV7ebRBuMrOheE/GenshinImpact_4.8.0.zip.004"

[13:03:54.690] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Download: FileName "GenshinImpact_4.8.0.zip.006", Url "https://autopatchhk.yuanshen.com/client_app/download/pc_zip/20240705190845_sEVV7ebRBuMrOheE/GenshinImpact_4.8.0.zip.006"

[13:03:54.690] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Download: FileName "Audio_Chinese_4.8.0.zip", Url "https://autopatchhk.yuanshen.com/client_app/download/pc_zip/20240705190845_sEVV7ebRBuMrOheE/Audio_Chinese_4.8.0.zip"

[13:03:54.690] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Download: FileName "Audio_English(US)_4.8.0.zip", Url "https://autopatchhk.yuanshen.com/client_app/download/pc_zip/20240705190845_sEVV7ebRBuMrOheE/Audio_English(US)_4.8.0.zip"

[13:03:54.690] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Download: FileName "Audio_Korean_4.8.0.zip", Url "https://autopatchhk.yuanshen.com/client_app/download/pc_zip/20240705190845_sEVV7ebRBuMrOheE/Audio_Korean_4.8.0.zip"

[13:03:54.691] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Download: FileName "Audio_Japanese_4.8.0.zip", Url "https://autopatchhk.yuanshen.com/client_app/download/pc_zip/20240705190845_sEVV7ebRBuMrOheE/Audio_Japanese_4.8.0.zip"

[13:08:32.729] [EROR] Starward.Services.InstallGame.GenshinInstallGameService
Install game error.
System.Net.Http.HttpIOException: The response ended prematurely, with at least 8378284240 additional bytes expected. (ResponseEnded)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1, CancellationToken)
   at Starward.Services.InstallGame.InstallGameService.DownloadFileAsync(DownloadFileTask task, CancellationToken cancellationToken, Boolean noTmp) in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 813
   at Starward.Services.InstallGame.InstallGameService.<>c__DisplayClass76_0.<<DownloadAsync>b__2>d.MoveNext() in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 546
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__53`1.<<ForEachAsync>b__53_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Starward.Services.InstallGame.InstallGameService.DownloadAsync(CancellationToken cancellationToken, Boolean noTmp) in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 540
   at Starward.Services.InstallGame.InstallGameService.StartAsync(Boolean skipVerify) in D:\a\Starward\Starward\src\Starward\Services\InstallGame\InstallGameService.cs:line 251
```

**Comment by Scighost** [comment]
It's a network error. The automatic retry mechanism will be added on latter version, and the download experience will be better
