### ISSUE TITLE
[Bug] 原神“账号记录”功能出现错误

### ISSUE THREAD

**Issue by JasonLI040114** [Scighost/Starward#958]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

依照原方法在“原神”-“账号记录”-“输入URL”中输入“派蒙菜单”-“反馈”中的链接地址后，出现以下报错信息：
ArgumentException -Input URL Input url is invalid. (Parameter 'url’)
根据初步分析，原因在于服务中心于4.8版本更新后进行改版，望开发者进行适配，感谢！

### Reproduction Steps

![微信图片_20240717212929](https://github.com/user-attachments/assets/d9dc27af-728d-4f72-bee4-6f742b55813d)

### Screenshots

![微信图片_20240717212929](https://github.com/user-attachments/assets/d990ae4e-328c-41d6-94d1-fee3e704fda7)

### Starward Version

0.12.0

### Windows Version

22631.3880

### Log

```shell
[20:36:55.745] [INFO] 
Welcome to Starward v0.12.0
System: Microsoft Windows NT 10.0.22631.0
Command Line: "D:\Games\miHoYo Games\Starward\app-0.12.0\Starward.dll"

[20:36:55.789] [INFO] Starward.Services.DatabaseService
Database path is 'D:\Games\miHoYo Games\Starward'

[20:36:55.822] [INFO] Starward.Services.DatabaseService
Database version is 9, target version is 9.

[20:36:55.961] [INFO] Starward.Pages.MainPage
Last game region is hk4e_cn

[20:36:55.990] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[20:36:57.868] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "D:\Games\miHoYo Games\Game Data\Genshin Impact Game"

[20:36:57.943] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "4.8.0".

[20:36:58.735] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[20:36:59.574] [INFO] Starward.Services.UpdateService
Current version: "0.12.0", latest version: "0.12.0", ignore version: null

[20:38:39.007] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hk4e_cn)
path: "D:\Games\miHoYo Games\Game Data\Genshin Impact Game\YuanShen.exe"
arg: null

[20:38:40.104] [INFO] Starward.Pages.GameLauncherPage
Game started ("YuanShen", 14708)

[20:38:42.122] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hk4e_cn, 14708)

[20:51:45.966] [INFO] Starward.Pages.MainPage
Navigate to "SelfQueryPage" with param hk4e_cn

[20:51:47.401] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[20:51:48.165] [INFO] Starward.Services.UpdateService
Current version: "0.12.0", latest version: "0.12.0", ignore version: null

[20:51:59.944] [EROR] Starward.Pages.SelfQueryPage
Input url
System.ArgumentException: Input url is invalid. (Parameter 'url')
   at Starward.Core.SelfQuery.SelfQueryClient.InitializeAsync(String url, GameBiz gameBiz, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\SelfQuery\SelfQueryClient.cs:line 86
   at Starward.Services.SelfQueryService.InitializeAsync(String url, GameBiz gameBiz) in D:\a\Starward\Starward\src\Starward\Services\SelfQueryService.cs:line 40
   at Starward.Pages.SelfQueryPage.InputURLAsync() in D:\a\Starward\Starward\src\Starward\Pages\SelfQueryPage.xaml.cs:line 308

[21:13:40.787] [INFO] Starward.Pages.MainPage
Last game region is hk4e_cn

[21:13:40.818] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[21:13:41.242] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "D:\Games\miHoYo Games\Game Data\Genshin Impact Game"

[21:13:41.264] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "4.8.0".

[21:13:42.192] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[21:13:42.254] [INFO] Starward.Pages.MainPage
Navigate to "ScreenshotPage" with param hk4e_cn

[21:13:42.302] [WARN] Starward.Pages.ScreenshotPage
Cannot find screenshot folder

[21:13:42.755] [INFO] Starward.Pages.MainPage
Navigate to "GameSettingPage" with param hk4e_cn

[21:13:42.898] [INFO] Starward.Services.UpdateService
Current version: "0.12.0", latest version: "0.12.0", ignore version: null

[21:13:49.318] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hk4e_cn

[21:13:49.339] [INFO] Starward.Services.GameRecordService
Change region to China.

[21:14:22.191] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[21:14:22.257] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "D:\Games\miHoYo Games\Game Data\Genshin Impact Game"

[21:14:22.280] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "4.8.0".

[21:14:22.979] [INFO] Starward.Pages.MainPage
Change game region to nap_cn

[21:14:22.980] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param nap_cn

[21:14:23.051] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "D:\Games\miHoYo Games\Game Data\ZenlessZoneZero Game"

[21:14:23.066] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.0.0".

[21:14:24.532] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param nap_cn

[21:14:26.282] [INFO] Starward.Services.Gacha.ZZZGachaService
Last gacha log id of uid 10800448 is 1721203200001083348

[21:16:10.962] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[21:16:10.963] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hkrpg_cn

[21:16:12.570] [WARN] Starward.Pages.GachaLogPage
Request mihoyo api error: "authkey timeout (-101)"

[21:16:12.902] [INFO] Starward.Pages.MainPage
Change game region to nap_cn

[21:16:12.903] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param nap_cn

[21:16:14.425] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[21:16:14.425] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hk4e_cn

[21:16:17.443] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[21:16:18.075] [INFO] Starward.Services.UpdateService
Current version: "0.12.0", latest version: "0.12.0", ignore version: null

[21:19:42.381] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[21:19:42.381] [INFO] Starward.Pages.MainPage
Navigate to "GachaLogPage" with param hkrpg_cn

[21:19:42.987] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hkrpg_cn

[21:19:43.053] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "D:\Games\miHoYo Games\Game Data\Star Rail Game"

[21:19:43.083] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.3.0".

[21:19:43.987] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hkrpg_cn)
path: "D:\Games\miHoYo Games\Game Data\Star Rail Game\StarRail.exe"
arg: null

[21:19:45.095] [INFO] Starward.Pages.GameLauncherPage
Game started ("StarRail", 1740)

[21:19:47.113] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hkrpg_cn, 1740)

[21:19:56.124] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[21:19:56.137] [INFO] Starward.Pages.GameLauncherPage
Game is running ("StarRail", 1740)

[21:19:57.137] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[21:21:31.909] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hkrpg_cn)
path: "D:\Games\miHoYo Games\Game Data\Star Rail Game\StarRail.exe"
arg: null

[21:21:32.998] [INFO] Starward.Pages.GameLauncherPage
Game started ("StarRail", 17656)

[21:21:35.004] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hkrpg_cn, 17656)

[21:24:11.142] [INFO] Starward.Pages.MainPage
Change game region to nap_cn

[21:24:11.144] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param nap_cn

[21:24:11.210] [INFO] Starward.Pages.GameLauncherPage
Game install path of nap_cn: "D:\Games\miHoYo Games\Game Data\ZenlessZoneZero Game"

[21:24:11.230] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of nap_cn is "1.0.0".

[21:24:12.179] [INFO] Starward.Pages.MainPage
Change game region to hkrpg_cn

[21:24:12.180] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hkrpg_cn

[21:24:12.259] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "D:\Games\miHoYo Games\Game Data\Star Rail Game"

[21:24:12.264] [INFO] Starward.Pages.GameLauncherPage
Game is running ("StarRail", 17656)

[21:24:12.278] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.3.0".

[21:24:12.976] [INFO] Starward.Pages.MainPage
Change game region to hk4e_cn

[21:24:12.977] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[21:24:13.044] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "D:\Games\miHoYo Games\Game Data\Genshin Impact Game"

[21:24:13.066] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "4.8.0".

[21:24:15.478] [INFO] Starward.Pages.MainPage
Navigate to "SelfQueryPage" with param hk4e_cn

[21:24:49.546] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[21:24:49.598] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "D:\Games\miHoYo Games\Game Data\Genshin Impact Game"

[21:24:49.618] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "4.8.0".

[21:24:50.548] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hk4e_cn)
path: "D:\Games\miHoYo Games\Game Data\Genshin Impact Game\YuanShen.exe"
arg: null

[21:24:51.981] [INFO] Starward.Pages.GameLauncherPage
Game started ("YuanShen", 20384)

[21:24:53.999] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hk4e_cn, 20384)

[21:25:16.509] [INFO] Starward.Pages.MainPage
Navigate to "SelfQueryPage" with param hk4e_cn

[21:25:18.301] [EROR] Starward.Pages.SelfQueryPage
Input url
System.ArgumentException: Input url is invalid. (Parameter 'url')
   at Starward.Core.SelfQuery.SelfQueryClient.InitializeAsync(String url, GameBiz gameBiz, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\SelfQuery\SelfQueryClient.cs:line 86
   at Starward.Services.SelfQueryService.InitializeAsync(String url, GameBiz gameBiz) in D:\a\Starward\Starward\src\Starward\Services\SelfQueryService.cs:line 40
   at Starward.Pages.SelfQueryPage.InputURLAsync() in D:\a\Starward\Starward\src\Starward\Pages\SelfQueryPage.xaml.cs:line 308
```

**Comment by Scighost** [comment]
新版的URL改了，你点右上角的返回旧版，这个可以继续使用。
![image](https://github.com/user-attachments/assets/e7e7d9b6-0a1b-44a6-8a19-fe85d9c1beeb)

**Comment by HyBoxwood** [comment]
> 新版的URL改了，你点右上角的返回旧版，这个可以继续使用。 ![image](https://private-user-images.githubusercontent.com/61003590/349534395-e7e7d9b6-0a1b-44a6-8a19-fe85d9c1beeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NTE2ODksIm5iZiI6MTcyMTg1MTM4OSwicGF0aCI6Ii82MTAwMzU5MC8zNDk1MzQzOTUtZTdlN2Q5YjYtMGExYi00NGE2LThhMTktZmU4NWQ5YzFiZWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDIwMDMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4MTI2NmQ0NGE5NjgwNzBlMjI0MDg4MDA5OTQ3NDFlMGRhM2EzN2YwZDlhNTdkMTBlY2E1ODljYTMzODhhODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uGMOKEkjWjvjN0a5BdNqlKqpeHzv2Dpu3vmfS72n2tc)

我想请问B服的是游戏内浏览器，也是要自己获取URL吗，显然它长得和官服新版或旧版都不一样。
