### ISSUE TITLE
星穹铁道unityplayer.dll修复后自动消失

### ISSUE THREAD

**Issue by SHINETSE945** [Scighost/Starward#977]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

星穹铁道unityplayer.dll自动消失，修复后依然自动消失，之前都好好的，甚至我今天下午还在玩，晚上一开电脑发现游戏缺失unityplayer.dll，用了修复后可以看到文件里面多了unityplayer.dll，但是马上又消失了。重复了好几次修复都不行，重新下载游戏也是一样的问题，后来我用了米哈游官方启动器修复就不会出现上面的问题了。看过杀毒程序没有隔离文件，退出杀毒程序也不能解决dll消失的问题。但是用官方启动器修复后再用starward启动星穹铁道，就可以正常运行游戏了。

### Reproduction Steps

先是打开游戏在网络正常的情况下出现获取全局分发错误，关闭游戏再次启动后显示缺失unityplayer.dll，选择修复后文件内会出现unityplayer.dll但又马上消失。目前安装的游戏中只有星穹铁道国际服会出现这样的问题，绝区零国服国际服都正常运行。

### Starward Version

0.12.0

### Windows Version

22631.3880

### Log

```shell
starward程序文件完整无报错，上述问题是突然发生的，从我下午最后一次打开游戏到晚上发现游戏无法启动也就过了5个小时，中间没有对电脑进行任何操作。
```

**Comment by SHINETSE945** [comment]
第一次在github上报告问题，不知道这样对不对

**Comment by SHINETSE945** [comment]
这里是我重新下载游戏后的日志
[02:25:31.830] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_global: "D:\starrail"

[02:25:31.879] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_global is "2.3.0".

[02:25:36.576] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_global: null

[02:25:36.576] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_global is null.

[02:25:45.510] [INFO] Starward.Pages.GameLauncherPage
Change game install path (hkrpg_global): "D:\xingqiongtiedao"

[02:25:45.513] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_global: "D:\xingqiongtiedao"

[02:25:45.518] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_global is "2.3.0".

[02:26:28.953] [INFO] Starward.Services.UpdateService
Start to check update (Preview: False, Arch: X64)

[02:26:29.855] [INFO] Starward.Services.UpdateService
Current version: "0.12.0", latest version: "0.12.0", ignore version: null

[02:35:29.393] [EROR] Starward.Pages.Setting.AboutSettingPage
Verify files
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean, Byte[], CancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions, HttpRequestMessage, Boolean, Stream, CancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions, HttpRequestMessage, Boolean, Stream, CancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(QueueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage, Boolean, Boolean, CancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage, HttpCompletionOption, CancellationTokenSource, Boolean, CancellationTokenSource, CancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.<FromJsonAsyncCore>g__Core|12_0[TValue,TJsonOptions](HttpClient, Task`1, Boolean, CancellationTokenSource, Func`4, TJsonOptions, CancellationToken)
   at Starward.Core.Metadata.MetadataClient.CommonGetAsync[T](String url, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\Metadata\MetadataClient.cs:line 55
   at Starward.Core.Metadata.MetadataClient.GetReleaseAsync(Boolean isPrerelease, Architecture architecture, CancellationToken cancellationToken) in D:\a\Starward\Starward\src\Starward.Core\Metadata\MetadataClient.cs:line 117
   at Starward.Pages.Setting.AboutSettingPage.VerifyFileAsync() in D:\a\Starward\Starward\src\Starward\Pages\Setting\AboutSettingPage.xaml.cs:line 93

[02:43:46.907] [INFO] Starward.Pages.GameLauncherPage
Change game install path (hkrpg_global): "D:\starrail"

[02:43:46.910] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_global: "D:\starrail"

[02:43:46.914] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_global is "2.3.0".

[02:43:51.509] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hkrpg_global)
path: "D:\starrail\StarRail.exe"
arg: null

[02:43:51.659] [INFO] Starward.Pages.GameLauncherPage
Game started ("StarRail", 21072)

[02:43:53.663] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hkrpg_global, 21072)

[02:44:26.672] [INFO] Starward.Pages.GameLauncherPage
Game process exited

[02:44:26.678] [INFO] Starward.Pages.GameLauncherPage
Game is running ("StarRail", 21072)

[02:44:27.680] [INFO] Starward.Pages.GameLauncherPage
Game process exited

**Comment by SHINETSE945** [comment]
之前有人也报了一个相似的星穹铁道dll消失BUG,但他的是切换版本修复时才出现的，我没有切换版本也没有进行任何操作dll还是消失了，而且修复完后dll会消失的BUG好像还是存在。

**Comment by Eric-Joker** [comment]
#973 重复问题
已修复但是尚未发布预编译版本，作者最近在忙新的下载器
